### ISSUE TITLE
Flexible cookie handling for play.mvc.Http.Response

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5015] opened 2015-08-19 22:48 UTC
All of the setCookie methods for Http.Response are additive in that you have to exhaustivly specify all the parameters as you go: 

https://www.playframework.com/documentation/2.4.x/api/java/play/mvc/Http.Response.html#setCookie-java.lang.String-java.lang.String-

A better way to handle this would be to define a setCookie method that took `Http.Cookie` as a parameter, and added a builder pattern for creating `Http.Cookie`.

**Comment by wsargent** [comment] 2015-08-19 22:50
This would probably make a nice feature for a Play newcomer.

**Comment by andrestc** [comment] 2015-08-22 21:05
I will take a shot at this one.

**Comment by darioalessandro** [comment] 2015-09-03 04:02
Whoa! I squashed all my changes into the last commit, I did not realized that by pushing to git it would generate all this changes, sorry about that.

**Comment by jroper** [comment] 2015-09-03 04:55
Oh don't worry about that, it's normal, it's just a stupid thing in GitHub where it doesn't clean up notifications from orphaned commits (caused by doing squashing/amending/forced pushes).

**Comment by marcospereira** [comment] 2015-09-09 20:21
Closed by #5076 thanks to @darioalessandro. :-)

**Closed by marcospereira** 2015-09-09 20:21 UTC
Labels: community, has-pr, improvement, newbie
