### ISSUE TITLE
mock&the global application anyway, set play.allowGlobalApplication = true,

### ISSUE THREAD

**Issue by kingsant** [playframework/playframework#9245] opened 2019-05-07 07:47 UTC
### Play Version (2.5.x / etc)

2.7.0

### API (Scala / Java / Neither / Both)
scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

windows

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

1.8

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

I run sbt test.

```
The global application reference is disabled. Play's global state is deprecated and will
be removed in a future release. You should use dependency injection instead. To enable
the global application anyway, set play.allowGlobalApplication = true.
       
java.lang.RuntimeException: 
The global application reference is disabled. Play's global state is deprecated and will
be removed in a future release. You should use dependency injection instead. To enable
the global application anyway, set play.allowGlobalApplication = true.
       
	at scala.sys.package$.error(package.scala:27)
	at play.api.Play$.privateMaybeApplication(Play.scala:92)
	at play.core.Execution$.internalContext(Execution.scala:24)
	at play.api.mvc.Action$.executionContext(Action.scala:498)
	at play.api.mvc.ActionBuilder$$anon$9.executionContext(Action.scala:329)
	at play.api.mvc.ActionBuilder$$anon$10.executionContext(Action.scala:417)
	at play.api.mvc.Action.apply(Action.scala:98)
	at play.api.mvc.Action.apply$(Action.scala:90)
	at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:416)
	at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:416)
	at mockws.FakeWSRequestHolder.executeResult(FakeWSRequestHolder.scala:115)
	at mockws.FakeWSRequestHolder.execute(FakeWSRequestHolder.scala:99)
	at mockws.FakeWSRequestHolder.execute(FakeWSRequestHolder.scala:182)
	at mockws.FakeWSRequestHolder.post(FakeWSRequestHolder.scala:198)
	at services.impl.publiccloud.CloudAlarmService.getIEStoken(CloudAlarmService.scala:189)
	at services.impl.publiccloud.CloudAlarmService.sending(CloudAlarmService.scala:215)
	at services.impl.publiccloud.CloudAlarmService.sendAlarm(CloudAlarmService.scala:163)
	at services.impl.publiccloud.CloudAlarmService.sendJobAlarm(CloudAlarmService.scala:89)
	at services.impl.publiccloud.CloudAlarmServiceTest.$anonfun$new$1(CloudAlarmServiceTest.scala:31)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at base.BaseSuite.org$scalatest$BeforeAndAfterEach$$super$runTest(BaseSuite.scala:22)
	at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:221)
	at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
	at base.BaseSuite.runTest(BaseSuite.scala:22)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at base.BaseSuite.org$scalatest$BeforeAndAfterAll$$super$run(BaseSuite.scala:22)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at base.BaseSuite.run(BaseSuite.scala:22)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```
### Reproducible Test Case
follow my code
```

object AlarmMock {

  def setTestMode() = {
    val client = getMockWSClient()

    new MockUp[CloudAlarmService]() {

      @Mock
      def url(endpoint: String) = {
        client.url(endpoint)
      }
    }
  }

  def getMockWSClient() = {

    val route1 = Route {
      case (POST, str) if str.contains("/oc/v2.3/tokens") => Action {
        Ok(Json.obj(
          "data" -> "token***********"
        ))
      }
      case (POST, str) if str.contains("/oc/v2.3/alarm/thirdalarms") => Action {
        //(json \ "log_description" \ "log_url")
        Ok
      }
      case x => Action {
        println(s"method:${x._1}, url: ${x._2}")
        Ok
      }
    }
    val ws = MockWS(route1)

    ws
  }

}
````
where occure error:' .post(Json.obj("user_id" -> configuration.get[String]("ies.userId"),'
```
private def getIEStoken: Future[String] = {

    val hostIp = getHostIp
    val password = CloudSkCryptService.instance.decrypt(iesEncodePassword)
    url(s"$iesEndpoint$tokenUri")
      .post(Json.obj("user_id" -> configuration.get[String]("ies.userId"),
        "value" -> password,
        "host_ip" -> hostIp))
      .map { res =>
        if (res.status == 200) {
          val jsValue = Json.parse(res.body)
          val token = (jsValue \ "data").as[String]
          token
        }
        else {
          logWarn(s"DLS server get token from IES, but IES return err. statusCode = ${res.status}")
          ""
        }
      }
      .recover {
        case e: Exception =>
          logError(e, "Exception when connect to IES")
          ""
      }
  }
```

**Comment by kingsant** [comment] 2019-05-07 11:27
@marcospereira please help me ...

**Comment by kingsant** [comment] 2019-05-07 12:44
@gmethvin

**Comment by renatocaval** [comment] 2019-05-07 14:29
@kingsant, what kind of help are you looking for?

You stated that you have an issue, but have you tried to do what the error message is suggesting?

> The global application reference is disabled. Play's global state is deprecated and will be removed in a future release. You should use dependency injection instead. To enable the global application anyway, set play.allowGlobalApplication = true.

Btw, I'm closing the issue because this is not a bug or change request, rather a call for help. It's better to ask for help on the developer forum. https://discuss.playframework.com

**Closed by renatocaval** 2019-05-07 14:29 UTC
