### ISSUE TITLE
Application reloads on assets or public files changes

### ISSUE THREAD

**Issue by codeepic** [playframework/playframework#7799] opened 2017-09-06 10:29 UTC
### Play Version (2.5.x / etc)
Play 2.5.2

### API (Scala / Java / Neither / Both)
Scala, Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
java version "1.8.0_131"
Java(TM) SE Runtime Enviro

This is a known issue [#2905](https://github.com/playframework/playframework/issues/2905) but it still haven't been resolved.

Any changes to JavaScript or CSS assets in public folder trigger Play framework to recompile the whole application, which is a time consuming process.

**Comment by codeepic** [comment] 2017-09-25 10:05
Guys, is there any resolution to this or at least a rough estimate whether it can be solved.
It's a big hurdle for our front-end team. Every time the .js or css file is changed, Play recompiles the whole project. The time it takes to wait for the browser to refresh is 90 seconds. If you consider how often these changes are made and the number of front-end guys working on it we are losing 20 hours weekly just waiting for the Play to recompile. I wonder why no one else raised this issue before.

**Comment by shkhln** [comment] 2017-09-26 05:02
> Every time the js or css file is changed, Play recompiles the whole project - all Scala and Java classes.

All of them? What do you see when you touch java code? Does incremental compilation work properly in that case?

**Comment by gmethvin** [comment] 2017-09-30 07:15
It would be useful if we had a project to test. #2905 seems to have a lot of people with different experiences, so the more information we have the better.

**Comment by richdougherty** [comment] 2017-10-02 20:30
@codeepic, Sorry to hear this is affecting you so much. I'll check up what's happening with this issue. I know we've got some file reloading issues on our radar but not sure what the plan is for this specific issue.

Just so you know, this kind of issue can be very tricky to resolve because it spans several subsystems - sbt, sbt-web, file change notifications, Play's reloading, classloaders, etc. And we don't want to make a mistake because we don't want to accidentally break reloading for other use cases.

Issue #2905 was fixed with a major refactor to Play (#3108), but perhaps has regressed since then or maybe you have a slightly different project setup.

With that in mind, any extra information you provide would be helpful. Best of all would be a script for us to follow showing what you're seeing, what actions you take (e.g. "modify file foo.css", "refresh the browser"), what the logs show ("recompiling 2 Scala files"), etc. A minimised project that demonstrates the issue would be great too. :)

**Comment by codeepic** [comment] 2017-10-06 16:12
@richdougherty 

So we have an Angular 2 application in public folder. I just changed 1 of the TypeScript files, which are watched by Webpack. Webpack recompiled the files into .js bundles in /dist folder inside public. Now I hit refresh button on the browser to see the changes, 57 seconds later I can see them. This happens every time, for all front-end devs at our company. Here is the log from Play with timestamps.
Just a note, our app requires the connection to MySQL, Cassandra and 2 instances of Elastic Search.
[play-log.txt](https://github.com/playframework/playframework/files/1363263/play-log.txt)

**Comment by richdougherty** [comment] 2017-10-09 21:38
Thanks @codeepic - how long does the TypeScript/Webpack build take vs the rest of the time for stopping/starting the application?

If the time is dominated by the actual restarting logic then a fix may would be to:
- watch **all** files for changes
- **always** run a build - will rebuild any files that have changed
- **conditionally** restart the application
  - do a restart if a Java/Scala class, template file, config file, etc changes
  - don't do a restart if only a CSS, JavaScript, HTML, etc asset has changed

**Comment by richdougherty** [comment] 2017-10-09 21:41
> don't do a restart if only a CSS, JavaScript, HTML, etc asset has changed

And the reason we don't need to restart here is because the `Assets` controller will always read the latest CSS, JavaScript, etc files directly from the drive. It doesn't need to be restarted to pick up changes to the files.

**Comment by garethdn** [comment] 2017-10-12 09:28
@richdougherty Can you give an example of the conditional application restart that you mention?

I can tell you that the Webpack build generally takes an average of 500ms to 1000ms, with stopping and starting of the application taking from 90 seconds to 120 seconds.

If it makes any difference, I can tell you that some of our public assets are referenced in `xxx.scala.html` files using:

`@routes.Assets.at("some_folder/dist/favicon-32x32.png")`

and

`@routes.Assets.versioned("some_folder/dist", "app.js")`

**Comment by shkhln** [comment] 2017-10-12 12:25
> an example of the conditional application restart

I'm pretty sure any Play application with default settings already works that way. The aforementioned refactor deals with exactly that issue.

> with stopping and starting of the Play application taking from 90 seconds to 120 seconds
> If it makes any difference

The restart itself takes about 12 seconds according to the timestamps in the provided log excerpt. I don't believe sbt is completely silent for the rest of time, so I'm baffled why the usual compilation output was omitted. It likely very relevant to your problem.

**Comment by codeepic** [comment] 2017-10-12 13:03
@shkhln So you think it may be an issue with our sbt setup since the logs go silent after initial 12s restart?

@richdougherty as @garethdn said, the Webpack rebuild is 1-2s so it's not dominating the restart time.
We don't need to restart the application - the issue we have is: we can't prevent Play from restarting the app. I checked Play documentation and it only mentions how to start local server with auto-reload enabled [running-the-server-in-development-mode](https://www.playframework.com/documentation/2.6.x/PlayConsole#running-the-server-in-development-mode) I am just trying to get to the bottom of it. If the auto-reload is enabled when you run your app in dev mode - it should also be possible to disable it, but the documentation doesn't provide answers. So is it possible or not?

As long as I can disable auto-reload I will be a happy front-end dev.

**Comment by shkhln** [comment] 2017-10-12 13:10
> So you think it may be an issue with our sbt setup since the logs go silent after initial 12s restart?
    
No, restart happens *after* compilation. It look like something is triggering java/scala recompilation and that is actually what you should look at, not restart. See https://www.playframework.com/documentation/2.6.x/SBTDebugging#Debugging-incremental-compilation.

**Comment by codeepic** [comment] 2017-10-12 14:14
@shkhln From what I understand Play observes `public` folder and any file changes in there (be it .js, .css or .java, .scala) triggers recompilation and then restart. In that case it will always recompile and then restart (reload recompiled files). Am I correct?

**Comment by shkhln** [comment] 2017-10-12 14:50
Assets are not directly served from `public` directory, sbt  copies both managed (`app/assets`) and unmanaged (`public`) assets to the `target/web/public/main/` directory. And that's why it watches `public` directory.

**Comment by moqichenle** [comment] 2017-10-12 15:25
two questions related: 
1. after we run "sbt run", we have sth like this: 
![image](https://user-images.githubusercontent.com/3297592/31504081-5d76884c-af69-11e7-8ee1-cdd427a6a863.png)
then it kinda freezes there **forever...(over 10mins or longer)** 
What is it doing that takes so long and no logs showing at all?
2.How to set watchSources only with scala and java files. The doc says it defaults to scala and java classes only. It doesn't seem to be the case for us. As @codeepic said, any typescript file can cause the sbt reload and recompile.
Thank you.

**Comment by shkhln** [comment] 2017-10-12 15:53
> then it kinda freezes there forever...(over 10mins or longer)
> What is it doing that takes so long and no logs showing at all?

Eh, compiling? You can try setting logging to level to 'debug' (http://www.scala-sbt.org/0.13/docs/Howto-Logging.html).

> The doc says it defaults to scala and java classes only.

That's not correct.

**Comment by moqichenle** [comment] 2017-10-12 16:06
![image](https://user-images.githubusercontent.com/3297592/31506134-80024248-af6e-11e7-8bc3-25486248530b.png)

If that s not correct, how to set it only reload for scala &java classes only?

**Comment by shkhln** [comment] 2017-10-12 16:34
Do you write anything to conf directory as part of asset building process?

**Comment by moqichenle** [comment] 2017-10-12 16:49
We have several modules and every of them has their conf files.

**Comment by shkhln** [comment] 2017-10-12 17:16
Right. Be that has nothing to do with my question.

**Comment by moqichenle** [comment] 2017-10-12 19:08
Hi Sorry What I wanted to say was we have different conf settings under sub-modules. The logs show that all the conf files from different modules were copied to target.  
Usual normal application conf files under those folders, some csv files used by scala classes. 
Is the Assets versioning in routes file the key problem here?

**Comment by shkhln** [comment] 2017-10-12 19:36
Can you please clone [play-scala-starter-example](https://github.com/playframework/play-scala-starter-example), checkout 2.5.x branch and test whether updating files in the `public` directory reloads application?

> Is the Assets versioning in routes file the key problem here?

Unlikely. However, you can easily test that yourself.

**Comment by garethdn** [comment] 2017-10-13 16:35
After cloning the starter project (2.6x branch) and running in debug mode I've noted that the load time (GET `http://localhost:9000/`) when there are no changes averages at **10 - 15ms**

After changing `hello.js` the subsequent load time averages at **1300 - 1440ms**. That's about 100 times slower. I don't whether this can be extrapolated to much larger projects.

Debug output on this reload is:

```
[debug] No changes
[debug] Copy resource mappings:
[debug]         (C:\xxxxxxxx\play-scala-starter-example-2.6.x\conf\application.conf,C:\xxxxxxxx\play-scala-starter-example-2.6.x\target\scala-2.12\classes\application.conf)
[debug]         (C:\xxxxxxxx\play-scala-starter-example-2.6.x\conf\logback.xml,C:\xxxxxxxx\play-scala-starter-example-2.6.x\target\scala-2.12\classes\logback.xml)
[debug]         (C:\xxxxxxxx\play-scala-starter-example-2.6.x\conf\routes,C:\xxxxxxxx\play-scala-starter-example-2.6.x\target\scala-2.12\classes\routes)
[debug] No changes
```

Will update with 2.5x results...

**Comment by shkhln** [comment] 2017-10-13 17:03
Okay, so no `--- (RELOAD) ---` message here, as expected. Now you need to add webpack/typescript configuration to the starter project in similar way you have it set up in your actual project.

**Comment by richdougherty** [comment] 2017-12-10 23:55
Possibly related: https://stackoverflow.com/questions/47701806/playframework-always-recompiles-everything-even-just-editing-a-css-file

**Comment by schmitch** [comment] 2017-12-27 21:14
Actually not reloading play on a file change is simple.
The problem is just, that if play does not reload. You will still get the stale (old file).
Some can remove the resource folder from ` PlayKeys.playMonitoredFiles`, but this will break play since it actually needs every file inside `target/web/public/main`. 
So basically if somebody copies the files manually and removes the correct resource folder from playMonitoredFiles, this should actually work.

**Comment by DwayneSmurdon** [comment] 2018-02-25 12:47
What is the resolution on this?  We have the same issues.

**Comment by shkhln** [comment] 2018-02-25 12:54
> What is the resolution on this? We have the same issues. Does 2.6 fix this?
Either somebody provides a repro or it's never going to fixed.

**Comment by DwayneSmurdon** [comment] 2018-02-25 13:55
Oh, you mean this doesn't happen to everyone?  Changing a *static* asset doesn't cause UNDO work?  What about @schmitch comment above serving files directly from public/ ?  Maybe just in dev mode?

I feel like I have had this issue on every version.  Am I wrong?

**Comment by shkhln** [comment] 2018-02-25 14:16
> Oh, you mean this doesn't happen to everyone?

Do you see _everyone_ complaining? There are 3 people _from the same organization_ and that's about it. That strongly indicates an issue with their setup. Likely some unobvious sbt gotcha, otherwise I have no idea.

> I feel like I have had this issue on every version. Am I wrong?

Try https://github.com/playframework/play-scala-starter-example, report your experience here.

**Comment by RichieAHB** [comment] 2018-04-12 09:15
If it helps anyone else, I took on an internal app that had the whole client side code inside `public`. I think this was probably the issue @codeepic was having reading his comments. Obviously that meant that every time a file was changed in there, Play would copy over some huge `node_modules` folder into `target/web/public/main` as mentioned by @shkhln. Quickly moving that out of there fixed the slowness I was seeing. Potentially a nice UX feature for play would be to warn if it's seeing a `node_modules` folder inside `public` - might save a few people a lot of time!

**Comment by SakulK** [comment] 2018-04-16 08:52
Our frontend developers are also experiencing this problem (very long reload time after changing anything in app/assets or public). Does anyone know of a way to disable the process of copying the assets to target/... while in DEV mode? We would like to set it up so that in DEV mode webpack handles the resources for hot-reloading and Play would stop hanging for 10 seconds after each change (I tried the snippets from this and previous issues but it seems they are outdated, we have Play 2.6.10 and SBT 1.1.1)

**Comment by RichieAHB** [comment] 2018-04-16 10:01
@sakulk are your node_modules (or similar) in the public folder like our were? If so can they be moved to the parent directory?

**Comment by SakulK** [comment] 2018-04-16 10:06
@RichieAHB no, our node_modules folder is at the same level as app and public, but thanks :)

**Comment by kajmagnus** [comment] 2018-04-16 10:28
@SakulK  Play 2.6 and SBT 1.1.1 don't recompile any Scala files or reload the Play server for me. Maybe there's something unusual with your `build.sbt` project? What about posting that file, & the Play log, in ... a Gist?

**Comment by SakulK** [comment] 2018-04-16 12:06
@kajmagnus I just took https://github.com/playframework/play-scala-starter-example and added a few megabytes of javascript to app/assets/javascripts and/or public/javascripts (both work the same), then did couple of refreshes (F5) on http://localhost:9000/
![load_time](https://user-images.githubusercontent.com/1440804/38805277-8e30960a-4175-11e8-9948-0005f9fc1c83.png)
so normally it takes under 30ms to reload the page but after modifying any of the javascript files it jumps up to more than 300ms. So there is no problem with recompilation of Scala or anything like that, my guess is it's the time to copy all the assets to /target + tell the server to use the new ones? Something like that. After that I connected VisualVM to our big project and found one thing which takes a long time (10-15s) when I refresh the page after changing something in javascript:
![devserver](https://user-images.githubusercontent.com/1440804/38808044-fea59a44-417e-11e8-90d2-5e1541fdc42f.png)
I tried all our build.sbt settings in the play-scala-starter-example and nothing changed, Play log doesn't print anything during this "pause period" before refreshing the page.

**Comment by SakulK** [comment] 2018-04-16 12:09
https://github.com/playframework/playframework/blob/680b166ca8d43b8ac4c102c3cfc9728723124476/framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala#L118
I think I found the source ;)

**Comment by kajmagnus** [comment] 2018-04-16 17:50
@SakulK about: "*after modifying any of the javascript files it jumps up to more than 300ms*" — yes I've noticed this too. Whenever anything in `public/` changes, the next request takes maybe a second, instead of instant. Also, there are no log messages or anything — which means that no Scala files get recompiled and that the app doesn't reload or restart.  .... Actually I was (and am) fine with this, one second didn't matter, so I didn't think any more about it.

I think the small 300 ms delay you observe in play-scala-starter-example, is something different than what's happening in your "real" project? — I mean, the one you wrote this about: `very long reload time`. (the starter project doesn't reload & restart the app at all, right?)

> After that I connected VisualVM to our big project

```
          /**
           * Calls the BuildLink to recompile the application if files have changed and constructs a new application
           * using the new classloader. Returns the existing application if nothing has changed.
           *
           * @return a Try, which is either a Success containing the application or Failure with exception.
           * When a Failure is returned, the server handles it by returning an error page, so that the error
           * can be displayed in the user's browser. Failure is usually the result of a compilation error.
           */
          def get: Try[Application] = {
            // Block here while the reload happens. Reloading may take seconds or minutes
            // so this is a potentially very long operation!
```

I'd think that that won't happen in the starter project? Maybe only in your big "real" project?

**Comment by SakulK** [comment] 2018-04-16 18:28
@kajmagnus actually I checked the starter project in VisualVM and the 300ms delay is also from DevServerStart, so it somehow does happen after all, but no it doesn't recompile Scala sources for either of my projects. To me it looks the same between the starter project and my real application, the only difference is the time it takes (maybe it scales with the size of the project which would make sense to me).

**Comment by shkhln** [comment] 2018-04-16 18:41
> found one thing which takes a long time (10-15s)

Pretty sure that's webpack compiling things. I haven't seen any webpack integration plugins for sbt leveraging incremental compilation, so if you don't need to run build tasks in a specific order, it's better to just start webpack dev server and fetch assets from that.

**Comment by kajmagnus** [comment] 2018-04-17 08:40
@SakulK Ok, interesting that DevServerStart gets called. Hmm I'm starting to wonder, how much data is in your `public/` folder? I have maybe 6 MB in total in `public/`.  (B.t.w. I transpile Javascript & minify CSS etc, with Gulp & Node.js, by the way, outside Play. Play doesn't know anything has changed, before Gulp is done and saves the resulting files in `public/`. I keep the Javascript source files in `client/` that Play doesn't know exist. )

**Comment by SakulK** [comment] 2018-04-17 11:28
Ok I did some more testing and found out that the size of /app/assets and /public doesn't change the refresh time in either the starter project or my big application, I deleted all files and left only one to be able to change something in it and still got the 30ms - 300ms difference for starter and 30ms - 10s difference for my application. So my theory now is that maybe Reloader.reload takes a lot of time checking if any Scala/Java sources have been modified to see if compilation is needed? Somewhere here maybe:
https://github.com/playframework/playframework/blob/d77772c4d7a1cd2bb5013d14d8aa71b5859a247a/framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala#L430
Our Play application is a part of a larger SBT multi-project build so that could be the issue. It would be great if Play detected that only assets files have changed so there is no need to check all the Scala/Java files.

@kajmagnus I'm considering doing something similar to your approach with having another directory for assets and only using /public when publishing a prod version of the app, this will probably resolve our issues as well ;)

**Comment by schmitch** [comment] 2018-04-17 11:47
the question is, if this code can be removed/changed to have a "better" interface and get the "changed" information from, sbt, gradle, etc...

**Comment by shkhln** [comment] 2018-04-17 21:18
> maybe Reloader.reload takes a lot of time checking if any Scala/Java sources have been modified to see if compilation is needed

Hmm... Try running `compile` command from the sbt console (multiple times). Does it also take 10 seconds per run?

**Comment by SakulK** [comment] 2018-04-18 06:03
@shkhln I just tried this and `compile` takes 3 seconds without any changes, changing a line in a controller makes that go up to 4-5 seconds

**Comment by jleider** [comment] 2018-05-02 20:35
@gmethvin @richdougherty 

I was having this same issue with my company's larger multi-project build and I've determined that at least for us it was `sbt-web` trying to do something with all our `SCSS`/`TS`/`Font Icon SVGs` in the `projectName/app/assets` directory for each of our sub projects. 

By moving all our precompiled assets out of the `projectName/app/assets` up a directory to `projectName/assets` we no longer see this issue. However, anything in `public` will still cause the reload slowness issue which is a fine work around for us since we have `grunt` and `webpack` output the compiled assets directly in the `target` dir during development so that we can avoid play trying to parse/copy/manipulate them from `app/public` to `target/public/main/lib/projectName/...`. For a production build we have `grunt` and `webpack` place complied assets in `public` so that `sbt-digest` will still act upon them. We dont use any other `sbt-web` plugins and even if I completely remove `sbt-digest` I still see the slowdown.

I have two remaining questions:

* I can move the assets out of the `app` directory but how can I have `sbt` ignore the `app/assets` dir that `sbt-web` adds to `sourceDirectory in Assets`? I was not able to find a working solution.
* **More importantly:** What is `sbt-web` doing that is causing such a large slowdown during incremental compiles?

**Comment by bharal** [comment] 2018-10-15 12:51
How does this "need verification", this issue has happened to pretty much everyone on this list?

**Comment by mkurz** [comment] 2024-06-14 08:55
Because I can not reproduce this and like written in my last comment, no one complained about this anymore since 2018 I am going to close this issue.
Of course, feel free to comment if you still experience problems.

**Closed by mkurz** 2024-06-14 08:55 UTC
Labels: type:defect, status:needs-info, status:needs-verification
