### ISSUE TITLE
play framework 2.6.15, “gradle dist” produces “Could not find com.typesafe.play:play-doc_2.11:1.1.0.”

### ISSUE THREAD

**Issue by jumpingfella** [playframework/playframework#8493] opened 2018-06-28 09:12 UTC
Hello,

I'm stuck with "gradle dist", which plainly refuses to produce jar. 
I get "Task :createPlayBinaryDistributionJar FAILED", Could not find com.typesafe.play:play-doc_2.11:1.1.0.
Details of the output are here: https://stackoverflow.com/questions/50949640/play-framework-2-6-15-gradle-dist-produces-could-not-find-com-typesafe-play

To me this looks like a bug with dependencies in "gradle dist", as I don't reference play-doc anywhere. 

I've been trying to embed play! into our system for quite some time now; the real showstopper is compilation of twirl templates, so I re-wrote build mechanism with gradle, but still can't get it working. 

Regards, Stepan.

**Comment by marcospereira** [comment] 2018-06-28 20:52
Hello @jumpingfella,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

This may also be a problem with Gradle itself instead of Play, but it would be better if you can create a small project that reproduces the problem. I could not reproduce the problem running `./gradlew dist` on our sample projects.

Best.

**Closed by marcospereira** 2018-06-28 20:52 UTC
