### ISSUE TITLE
SBT plugin 2.5.14 no longer visible

### ISSUE THREAD

**Issue by jtescher** [playframework/playframework#7238] opened 2017-04-17 19:19 UTC
Seeing `com.typesafe.play#sbt-plugin;2.5.14: not found` when looking for play 2.5.14.

Looked in:
```
 ==== typesafe-ivy-releases: tried
https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.5.14/ivys/ivy.xml
==== sbt-plugin-releases: tried
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.5.14/ivys/ivy.xml
==== public: tried
https://repo1.maven.org/maven2/com/typesafe/play/sbt-plugin_2.10_0.13/2.5.14/sbt-plugin-2.5.14.pom
```

Seems like the `sbt-plugin-releases` permissions for 2.5.14's ivy.xml are off. The file is publicly visible https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.5.14/ivys/

But the actual file returns `Forbidden!`: https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.5.14/ivys/ivy.xml

**Comment by hlian** [comment] 2017-04-17 19:21
I can reproduce this.

**Comment by bakku** [comment] 2017-04-17 20:23
Happens for me with sbt-plugin version `2.5.13` as well.

```
[info] Resolving com.typesafe.play#sbt-plugin;2.5.13 ...
[warn] 	module not found: com.typesafe.play#sbt-plugin;2.5.13
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.5.13/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.5.13/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.5.13/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/sbt-plugin_2.10_0.13/2.5.13/sbt-plugin-2.5.13.pom
[info] Resolving org.irundaia.sbt#sbt-sassify;1.4.2 ...
[warn] 	module not found: org.irundaia.sbt#sbt-sassify;1.4.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.irundaia.sbt/sbt-sassify/scala_2.10/sbt_0.13/1.4.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.irundaia.sbt/sbt-sassify/scala_2.10/sbt_0.13/1.4.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/org.irundaia.sbt/sbt-sassify/scala_2.10/sbt_0.13/1.4.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/irundaia/sbt/sbt-sassify_2.10_0.13/1.4.2/sbt-sassify-1.4.2.pom
[info] Resolving org.foundweekends.giter8#sbt-giter8-scaffold;0.7.1 ...
[warn] 	module not found: org.foundweekends.giter8#sbt-giter8-scaffold;0.7.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.10/sbt_0.13/0.7.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.10/sbt_0.13/0.7.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.10/sbt_0.13/0.7.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/foundweekends/giter8/sbt-giter8-scaffold_2.10_0.13/0.7.1/sbt-giter8-scaffold-0.7.1.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#sbt-plugin;2.5.13: not found
[warn] 	:: org.irundaia.sbt#sbt-sassify;1.4.2: not found
[warn] 	:: org.foundweekends.giter8#sbt-giter8-scaffold;0.7.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by naderghanbari** [comment] 2017-04-17 20:56
Seems to be fixed now (apparently it was happening for all 2.5.x versions).

**Closed** 2017-04-17 22:48 UTC

**Comment by olitazl** [comment] 2017-04-27 09:48
same here! ivy.xml is forbidden!
