### ISSUE TITLE
[2.5.x] Add deprecated doc information like on Akka docs

### ISSUE THREAD

**Issue by kubukoz** [playframework/playframework#5858] opened 2016-03-10 19:57 UTC
http://doc.akka.io/docs/akka/2.4.0/scala.html - you can see a message like:

"You are browsing the docs for Akka 2.4.0, however the latest release in this series is: 2.4.2."

Would be useful to have something like that in play's docs.

**Comment by kubukoz** [comment] 2016-03-10 20:16
You meant 2.5, right? :P

**Comment by kubukoz** [comment] 2016-03-10 20:24
Ah, I thought by saying "playframework docs will actually also bring" you meant the desired behavior, not the actual one. You're right, of course

**Comment by wsargent** [comment] 2016-03-11 23:30
Possible duplicate of https://github.com/playframework/playframework.com/issues/43

**Comment by gmethvin** [comment] 2016-03-11 23:48
It looks like playframework/playframework.com#43 is about "major" versions (Google should prefer the latest play major version), whereas this is about "minor" versions.

**Comment by kubukoz** [comment] 2016-03-11 23:50
This is about showing the user that it's not the latest stable version - so both major and minor versions, but not in a SEO-based way, but like the Akka docs do.

**Comment by wsargent** [comment] 2016-03-15 19:38
This should still be filed on playframework.com though.

**Closed by wsargent** 2016-03-15 19:38 UTC
