### ISSUE TITLE
AkkaHttpConfiguration issue - documentation seems not correct

### ISSUE THREAD

**Issue by adridadou** [playframework/playframework#7395] opened 2017-05-31 10:58 UTC
Play version: Play 2.6.0-RC1
API (Scala) (But I guess it is a problem for both)

Operating System ( MacOS 10.12.5)

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
Paste the output from `java -version` at the command line.

### Expected Behavior
I followed the documentation here : https://playframework.com/documentation/2.6.x/SettingsAkkaHttp 
to reconfigure the request timeout but the configuration was ignored.

I saw that the documentation is also mentioning Akka's documentation to get further information. 
http://doc.akka.io/docs/akka-http/current/scala/http/configuration.html

So instead of using the format described in Play's documentation, I used the one in Akka and it worked.

The configuration I tried and didn't work:
play {

  server {
    akka {
      https.idleTimeout = 75 seconds
      http.idleTimeout = 75 seconds

      requestTimeout = 10 minutes
    }
  }
}

The configuration that worked:
akka.http {
  server {
    idle-timeout = 10 minutes 
    request-timeout = 10 minutes
  }
}

**Comment by marcospereira** [comment] 2017-05-31 11:03
Closing since this is a duplicate of #7172. See also #7364 and #7067.

@adridadou if you have time, a pull request to correct the docs would be very welcomed. :-)

Thanks.

**Closed by marcospereira** 2017-05-31 11:03 UTC
