### ISSUE TITLE
［Play2.5.0］Form submission with Chinese and receive with request().body().asFormUrlEncoded(),It has unrecognizable characters

### ISSUE THREAD

**Issue by howenx** [playframework/playframework#5935] opened 2016-03-24 13:01 UTC
### Are you looking for help?

［Play 2.5.0 Java］Form submission in "application/x-www-form-urlencoded" some fields with Chinese and receive with request().body().asFormUrlEncoded(),It has unrecognizable characters.
But I switch v2.4.6,It's ok.

### Play Version (2.5.x / etc)
2.5.0

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.11.3 

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle 1.8.0_45
### Library Dependencies

PostgreSQL

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1.It should show Chinese normal.

### Actual Behavior

1.It has the unrecognizable characters and before submit,original text is in Chinese

**Comment by mkurz** [comment] 2016-03-24 13:04
Duplicate of #5919
This has been fixed (#5920) in upcoming Play 2.5.1.

**Closed by mkurz** 2016-03-24 13:04 UTC
