### ISSUE TITLE
sbt-fork-run-plugin breaks SBT

### ISSUE THREAD

**Issue by jkutner** [playframework/playframework#4839] opened 2015-07-12 15:00 UTC
Including sbt-fork-run-plugin in a project results in this error:

```
$ sbt update
....

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbtrc#client-2-11;0.3.1: not found
[warn]  :: com.typesafe.sbtrc#actor-client-2-11;0.3.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.typesafe.sbtrc:client-2-11:0.3.1
[warn]        +- com.typesafe.play:fork-run-protocol_2.11:2.3.9 ((play.sbt.forkrun.PlayForkRun) PlayForkRun.scala#L49)
[warn]        +- com.typesafe.play:fork-run_2.11:2.3.9 ((play.sbt.forkrun.PlayForkRun) PlayForkRun.scala#L49)
[warn]        +- computer-database-scala:computer-database-scala_2.11:0.0.1-SNAPSHOT
[warn]      com.typesafe.sbtrc:actor-client-2-11:0.3.1
[warn]        +- com.typesafe.play:fork-run_2.11:2.3.9 ((play.sbt.forkrun.PlayForkRun) PlayForkRun.scala#L49)
[warn]        +- computer-database-scala:computer-database-scala_2.11:0.0.1-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.sbtrc#client-2-11;0.3.1: not found
[error] unresolved dependency: com.typesafe.sbtrc#actor-client-2-11;0.3.1: not found
[error] Total time: 31 s, completed Jun 23, 2015 1:25:12 AM
[computer-database-scala] $ show fullResolvers
[info] ArrayBuffer(Raw(ProjectResolver(inter-project, mapped: )), FileRepository(local,FileConfiguration(true,None),Patterns(ivyPatterns=List(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=List(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)), public: https://repo1.maven.org/maven2/, Typesafe Releases Repository: https://repo.typesafe.com/typesafe/releases/)
[success] Total time: 0 s, completed Jun 23, 2015 1:26:26 AM
[computer-database-scala] $ exit
```

Here's a project that reproduces. Running `sbt stage` against this application has a different result than `activator stage`:
https://github.com/gifman009/Licenta

More information in this thread:
https://groups.google.com/forum/#!topic/play-framework/RLSPwvOqBIE

Other related issues:
https://github.com/sbt/sbt/issues/2054
https://github.com/typesafehub/activator/issues/979

I would like to see sbt-fork-run-plugin completely disable itself if not running under Activator. But I'm not sure how to code this up. Could it check for the "development" env?

Aside from the dependency resolution, I have some big concerns that stuff like this will break CI, PaaS, and even Production deployment, where sbt and Activator are used in intended to run in the foreground.

**Comment by cchantep** [comment] 2015-07-13 19:09
Hi @jkutner, please first ask such question on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework), rather than on this issue tracker (dedicated to confirmed issue). Best regards.

**Comment by jkutner** [comment] 2015-07-13 19:34
@cchantep I brought this up already: https://groups.google.com/d/topic/play-framework/RLSPwvOqBIE/discussion

Why did you close this?

**Comment by cchantep** [comment] 2015-07-13 19:39
According the [contribution guidelines](https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md), until there is a confirmed issue, there is no need to have ticket on this issue tracker. Best regards.

**Comment by jkutner** [comment] 2015-07-13 19:42
@cchantep I've created another thread: https://groups.google.com/forum/#!topic/play-framework/XOGhUpZIDFw. The reproducible example is linked above.

**Comment by richdougherty** [comment] 2015-07-13 23:52
@jkutner, Here's something to try.

Activator sometimes creates `.sbt` files with extra build settings. I noticed some of these files in the `project` directory of https://github.com/gifman009/Licenta. Maybe the settings are out of date. Can you try removing them?

Activator shims to remove: `play-fork-run.sbt`, `sbt-ui.sbt`.

I also noticed some lock files that you can probably remove too: `.sbtserver`, `.sbtserver.lock`.

**Comment by richdougherty** [comment] 2015-07-13 23:53
I'm going to open this issue because it has been confirmed.

**Comment by jkutner** [comment] 2015-07-14 02:16
@richdougherty Yes, this file is created by Activator, and it works fine with Activator. But when it is used with SBT it fails with the error above.  

Here is where it's added:
https://github.com/typesafehub/activator/blob/7618e81feb658eb0904ae471d06c08edf269753f/ui/app/assets/services/sbt/configuration.js#L26

I work for Heroku and we have had numerous reports from users that generate an app with Activator, and deploy it to Heroku. Heroku only uses SBT, and this causes the failure. The people that are encountering the error have no idea what has caused the problem because they never added the file.

Is there a particular resolver that could be added to the template for the `play-fork-run.sbt` file that would ensure it works with SBT? 

Thanks!

**Comment by richdougherty** [comment] 2015-07-14 04:40
@jkutner, I've pinged the Activator team to ask for some help on this one.

To answer your question about resolvers, it looks like the JARs can be found here: https://dl.bintray.com/typesafe/ivy-releases/com.typesafe.sbtrc/. Maybe the following resolver would work:

```scala
resolvers += "Typesafe Bintray Ivy releases" at "https://dl.bintray.com/typesafe/ivy-releases"
```

**Comment by dwijnand** [comment] 2015-07-14 08:34
I think the sbt team would rather the typesafe.com URL be used, rather than the underlying Bintray URL:

```scala
resolvers += "Typesafe Ivy releases" at "https://repo.typesafe.com/typesafe/ivy-releases"
```

**Comment by jkutner** [comment] 2015-07-14 13:11
Neither of those resolvers solves the problem. The `com.typesafe.sbtrc:client-2-11:0.3.1` and `com.typesafe.sbtrc:actor-client-2-11:0.3.1` are still unresolved. 

I think there is something deeper going on here. Unless...is there another resolver that Activator uses to get these dependencies and SBT does not have by default?

**Comment by jkutner** [comment] 2015-07-14 13:27
I've found that adding this resolve to the project's `build.sbt` fixes the problem:

```scala
resolvers += Resolver.url("Typesafe Ivy releases", url("https://repo.typesafe.com/typesafe/ivy-releases"))(Resolver.ivyStylePatterns)
```

So what is going on here? Shouldn't that be unnecessary? It seems that when including the sbt-fork-run-plugin in the Play app, it should not be necessary to add resolvers.

**Comment by alonsoir** [comment] 2016-03-09 10:26
Hi, i have the same problem, i just added this line as jkutner said:

resolvers += Resolver.url("Typesafe Ivy releases", url("https://repo.typesafe.com/typesafe/ivy-releases"))(Resolver.ivyStylePatterns)

 to build.sbt file and it works!

I guess that this is an activator issue, isn't ?

**Comment by wsargent** [comment] 2016-08-06 17:21
Yeah, this is activator.  Closing.

**Closed by wsargent** 2016-08-06 17:21 UTC

**Comment by jkutner** [comment] 2016-08-07 14:29
You can punt this, but it still affects adoption of Play Framework because so many people run into it.
https://github.com/typesafehub/activator/issues/1036
https://github.com/typesafehub/activator/issues/1057

**Comment by wsargent** [comment] 2016-08-08 16:29
@jkutner I'm aware.  It's not something the Play team can fix.
