### ISSUE TITLE
add more api to CacheApi

### ISSUE THREAD

**Issue by hepin1989** [playframework/playframework#5192] opened 2015-10-21 11:43 UTC
I found I need some like ```keys```,```clean/removeAll``` and so on,currentl cache api is really small.

**Comment by AliMoradian** [comment] 2015-11-06 18:39
I've commented a possible workaround here: https://github.com/playframework/playframework/issues/4757

**Comment by gmethvin** [comment] 2015-11-09 02:16
`CacheApi` is designed to work as a generic interface for all types of caches. Unfortunately that also means some functionality doesn't make sense in the interface. On many distributed caches it can be unfeasible to get or clear all the cache keys.

I'm going to close this issue since this is essentially a duplicate of #4757 (and that was the earlier issue).

**Closed by gmethvin** 2015-11-09 02:16 UTC
