### ISSUE TITLE
Make content of Configuration injectable.

### ISSUE THREAD

**Issue by jCalamari** [playframework/playframework#4842] opened 2015-07-13 11:28 UTC
Having a following configuration:

```
app.service.url = "http://url.com"
app.service.url.timeout = 500
```

It would be really good to make body of configuration injectable:

```
@javax.inject.Named("app.service.url")
private String url;

@javax.inject.Named("app.service.url.timeout")
private Long timeout;
```

Instead of calling static methods on Play object:

```
 Play.application().configuration().getString()
```
Why? Junits. It would be much easier to mock injected properties.

**Comment by nateww** [comment] 2015-07-13 15:19
+1

**Comment by richdougherty** [comment] 2015-07-13 20:45
Nice idea. Can I suggest using a different annotation, e.g. `@Config("app.service.url")`? We'd also want some mechanism to handle the different types of configuration: `String`, `Int`, `Config`, `Duration`, etc as well as possibly optional values.

I've labelled this issue as **community** and **improvement** to show that the issue is available to be picked up by an enthusiastic community member. :)

**Comment by njovy** [comment] 2015-07-16 15:17
+1
An annotation for reading config values sounds really cool.

**Comment by jCalamari** [comment] 2015-07-16 16:25
I quickly wrote few lines - without annotation yet. Not sure what to do with lists and objects. Any hints are welcome.
```
class InjectableConfigModule extends Module {

  override def bindings(environment: Environment, configuration: Configuration): Seq[Binding[_]] = {
    configuration.entrySet.filter { e =>
      val valueType: ConfigValueType = e._2.valueType()
      valueType == ConfigValueType.BOOLEAN || valueType == ConfigValueType.STRING || valueType == ConfigValueType.NUMBER
    } map { e =>
      val unwrapped: AnyRef = e._2.unwrapped()
      e._2.valueType() match {
        case ConfigValueType.BOOLEAN => bind[Boolean].qualifiedWith(e._1).toInstance(unwrapped.asInstanceOf[Boolean])
        case ConfigValueType.STRING => bind[String].qualifiedWith(e._1).toInstance(unwrapped.asInstanceOf[String])
        case ConfigValueType.NUMBER => unwrapped match {
          case _: java.lang.Long => bind[java.lang.Long].qualifiedWith(e._1).toInstance(unwrapped.asInstanceOf[java.lang.Long])
          case _: java.lang.Integer => bind[java.lang.Integer].qualifiedWith(e._1).toInstance(unwrapped.asInstanceOf[java.lang.Integer])
          case _: java.lang.Double => bind[java.lang.Double].qualifiedWith(e._1).toInstance(unwrapped.asInstanceOf[java.lang.Double])
        }
      }
    } toSeq
  }
}
```

**Comment by jroper** [comment] 2015-07-20 02:44
This could be done as an optional module - potentially with a configurable base path for configuration values to make injectable (injecting everything from typesafe config is probably not desirable).

**Comment by jCalamari** [comment] 2015-07-23 08:29
I created a github project to host the improvement - feel free to explore it. It uses only Play API.
https://github.com/jCalamari/icm

I am not making a pull request because I would like to take another approach in implementing the feature - Guice custom injecton.

https://github.com/google/guice/wiki/CustomInjections

I would like to get your feedback on these two approaches.

**Comment by w4tson** [comment] 2015-10-19 16:28
+1 for this. I've used something similar but in a custom use of Guice using Play 2.3.x and it's very useful. @jCalamari I appreciate you're exploring other implementations but is done better than perfect and Can this be merged in as is? If not can I help?

**Comment by mkurz** [comment] 2016-01-19 10:15
@jCalamari @w4tson Any news here?

**Comment by wsargent** [comment] 2016-08-06 18:18
This is actually better done as an injectable module outside of Play.  Closing.

**Closed by wsargent** 2016-08-06 18:18 UTC
Labels: community, improvement
