### ISSUE TITLE
 A client error occurred: Illegal character in path when URL contains "unsafe" characters

### ISSUE THREAD

**Issue by aiyanbo** [playframework/playframework#6527] opened 2016-09-06 04:49 UTC
**Request**

`GET /projects/1234/users/18620538586 | 上海/characteristic`

Encode to `/projects/1234/users/18620538586%20%7C%20上海/characteristic`

**Breakpoint**

[play.core.server.netty.NettyModelConversion#62](https://github.com/playframework/playframework/blob/2.5.6/framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala#L62)

```
java.net.URISyntaxException: Illegal character in path at index 36: /projects/1234/users/18620538586 | 上海/characteristic
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at play.core.server.netty.NettyModelConversion$$anonfun$tryToCreateRequest$1.apply(NettyModelConversion.scala:62)
	at play.core.server.netty.NettyModelConversion$$anonfun$tryToCreateRequest$1.apply(NettyModelConversion.scala:53)
	at scala.util.Try$.apply(Try.scala:192)
	at play.core.server.netty.NettyModelConversion.tryToCreateRequest(NettyModelConversion.scala:53)
	at play.core.server.netty.NettyModelConversion.convertRequest(NettyModelConversion.scala:46)
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:64)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:745)

```

### Play Version

2.5.4 & 2.5.6

**Comment by avdv** [comment] 2016-09-06 07:08
Nice report! We just ran into the same issue with using spaces (encoded as %20) in the URL's path.

@schmitch, is there a chance to get your PR merged in the next days or does it make sense to get a quick fix for this issue into place?

**Comment by schmitch** [comment] 2016-09-06 08:06
Actually from looking at his URI, it is not valid since it contains whitespace:

`/projects/1234/users/18620538586%20%7C%20上海/characteristc`this one will work, but you can't have whitespace inside a URI.

**Closed** 2016-09-06 08:07 UTC

**Comment by avdv** [comment] 2016-09-06 09:20
> /projects/1234/users/18620538586%20%7C%20上海/characteristcthis one will work, but you can't have whitespace inside a URI.

No, this does not work for me. But the problem is not directly in Play, read on.

According to http://netty.io/4.0/api/io/netty/handler/codec/http/QueryStringDecoder.html#path() this method "Returns the decoded path string of the URI."

In a simple test project I have created with `activator new` using the play-scala template, this is the result:

```
scala> new io.netty.handler.codec.http.QueryStringDecoder("/foo/space%20and%20space/?asdf")
res1: io.netty.handler.codec.http.QueryStringDecoder = io.netty.handler.codec.http.QueryStringDecoder@4b217955

scala> res1.path
res2: String = /foo/space%20and%20space/
```

But, we are using netty 4.0.41.Final because of the memory problems (#6491) where the output is as follows:

```
scala> new io.netty.handler.codec.http.QueryStringDecoder("/foo/space%20and%20space/?asdf")
res0: io.netty.handler.codec.http.QueryStringDecoder = io.netty.handler.codec.http.QueryStringDecoder@2fdd77ae

scala> res0.path
res1: String = /foo/space and space/
```

So, apparently Netty has fixed a bug, but broke backwards compatibility...

**Comment by schmitch** [comment] 2016-09-06 09:29
yeah but that bug is already tracked anyway:
https://github.com/playframework/playframework/issues/6507

It just looked that you tried to make a GET with whitespace and tought it will work. The hint to netty would've been great.

Here is the PR: https://github.com/playframework/playframework/pull/6529 you could try it against you application, if you wish.
