### ISSUE TITLE
Error in application.conf causes incomprehensible internal server error

### ISSUE THREAD

**Issue by cayhorstmann** [playframework/playframework#10744] opened 2021-03-08 10:02 UTC
### Play Version

2.8.7

### Operating System

Linux cay-ThinkPad-X390-Yoga 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

### Expected Behavior

1. Have a malformed `application.conf`, e.g. with an entry `uploadURL=http://localhost:8080/api/upload` (where the right hand side should have been quoted)
2. An error message appears flagging the offending entry in `application.conf`

### Actual Behavior

1. An error message appears:
```
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
        at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
        at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
```
2. The developer finds solace at https://stackoverflow.com/questions/58582995/inner-flow-was-completed-without-producing-result-elements-for-1-outstanding-ele

### Reproducible Test Case

Add the line `greeting=hello:` to application.conf.

**Comment by mkurz** [comment] 2021-03-09 19:34
Duplicate of #9020. This will be fixed in soon to be released Play 2.8.8

**Closed by mkurz** 2021-03-09 19:34 UTC

**Comment by kuscsik** [comment] 2021-07-14 09:15
Reproduced on 2.8.8. Can't locate the source of the issue.

**Comment by mkurz** [comment] 2021-07-14 09:20
@kuscsik Can you reproduce the problem? If so, can you please switch to [the netty server backend](https://www.playframework.com/documentation/2.8.x/NettyServer#Netty-Server-Backend), which should give you a much better error message, so we know what is causing the problem. In your `build.sbt` you need to disable the akka-http backend and enable the netty plugin and restart sbt:
```
lazy val root = (project in file("."))
  .enablePlugins(..., PlayNettyServer)
  .disablePlugins(PlayAkkaHttpServer)
```
Thanks!
