### ISSUE TITLE
Json macros don't work when case class has more than 23 fields

### ISSUE THREAD

**Issue by meddulla** [playframework/playframework#5685] opened 2016-02-18 12:37 UTC
```
import play.api.libs.json.{Json, Writes}
class FnTestFormatter {

  case class FnX(
                    field1: String,
                    field2: String,
                    field3: String,
                    field4: String,
                    field5: String,
                    field6: String,
                    field7: String,
                    field8: String,
                    field9: String,
                    field10: String,
                    field11: String,
                    field12: String,
                    field13: String,
                    field14: String,
                    field15: String,
                    field16: String,
                    field17: String,
                    field18: String,
                    field19: String,
                    field20: String,
                    field21: String,
                    field23: String,
                    field24: String // if you comment this, it compiles!
                  )
  implicit val FnXWrites: Writes[FnX] = Json.writes[FnX]
}
```

Play framework 2.4.6

**Comment by jroper** [comment] 2016-02-18 23:26
Duplicate of #3174.

**Closed by jroper** 2016-02-18 23:26 UTC
