### ISSUE TITLE
HEAD request on websocket throws ugly 500

### ISSUE THREAD

**Issue by gpgekko** [playframework/playframework#4878] opened 2015-07-22 09:53 UTC
Tripped over this by complete coincidence, but when you do a `HEAD` request to a websocket endpoint, you get a ugly internal server error (see stacktrace at the bottom).

I started poking around, but this is the only case I could come up with that would break, so I'm guessing this is the automagic `GET`s-also-serve-`HEAD`s code messing things up here, probably failing to return a `WebSocket.reject response`.
Other things I tried, but were handled perfectly fine:
- normal `GET` request to the websocket endpoint, without websocket headers (`400 bad request`, expecting this from the `HEAD` request too)
- other HTTP method requests (like `DELETE`, `OPTION`, `PUT`) to the websocket endpoint (`404 not found`)
- `HEAD` request to non websocket endpoints (`200 OK`)

It would be nice to get a clean response instead of a nasty stacktrace, even though it is unlikely that someone will run in to this.

```
[ERROR] from application in New I/O worker #19 - ! @6mpedf1kb - Internal server error, for (HEAD) [/news/stream] -> play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MatchError: Some(WebSocket(<function1>)) (of class scala.Some)]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:59) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57) [play-server_2.11-2.4.2.jar:2.4.2]
    at scala.util.Either$RightProjection.flatMap(Either.scala:522) [scala-library-2.11.7.jar:na]
    at play.core.server.Server$class.getHandlerFor(Server.scala:57) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:33) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at scala.util.Either.fold(Either.scala:99) [scala-library-2.11.7.jar:na]
    at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:127) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
    at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [netty-http-pipelining-1.1.4.jar:na]
    at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.3.Final.jar:na]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.3.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: scala.MatchError: Some(WebSocket(<function1>)) (of class scala.Some)
    at play.api.GlobalSettings$$anonfun$3.apply(GlobalSettings.scala:119) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.api.GlobalSettings$$anonfun$3.apply(GlobalSettings.scala:113) ~[play_2.11-2.4.2.jar:2.4.2]
    at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
    at play.api.GlobalSettings$class.onRequestReceived(GlobalSettings.scala:113) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.core.j.JavaGlobalSettingsAdapter.onRequestReceived(JavaGlobalSettingsAdapter.scala:14) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.api.http.GlobalSettingsHttpRequestHandler.handlerForRequest(HttpRequestHandler.scala:183) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:38) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:37) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.7.jar:na]
    at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:na]
    at scala.util.Success.map(Try.scala:237) ~[scala-library-2.11.7.jar:na]
    at play.core.server.Server$class.sendHandler$1(Server.scala:37) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:58) [play-server_2.11-2.4.2.jar:2.4.2]
    ... 38 common frames omitted
```

**Comment by gmethvin** [comment] 2015-07-27 11:36
Basically, the issue is that we permit HEAD requests against GETs without an explicit mapping in routes, but the match in `GlobalSettings` isn't exhaustive: https://github.com/playframework/playframework/blob/2.4.2/framework/src/play/src/main/scala/play/api/GlobalSettings.scala#L119

If you use the new `HttpRequestHandler`, it looks like it will serve a 404 in this case: https://github.com/playframework/playframework/blob/2.4.2/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L128

It would probably make sense to specifically handle `WebSocket` in both cases, and always serve a 400 for a HEAD request on a websocket.

**Comment by gpgekko** [comment] 2015-07-27 13:04
The new `HttpRequestHandler` looks like it will handle this case the same, the code for HEAD handling looks identical to me. But yeah, those are the bits of code I suspect to be the cause here too.

**Comment by gmethvin** [comment] 2015-07-27 23:18
@gpgekko the line I linked shows that anything that isn't `Some(action: EssentialAction)` is mapped to a 404. In `GlobalSettings` only `None` is mapped to 404, which is why you got a `MatchError`, since there is nothing that matches `Some(WebSocket(...))`

**Comment by gpgekko** [comment] 2015-07-28 07:41
Oh wow, you're right! My apologies, seems I read to quickly. Better test
the code I've written around that time yesterday in case I had more brain
failures, lol.

Met vriendelijke groet,
Guylian Pot

2015-07-28 1:18 GMT+02:00 Greg Methvin <notifications@github.com>:

**Comment by cchantep** [comment] 2016-09-09 12:11
Closing this for now. A up-to-date ticket can be raised against master if it's still reproduced with. Best regards

**Comment by alaz** [comment] 2017-03-02 18:46
We see it in production:

```
! @73897i09l - Internal server error, for (HEAD) [/api/feed/socket] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MatchError: Some(WebSocket(<function1>)) (of class scala.Some)]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[com.typesafe.play.play_2.11-2.4.8.jar:2.4.8]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.8.jar:2.4.8]
        at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50) [com.typesafe.play.play-server_2.11-2.4.8.jar:2.4.8]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:59) [com.typesafe.play.play-server_2.11-2.4.8.jar:2.4.8]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57) [com.typesafe.play.play-server_2.11-2.4.8.jar:2.4.8]
        at scala.util.Either$RightProjection.flatMap(Either.scala:522) [org.scala-lang.scala-library-2.11.8.jar:na]
        at play.core.server.Server$class.getHandlerFor(Server.scala:57) [com.typesafe.play.play-server_2.11-2.4.8.jar:2.4.8]
        at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:37) [com.typesafe.play.play-netty-server_2.11-2.4.8.jar:2.4.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:143) [com.typesafe.play.play-netty-server_2.11-2.4.8.jar:2.4.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:143) [com.typesafe.play.play-netty-server_2.11-2.4.8.jar:2.4.8]
        at scala.util.Either.fold(Either.scala:99) [org.scala-lang.scala-library-2.11.8.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:131) [com.typesafe.play.play-netty-server_2.11-2.4.8.jar:2.4.8]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.10.5.Final.jar:na]
        at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [com.typesafe.netty.netty-http-pipelining-1.1.4.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.10.5.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.10.5.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: scala.MatchError: Some(WebSocket(<function1>)) (of class scala.Some)
        at play.api.GlobalSettings$$anonfun$3.apply(GlobalSettings.scala:119) ~[com.typesafe.play.play_2.11-2.4.8.jar:2.4.8]
        at play.api.GlobalSettings$$anonfun$3.apply(GlobalSettings.scala:113) ~[com.typesafe.play.play_2.11-2.4.8.jar:2.4.8]
        at scala.Option.getOrElse(Option.scala:121) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at play.api.GlobalSettings$class.onRequestReceived(GlobalSettings.scala:113) ~[com.typesafe.play.play_2.11-2.4.8.jar:2.4.8]
        at play.api.DefaultGlobal$.onRequestReceived(GlobalSettings.scala:212) ~[com.typesafe.play.play_2.11-2.4.8.jar:2.4.8]
        at play.api.http.GlobalSettingsHttpRequestHandler.handlerForRequest(HttpRequestHandler.scala:183) ~[com.typesafe.play.play_2.11-2.4.8.jar:2.4.8]
        at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:38) ~[com.typesafe.play.play-server_2.11-2.4.8.jar:2.4.8]
        at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:37) ~[com.typesafe.play.play-server_2.11-2.4.8.jar:2.4.8]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.util.Try$.apply(Try.scala:192) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.util.Success.map(Try.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at play.core.server.Server$class.sendHandler$1(Server.scala:37) [com.typesafe.play.play-server_2.11-2.4.8.jar:2.4.8]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:58) [com.typesafe.play.play-server_2.11-2.4.8.jar:2.4.8]
        ... 39 common frames omitted
```

**Comment by wsargent** [comment] 2017-03-07 18:25
@alaz can you provide a test case for this please?  A small github project that can repo it will work as well.

**Comment by alaz** [comment] 2017-03-07 20:00
1. Get a [Play Websocket example](https://github.com/playframework/play-scala-websocket-example)
2. Run it: `sbt ~run`
3. Open another terminal window and invoke `curl -I http://localhost:9000/ws`
4. Voila:

```
$ curl -I http://localhost:9000/ws
HTTP/1.1 500 Internal Server Error
Content-Length: 4936
Content-Type: text/html; charset=utf-8
Date: Tue, 07 Mar 2017 19:58:49 GMT
```

**Comment by marcospereira** [comment] 2017-03-08 22:02
Thanks @alaz. I was able to reproduce the problem following the steps you described. This is still an issue with Play 2.5.12 (the latest stable release).

Reopening.

**Comment by mkurz** [comment] 2017-03-09 13:25
@marcospereira Is this also happening in the master branch?

**Comment by marcospereira** [comment] 2017-03-09 14:25
@mkurz yes.

**Comment by marcospereira** [comment] 2017-03-09 19:34
Please see #7060, #7057 and #7059.

**Closed** 2017-03-13 19:07 UTC
Labels: defect
