### ISSUE TITLE
ORACLE [ORA-01735: invalid ALTER TABLE] error when executing DOWNS  

### ISSUE THREAD

**Issue by rosca81** [playframework/playframework#6841] opened 2016-12-28 20:27 UTC
Hello,
We are having an error when using evolutions and ORACLE 12G, it seems to work fine but whenever we made a change in a model, applying DOWNS script sends out this error:

<img width="1251" alt="screenshot 2016-12-28 13 11 55" src="https://cloud.githubusercontent.com/assets/651838/21529468/41e98d74-ccff-11e6-88c7-2aaa119b179b.png">

### JDK (Oracle 1.8.0_45)

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### Library Dependencies

<b>ojdbc7.jar</b> to connect to ORACLE 12G, mainly we added this driver to our  lib folder however we're receiving this error any time we restart play server: 

[info] application - Creating Pool for datasource 'default'
[warn] c.z.h.u.DriverDataSource - Registered driver with driverClassName=oracle.jdbc.driver.OracleDriver was not found, trying direct instantiation.

Our config file for ORACLE:

  # ORACLE
  default.url="jdbc:oracle:thin:@//10.0.2.81:1521/orcl"
  default.driver=oracle.jdbc.driver.OracleDriver
  default.username="ok"
  default.password="ok"

I don't know why and somehow if this can be the source of the main problem of this issue...

### Expected Behavior

The expected behavior is to use automatic evolutions as it goes, in order to avoid creating UPS and DOWNS scripts by hand as when you turn off evolutions.

1. UPS script is working fine, we can successfully create database with auto generated script:  1.sql
2. If we make any change on any model,  we required to apply evolutions 

<img width="1680" alt="screenshot 2016-12-28 13 03 48" src="https://cloud.githubusercontent.com/assets/651838/21530489/c44c4d86-cd06-11e6-9b7f-2f2dd00dea6c.png">

### Actual Behavior

3. After we apply this evolution, the error comes out. It is obviously  because there is no "If exists" clause in ORACLE.

<img width="1251" alt="screenshot 2016-12-28 14 22 48" src="https://cloud.githubusercontent.com/assets/651838/21530837/222cf6a6-cd09-11e6-90a4-1e1668988e5e.png">

If we copy&paste first sentence to SQLDeveloper: 
<img width="673" alt="screenshot 2016-12-28 14 08 47" src="https://cloud.githubusercontent.com/assets/651838/21530569/4e4a71d4-cd07-11e6-9243-d8b73f61b73f.png">

Sintaxis error.... near "if exists"

### Reproducible Test Case

Example of one of our model classes:

    @Entity
    @Table(name="PS_ENT_SOLICITUDES_CONTRATOS")
    public class EntregableSolicitud extends Model {

    @Id
    @Column(name="ENS_ID_N")
    @SequenceGenerator(name="gen", sequenceName="PS_ENS_SEQ",allocationSize=1) 
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "gen")
    public Long id;

    @Column(name="ENS_NOMBRE_STR")
    public String nombre;

    @Column(name="ENS_DECRIPCION_STR")
    public String descripcion;

    @Column(name="ENS_PATH_ECM_STR")
    public String pathEcm;

    @ManyToOne
    @JoinColumn(name="ENS_SOL_ID_N",referencedColumnName="SOL_ID_N")
    @Column(name="ENS_SOL_ID_N")
    public Solicitud solicitud;

    @ManyToOne
    @JoinColumn(name="USU_ALTA",referencedColumnName="USU_ID_N")
    @Column(name="USU_ALTA")
    public Usuario createdBy;

    @ManyToOne
    @JoinColumn(name="USU_MOD",referencedColumnName="USU_ID_N")
    @Column(name="USU_MOD")
    public Usuario updatedBy;

    @JsonIgnore
    @WhenCreated
    @Column(name="FEC_ALTA")
    public Date created;

    @JsonIgnore
    @WhenModified
    @Column(name="FEC_MOD")
    public Date updated;

    @Column(name="BIT_ACTIVO")
    public boolean activo;

Hope someone can help us out in here!

**Comment by cchantep** [comment] 2016-12-30 09:47
Hi, the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) is the place to ask for help (rather than this tracker for confirmed issue). I suggest you move the discussion. Best regards.

**Comment by gmethvin** [comment] 2017-01-09 23:40
Closing since based on additional info from the mailing list post this doesn't look like a Play issue.

**Closed by gmethvin** 2017-01-09 23:40 UTC
