### ISSUE TITLE
Constraints.emailAddress regex error

### ISSUE THREAD

**Issue by mizerlou** [playframework/playframework#4268] opened 2015-04-21 20:55 UTC
if you attempt to validate an email address that contains a single char domain, Constraints.emailAddress incorrectly flags the address as invalid.

scala> Constraints.emailAddress("foo@x.com")
res5: play.api.data.validation.ValidationResult = Invalid(List(ValidationError(error.email,WrappedArray())))

**Comment by jroper** [comment] 2015-04-22 00:15
Duplicate of #4022.

**Closed by jroper** 2015-04-22 00:15 UTC
