### ISSUE TITLE
Action's logic is executed after all Filters are executed.

### ISSUE THREAD

**Issue by FranklinYinanDing** [playframework/playframework#8163] opened 2018-01-16 20:29 UTC
### Play Version (2.5.x / etc)

Play 2.6.x

### API (Scala / Java / Neither / Both)

Both

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. When Filter calls `next(request)`, Action's logic is executed before it returns.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "the page renders a 500 error code with no body content."  Copy and paste logs, and include any URLs.  Turn on internal Play logging with `<logger name="play" value="TRACE"/>` if there is no log output.  

1. Action's logic is executed after `next(request)` is returned.

### Reproducible Test Case

Please provide a PR with a failing test.  

If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

https://github.com/FranklinYinanDing/play-scala-starter-example/tree/request-order

This behavior is reproduced with both Akka Http Server and Netty. The example is just for Akka, but feel free to switch to Netty.

Explain:
1. `filters.ExampleFilter` setups a `ConcurrentHashMap` in request's attributes, puts "foo"-"bar" into the map, then calls `next(request)`, and cleans the map.
2. `controllers.HomeController.index` reads "foo" out of request's cache attribute.

Action's logic is expected to be executed during `next(request)`, so cleanup the map shouldn't affect the Action method. But instead, Action explodes because cache.get("foo") is None.

**Comment by FranklinYinanDing** [comment] 2018-01-16 20:36
I've debugged it a bit. Basically, `next(request)` only calls `def apply(rh: RequestHeader): Accumulator[ByteString, Result]`. The `def apply(request: Request[A]): Future[Result]` is wrapped and executed in `Accumulator.mapFuture`, which would not be executed until materializing the `Accumulator`.

**Comment by richdougherty** [comment] 2018-01-16 20:43
Exactly - `next` just schedules creates an asynchronous task (an `Accumulator`) which will be run later as the request body streams in. You'll want to modify the `Accumulator` with `map*` or `recover*` if you want code to run after it completes.

I'm going to close this because I think it's expected behaviour. Please comment if you think it should be opened again.

**Closed by richdougherty** 2018-01-16 20:43 UTC
