### ISSUE TITLE
IntelliJ run configuration immediately terminates the server

### ISSUE THREAD

**Issue by ianknowles** [playframework/playframework#10917] opened 2021-07-06 16:47 UTC
Play Version **2.8.8**
API **Scala**
Operating System **Win10**
JDK **11**
IntelliJ IDEA 2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40
org.intellij.scala (2021.1.21)

### Expected Behavior

1. Follow the instructions at https://www.playframework.com/documentation/2.8.x/IDE#IntelliJ-IDEA to setup a run configuration that starts the run task in the sbt shell
2. The play app should run and wait for user input to terminate (manually running the sbt task in the sbt shell works as expected)

### Actual Behavior

1. The play app starts up and immediately terminates

![image](https://user-images.githubusercontent.com/26507830/124637468-ae383a00-de81-11eb-8323-58611e3d98b1.png)

```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="run" type="SbtRunConfiguration" factoryName="sbt Task" show_console_on_std_err="false" show_console_on_std_out="false">
    <option name="allowRunningInParallel" value="false" />
    <option name="projectPathOnTarget" />
    <option name="selectedOptions">
      <list />
    </option>
    <option name="tasks" value="run" />
    <option name="useSbtShell" value="true" />
    <option name="vmparams" value="-Xms512M -Xmx1024M -Xss1M -XX:+CMSClassUnloadingEnabled" />
    <option name="workingDir" value="$PROJECT_DIR$" />
    <method v="2">
      <option name="Make" enabled="true" />
    </method>
  </configuration>
</component>
```

**Comment by Max-AR** [comment] 2022-01-19 11:01
@ianknowles This looks like a duplicate of #11086. Upgrading to 2.8.13 should resolve that problem.

**Comment by mkurz** [comment] 2022-01-29 22:45
@ianknowles does Play 2.8.13 work for you?

**Comment by mkurz** [comment] 2022-02-16 12:26
@ianknowles I am closing this as duplicate of #11086, however, if the problem still occurs with Play  2.8.13, please let us know. Thanks!

**Closed by mkurz** 2022-02-16 12:26 UTC
