### ISSUE TITLE
Improve Play.WS redirect behaviour

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#3948] opened 2015-02-19 07:01 UTC
It'd be great for Play.WS to support `307` redirect status codes as I understand that it does not presently. In addition Play.WS should allow for non `GET` or `HEAD` methods to be used for these redirects where the target URL is trusted. My suggestion is to add an new method to express this trust e.g.:

``` scala
WS.url(someTrustedServiceUrl).withFollowRedirects(POST) ...
```

i.e. as well as the existing `withFollowRedirects(follow: boolean)`, have a method that declares the http method that may be followed. Note also that with `307` redirects, the method is not permitted to change.

In addition to supporting the above redirect logic, we should honour any `Cache-Control` header that is returned with a `307`, in particular, `max-age`. Play.WS should cache redirects accordingly.

**Comment by wsargent** [comment] 2015-02-23 18:10
I can take this.

**Comment by wsargent** [comment] 2015-02-24 22:17
It looks like 307 is covered in the internal redirect method:

https://github.com/AsyncHttpClient/async-http-client/blob/1.8.x/src/main/java/com/ning/http/client/providers/netty/NettyAsyncHttpProvider.java#L1967

``` java
        if (redirectEnabled && (statusCode == 302 || statusCode == 301 || statusCode == 303 || statusCode == 307)) {
````

**Comment by huntc** [comment] 2015-02-24 22:27
I suspect that the problem then may be that with `307`, the method is being changed to a `GET`. Just guessing, but `307` shouldn't change the method.

Here's the definitions from [Wikipedia](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection):

> 303 - The response to the request can be found under another URI using a GET method. When received in response to a POST (or PUT/DELETE), it should be assumed that the server has received the data and the redirect should be issued with a separate GET message.

> 307 - In this case, the request should be repeated with another URI; however, future requests should still use the original URI. In contrast to how 302 was historically implemented, the request method is not allowed to be changed when reissuing the original request. For instance, a POST request should be repeated using another POST request.

**Comment by wsargent** [comment] 2015-02-24 22:32
Okay, will change that.

**Comment by wsargent** [comment] 2015-02-24 22:35
I believe this may be related to https://github.com/gatling/gatling/issues/2423

**Comment by wsargent** [comment] 2015-02-24 22:58
Looks like AsyncHttpClient specified the current GET behavior in https://github.com/AsyncHttpClient/async-http-client/commit/9d922ad6ac44a2acffaba635f0011ffa5357efab

**Comment by huntc** [comment] 2015-02-24 23:02
Is this the line? https://github.com/AsyncHttpClient/async-http-client/commit/9d922ad6ac44a2acffaba635f0011ffa5357efab#diff-f86cd91228f3cde51e071f609d997d5bR2127

**Comment by wsargent** [comment] 2015-02-24 23:02
This is odd -- per https://github.com/AsyncHttpClient/async-http-client/blob/1.8.x/src/main/java/com/ning/http/client/providers/netty/NettyAsyncHttpProvider.java#L1979-L1981 the status code is 307, and so still shouldn't be set directly.

**Comment by huntc** [comment] 2015-02-24 23:09
So may be 307 is being handled correctly, however their tests don't appear to test the method, so it is hard to know. Perhaps the problem is within Play.WS then. I do recall seeing mention only of 301 and 302 in there.

**Comment by wsargent** [comment] 2015-02-26 01:59
I'm not seeing it...

```
/*
 * Copyright (C) 2009-2015 Typesafe Inc. <http://www.typesafe.com>
 */
package play.it.libs

import play.it.tools.HttpBinApplication

import play.api.test._
import play.api.mvc._
import play.it._
import scala.concurrent.Await
import scala.concurrent.duration._
import play.api.libs.iteratee._
import play.api.libs.concurrent.Promise
import scala.concurrent.ExecutionContext.Implicits.global
import java.io.IOException

object WSRedirectSpec extends PlaySpecification with ServerIntegrationSpecification with NettyIntegrationSpecification {

  sequential

  def app = HttpBinApplication.app

  val redirLocation = s"http://localhost:$testServerPort/redirLocation"

  def withResult[T](block: Port => T) = {
    val port = testServerPort
    running(TestServer(port, FakeApplication(withRoutes = {
      case (_, "/redirect307") =>
        Action(Results.TemporaryRedirect(redirLocation))
      case (method, "/redirLocation") =>
        Action(Results.Ok(s"hello world, redirect method was $method"))
      case (method, path) =>
        Action(Results.Ok(s"incorrect location, $method = $path"))
    }))) { block(port) }
  }

  "307 Redirect" should {
    import play.api.libs.ws.{ WS, WSSignatureCalculator, WSRequest }
    import play.api.Play.current

    "make a GET request and result in a GET response" in withResult { port =>
      val req = WS.url(s"http://localhost:$port/redirect307").withFollowRedirects(true).get

      Await.result(req, Duration(1, SECONDS)).body aka "body" must_== "hello world, redirect method was GET"
    }

    "make a POST request and result in a POST response" in withResult { port =>
      val req = WS.url(s"http://localhost:$port/redirect307").withFollowRedirects(true).post("hello")

      Await.result(req, Duration(1, SECONDS)).body aka "body" must_== "hello world, redirect method was POST"
    }
  }
}
```

```
./build "testOnly play.it.libs.WSRedirectSpec"
```

```
[info] WSRedirectSpec
[info]
[info] 307 Redirect should
[info] + make a GET request and result in a GET response
[info] + make a POST request and result in a POST response
[info]
[info] Total for specification WSRedirectSpec
[info] Finished in 3 seconds, 518 ms
[info] 2 examples, 0 failure, 0 error
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 15 s, completed Feb 25, 2015 5:57:07 PM
```

**Comment by huntc** [comment] 2015-02-26 02:15
Thanks @wsargent . We are using Play 2.3 - could this problem have been addressed since then?

**Comment by huntc** [comment] 2015-02-26 03:34
Here's a transcript of what was causing an issue for us before. We'll also try again, but I'm also wondering whether the presence of any other headers are contributing, in particular `Cache-Control`. #clutchingatstraws. :-)

```
huntc$ curl -v http://192.168.59.103:9008/services/visualizer
* Hostname was NOT found in DNS cache
*   Trying 192.168.59.103...
* Connected to 192.168.59.103 (192.168.59.103) port 9008 (#0)
> GET /services/visualizer HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 192.168.59.103:9008
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< Location: http://172.17.0.26:9000/visualizer
< Cache-Control: private="Location", max-age=60
* Server akka-http/2.3.9 is not blacklisted
< Server: akka-http/2.3.9
< Date: Thu, 26 Feb 2015 03:32:09 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 45
< 
* Connection #0 to host 192.168.59.103 left intact
Located at http://172.17.0.26:9000/visualizer
```

**Comment by wsargent** [comment] 2015-02-26 16:30
@huntc imma need a reproducible test case...

**Comment by huntc** [comment] 2015-02-27 01:15
We may have found the issue, and it could be that Play's support for `307` is indeed there. We will do some further testing and report back here.

Supporting the `Cache-Control` `max-age` header value is something that is still required, but not so urgently; perhaps in the next couple of weeks.

**Comment by wsargent** [comment] 2015-02-27 20:26
@huntc Just confirming -- you need the cache-control header support on Play 2.3.x, and then we can forward port onto 2.4.x?

**Comment by huntc** [comment] 2015-03-09 06:47
@wsargent I've improved my little side library so that my client style APIs can take a cache-like structural type as an argument. I was thinking that this may be a useful approach to supplying Play.WS with a cache also. For example:

```scala
val cache = ... // some "cache-like" thing
WS.url("someurl").withCache(cache)...
```

I think it is important to provide WS with the cache, and not for it to assume that it has it all to itself.

This all begs the question as to what the "cache-like" type would look like. Here's what I've come up with:

```scala
  type CacheLike = {
    def getOrElseUpdate(uri: String)(op: => Future[Option[(String, Option[FiniteDuration])]]): Future[Option[String]]
  }
```

I chose `getOrElseUpdate` as that is what is provided by `MapLike`. So the above is therefore map-like, but only with respect to `getOrElseUpdate`. The `op` is an operation responsible for performing the request and then returning the value to cache, along with how long the value should be cached for (if any). The future result is influenced by spray-cache in order to avoid the thundering herds issue.

WDYT?

**Comment by wsargent** [comment] 2015-03-10 20:24
Okay, I have something working up at

https://github.com/wsargent/playframework/tree/ws-caching

Not quite ready for code review yet, but if you're curious...

Will Sargent
Consultant, Professional Services
Typesafe <http://typesafe.com>, the company behind Play Framework
<http://www.playframework.com>, Akka <http://akka.io> and Scala
<http://www.scala-lang.org/>

**Comment by marcospereira** [comment] 2017-02-09 06:33
@wsargent play-ws now supports cache.

Can we close this?

**Comment by wsargent** [comment] 2017-03-18 17:05
We can close this now.

**Closed by wsargent** 2017-03-18 17:05 UTC
