### ISSUE TITLE
ArrayIndexOutOfBoundsException when encountering an empty cookie value

### ISSUE THREAD

**Issue by jleider** [playframework/playframework#7695] opened 2017-08-03 20:20 UTC
Play 2.6 using the Scala API
Mac OS 10.11.6
Oracle 1.8.0_131

During the Play 2.6 upgrade process I found that it is possible in Play 2.5 to create an empty flash cookie values which causes an `ArrayIndexOutOfBoundsException` for every request thereafter in Play 2.6 until the cookie is updated. The error is either swallowed or non existent in Play 2.5.

To reproduce:

Take the `request.flash` value and add it back to the response by `response.flashing(request.flash)`. If the `request.flash` value is empty you will now have an empty flash cookie value which will cause an `ArrayOutOfBoundsException` on future requests at least in Play 2.6.

I am unaware if it is possible to create empty flash cookie values in Play 2.6. Either way, the framework should handle an empty cookie value without an exception.

**Comment by el-dom** [comment] 2017-08-03 20:31
You might want to check out #7680

**Comment by marcospereira** [comment] 2017-08-03 20:33
Closing as a duplicate of #7680. Also, see #7688.

**Closed by marcospereira** 2017-08-03 20:33 UTC
