### ISSUE TITLE
2.3 lazy loading @ManyToMany race conditions

### ISSUE THREAD

**Issue by michalzubkowicz** [playframework/playframework#3156] opened 2014-07-09 14:29 UTC
On slower systems when I'm trying to access Entity field by getter getOpcjaList is returning empty list.

**Comment by heat** [comment] 2016-02-26 12:22
I can't reproduce that error even lower vm. Maybe we can close this issue. @cchantep could you tell which play version did u use or if this issue was solved.

**Comment by wsargent** [comment] 2016-03-19 05:07
Closing as not reproducible.

**Closed by wsargent** 2016-03-19 05:07 UTC
Labels: needs info, needs-verification
