### ISSUE TITLE
Reflective calls in split routes file

### ISSUE THREAD

**Issue by pauldraper** [playframework/playframework#5029] opened 2015-08-24 16:06 UTC
Splitting routes files causes a warning about reflective calls.

> [warn] /home/paul/test/conf/routes:1: 
> reflective access of structural type member method unapply should be 
> enabled 
> [warn] by making the implicit value scala.language.reflectiveCalls visible. 

https://groups.google.com/forum/#!topic/play-framework/nNr2NdBtWuw
https://groups.google.com/forum/#!topic/play-framework/gMZRKqQpsK0

The routes generator should either be changed to not use reflective calls, or `scala.language.reflectiveCalls` should be added to `routesImport` by default.

**Comment by jroper** [comment] 2015-08-25 03:21
Interesting - that is a problem with the code we're generating, our generated code shouldn't do any reflective calls. What version of Play are you seeing this in? The links you post refer to Play 2.1 and 2.2, does it happen in 2.4?  Our tests for the routes compiler actually compile with [`-Xfatal-warnings`](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt#L62), and there are definitely sub routers in those tests, so I'd be surprised if the issue still exists in Play 2.4.

**Comment by pauldraper** [comment] 2015-09-22 00:02
It happens for me in 2.3.

I will check 2.4.

**Comment by marcospereira** [comment] 2019-05-08 20:30
Closing since I've could not reproduce this in 2.6+.

**Closed by marcospereira** 2019-05-08 20:30 UTC
Labels: status:backlog, status:needs-verification
