### ISSUE TITLE
NTLM header is rendered incorrectly with AkkaHttpServer

### ISSUE THREAD

**Issue by SriniMangipudi** [playframework/playframework#8149] opened 2018-01-11 14:39 UTC
After upgrading to Play 2.6. AkkaHttpServer has become the default and NTLM authentication is failing because of a bug in AkkaHttpServer (https://github.com/akka/akka-http/pull/1329)
It used to work with previous version of Play framework.
is there a way to fix this in Play framework or How do I use the new version of AkkaHttpServer with Play.
Appreciate any inputs. 

### Play Version (2.5.x / etc)
Play version 2.6

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.
1. Server start with play.core.server.AkkaHttpServer] - Listening for HTTP 
2. User tries to login to the system with NTLM authentication
3. NTLM negotiation happens and the user logs in to the system

### Actual Behavior
NTLM authentication is failing because invalid header format generated by server: 
for example: WWW-Authenticate: NTLM ="TlRMTVNTUAABAAAABzIAAAYABgArAAAACwALACAAAABXT1JLU1RBVElPTkRPTUFJTg=="
The correct header should be something like WWW-Authenticate: NTLM TlRMTVNTUAABAAAABzIAAAYABgArAAAACwALACAAAABXT1JLU1RBVElPTkRPTUFJTg==

Thank you for your help,
Srini

**Comment by dwickern** [comment] 2018-01-17 21:53
This was recently fixed in akka/akka-http#1427. It would be nice to get this fix into Play 2.7.

**Comment by schmitch** [comment] 2018-03-14 22:17
actually the fix is already inside the master branch so at least it will be fixed in 2.7

**Comment by richdougherty** [comment] 2018-03-21 03:56
This is likely to be fixed by #8296 which will be going into the next release of Play 2.6.x. If you can supply exact headers that reproduce the issue then I can verify this.

**Comment by SriniMangipudi** [comment] 2018-03-26 14:32
Hi Rich, 
To reproduce the issue, you will have to run an application with NTLM authentication enabled.
So if there is a protected resource and the user is not already authenticated, Server responds back with Unauthorized error with WWWAuthenticate: NTLM header and then the NTLM negotiation happens. 
Following link has the details: https://blogs.msdn.microsoft.com/chiranth/2013/09/20/ntlm-want-to-know-how-it-works/

Hope this information helps.

Thanks,
Srini

**Comment by marcospereira** [comment] 2018-04-06 19:58
Hi @SriniMangipudi, 

We believe that [Play 2.6.13](https://discuss.lightbend.com/t/play-2-6-13-released/629) contains a fix for this problem. Could you please try this new version and confirm it is working for you?

I'm not closing this since we don't have a test for your specific use case, but everything should be working now.

Best.

**Comment by richdougherty** [comment] 2018-04-09 22:30
Thanks @SriniMangipudi for the info, I didn't get a chance to reproduce from your instructions. Is there any chance that you can test against the new 2.6.13 release of Play?

**Comment by richdougherty** [comment] 2018-05-07 21:33
I'm going to assume this is fixed and close this issue now. Please reply/reopen if the bug is still present.

**Closed by richdougherty** 2018-05-07 21:33 UTC
Labels: bug, help:needs-verification, topic:upstream

**Comment by dwickern** [comment] 2018-05-07 21:34
👍 It's working for me now. I was able to switch from netty to akka-http.

**Comment by richdougherty** [comment] 2018-05-22 01:35
Thanks @dwickern for the confirmation. :+1:
