### ISSUE TITLE
BodyParsers.parse.json should answer a BadRequest with JsError.toFlatJson instead of JsError.toFlatForm

### ISSUE THREAD

**Issue by dgouyette** [playframework/playframework#3893] opened 2015-02-04 15:24 UTC
When you defined a json body parser on an action, and when you got an error,
you expect a status code = 400 + an json error content. 

```
{
    "obj.name": [
        {
            "msg": "error.path.missing",
            "args": []
        }
    ]
}
```

But when the submitted json is invalid, the body parser is using JsError.toFlatForm.
So you obtain a html page with a text message. I can't use the error page with my REST client or my javascript client.

For the moment i'm using the following json body parser. WDYT ?

```
def jsonWithFlatJson[A](implicit reader: Reads[A]): BodyParser[A] =
    BodyParser("json reader") { request =>
      import play.api.libs.iteratee.Execution.Implicits.trampoline
      BodyParsers.parse.json(request) mapM {
        case Left(simpleResult) =>
          Future.successful(Left(simpleResult))
        case Right(jsValue) =>
          jsValue.validate(reader) map { a =>
            Future.successful(Right(a))
          } recoverTotal { jsError =>
            Future.successful(Left(Results.BadRequest(JsError.toFlatJson(jsError))))
          }
      }
    }
```

If you want i can provide a pull request + tests

**Comment by gmethvin** [comment] 2015-02-05 04:25
I think the best solution would be to provide some way of customizing the error result (see #3039).

**Comment by jroper** [comment] 2015-02-05 05:56
I think it'd be great to return json by default from the json parser.  But - I think the `onClientError` method should still be invoked, for monitoring or whatever.  In #3629 we were considering adding the exception to `onClientError`, which would allow us to do this, but then @dotta convinced me that's not a good solution.  But now I'm feeling like it is again...

**Comment by tarmath** [comment] 2015-08-22 02:05
+1

**Comment by chrissom** [comment] 2016-02-15 15:01
+1

**Comment by chrissom** [comment] 2016-02-19 17:01
@gmethvin Is it possible to add this issue to the 2.4.7 milestones?

This fix could remove some repeatable code on every controllers.

**Comment by feliperazeek** [comment] 2016-02-24 19:55
+1

**Comment by kyouz** [comment] 2016-07-16 16:27
Hi,

Here are some very interesting and helpful articles, I think you may like them.You may read them here <http://assist.baseil.com/e3kns>

Rushing, amsdta_09@yahoo.com

**Comment by oripwk** [comment] 2017-10-06 11:50
> `JsError.toFlatJson`

For anyone who's reading this in 2017, the method is now called `JsError.toJson`.

**Comment by richdougherty** [comment] 2017-10-09 03:02
By the way #6171 captures the discussion about improving error handling generally.

**Comment by gmethvin** [comment] 2017-10-30 05:48
Duplicate of #5782

**Closed by gmethvin** 2017-10-30 05:48 UTC
Labels: enhancement
