### ISSUE TITLE
Unable to add header to `Http.Request` object using the new method `adding()`

### ISSUE THREAD

**Issue by moga111** [playframework/playframework#11640] opened 2023-01-26 15:41 UTC
### Play Version

2.8.18

### API

Java

### Operating System

Mac

### JDK

java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

### What is working

`Http.Request`'s `getHeaders().addHeader(..)` works fine but deprecated.

### The problem

`Http.Request`'s `getHeaders().adding(..)` does not add to headers when intercepting the request, and I have to use the deprecated method for now.

You can reproduce this by adding any header to the `Http.Request` object using both methods to see.

**Comment by mkurz** [comment] 2023-01-26 18:43
@moga111 Why do you want to add headers to the request? I you want to add information to the request you should use request attributes: https://www.playframework.com/documentation/2.8.x/Highlights26#Request-attributes

**Comment by moga111** [comment] 2023-01-26 20:39
Hello @mkurz 
Attributes are great, and I should adopt them; however, there are certain uses where I had to intercept the header to add an extra header for our requirements.

The new method `adding()` is considered a replacement for `addHeader()` which is not working in my case, and I believe it is broken.

**Comment by mkurz** [comment] 2023-01-26 20:40
Can you please elaborate your use case? I would be interested why you want to add a header to the request.

**Comment by mkurz** [comment] 2024-03-15 22:27
@moga111 did you find a solution besides using the deprecated methed meanwhile? I still think request attributes are the way to go here.
Actually I get your point, you can not add headers to a request yourself anymore, but actually I would argue this is by design, the headers on a request are immutable and you can not modify them or add new ones. That's because the request object and its headers get created in the backend server and you are not supposed to add new headers to the request - because the headers are sent by the client, why would you add more headers in your code to the request instance?

> there are certain uses where I had to intercept the header to add an extra header for our requirements.

Again, can you please share your use case?

**Comment by mkurz** [comment] 2024-03-17 11:48
Thanks for your feedback @moga111!
Closing this issue as you now use the "correct" way to solve your use case.

**Closed by mkurz** 2024-03-17 11:48 UTC
