### ISSUE TITLE
URL path parse exception

### ISSUE THREAD

**Issue by bvdmitri** [playframework/playframework#3945] opened 2015-02-18 08:57 UTC
If you will type host:// your application will cause parse exception, and you can do nothing to catch this error. This error even is on the official site, if you will type https://playframework.com/asdasd site will redirect you to 404 page, but https://playframework.com// cause exception and there is no redirection, only error message

**Comment by hermanbanken** [comment] 2015-02-18 17:18
This is already discussed in #2342. This issue was closed but the discussion continued. @jroper, how about still compressing the first two slashes in the relative path? (I can try to do this)

**Comment by jroper** [comment] 2015-02-19 01:25
Closing as a duplicate of #2342.  If someone wants to add a configuration flag where double slashes are compressed, happy to accept that feature, but the default should be spec conformance, which is to return 400 errors on `//`.

**Closed** 2015-02-19 01:26 UTC
