### ISSUE TITLE
RedirectHttpsFilter spams in console

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#7592] opened 2017-07-07 13:44 UTC
### Play Version (2.5.x / etc)

2.6.1

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

macOS 10.12.5

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### Library Dependencies

None

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Add
```scala
play.filters.enabled += play.filters.https.RedirectHttpsFilter
```
to `application.conf`
2. Run in dev mode
3. Open `localhost:9000`
4. `RedirectHttpsFilter` is ignored and you see non-redirected page

### Actual Behavior

1. All from expected
2. Annoying messages
```
[info] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.redirectEnabled flag is not set.
[info] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.redirectEnabled flag is not set.
[info] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.redirectEnabled flag is not set.
...
```
in console after every request. In dev mode, of course.

How to disable these messages?

**Comment by marcospereira** [comment] 2017-07-07 14:10
You can add the following line to your `conf/logback.xml` file:

```xml
<logger name="play.filters.https.RedirectHttpsFilter" level="WARN" />
```

But I think you really should consider activating it in dev environment. At least I prefer to keep dev as close as possible to staging/prod environments.

I'm closing this since it is not a bug. Anyway, we can reopen it later if necessary.

**Closed by marcospereira** 2017-07-07 14:10 UTC

**Comment by PromanSEW** [comment] 2017-07-07 14:22
@marcospereira thanks for solution

**Comment by jamesward** [comment] 2018-05-30 16:14
While the workaround is decent I think the default shouldn't be so noisy and this should be re-opened.

**Comment by wsargent** [comment] 2018-05-30 16:24
If you don't want this filter activated in dev, don't activate it in dev.  Set up a `production.conf` that gets added in deploy and set it up through sbt-native-packager: https://www.scala-sbt.org/sbt-native-packager/recipes/package_configuration.html
