### ISSUE TITLE
Could not resolve substitution to a value: ${play.server.dir}]

### ISSUE THREAD

**Issue by Christewart** [playframework/playframework#10464] opened 2020-10-03 13:59 UTC
### Play Version

>addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.2")

### API

Scala

### Operating System

>Linux suredbits-XPS-13-9370 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### JDK

>openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)

### Expected Behavior

1. I have a library that resolves a configuration file [here](https://github.com/bitcoin-s/bitcoin-s/blob/856f88f0ddbb7adc437ecb1cdc6ebf3c7128cd76/db-commons/src/main/scala/org/bitcoins/db/AppConfig.scala#L230)
2. I do this resolving in a controller
3. Things should just work without throwing an exception

### Actual Behavior

When the controller is created on server startup, I get this error

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[UnresolvedSubstitution: reference.conf @ jar:file:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-server_2.13/2.8.2/play-server_2.13-2.8.2.jar!/reference.conf: 90: Could not resolve substitution to a value: ${play.server.dir}]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:359)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:261)
        at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:109)
        at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:105)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
        at play.core.server.Server$.getHandlerFor(Server.scala:129)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:316)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:191)
        at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1284)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: reference.conf @ jar:file:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-server_2.13/2.8.2/play-server_2.13-2.8.2.jar!/reference.conf: 90: Could not resolve substitution to a value: ${play.server.dir}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:111)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.ConfigDelayedMerge.resolveSubstitutions(ConfigDelayedMerge.java:132)
        at com.typesafe.config.impl.ConfigDelayedMerge.resolveSubstitutions(ConfigDelayedMerge.java:59)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
```

**Comment by mkurz** [comment] 2021-02-01 16:41
I had a quick look in the code you referenced.
The problem is that you parse all `reference.conf`s, but that doesn't mean they get resolved. That's why `play.server.dir` never gets set because `user.dir` isn't "available", see https://github.com/bitcoin-s/bitcoin-s/blob/856f88f0ddbb7adc437ecb1cdc6ebf3c7128cd76/db-commons/src/main/scala/org/bitcoins/db/AppConfig.scala#L201

I don't have everything in my head right now but what you need to do is to resolve your `classPathConfig` with something like 
`.withFallback(context.initialConfig())` where `context` is Play's `ApplicationLoader.Context`
_or_
I think you can also use resolve it with one of those `Configuration.load(...)` methods.
Then the `classPathConfig` should get resolved with all that env vars, etc.

Anyway, not a Play bug.

**Closed by mkurz** 2021-02-01 16:41 UTC
