### ISSUE TITLE
Hello World page does not work

### ISSUE THREAD

**Issue by ranmx** [playframework/playframework#9942] opened 2019-12-24 09:40 UTC
### Play Version

2.8.x

### API

nop

### Operating System

linux

### JDK

java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

### Library Dependencies

nop 

### Expected Behavior

1. copy and paste examples in https://www.playframework.com/documentation/2.8.x/ImplementingHelloWorld should work

### Actual Behavior

comes out the error:
```
Compilation error
not enough arguments for method apply: (title: String, assetsFinder: controllers.AssetsFinder)(content: play.twirl.api.Html)play.twirl.api.HtmlFormat.Appendable in object main.
Unspecified value parameter assetsFinder.

In /users/a/play-samples-play-scala-starter-example/app/views/hello.scala.html:1
1@main("hello") { 
2    <section id="top">
3        <div class="wrapper">
4            <h1>Hello</h1>
5        </div>
```

**Comment by ranmx** [comment] 2019-12-24 12:51
it's due to the fact that the examples in play-samples-play-scala-starter-example are different from that of in playframework

**Comment by ignasi35** [comment] 2020-01-09 09:54
You're right. The tutorial is incorrect since `main` requires an `assetsFinder` paramter since https://github.com/playframework/play-samples/commit/dc2b3feaae073211d635899cb958ad7fabc3ca42

**Comment by ignasi35** [comment] 2020-01-09 11:35
The tutorial is incorrect for `scala` only. The problem is there's a single tutorial for both `java` and `scala` and the sample code the tutorial is based on differs in each implementation.

The commit https://github.com/playframework/play-samples/commit/dc2b3feaae073211d635899cb958ad7fabc3ca42 moved the `play-scala-starter-example` to config-based `Assets` (and use of `AssetsFinder`) but the `play-java-starter-example` remained the same. This means the [snippets](https://github.com/playframework/playframework/blob/2.8.x/documentation/manual/tutorial/code/javaguide/hello/hello.scala.html#L6) in the tutorial are only valid for the Java users.

We have two options:

1. move `play-scala-starter-example` back (undo https://github.com/playframework/play-samples/commit/dc2b3feaae073211d635899cb958ad7fabc3ca42)
2. upgrade `play-java-starter-example` to config-based assets management.

The problem with option `1.` is that it uses deprecated API (that was the motivation for the change in the commit linked in `1.`)

The problem with option `2.` is that the resulting code is a bit too verbose for a tutorial because `assetsFinder` has to be injected and passed everywhere. The impact of injecting and using `assetsFinder` is small in the scala implementations thanks to the use of implicits but in the java code it's very noisy in my opinion:

```java
public class HomeController extends Controller {

    private final AssetsFinder assetsFinder;

    @Inject
    public HomeController(AssetsFinder assetsFinder) {
        this.assetsFinder = assetsFinder;
    }

    /**
     * An action that renders an HTML page with a welcome message.
     * The configuration in the <code>routes</code> file means that
     * this method will be called when the application receives a
     * <code>GET</code> request with a path of <code>/</code>.
     */
    public Result index() {
        return ok(
            index.render(
                "Your new application is ready.",
                assetsFinder
            ));
    }
}
```

as opposed to the current code:

```java
public class HomeController extends Controller {

    /**
     * An action that renders an HTML page with a welcome message.
     * The configuration in the <code>routes</code> file means that
     * this method will be called when the application receives a
     * <code>GET</code> request with a path of <code>/</code>.
     */
    public Result index() {
        return ok(
            index.render(
                "Your new application is ready."
            ));
    }
}
```

Specially considering the tutorial only highlights very small snippets of the previous code:

![Screenshot 2020-01-09 at 12 33 11](https://user-images.githubusercontent.com/762126/72064530-59dbea80-32dc-11ea-9a5f-831ae6e42df8.png)

The root problem is the code in the tutorial is not the code on the sample app, they are out-of-sync copies.

**Comment by mkurz** [comment] 2020-01-21 10:42
Fixed by https://github.com/playframework/playframework/pull/9982 and https://github.com/playframework/play-samples/pull/83 
@ignasi35 please re-open if I am wrong.

**Closed by mkurz** 2020-01-21 10:42 UTC
Labels: triage

**Comment by ignasi35** [comment] 2020-01-21 12:08
You are not wrong @mkurz. :-)
