### ISSUE TITLE
[2.4.2] Custom java http error handler not trigger

### ISSUE THREAD

**Issue by jCalamari** [playframework/playframework#4857] opened 2015-07-15 11:30 UTC
Not sure if configuration issue or play issue, so here we go.
I have implemented custom error handler:

```
package global;

public class CustomHttpErrorHandler implements HttpErrorHandler {

    @Override
    public F.Promise<Result> onClientError(Http.RequestHeader request, int statusCode, String message) {
        if (statusCode == play.mvc.Http.Status.BAD_REQUEST) {
           // ...
        }
        return null;
    }

    @Override
    public F.Promise<Result> onServerError(Http.RequestHeader request, Throwable exception) {
        Logger.error("Server error", exception);
        // ...
        return pure(Controller.internalServerError("Unexpected exception."));
    }

}
```

Configured it in application.conf:

```
play {
  // ...
  http {
    errorHandler = "global.CustomHttpErrorHandler"
  }
}
```

And I was trying to test it with a restful call to controller throwing runtime exception:

```
public class CustomController extends Controller {

    public Result test() {
        throw new Rollback("Rolling back");
    }

}
```

Result: custom java error handler is not triggered, instead scala GlobalSettingsHttpErrorHandler is used. See stacktrace:

```
[error] application - 

! @6mng3d1oa - Internal server error, for (GET) [/killme] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[Rollback: Rolling back]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library.jar:na]
	at scala.util.Try$.apply(Try.scala:191) [scala-library.jar:na]
Caused by: models.services.transaction.Rollback: Rolling back
	at controllers.CustomController.test(CustomController.java:10) ~[classes/:2.4.2]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$110$$anonfun$apply$110.apply(Routes.scala:2943) ~[classes/:na]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$110$$anonfun$apply$110.apply(Routes.scala:2943) ~[classes/:na]
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[play_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library.jar:na]

```

Btw, I am using custom `GuiceApplicationLoader`

**Comment by demianberjman** [comment] 2015-08-27 14:22
Hi. Same issue. I follow the code and found this at trait play.core.server.Server:

```scala
def logExceptionAndGetResult(e: Throwable) = {
      DefaultHttpErrorHandler.onServerError(request, e)
}
```

LazyHttpErrorHandler instead of DefaultHttpErrorHandler should do the trick (?).

Cheers,

**Comment by Yurii-Buhryn** [comment] 2015-11-05 15:36
HI, Same issue

**Comment by jCalamari** [comment] 2015-11-05 19:55
There is a workaround. Override ```HttpErrorHandler``` binding in custom ```ApplicationLoader```

**Comment by breadfan** [comment] 2015-11-10 16:20
Same for us!

**Comment by suya55** [comment] 2015-12-01 06:02
Same issue!!

**Comment by keithblaha** [comment] 2015-12-02 22:31
:+1:

**Comment by mkurz** [comment] 2015-12-02 22:45
Are you using 2.4.4?

**Comment by keithblaha** [comment] 2015-12-02 23:57
I tried first with 2.4.2, and then with 2.4.4 and had same problem either way

**Comment by MartijnDwars** [comment] 2016-01-02 16:27
I'm using 2.4.4 and having the same issue.

**Comment by jesterhazy** [comment] 2016-01-19 01:52
Still not working in 2.4.6.

**Comment by mkurz** [comment] 2016-01-19 08:23
I can **not** reproduce this bug using Play 2.4.6.
I also have a `CustomApplicationLoader`.

Can someone provide a test-project (on GitHub) which actually reproduces the bug?

**Comment by mkurz** [comment] 2016-01-19 08:43
[This](https://github.com/mkurz/errorHandlerTest) is the test project I used. Feel free to fork and modify it to reproduce the bug.

**Comment by jesterhazy** [comment] 2016-01-19 19:44
uh oh. i misread the thread -- i am actually having the problem with play-scala, not play-java.

[Here](https://github.com/jesterhazy/playScalaCustomErrorHandlerTest) is a (scala) demonstration of the bug.

**Comment by jesterhazy** [comment] 2016-01-19 21:04
Opened a new issue for play-scala version of this bug.

**Comment by jesterhazy** [comment] 2016-01-19 21:23
play-scala is actually working correctly. can't speak to the (original) java issue.

**Comment by mkurz** [comment] 2016-01-20 07:14
I also tried with Play 2.4.2 - still can not reproduce the issue.
@jCalamari @Yurii-Buhryn @demianberjman @breadfan @suya55 @keithblaha @MartijnDwars could you please provide a test project which shows the error?

**Comment by MartijnDwars** [comment] 2016-01-20 08:17
Strange, I just tried again and the error handler seems to be working. No idea what went wrong previously.

**Comment by marcospereira** [comment] 2016-02-19 02:37
Can we close this issue?

**Comment by mkurz** [comment] 2016-04-06 10:25
I am closing this issue. I can not reproduce the issue and no one provides a sample project/code for reproduction.

Feel free the open a new issue in case you run into problems again.

**Closed by mkurz** 2016-04-06 10:25 UTC
Labels: needs info, needs-verification
