### ISSUE TITLE
CORS broken in Play 2.7

### ISSUE THREAD

**Issue by nextdtinc** [playframework/playframework#8732] opened 2018-10-26 05:00 UTC
### JDK openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### Expected Behavior
Play should accept HTTP requests from other hosts when CORS is enabled.
By default `play.filters.enabled += "play.filters.cors.CORSFilter"` should allow all hosts.

### Actual Behavior
Request is rejected with error message `[warn] p.f.c.CORSFilter - Invalid CORS request;Origin=Some(null);Method=GET;Access-Control-Request-Headers=None`
1. open attached SBT project
2. verify in a browser that http://localhost:9000 responds with a valid result ("123")
3. open `cors.html` in a browser, which tries to access localhost:9000 via Ajax, but gets the error: `[warn] p.f.c.CORSFilter - Invalid CORS request;Origin=Some(null);Method=GET;Access-Control-Request-Headers=None`

### Minimum viable project demonstrating this bug is attached

[cors-example.zip](https://github.com/playframework/playframework/files/2517760/cors-example.zip)

**Comment by gmethvin** [comment] 2018-10-27 06:14
I think this is a duplicate of #8600. Does it work when the origin is not null?

**Comment by gmethvin** [comment] 2018-10-27 07:38
I've verified the example works for me when served from an HTTP origin, so I think this is a duplicate. Closing.

**Closed by gmethvin** 2018-10-27 07:38 UTC
