### ISSUE TITLE
email validator fails for 1 character long hostnames

### ISSUE THREAD

**Issue by gandalfu** [playframework/playframework#4880] opened 2015-07-22 21:18 UTC
The email validator in fails to validate someone@x.org as a valid email address.

One character email addresses are not handled by the current regex which assumes a minimum of two characters for the host name.)

Examples: x.org, q.com

**Comment by azemm** [comment] 2015-07-24 13:53
They use regex ? why use regex when this problem has already been solved by others.

**Comment by marcospereira** [comment] 2015-07-26 22:33
@gandalfu do you mind submitting a PR to solve this?

Here are the places were there are a regex to validate an email:

1. [framework/src/play/src/main/scala/play/api/data/validation/Validation.scala](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/data/validation/Validation.scala#L76-L83)
2. [framework/src/play-java/src/main/java/play/data/validation/Constraints.java](https://github.com/playframework/playframework/blob/master/framework/src/play-java/src/main/java/play/data/validation/Constraints.java#L364-L365)
3. [framework/src/play-json/src/main/scala/play/api/libs/json/JsConstraints.scala](https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/main/scala/play/api/libs/json/JsConstraints.scala#L139-L140)

It would be even better if you can add some tests. ;-)

**Comment by wsargent** [comment] 2015-07-27 17:49
Ideally, you'd use something like isEmail: https://github.com/dominicsayers/isemail / https://code.google.com/p/isemail/

**Comment by azemm** [comment] 2015-07-27 17:59
Instead of writing complex regex, why not use common email from apache who already solve this problem.

**Comment by marcospereira** [comment] 2015-07-27 18:38
@azemm I think you are talking about commons validator, instead of commons email. I think it is a good idea to use it instead of rewrite all the regexes again (by the way, commons validator is also using regexes to validate emails).

**Comment by jroper** [comment] 2015-08-05 01:42
This is a duplicate of #4022, the issue was fixed in Play 2.4.0, and discussion of why we use a regex, where that regex came from, and our approach to email validation can be found on the #4022 ticket.  Specifically, we didn't write any complex regex, we simply copied a regex from the HTML5 standard.

**Closed by jroper** 2015-08-05 01:42 UTC
Labels: defect
