### ISSUE TITLE
[2.6.9] The server was not able to produce a timely response to your request error after 20 seconds

### ISSUE THREAD

**Issue by almothafar** [playframework/playframework#8096] opened 2017-12-14 12:37 UTC
When I do request and wait for more than 20 seconds, the request fails with the following message:

> The server was not able to produce a timely response to your request.
> Please try again in a short while!

And status 503

### Play Version (2.6.9)
And it is OK in version 2.6.7 no problem there, so I downgraded for now.

### API (Scala / Java / Neither / Both)
Java / so it is maybe Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

### Expected Behavior
It should be taking my config:

```
play.server {
  akka {
    requestTimeout = 180s
  }
  http {
    idleTimeout = 180s
  }
}
```

### Actual Behavior
Status code with 503 and error message:

> The server was not able to produce a timely response to your request.
> Please try again in a short while!

### Reproducible Test Case
Inside any API in the controller, I do sleep for 20 seconds, something like:

```
public CompletionStage<Result> getOrderDetails(String orderId) throws InterruptedException {
        Thread.sleep(20 * 1000); // 20 seconds
        Order order = Ebean.find(Order.class).where().eq("orderId", orderId).findOne();
        if (order != null) {
                return CompletableFuture.completedFuture(ok(Json.toJson(order)));
        }
        thorw new CustomException("Order not found");
}
```

**Comment by almothafar** [comment] 2017-12-14 12:38
Reference #7067
Maybe this issue is back again

**Comment by marcospereira** [comment] 2017-12-14 22:16
Hi @almothafar, 

Is this something you see in DEV or PROD mode? For DEV mode, you need to set these values like documented here:

https://playframework.com/documentation/2.6.x/ConfigFile#Using-with-the-run-command

And I was not able to reproduce it in PROD mode. I have the following configurations:

```HOCON
play.server.http.idleTimeout = 60s
play.server.akka.requestTimeout = 40s
```
And the following action:

```scala
def neverFinish = Action.async {
  import scala.concurrent._
  Future.never
}
```
------
I've just noticed that we don't have shortcuts for these properties like we have `http.port`, `http.address` and others. Maybe we can have another issue to handle that.

**Comment by almothafar** [comment] 2017-12-14 22:52
Not got a chance to test that in production, I got the problem before I deploy to production while debugging, using IntelliJ Idea IDE and on port 9000 with predefined config for sbt, but for the config that I running is the same `-Dhttp.port=9000`

I can't see how the config that you mentioned would help, as I said, I have no problem with previous versions, I got API that takes like 2minutes to finish before return result, all was working from 2.6.1 (the first version that I started with) until 2.6.7 and no issues, but 2.6.9 is directly noticeable.

But for sure this is happening right now in DEV, I will give it a try tomorrow with my stage environment that running PROD.

**Comment by schmitch** [comment] 2017-12-16 11:34
@marcospereira I think the problem is that play uses the default request timeout when no timeout is set. 
We should probably set the timeout in Dev Mode (and only in Dev mode) to `infinite`

**Comment by almothafar** [comment] 2017-12-21 10:08
@schmitch I think in dev mode should respect the config that you provide whatever it was,  I'm a developer and if I want a longer time, I can provide special config file that overrides inherited prod config file, so it is a bad idea to set values inside depends on the environment.

---------

Anyway, it seems I can't reproduce the issue again in prod, indeed it is only dev issue for now! also, it was happening while debugging in dev mode, it seems.

Even in the code provided in OP, it is working for prod and dev, now, the only thing changed for me is the plugin of intelliJ got updated, do you think it was their issue?

**Comment by rtyley** [comment] 2017-12-21 16:37
There's definitely been a change in the Production-mode default for Play from v2.6.6 to v2.6.9 - we noticed lots of timeouts when we switched to v2.6.9, and had to go hunting until we finally saw this issue and realised we need to set `play.server.akka.requestTimeout = 75s` in our `application.conf`.

**Comment by dusanstanojeviccs** [comment] 2017-12-22 23:26
Very easy to recreate and is blocking us from updating the Play version.

Here is a repository with this issue https://github.com/dusanstanojeviccs/play-issue-akka. You can run 'sbt run' open http://localhost:9000, wait 30 seconds and see the issue happen. I have attached a screenshot of what happens:

<img width="1161" alt="screen shot 2017-12-22 at 3 26 32 pm" src="https://user-images.githubusercontent.com/15340338/34314801-82ab890a-e72c-11e7-8eab-1722b952e284.png">

**Comment by ertra** [comment] 2017-12-25 17:36
I can confirm the same problem with 2.6.10 (just upgraded from older version).
Requests, which take longer time gets the timeout message.

I have never seen this message with the older version. (I use Java)

**Comment by saqib-ali** [comment] 2017-12-27 05:27
Yup, same problem with 2.6.10

**Comment by almothafar** [comment] 2017-12-27 09:40
Hmm, I'm still not confident to move into 2.6.10, sitting on 2.6.7 

it seems happening with complex function but simple it is not happening, and still not sure if this is only on dev or with prod as well, even if this is only in dev, this is annoying and making debugging is hard.

Test code I'm trying for the route `GET         /futureMessage/:seconds        controllers.AsyncController.message(seconds: Int)`:

```

    /**
     * An action that returns a plain text message after a delay
     * of <code>seconds</code>.
     * <p>
     * The configuration in the <code>routes</code> file means that this method
     * will be called when the application receives a <code>GET</code> request with
     * a path of <code>/message</code>.
     *
     * @param seconds seconds to delay
     */
    public CompletionStage<Result> message(int seconds) throws InterruptedException {
        return getScheduledFutureMessage(seconds, TimeUnit.SECONDS).thenApplyAsync(Results::ok, exec);
//        return getFutureMessage(seconds).thenApplyAsync(Results::ok, exec);
    }

    private CompletionStage<String> getScheduledFutureMessage(long time, TimeUnit timeUnit) throws InterruptedException {
        CompletableFuture<String> future = new CompletableFuture<>();
        Thread.sleep(1000 * time / 2);
        actorSystem.scheduler().scheduleOnce(
                Duration.create(time / 2, timeUnit),
                () -> future.complete("Hi!"),
                exec
        );
        return future;
    }

    private CompletionStage<String> getFutureMessage(long time) throws InterruptedException {
        long timeInMillis = time * 1000;
        Thread.sleep(timeInMillis / 2);
        return CompletableFuture.supplyAsync(() -> {
            try {
                Thread.sleep(timeInMillis / 2);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            return "Hi !";
        });
    }
```

It is OK like this, but complex flow like:

```
        return validateItemIfExist(cart, userId)
                .thenCompose(validSomething-> placeAnOrder(cart, userId).thenApply(newOrderId -> Pair.of(newOrderId, validItem)))
                .thenCompose(orderIdPairs -> {
                    orderIdAtomicReference.set(orderIdPairs .getLeft());
                    return getValidPaymentMethod(userId, cart.getPaymentInfo(), orderIdPairs.getRight())
                            .thenApply(creditCardDTO -> Pair.of(creditCardDTO, orderIdPairs.getRight()));
                })
                .thenApply(pair -> {
                    PaymentTransactionBO transactionBO = prepareTransactionFromCart(orderIdAtomicReference.get(), cart, pair.getLeft(), pair.getRight());
                    return Pair.of(pair.getLeft(), transactionBO);
                })
                .thenCompose(pair -> paymentService.processPayment(pair.getRight(), true)
                        .thenApply(checkoutDTO -> Pair.of(pair.getLeft(), checkoutDTO)))
                .thenApply(pair -> updateOrderWithPaymentInfo(orderIdAtomicReference.get(), pair).toCompletableFuture().join())
                .thenCompose(pair -> userProfileService.addPaymentBasicInfo(userId, cart.getPaymentInfo(), pair.getLeft())
                        .thenApply(creditCardDTO -> pair))
                .thenCompose(pair -> buildUserOrderHistoryFromUserCartFireBase(pair.getRight(), cart.getOrderShipMethod(), userId))
                .thenCompose(userOrderHistoryObject -> userOrderHistoryService.addUserOrderHistory(userId, userOrderHistoryObject))
                .thenApply(userOrderHistoryId -> Json.newObject().put("userOrderHistoryId", userOrderHistoryId))
                .thenApply(Results::ok)
                .exceptionally(throwable -> {
                    if (!Strings.isNullOrEmpty(orderIdAtomicReference.get())) {
                        ordersService.cancelOrder(orderIdAtomicReference.get())
                                .thenAccept(order -> logger.info("Order with orderId {} canceled", order.getOrderId()));
                    }
                    throw new BusinessException(throwable.getCause() != null ? throwable.getCause().getMessage() : throwable.getMessage());
                });
```

It is throwing the error sometimes, everything in 2.6.7 is OK but it may not be stable after this version I think, in dev and during development, i have issues, for prod, I can't be sure.

**Comment by hiro20v** [comment] 2017-12-27 14:04
### I also experience the same error.
Errors can be seen in this project.
https://github.com/hiro20v/FinePlay/tree/f61f79524273872253c6dbcbd27c0b8000ecf04b

**Steps to Reproduce**
1. ./start.sh
2. http://localhost:9000
3. Click Green User icon
4. Click admin@example.com user
5. Click Signin
6. Click hamburger icon
7. Click Lab
8. Click Application
9. Click Download
10. Input option+H (The hidden UI appears.)
11. Click Download of 'IVD Stream'

**plugins.sbt**
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.7")
No error
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.9")
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.10")
Error occurs

**Comment by saqib-ali** [comment] 2017-12-27 15:38
@rtyley ,

I added   `play.server.akka.requestTimeout = 75s` to application.conf file but that didn't help.

```
akka {
  # "akka.log-config-on-start" is extraordinarly useful because it log the complete
  # configuration at INFO level, including defaults and overrides, so it s worth
  # putting at the very top.
  #
  # Put the following in your conf/logback.xml file:
  #
  # <logger name="akka.actor" level="INFO" />
  #
  # And then uncomment this line to debug the configuration.
  #
  #log-config-on-start = true
  play.server.akka.requestTimeout = 75s
}

```

**Comment by rtyley** [comment] 2017-12-27 15:57
Ah, there are now at least **three** things going on here! :christmas_tree: :gift: :sparkles: 



ONE: Production-mode default `requestTimeout` became _20 seconds_ with Play 2.6.9
-------------

This is the problem I personally had, which I resolved by setting `play.server.akka.requestTimeout = 75s` in our `application.conf`.

I don't think I've seen any comments to indicate that the new default is intentional, it's not mentioned in any migration guide.

TWO: Http-related settings (like `play.server.akka.requestTimeout`) in `application.conf` don't take affect in Dev mode
-----------

This is a known behaviour in Play when you use `run` rather than `start`, and if you want those settings to take affect, you need to use `PlayKeys.devSettings` in your sbt build:

https://playframework.com/documentation/2.6.x/ConfigFile#Using-with-the-run-command

I think this is what @almothafar was encountering, and was explained by @marcospereira in https://github.com/playframework/playframework/issues/8096#issuecomment-351852945

THREE: The key is called `play.server.akka.requestTimeout`, not `akka.play.server.akka.requestTimeout`
-----

@saqib-ali, according to the code snippet [you posted above](https://github.com/playframework/playframework/issues/8096#issuecomment-354131017), you attempted to set configuration on a value called `akka.play.server.akka.requestTimeout`, because you nested `play.server.akka.requestTimeout` inside a stanza called `akka`. So take the key out, and it should work (in Prod mode, see **TWO** above)

e.g.: 
```
play.server.akka.requestTimeout = 75s

akka {
  # "akka.log-config-on-start" is extraordinarly useful because it log the complete
  ...
}
```

**Comment by dusanstanojeviccs** [comment] 2017-12-28 05:23
@rtyley 

Hey, I don't quite understand what you mean by the number TWO. I don't want to set any additional settings (port or address). I have been using 'sbt run' with Play 2.6.6 and it was working intuitively and parsing the timeouts from application.config properly. Please pull my project from the comment above to see that the settings in application.conf are not working with Play 2.10 with 'sbt run' (perhaps I am not setting something correctly?). 

------

From everything I've got so far - there is no way to make timeouts work with 'sbt run' at all with Play 2.10.

Can anyone deny/confirm this? @marcospereira

**Comment by saqib-ali** [comment] 2017-12-28 18:02
@rtyley, thanks that worked! :)

**Comment by git-josip** [comment] 2017-12-29 09:27
@rtyley Thank you for **play.server.akka.requestTimeout** conf value. This is working for me now in PRODUCTION(project built with 'sbt dist' task) with **Play Framework [ Scala] 2.6.9**.
I was going mad last few days as I was thinking nginx is cutting my connections for some reason.

Locally I can not make it to work, but for now that is OK, as long production is working.

**Comment by ertra** [comment] 2017-12-29 22:04
please, will this be fixed in 2.6.11 ?

**Comment by marcospereira** [comment] 2018-01-04 17:36
Hey everyone,

I was able to identify what is causing the behavior. It was a change introduced in https://github.com/playframework/playframework/pull/8064. Before that, `getOptional[Duration]` was returning `Some(Duration.Inf)` if the key value is `null`, since the `durationLoader` handles that:

https://github.com/playframework/playframework/blob/e7c9a45f73bc753fbfd4f7005574bee47d9f2996/framework/src/play/src/main/scala/play/api/Configuration.scala#L1036-L1040

And `getOptional` had no logic to handle null values:

https://github.com/playframework/playframework/blob/e7c9a45f73bc753fbfd4f7005574bee47d9f2996/framework/src/play/src/main/scala/play/api/Configuration.scala#L232-L234

This changed in 2.6.9 and now `getOptional` returns `None` if the value is `null`:

https://github.com/playframework/playframework/blob/a5235c16d569474b88964eb73dfa5d1db23f7d9c/framework/src/play/src/main/scala/play/api/Configuration.scala#L233-L239

Since the reference value is null (with Because of that, we are not setting any request timeout.

We can easily fix this specific scenario (request timeout is not configured), but maybe we should revert the `getOptional` change since it is impacting both Play and also any other application/module using `getOptional[Duration]`.

Anyway, I'm working on a fix for this issue.

/cc @mkurz.

**Comment by gmethvin** [comment] 2018-01-04 20:44
Using `null` for an infinite duration is strange anyway. We should change the `reference.conf` to use `infinite` for clarity if that's what we want as the default. To me that's the main problem. In virtually all other cases there's no issue with using `null` to represent the "none" case of an optional setting.

**Comment by marcospereira** [comment] 2018-01-04 22:06
@gmethvin yep.

Also, not sure "infinite" is a reasonable default since "infinite" kind of goes against having a timeout at all.

For Play 2.7.0 we can go with Akka default (20 seconds).

**Comment by mkurz** [comment] 2018-01-08 18:32
@marcospereira 
> ..., but maybe we should revert the `getOptional` change since it is impacting both Play and also any other application/module using `getOptional[Duration]`.

I would not revert #8064 because `getOptional` *did* behave wrong and my PR fixed that - so that was a bugfix. If now something fails we should instead fix code that relied on obviously wrong behavior.
My 2 cents :wink:

**Comment by marcospereira** [comment] 2018-01-08 18:46
> I would not revert #8064 because getOptional did behave wrong and my PR fixed that - so that was a bugfix. If now something fails we should instead fix code that relied on obviously wrong behavior.

@mkurz thanks for chime in. Just to be clear, I had no intent to criticize, in fact, I don't have a strong opinion here. But changing a valid (in the sense it was documented) existing behavior (`getOptional[Duration]` returns `Duration.Inf` for `null` configurations) is something that concerns me. It is easy to change the behavior inside Play, but it can also cause unexpected behaviors on modules and users applications.

Anyway, at this point, I agree with you about not reverting it and there is #8137 to fix this specific problem.

**Closed** 2018-01-09 17:39 UTC
Labels: help:needs-info
