### ISSUE TITLE
Need to get rid of generic error message: No configuration setting found for key 'play'

### ISSUE THREAD

**Issue by tenstriker** [playframework/playframework#8058] opened 2017-12-01 02:37 UTC
### JDK (Oracle 1.8.0_72)
Play Maven Plugin Version - 1.0.0-rc1

Following stacktrace bleeds on log in multiple situation. I have seen it on hot reload error due to compilation issue, missing configuration, when Modules or Routers are not loaded, Dependencies are missing or conflicting.
Sometime hitting the same url gives different error message and that can actually point to real issue but it shouldn't be the case. Hitting same url should be idempotent as far as play framework is concern.

I think is very misleading to use this stacktrace which doesn't pin point any issue. Proper error should catch via responsible component and emits meaningful error messages.

e.g. For compilation issue on hot reload, it shouldn't even try to refresh application and just emit compilation errors
For missing configuration, it should be able to tell what key is missing. I don't see in such key or variable as 'play' in my application.conf. If it's internal present the documentation on that.
For missing modules or routes definition give user a WARN messages 
For missing dependencies give a meaningful error message in first place.

```
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'play'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:264)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:270)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
	at play.api.ConfigLoader$$anonfun$36$$anonfun$apply$34.apply(Configuration.scala:1065)
	at play.api.ConfigLoader$$anonfun$36$$anonfun$apply$34.apply(Configuration.scala:1065)
	at play.api.ConfigLoader$$anon$3.load(Configuration.scala:1021)
	at play.api.ConfigLoader$$anon$2.load(Configuration.scala:1013)
	at play.api.Configuration.get(Configuration.scala:214)
	at play.core.server.common.ForwardedHeaderHandler$ForwardedHeaderHandlerConfig$.apply(ForwardedHeaderHandler.scala:233)
	at play.core.server.common.ReloadCache.reloadForwardedHeaderHandler(ReloadCache.scala:74)
	at play.core.server.AkkaHttpServer$$anon$3.reloadValue(AkkaHttpServer.scala:170)
	at play.core.server.AkkaHttpServer$$anon$3.reloadValue(AkkaHttpServer.scala:167)
	at play.core.server.common.ReloadCache$$anonfun$1.apply(ReloadCache.scala:25)
	at play.core.server.common.ReloadCache$$anonfun$1.apply(ReloadCache.scala:25)
	at play.utils.InlineCache.fresh(InlineCache.scala:69)
	at play.utils.InlineCache.apply(InlineCache.scala:55)
	at play.core.server.common.ReloadCache.cachedFrom(ReloadCache.scala:31)
	at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$modelConversion(AkkaHttpServer.scala:183)
	at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$handleRequest(AkkaHttpServer.scala:189)
	at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:106)
	at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:106)
	at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:728)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:743)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:653)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)  
```

Steps to reproduce:

It is been tested only with Play-maven projects as that is what I am trying to build on:

1. Download play-scala-rest-api from here: https://github.com/playframework/play-scala-rest-api-example
2. Disable Module from applicaiton.conf : play.modules.disabled += "Module"
3. Run server using `mvn play2:run`
4. Hit any url on server. e.g. http:localhost:9000

Another way to reproduce:
1. Download play-scala-rest-api from here: https://github.com/playframework/play-scala-rest-api-example
2. Keep the Module enabled in applicaiton.conf : play.modules.enabled += "Module"
3. Change PostResoureHandler definition to add WSClient dependency. 
class PostResourceHandler @Inject()(
    ws: WSClient,
    routerProvider: Provider[PostRouter],
    postRepository: PostRepository)(implicit ec: ExecutionContext)
4. Add play-ws dependency suggested on play-maven site.
```
        <dependency>
		  <groupId>com.typesafe.play</groupId>
		  <artifactId>play-ws_${play2-scala.version}</artifactId>
		  <version>${play2.version}</version>
	  </dependency>
```
5. Run server using `mvn play2:run`
6. Hit any url on server. e.g. http:localhost:9000

**Comment by richdougherty** [comment] 2017-12-01 03:06
Hi @tenstriker, thanks for the report.

The problem appears to occur when getting sub-configuration for `play.http.forwarded` from here: https://github.com/playframework/playframework/blob/2.6.7/framework/src/play-server/src/main/scala/play/core/server/common/ForwardedHeaderHandler.scala#L233. Since we're getting an error about missing config for the key `play` I assume that Play is somehow missing *all* of it's configuration, not just the `ForwardedHeaderHandler` configuration. Perhaps an error during load is somehow loading the server in a weird state?

Do you have steps that we can use to reproduce this error?

If we can reproduce and diagnose properly then we can perhaps improve reporting in Play or suggest to the upstream https://github.com/lightbend/config project to improve the root error message.

**Comment by tenstriker** [comment] 2017-12-01 19:25
I added steps and version information in op. FYI, I am using play-maven not play-sbt.

**Comment by gmethvin** [comment] 2017-12-03 04:15
We don't support the play2 maven plugin. Is it possible to repro with a plain maven project? If not it may be a problem with the way the maven plugin is loading the server.

Also `play-ws` is the ws API and does not provide an implementation. You probably want `play-ahc-ws`.

**Comment by tenstriker** [comment] 2017-12-19 19:55
do you mean try it on plain play-sbt project?

**Comment by gmethvin** [comment] 2018-01-04 20:58
@tenstriker No, I meant a maven project that simply uses the Play dependencies directly and does not use any maven plugins.

**Comment by marcospereira** [comment] 2019-04-24 18:18
Closing since this is using play2-maven-plugin which we don't support.

**Closed by marcospereira** 2019-04-24 18:18 UTC
Labels: status:backlog, status:needs-info, status:needs-verification, type:defect
