### ISSUE TITLE
Server Sent Events / SSE documentation

### ISSUE THREAD

**Issue by lutzh** [playframework/playframework#3824] opened 2015-01-16 10:20 UTC
I have a feeling that Server Sent Events or short SSE are not covered in the Play documentation.
```
Your search - SSE site:www.playframework.com/documentation/2.3.x - did not match any documents.
```

A search for Server Sent Events yields some ScalaDoc results, EventSource not being anywhere near the top of the list, though.

**Comment by cchantep** [comment] 2015-01-29 21:09
Duplicate of #1801

**Closed by cchantep** 2015-01-29 21:09 UTC
Labels: documentation
