### ISSUE TITLE
[Play 2.4.1 Java] request().remoteAddress() hangs

### ISSUE THREAD

**Issue by njovy** [playframework/playframework#4798] opened 2015-07-01 08:51 UTC
Hello!
My play application hangs when it calls request().remoteAddress() in controller. It only happens when it gets called by a lot of requests simultaneously.
The problematic method handles uploaded files as a MultiPartFormData and it returns Promise<Result>. 

Here is thread dump: https://gist.github.com/njovy/2db4a85d63d1f3450960

Is there a workaround to avoid this issue?

Thank you.

**Comment by richdougherty** [comment] 2015-07-02 00:41
Hmm, looks like a weird interaction between:
* [look up of the `ForwardedHeaderHandler`](https://github.com/playframework/playframework/blob/2.4.1/framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala#L36-L37)
* [getting a thread pool](https://github.com/playframework/playframework/blob/2.4.1/framework/src/play/src/main/scala/play/core/Execution.scala#L15-L21) while [getting the Application](https://github.com/playframework/playframework/blob/2.4.1/framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala#L110)

**Comment by njovy** [comment] 2015-07-02 02:11
I created a simple project with a threaddump here. https://github.com/njovy/play-remote-address-tester
Calling request().remoteAddress() multiples times upon initialization hangs the application in a DEV mode.

**Comment by jroper** [comment] 2015-07-03 04:54
The long term (non Play 2.4) solution to this is that `ForwardedHeaderHandler`, or its configuration dependencies, should be made available through `Application` some how.  Possibly by putting its configuration in `HttpConfiguration`, and exposing that through `Application`, something I'm sure we'll want to do anyway.

**Comment by marcospereira** [comment] 2019-05-07 19:25
I could not reproduce this problem anymore (Play 2.7). So I'm closing this.

@njovy, please let me know if you still see this happening with newer versions of Play.

Best.

**Closed by marcospereira** 2019-05-07 19:25 UTC
Labels: status:backlog, type:defect
