### ISSUE TITLE
Manually adding error on form

### ISSUE THREAD

**Issue by EdozdeDandez** [playframework/playframework#10110] opened 2020-03-05 10:55 UTC
### Play Version

2.8.0

### API

Java

### Operating System
Mac OS

### JDK

openjdk version "1.8.0_202-release"
### Expected Behavior

1. Return a form withError
2. Retrieve form errors and display
3. The returned error should be among the form errors

### Actual Behavior

1. Form is returned withError
2. Form errors are retrieved
3. Nothing is displayed

**Comment by mkurz** [comment] 2020-03-05 11:02
First: It it depends if you added a global error or a error for an form element. Please read https://www.playframework.com/documentation/2.8.x/JavaForms#Handling-binding-failure
Please also read: https://www.playframework.com/documentation/2.8.x/JavaFormHelpers

Second: You should post some code so we can reproduce the problem.

Third: If this is a question, please open a thread in our discussion forum: https://discuss.lightbend.com/c/play/

**Comment by mkurz** [comment] 2020-11-11 09:44
@EdozdeDandez Can you please give more information or an example what your exact problem is?

**Comment by mkurz** [comment] 2021-02-08 14:10
Closing because of lack of information.

**Closed by mkurz** 2021-02-08 14:10 UTC
Labels: status:needs-info
