### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by a-panchenko** [playframework/playframework#8429] opened 2018-05-22 09:12 UTC
There are several dependency conflicts while compiling Play 2.6.13 application

### Play Version (2.5.x / etc)

2.16.13

### API (Scala / Java / Neither / Both)

Scala 2.12.6

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOs

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

### Expected Behavior

No warnings about dependencies conflicts must be.

### Actual Behavior

There are several warnings about dependencies conflicts:

```
[info] Here are other depedency conflicts that were resolved:
[info]  * org.scala-lang.modules:scala-parser-combinators_2.12:1.0.6 is selected over 1.0.4
[info]      +- com.typesafe:ssl-config-core_2.12:0.2.2            (depends on 1.0.4)
[info]      +- com.typesafe.play:play_2.12:2.6.13                 (depends on 1.0.4)
[info]  * com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.11 is selected over 2.8.9
[info]      +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info]      +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info]  * com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.8.11 is selected over 2.8.9
[info]      +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info]      +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info]  * com.fasterxml.jackson.core:jackson-databind:2.8.11 is selected over {2.8.2, 2.8.9}
[info]      +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.11 (depends on 2.8.11)
[info]      +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.8.11 (depends on 2.8.11)
[info]      +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info]      +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info]      +- io.jsonwebtoken:jjwt:0.7.0                         (depends on 2.8.2)
[info]  * com.fasterxml.jackson.core:jackson-annotations:2.8.11 is selected over {2.8.9, 2.8.0}
[info]      +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info]      +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.11 (depends on 2.8.0)
[info]      +- com.fasterxml.jackson.core:jackson-databind:2.8.11 (depends on 2.8.0)
[info]      +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info]  * com.fasterxml.jackson.core:jackson-core:2.8.11 is selected over {2.8.9, 2.8.10}
[info]      +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.11 (depends on 2.8.11)
[info]      +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.8.11 (depends on 2.8.11)
[info]      +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info]      +- com.fasterxml.jackson.core:jackson-databind:2.8.11 (depends on 2.8.10)
[info]      +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info]  * com.typesafe:config:1.3.2 is selected over 1.2.0
[info]      +- com.typesafe:ssl-config-core_2.12:0.2.2            (depends on 1.2.0)
[info]      +- com.typesafe.akka:akka-actor_2.12:2.5.11 ()        (depends on 1.2.0)

```

**Comment by PromanSEW** [comment] 2018-05-22 12:06
Duplicate of #7832

**Comment by gmethvin** [comment] 2018-05-24 00:06
Closing because this is a duplicate. Also what you pasted are not warnings, they are `info` messages. But there are also some warnings as mentioned in #7832.

**Closed by gmethvin** 2018-05-24 00:06 UTC
