### ISSUE TITLE
Branch condition is wrong in .travis.yml

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9924] opened 2019-12-16 16:57 UTC
https://github.com/playframework/playframework/blob/master/.travis.yml#L5

declares a condition to prevent unnecessary builds. The final condition `... OR branch IN (master, 2.7.x, 2.6.x)` is missing `2.8.x` but merges on `2.8.x` are actually being built. So:

 - the list is wrong
 - the list is ignored anyways...

**Comment by mkurz** [comment] 2019-12-20 20:57
@ignasi35 Fixed in #9923 already?

**Comment by dwijnand** [comment] 2020-01-02 16:22
No, that was the PR that highlighted that something is wrong with the condition: 2.8.x was missing but it was building anyways.

**Comment by mkurz** [comment] 2020-01-21 12:56
> The final condition `... OR branch IN (master, 2.7.x, 2.6.x)` is missing `2.8.x` but merges on `2.8.x` are actually being built.

Just a guess: `type != push` comes first, which therefore (probably) is the first condition that will be evaluated, will be true for any pull request, no matter what's the current branch.
And because all conditions are `OR`d nothing else will be evaluated anymore.
So not the list is wrong (it wont even be evaluated), the `OR` logic is wrong.

**Comment by dwijnand** [comment] 2020-01-21 13:17
The problem isn't the pull requests, though.  It's about the branch merges, which are `type = push` (merge) commits.

So at the time it should have evaluated to:

```
type != push								# FALSE, type = push
	OR tag IS present						# FALSE, not a tag build
	OR repo != playframework/playframework	# FALSE, repo = play/play
	OR branch IN (master, 2.7.x, 2.6.x)		# FALSE, 2.8.x is missing
```

**Comment by mkurz** [comment] 2020-01-21 13:56
Note (to myself)
Looking at the Travis "Requests" list I see that the _merge commit_ 35e4ca6 of pull request #9982, which was opened 12 days ago, failed the `if` condition:

![image](https://user-images.githubusercontent.com/644927/72809168-6278dd00-3c5b-11ea-8e64-edf3d33d33d5.png)

The interesting thing to note here is that the list showed in the tooltip is missing `2.8.x`, meaning that the `.travis.yml` config from the 2.8.x branch was used. The config in the master branch does contain `2.8.x`. Both configs were changed 15 days ago, _before_ the pull request was even opened.

current master:
https://github.com/playframework/playframework/blob/701a8e4a527725ad137dcc7f69b5cef8ce1bb19c/.travis.yml#L5

current 2.8.x:
https://github.com/playframework/playframework/blob/35e4ca67ce64d261ca01af64f24a3f27a4ec20cc/.travis.yml#L5

That also confirms that a merge commit must be of type `push`, like Dale said.

**Comment by mkurz** [comment] 2020-01-21 13:59
Another thought (probably wrong, but still to note): Maybe `.travis.yml` (or its settings) gets cached?

**Comment by dwijnand** [comment] 2020-01-21 14:14
> the _merge commit_ [35e4ca6](https://github.com/playframework/playframework/commit/35e4ca67ce64d261ca01af64f24a3f27a4ec20cc) of pull request #9982, which was opened 12 days ago, failed the `if` condition

> current 2.8.x:
> https://github.com/playframework/playframework/blob/35e4ca67ce64d261ca01af64f24a3f27a4ec20cc/.travis.yml#L5

OK, so looks like we need/should've backported the 2.8.x change in .travis.yml to the 2.8.x branch.

I guess none of us remembered how Travis CI uses the .travis.yml of the branch (or, in the case of PR builds, the target branch), rather than just the single .travis.yml on the default branch (aka `master` for Play).  This is as opposed to Mergify, which just uses teh default branch's .mergify.yml.  I think these behaviours make sense for them, but the difference can be forgotten.

So do we still have a problem here?  If pushes to the 2.8.x branch aren't being built (only cron builds on it), then the logic must just be right, no?

**Comment by mkurz** [comment] 2021-01-26 08:40
> So do we still have a problem here? If pushes to the 2.8.x branch aren't being built (only cron builds on it), then the logic must just be right, no?

There is and was no problem. You explanation is correct. Travis always uses the `.travis.yml` of the branch your are pushing to (or in case it's a PR the base branch). In the first commit of this issue Ignasi talks about pushing to 2.8.x but refering to `.travis.yml` in the master branch, that was the problem.

**Closed by mkurz** 2021-01-26 08:40 UTC
