### ISSUE TITLE
Playdevmode compiles twice

### ISSUE THREAD

**Issue by jtjeferreira** [playframework/playframework#10373] opened 2020-07-03 16:17 UTC
### Play Version

Play 2.8.2

### API

Scala

### Operating System

Arch Linux 5.7.4

### JDK

```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

### Expected Behavior

1. checkout https://github.com/jtjeferreira/compile-twice-play-seed/tree/master
2. launch sbt
3. compile
4. modify `A.scala` file in `core` module
5. run
6. make a request to http://localhost:9000

Expected that compilation of `A.scala` only happens once

### Actual Behavior

Repeat all of the steps above, but compilation of `A.scala` happens twice. Once before the devmode server launches, and on the first request received by the  server.

This problem also happens in my work project, and is a pain because if you pull a lot of changes from git and you `run` compilation will happen twice, and one will have to wait double the time...

### Reproducible Test Case

https://github.com/jtjeferreira/compile-twice-play-seed/tree/master

This is a `play-scala-seed` project modified to a multimodule project. The project has a `root` module that depends and aggregates on a `core` module.

**Comment by jtjeferreira** [comment] 2020-07-03 16:20
In https://github.com/jtjeferreira/compile-twice-play-seed/blob/master/sbt-debug.log you have the logs of `run` with sbt debug mode on

**Comment by mkurz** [comment] 2020-07-13 11:11
I can confirm this issue. Pull requests are welcome.

**Comment by jtjeferreira** [comment] 2020-08-24 10:47
@mkurz I will try to have a look this week. You have any pointers where the problem might be?

**Comment by mkurz** [comment] 2020-08-24 10:50
@jtjeferreira Sorry, I don't have time this week and also not the next couple weeks...

**Comment by jtjeferreira** [comment] 2020-08-25 17:45
An workaround is to set `playInteractionMode := play.sbt.StaticPlayNonBlockingInteractionMode`. 

A proper fix should be done in the efforts of https://github.com/playframework/playframework/issues/9956

**Comment by mkurz** [comment] 2021-01-27 09:00
Looks like this bug is solved when using sbt 1.4!

@jtjeferreira I changed the sbt version [in your example](https://github.com/jtjeferreira/compile-twice-play-seed/blob/master/project/build.properties) to 1.4.6 (or even 1.4.0) and I can not reproduce the redundant compilation anymore (with the steps you provided in your intial comment).
Please try yourself and let me know if that is true for you as well (btw, are you using macOS? I did my testing in Ubuntu)
(However, be aware Play does not yet fully support sbt 1.4, I am working on full support for the next 2.7.x and 2.8.x releases, which means you still have to wait for the next releases to upgrade your projects to sbt 1.4)

**Comment by jtjeferreira** [comment] 2021-01-27 10:46
I have been using [this](https://github.com/playframework/playframework/issues/10373#issuecomment-680174967) workaround, but I am also using sbt 1.4 already with someworkarounds, so I will check if sbt 1.4 really fixed it.

**Comment by mkurz** [comment] 2021-04-09 09:40
@jtjeferreira Play 2.8.8 is released with support for sbt 1.4.9 and sbt 1.5.0. I just tried again with your reproducer project and I could not reproduce anymore with these two sbt versions (but I _could_ reproduce with sbt 1.3.13).
So IMHO the solution is to upgrade to sbt 1.4.9/1.5 (and Play 2.8.8)
Can you confirm? Can we close this issue?

**Comment by ignasi35** [comment] 2021-04-09 15:44
Great news, @mkurz.

It may be good to add this issue to the `2.8.8` milestone and release notes to increase its visibility.

**Comment by jtjeferreira** [comment] 2021-04-09 15:52
Lets close. Thanks for all your efforts with 2.8.8.

**Closed** 2021-04-09 15:52 UTC
Labels: topic:dev-environment, type:defect

**Comment by mkurz** [comment] 2021-04-09 16:10
@ignasi35 Added to the release notes:
![image](https://user-images.githubusercontent.com/644927/114209358-d2f24380-995e-11eb-8b08-1d72753ffefb.png)
