### ISSUE TITLE
The "Found an error in the documentation" links are dead.

### ISSUE THREAD

**Issue by jbdeboer** [playframework/playframework#6253] opened 2016-06-19 01:18 UTC
The "Found an error in the documentation" links are dead.

e.g.

    1. Go to https://www.playframework.com/documentation/2.5.x/PlaySlick
    2. Click on the "found an error" link at the bottom on the page. It points to https://github.com/playframework/playframework/blob/2.5.x/documentation/manual/working/scalaGuide/main/sql/slick/PlaySlick.md

Github.com returns a 404 for the linked URL.

**Comment by gmethvin** [comment] 2016-06-19 11:15
Duplicate of playframework/playframework.com#86

**Closed by gmethvin** 2016-06-19 11:15 UTC
