### ISSUE TITLE
query parameter parsing broken in 2.5.7 and 2.5.8 when it contains a comma

### ISSUE THREAD

**Issue by mkoester** [playframework/playframework#6604] opened 2016-09-28 08:50 UTC
### Play Version (2.5.x / etc)

Working 2.5.6
Broken: 2.5.7 and 2.5.8

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

### Expected Behavior

I created a new Play Framework (2.5.8) project using activator. I just added very simple test cases using routes and my own controller (TestController). Query parameters with a comma (,) are parsed incorrectly: the part after the comma is cut off. Using url encoded commas (%2C) on the other hand works (in 2.5.8, not in 2.5.7):
https://github.com/mkoester/play_2.5.8_query_parameter_parsing_error

- http://localhost:9000/test_option_string?stringOption=123%2C456,789 -> Some(123,456,789)
- http://localhost:9000/test_string?string=123%2C456,789 -> 123,456,789
- http://localhost:9000/test_string/123%2C456,789 -> 123,456,789

### Actual Behavior

2.5.7:
- http://localhost:9000/test_option_string?stringOption=123%2C456,789 -> Some(123)
- http://localhost:9000/test_string?string=123%2C456,789 -> 123
- http://localhost:9000/test_string/123%2C456,789 -> 123,456,789

2.5.8:
- http://localhost:9000/test_option_string?stringOption=123%2C456,789 -> Some(123,456)
- http://localhost:9000/test_string?string=123%2C456,789 -> 123,456
- http://localhost:9000/test_string/123%2C456,789 -> 123,456,789

this is similar to https://github.com/playframework/playframework/issues/6549

### Reproducible Test Case
https://github.com/mkoester/play_2.5.8_query_parameter_parsing_error

**Comment by schmitch** [comment] 2016-09-28 09:56
this is already revert, there is just no new version yet:
https://github.com/playframework/playframework/commit/6d2a70bbd89f4e7a549bf3d52b028875fbc8d58b

actually this also reverts matrix params, i.e. it will basically be the behavior of 2.5.4

**Comment by gmethvin** [comment] 2016-09-28 20:10
@schmitch @mkoester Yes we should do another release by the end of the week.

**Comment by schmitch** [comment] 2016-10-12 07:02
This is fixed in 2.5.9

**Closed by schmitch** 2016-10-12 07:02 UTC

**Comment by adibaranga** [comment] 2016-11-15 13:44
What about semicolon? The issue is reproducing in 2.5.9.

**Comment by schmitch** [comment] 2016-11-15 13:49
The semicolon was handled even in 2.5.[0-6]

**Comment by adibaranga** [comment] 2016-11-15 15:10
@schmitch Thanks for your quick response. We are using comma and semicolon in some of our query params and while the problem related to comma was fixed for 2.5.9, the value of the query param is cut off after semicolon. BTW, it's working sing url encoded semicolon (%3B).

**Comment by schmitch** [comment] 2016-11-15 15:12
well as said the current behavior is the same as it was in pre 2.5.7, exactly the same and it's really problematic to change the behavior (as I learned the hard way) in a minor release.
I'm not sure if we change the behavior in 2.6.0
