### ISSUE TITLE
failed: nightly build failed because of binary incompatible sbt check

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10971] opened 2021-09-02 09:32 UTC
The nightly build is failing since we merged https://github.com/playframework/playframework/pull/10956

I didn't look further, but I suspect this is due to the upgrade to sbt 1.5.5 and the fact that the nightly build uses a akka-http snapshot. 

If I understand correct, what was previously an eviction warning is not by default an error. 

```scala
 java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.scala-lang.modules:scala-java8-compat_2.13:1.0.0 (early-semver) is selected over 0.9.1
[error] 	    +- com.typesafe.play:play-streams_2.13:2.8.1+1278-9f273803-akka-2.6.16+64-bb839128-SNAPSHOT-akka-http-10.1.14+6-971cf72c-SNAPSHOT (depends on 1.0.0)
[error] 	    +- com.typesafe.akka:akka-actor_2.13:2.6.16+64-bb839128-SNAPSHOT (depends on 1.0.0)
[error] 	    +- org.scala-lang.modules:scala-java8-compat_2.13:0.9.1 (depends on 0.9.1)
[error] 
[error] 
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
```

**Comment by octonato** [comment] 2021-09-02 09:34
Yep, that's sbt 1.5.5
https://eed3si9n.com/sbt-1.5.0

**Comment by mkurz** [comment] 2021-09-02 20:01
The problem is not really sbt 1.5.x. The master branch is using sbt 1.5.x already since probably half a year or so now and cron jobs were working fine.

The "problem" is that akka 2.6.15 switched to `scala-java8-compat` version 1.0.0. And because the cron job is using the latest akka snapshot, sbt 1.5 is complaining now that the version Play is using and the version akka 2.15+ is using are incompatible.

Anyway, that will be fixed by #10969, were I upgrade a couple of dependencies all at once which should silent any sbt complains.

**Comment by ennru** [comment] 2021-09-07 10:25
`scala-java8-compat` 1.0.0 is considered bin-compatible with 0.9.1, even though it reads differently.

Akka added this explicit resolution https://github.com/akka/akka/pull/30375 for it.

**Closed** 2022-01-18 11:46 UTC
Labels: failed

**Comment by mkurz** [comment] 2022-01-18 11:50
Finally, more than half a year of broken cron build :partying_face:
