### ISSUE TITLE
play-scala seed doesn't work

### ISSUE THREAD

**Issue by hrcorrado** [playframework/playframework#4563] opened 2015-05-28 20:59 UTC
hi, 
just tried to create new project from play-scala seed and fails...

with activator ui:
```
[debug] [Loading] Found root project root w/ remaining
java.lang.NoClassDefFoundError: play/Play$
	at play.sbt.forkrun.PlayForkRun$.requires(PlayForkRun.scala:35)
	at sbt.Plugins$.asRequirements(Plugins.scala:281)
	at sbt.Plugins$$anonfun$3.apply(Plugins.scala:146)
	at sbt.Plugins$$anonfun$3.apply(Plugins.scala:146)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbt.Plugins$.deducer(Plugins.scala:146)
	at sbt.DetectedPlugins.deducePluginsFromProject(BuildStructure.scala:150)
	at sbt.Load$.resolveProject(Load.scala:650)
	at sbt.Load$.finalizeProject$1(Load.scala:549)
	at sbt.Load$.loadTransitive(Load.scala:577)
	at sbt.Load$.loadProjects$1(Load.scala:442)
	at sbt.Load$.loadUnit(Load.scala:446)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: play.Play$
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at play.sbt.forkrun.PlayForkRun$.requires(PlayForkRun.scala:35)
	at sbt.Plugins$.asRequirements(Plugins.scala:281)
	at sbt.Plugins$$anonfun$3.apply(Plugins.scala:146)
	at sbt.Plugins$$anonfun$3.apply(Plugins.scala:146)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbt.Plugins$.deducer(Plugins.scala:146)
	at sbt.DetectedPlugins.deducePluginsFromProject(BuildStructure.scala:150)
	at sbt.Load$.resolveProject(Load.scala:650)
	at sbt.Load$.finalizeProject$1(Load.scala:549)
	at sbt.Load$.loadTransitive(Load.scala:577)
	at sbt.Load$.loadProjects$1(Load.scala:442)
	at sbt.Load$.loadUnit(Load.scala:446)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: play/Play$
[error] Use 'last' for the full log.
[debug] > load-failed
[debug] > last
```

and error when creating from command line:

```
java.lang.UnsupportedClassVersionError: play/runsupport/classloader/ApplicationClassLoaderProvider : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at play.sbt.run.PlayRun$.<init>(PlayRun.scala:35)
	at play.sbt.run.PlayRun$.<clinit>(PlayRun.scala)
	at play.sbt.PlaySettings$.defaultSettings$lzycompute(PlaySettings.scala:70)
	at play.sbt.PlaySettings$.defaultSettings(PlaySettings.scala:47)
	at play.sbt.Play$.projectSettings(Play.scala:26)
	at sbt.Load$$anonfun$autoPluginSettings$1$1.apply(Load.scala:666)
	at sbt.Load$$anonfun$autoPluginSettings$1$1.apply(Load.scala:666)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbt.Load$.autoPluginSettings$1(Load.scala:666)
	at sbt.Load$.sbt$Load$$expandSettings$1(Load.scala:681)
	at sbt.Load$$anonfun$sbt$Load$$expandSettings$1$2.apply(Load.scala:682)
	at sbt.Load$$anonfun$sbt$Load$$expandSettings$1$2.apply(Load.scala:682)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
	at sbt.Load$.sbt$Load$$expandSettings$1(Load.scala:682)
	at sbt.Load$.resolveProject(Load.scala:684)
	at sbt.Load$.finalizeProject$1(Load.scala:549)
	at sbt.Load$.loadTransitive(Load.scala:577)
	at sbt.Load$.loadProjects$1(Load.scala:442)
	at sbt.Load$.loadUnit(Load.scala:446)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.UnsupportedClassVersionError: play/runsupport/classloader/ApplicationClassLoaderProvider : Unsupported major.minor version 52.0
```
latest activator version, latest sbt

**Comment by wsargent** [comment] 2015-05-28 21:03
Check that your JDK is 1.8.x with `java -version` -- Play 2.4.0 requires JDK 1.8 to run.

**Comment by hrcorrado** [comment] 2015-05-28 21:50
Yep, wasn't 1.8.x. But it didn't fix the first ```java.lang.NoClassDefFoundError: play/Play$``` error

**Comment by wsargent** [comment] 2015-05-28 22:12
I would also check that you have the latest activator: you should have 1.3.2 

https://www.typesafe.com/get-started

**Comment by hrcorrado** [comment] 2015-05-28 22:49
yes, I have the latest, I checked it when I got this error. please look above, I mentioned it in issue

**Comment by marcospereira** [comment] 2015-05-28 23:01
It works as expected to me. Could you please clear your ivy cache (directory `~/.ivy2/cache`) and see if it works?

**Comment by wsargent** [comment] 2015-05-28 23:29
Also can't reproduce this.

**Comment by hrcorrado** [comment] 2015-05-28 23:36
damn, cleared cache, re-checked versions, everything is fine, still getting ```java.lang.NoClassDefFoundError: play/Play$```

**Comment by jroper** [comment] 2015-05-29 00:54
What version of activator are you using?

What is in your `project` directory? Try removing all files other than plugins.sbt and build.properties, and then run it on the command line (ie, not using activator ui).

**Comment by wsargent** [comment] 2015-05-29 03:32
I think this might be the fork join sbt plugin -- it should be  `addSbtPlugin("com.typesafe.play" % "sbt-fork-run-plugin" % "2.4.0")`

**Comment by jroper** [comment] 2015-05-29 03:50
Yes, and Activator automatically adds (and always reverts any changes you've made) 2.3.8.

**Comment by hrcorrado** [comment] 2015-05-29 12:04
thanks, removing all files except ```plugins.sbt``` and ```build.properties``` helped. strange thing, I did not add any of those files, everything was created automatically with activator (1.3.2)

**Comment by wsargent** [comment] 2015-05-30 00:14
Closing.

**Closed by wsargent** 2015-05-30 00:14 UTC
Labels: needs-verification

**Comment by hrcorrado** [comment] 2015-05-30 18:31
well, if I create new one, it still fails. but if I remove all files except those, like it is in repo in the beginning, it works

**Comment by jamesward** [comment] 2015-06-02 19:28
Just got the same error when creating a new app from the `play-scala-seed` template using the Activator 1.3.2 UI.

**Comment by henrikengstrom** [comment] 2015-06-02 20:17
The reason for this problem is that the Play versions in the ``project/plugins.sbt`` and the auto-generated file ``project/play-fork-run.sbt`` are not aligned. The latter contains an old version and this causes the error.
We are working on a fix to be shipped asap. Thanks for reporting.

**Comment by hemraj-sharma** [comment] 2015-06-04 06:16
Done updating.
play/Play$
java.lang.NoClassDefFoundError: play/Play$
Use 'last' for the full log.
Failed to load project.

Hi, All I am getting the same problem.
Please tell if someone will get the solution

**Comment by mleong245** [comment] 2015-06-05 18:58
I was experiencing this exact same problem too.  For me, what worked was to update to JDK Version 8 (1.8.0_45) and then to change the line in play-fork-run.sbt mentioned above to have "2.4.0" instead of "2.3.9", and then it built properly on Activator UI.

**Comment by ebottabi** [comment] 2015-06-12 03:39
Hi i am facing same issue with but play 2.3.9, surprisingly i created initially an app without the issue, and after couple of days, i am now getting this issue. Kind of need help to resolve it.

**Comment by jwmach1** [comment] 2015-06-12 16:30
I am working around the problem by first launching the activator ui, then modifying the project/play-fork-run.sbt  to use 2.4.0 instead of 2.3.9. Once you modify the file, activator will rebuild.  Once you restart the UI, activator will (currently) change the file back to 2.3.9 forcing you to edit it again.

**Comment by eljojo** [comment] 2015-06-13 19:11
@jwmach1 your solution https://github.com/playframework/playframework/issues/4563#issuecomment-111548105 did the job for me. Thanks a lot!

**Comment by vishbin** [comment] 2015-06-17 07:23
Same issue . 
Using Java 8 .
Activator (current version 1.3.4)
sbt launcher version 0.13.5 

[error] java.lang.NoClassDefFoundError: play/Play$

**Comment by marcospereira** [comment] 2015-06-17 12:31
@vishbin you need to use sbt versoin 0.13.8, as stated in the migration docs:

https://www.playframework.com/documentation/2.4.x/Migration24#sbt-upgrade

**Comment by vishbin** [comment] 2015-06-18 07:48
@marcospereira Thanks!
upgrading sbt launcher fixed it .
$brew unlink sbt
$brew install sbt
