### ISSUE TITLE
"Content-Type set both in header" in Assets

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#6055] opened 2016-04-17 22:05 UTC
### Play Version (2.5.x / etc)
2.5.2

### API (Scala / Java / Neither / Both)
Neither

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
1.8.0_66

### Expected Behavior
```<img src="@routes.Assets.versioned("images/image.png")" alt="my image" />```
should be served normally

### Actual Behavior
It produces a warning:
```
[application-akka.actor.default-dispatcher-6] [warn] play.core.server.netty.NettyModelConversion - Content-Type set both in header (image/png) and attached to entity (image/png), ignoring content type from entity. To remove this warning, use Result.as(...) to set the content type, rather than setting the header manually.
```

**Comment by eximius313** [comment] 2016-04-17 22:09
same with JS and CSS:
```
<link rel="stylesheet" href="@routes.Assets.versioned("stylesheets/main.min.css")" type="text/css">
<script type="text/javascript" src="@routes.Assets.versioned("javascripts/main.js")"></script>
```
produces:
```
[application-akka.actor.default-dispatcher-7] [warn] play.core.server.netty.NettyModelConversion - Content-Type set both in header (application/javascript; charset=utf-8) and attached to entity (application/javascript; charset=utf-8), ignoring content type from entity. To remove this warning, use Result.as(...) to set the content type, rather than setting the header manually.
[application-akka.actor.default-dispatcher-2] [warn] play.core.server.netty.NettyModelConversion - Content-Type set both in header (text/css; charset=utf-8) and attached to entity (text/css; charset=utf-8), ignoring content type from entity. To remove this warning, use Result.as(...) to set the content type, rather than setting the header manually.
```

**Comment by mkurz** [comment] 2016-04-17 22:12
This has been fixed in #6043, just ignore it for now.

**Closed by mkurz** 2016-04-17 22:12 UTC

**Comment by eximius313** [comment] 2016-04-18 02:01
@mkurz, could the following issue also caused by this bug:
I can point my Chrome browser to any JS/CSS file (https://www.playframework.com/assets/css/43a7b40035011e5ad60668dab1be2245-main.min.css) and the file gets opened in new tab. 
Same behaviour ocurrs with local assets and Play 2.5.1, but with Play 2.5.2 they get downloaded instead.
In FF it works as expected. 
Is this issue caused by the https://github.com/playframework/playframework/pull/6043 or its another issue?
Kind regards

**Comment by mkurz** [comment] 2016-04-18 06:49
Maybe that's caused by #5981?
@marcospereira maybe you know more?

**Comment by marcospereira** [comment] 2016-04-18 17:29
See #6058.
