### ISSUE TITLE
Cookie or similar to persist default version when exploring https://www.playframework.com/documentation/x.x.x/

### ISSUE THREAD

**Issue by aholland** [playframework/playframework#5864] opened 2016-03-11 21:50 UTC
### Play Version (2.5.x / etc)
All / documentation and website.

### API (Scala / Java / Neither / Both)
Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
n/a

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
n/a

### Library Dependencies
n/a

### Expected Behavior <- DESIRED behaviour

1. find url in google, e.g. https://www.playframework.com/documentation/2.4.x/CorsFilter
2. go to that url
3. your website detects that I always want 2.5.0 and automatically redirects me to
     https://www.playframework.com/documentation/2..5.x/CorsFilter
i.e. the same URL but for the desired version, 2.5.x not 2.4.x that google happened to turn up.

Question: how should the site initially record which version I prefer to see? 
Answer - use whichever version I last selected from the dropdown. If the last version I selected was the latest version at the time and there is a new latest version, draw my attention to that fact so that I choose between my previous selection and the new latest version. If there is no cookie then automatically show the latest version.

### Actual Behavior

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "the page renders a 500 error code with no body content."  Copy and paste logs, and include any URLs.  Turn on internal Play logging with `<logger name="play" value="TRACE"/>` if there is no log output.  

1. find url in google, e.g. https://www.playframework.com/documentation/2.4.x/CorsFilter
2. go to that url
3. your website serves up that exact page, leaving me and all readers to manually fix the version in the drop down just about every single time we visit your site (the latest docs typically aren't as highly discovered by google as older ones, and there are many old and only one new / correct, so the natural hit rate it low)

### Reproducible Test Case

This is a very simple issue with your website.

**Comment by wsargent** [comment] 2016-03-11 23:29
Duplicate of https://github.com/playframework/playframework.com/issues/43

**Closed** 2016-03-11 23:29 UTC

**Comment by gmethvin** [comment] 2016-03-11 23:43
@wsargent this not quite the same as playframework/playframework.com#43. That issue is just to make sure the latest version is linked from Google, which may not necessarily be the one the user wants. @aholland is actually asking for it to remember which play version you specifically are using and show that version's documentation.

Perhaps another option would be for it to show a small warning in the documentation (similar to what the Akka documentation has) that tells you you aren't using your desired version, giving you a link to either set a different default version or go to your desired version's documentation.

**Comment by aholland** [comment] 2016-03-17 08:45
@gmethvin yes, that's exactly right.
