### ISSUE TITLE
Provide raw headers when using akka-http backend

### ISSUE THREAD

**Issue by urcadox** [playframework/playframework#7737] opened 2017-08-17 15:09 UTC
Hello,

I just ran into an issue with Akka HTTP parsing an Authorization header in a weird way, which in my case ended up in experiencing errors because I'm doing authentication delegation by forwarding the header to another service which did not expect this "format".

Akka HTTP seems to provide `RawHeader` instances according to the documentation (http://doc.akka.io/docs/akka-http/10.0.9/scala/http/common/http-model.html#http-headers). It would be nice to have access to those from the Play API for such cases. I'm not sure what would make more sense API-wise though. For now, I'm going to use Netty.

### Play Version (2.5.x / etc)
2.6.3

### API (Scala / Java / Neither / Both)
Scala

**Comment by richdougherty** [comment] 2017-08-17 21:51
Hi @urcadox, thanks for the report. Here's the code in Play that converts Play headers into Akka HTTP headers.

https://github.com/playframework/playframework/blob/6518d8fb0610aa77552225c7a8b8b8187a537f44/framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala#L295-L319

As you can see there's already some code for using a `RawHeader` for the `Content-Disposition` header or if it's a header which Akka HTTP cannot parse it. Perhaps what we need to do is add a whitelist into Play to force certain headers to use `RawHeader`.

```
play.server.akka.rawHeaders = [
  "Content-Disposition"
]
```

Here are two other reported issues where having a whitelist would help:

- https://github.com/playframework/playframework/issues/7735
- https://github.com/playframework/playframework/issues/7733

Also, would you mind giving some info about the weird parsing issue that you're encountering so we can get it fixed upstream in Akka HTTP?

Cc @jrudolph, @ktoso.

**Comment by urcadox** [comment] 2017-08-18 12:03
Hey @richdougherty,

I was actually talking about requests' headers, not responses.

Here is an example:

Authorization header sent by the client:
```
OAuth realm="https://api.clever-cloud.com/v2/oauth", oauth_consumer_key="<key>", oauth_token="<token>", oauth_signature_method="HMAC-SHA512", oauth_signature="<signature>", oauth_timestamp="1502979668", oauth_nonce="402047"
```

Authorization header as seen from `request.headers.get("Authorization")`:
```
OAuth oauth_signature_method=HMAC-SHA512,oauth_signature="<signature>",oauth_consumer_key=<key>,oauth_token=<token>,oauth_timestamp=1502979668,realm="https://api.clever-cloud.com/v2/oauth",oauth_nonce=402047
```

A whitelist would probably make more sense though, yes.

**Comment by richdougherty** [comment] 2017-08-21 00:36
OK thanks for clarifying. To support this raw headers on requests we'd need to have support in akka-http itself. It would also be good if akka-http could preserve a header's existing formatting unless it really needs to change.

**Comment by richdougherty** [comment] 2017-11-22 21:44
Tagged as 2.6.8 because this is an Akka HTTP backend related regression that we should fix on the 2.6.x branch.

**Comment by ktoso** [comment] 2017-11-23 04:58
Would an option to keep along RawHeader for everything or selected headers work for this?
I could not find a ticket for this in akka-http yet, let me know if there isn't one or if I'm blind, sounds like we should solve it in there indeed :)

**Comment by gmethvin** [comment] 2017-11-23 05:39
@ktoso It would be great if we could just get RawHeaders for everything since we currently have no mechanism to use typed headers in Play.

**Comment by richdougherty** [comment] 2017-11-24 06:13
Added issue to track this upstream: https://github.com/akka/akka-http/issues/1550

**Comment by masahitojp** [comment] 2017-12-22 02:15
It seems akka/akka-http#1550 is closed. 
The same problem came out in our product.
Does Playframework develop team change?

**Comment by richdougherty** [comment] 2018-01-31 07:21
Hi @masahitojp, we still need to integrate the Akka HTTP fix into Play.

**Comment by richdougherty** [comment] 2018-03-16 07:51
FYI, I'm working on this  now. See #8296.

**Comment by marcospereira** [comment] 2018-04-06 19:56
@urcadox,

@eximius313 @Flo354,

There is a fix for this issue on [Play 2.6.13](https://discuss.lightbend.com/t/play-2-6-13-released/629). Could you please try this new version and confirm it is working for you?

I'm closing it now, but if the fix doesn't work, we can reopen this issue with the additional information.

Thanks!

**Closed by marcospereira** 2018-04-06 19:56 UTC
Labels: bug, topic:upstream

**Comment by eximius313** [comment] 2018-04-08 16:41
seems to be fixed now  (despite [other problems](https://github.com/playframework/playframework/issues/7997#issuecomment-379563571))

**Comment by richdougherty** [comment] 2018-04-08 19:25
Thanks for reporting, I'll take a look at those other issues.
