### ISSUE TITLE
[Play 2.3.9] Cookie.maxAge broken?

### ISSUE THREAD

**Issue by mushtaq** [playframework/playframework#4445] opened 2015-05-13 08:18 UTC
The following test fails:

>val cookie = Cookie("name1", "value1", Some(3153600))
>val result = Results.Ok("ok").withCookies(cookie)
>Helpers.cookies(Future.successful(result)).get("name1").get.maxAge.get mustEqual 3153600

If maxAge is set to a lower value (say 315360), the test is green. This prevents us from migrating to the latest version

(Using Play 2.3.9, Scala 2.11.6, Java 64-Bit 1.7.0_40, Mac OSX 10.9.2)

**Comment by gmethvin** [comment] 2015-05-13 09:19
Looks like a dupe of #4432. See netty/netty#3777

**Closed by gmethvin** 2015-05-13 09:19 UTC
