### ISSUE TITLE
[play-scala 2.5.0] ERR_CONTENT_LENGTH_MISMATCH error occurs  on Heroku when the response is greater than 85kb

### ISSUE THREAD

**Issue by joymufeng** [playframework/playframework#5835] opened 2016-03-09 03:10 UTC
The demo project source code is here [https://github.com/joymufeng/play250](https://github.com/joymufeng/play250). And the demo application on Heroku is:
```
http://play250.herokuapp.com/getResponse?len=99000 
```
You can change the len parameter to control the response length. If the response length is lower than 85kb, it works well, otherwise ERR_CONTENT_LENGTH_MISMATCH  error occurs in the browser.

**Comment by jroper** [comment] 2016-03-11 06:00
You should raise an issue with heroku.  It works fine for me, Play is returning exactly the right number of bytes.  Have you been able to reproduce this anywhere other than behind the Heroku proxy?  If you can't, then the issue is not likely to be in Play, it's likely to be in the Heroku proxy.

**Comment by joymufeng** [comment] 2016-03-11 13:27
Thanks for your feedback. The same code works well on my own server. So it maybe an issue of Heroku.

**Comment by lauraluiz** [comment] 2016-03-16 13:56
I have the same problem. In my case the reason for the content-length mismatch is that not all the promised content is sent, as you can notice when accessing it via cURL. You receive a truncated HTML and the following error:
```
curl: (18) transfer closed with 7626 bytes remaining to read
```
From the Heroku logs, I can see a H18 error, which according to [Heroku documentation](https://devcenter.heroku.com/articles/error-codes#h18-server-request-interrupted):
> The backend socket, belonging to your app’s web process was closed before the backend returned an  HTTP response.

According to Heroku it would be a Play issue and this non-Heroku-related issue seems to confirm it: https://github.com/playframework/playframework/issues/5874

@joymufeng is it also true for you?

**Comment by schmitch** [comment] 2016-03-16 14:02
Could you guys create a demo application where the issue is reproduced?

**Comment by lauraluiz** [comment] 2016-03-16 14:19
@joymufeng already provided a demo app:
- app source:  https://github.com/joymufeng/play250
- running app in Heroku: http://play250.herokuapp.com/getResponse?len=99000 (specify the desired length)

@schmitch could you specify what else would help you to have in the app, so that I can provide it?

**Comment by schmitch** [comment] 2016-03-16 14:29
@lauraluiz the problem with this test app is that, it's working fine, locally and even adds the Content-Length correctly. ``Content-Length:99000``

**Comment by lauraluiz** [comment] 2016-03-16 14:33
The content-length is always set correctly.
The issue is that on "complex" systems (that's the best I can define them, i.e. systems behind LB, proxies) like Heroku, the content gets truncated because the web server seems to close the connection, thus providing content not matching the content-length.

Unfortunately I don't have more details than those about the problem ATM.

**Comment by jroper** [comment] 2016-03-16 23:46
I've reproduced it locally, it seems to only happen when using HTTP/1.0:

```
$ curl -0 http://localhost:9000/getResponse?len=10000000 | wc -c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (18) transfer closed with 2571777 bytes remaining to read
7428223
```

**Comment by jroper** [comment] 2016-03-17 00:09
Fixed in https://github.com/typesafehub/netty-reactive-streams/pull/7, I tested those changes with the app, and the problem went away.

**Comment by schmitch** [comment] 2016-03-17 13:35
also this is prolly duplicated with #5874

**Closed** 2016-03-19 05:11 UTC
Labels: defect
