### ISSUE TITLE
Evolution makes modules and singleton injected classes to be instantiated twice

### ISSUE THREAD

**Issue by arunasr** [playframework/playframework#6433] opened 2016-08-13 21:26 UTC
I am trying to create a periodic job from a module. The POC code is this:
```
package modules
import akka.actor._
import javax.inject._

import com.google.inject.AbstractModule
import play.api.libs.concurrent.AkkaGuiceSupport

import scala.concurrent.ExecutionContext
import scala.concurrent.duration._
import play.api.Logger

class JobModule extends AbstractModule with AkkaGuiceSupport {
  Logger info "Job module created"
  def configure() = {
    bind(classOf[Scheduler]).asEagerSingleton
  }
}

object Scheduler
{
  Logger info "Scheduler object created"
  var ticker = 0
}

class Scheduler @Inject() (val system: ActorSystem)(implicit ec: ExecutionContext)
{
  import Scheduler._
  Logger info "Scheduler class created"

  system.scheduler.schedule(0.seconds, 1.second) {
    Logger debug s"tick $ticker"
    ticker += 1
  }
}
```
I use in-memory H2 DB driver, so every time I restart the application, it needs an evolution. Unfortunately, my JobModule, all the dependencies and even the companion object are instantiated twice, once before the evolution and then again after the evolution has been applied. I end up with the same task scheduled twice.
From the log it looks as if the Logger instance and HikariPool are also instantiated twice.

Log before evolution:
```
(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 1 Scala source to /home/arunasr/Projects/play/bnitracker/target/scala-2.11/classes...
Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which in some cases may be orders of magnitude slower than using node.js.
13 21:55:00.003 [info]application: Job module created
13 21:55:00.491 [info]application: Creating Pool for datasource 'default'
13 21:55:00.503 [info]c.z.h.HikariDataSource: HikariPool-0 - is starting.
13 21:55:00.666 [info]p.a.d.DefaultDBApi: Database [default] connected at jdbc:h2:mem:bnitracker
13 21:55:00.782 [info]a.e.s.Slf4jLogger: Slf4jLogger started
13 21:55:00.791 [info]application: Scheduler class created
13 21:55:00.798 [info]application: Scheduler object created
13 21:55:00.798 [debug]application: tick 0
13 21:55:00.869 [error]application: 

! @7145bjbge - Internal server error, for (GET) [/] ->
 
play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:77)
```
After evolution:
```
13 21:55:01.799 [debug]application: tick 1
13 21:55:02.810 [debug]application: tick 2
13 21:55:03.810 [debug]application: tick 3
13 21:55:04.810 [debug]application: tick 4
13 21:55:05.810 [debug]application: tick 5
13 21:55:05.975 [info]application: Job module created
13 21:55:06.025 [info]application: Creating Pool for datasource 'default'
13 21:55:06.026 [info]c.z.h.HikariDataSource: HikariPool-1 - is starting.
13 21:55:06.029 [info]p.a.d.DefaultDBApi: Database [default] connected at jdbc:h2:mem:bnitracker
13 21:55:06.061 [info]a.e.s.Slf4jLogger: Slf4jLogger started
13 21:55:06.064 [info]application: Scheduler class created
13 21:55:06.067 [info]application: Scheduler object created
13 21:55:06.067 [debug]application: tick 0
13 21:55:06.161 [info]play.api.Play: Application started (Dev)
13 21:55:06.810 [debug]application: tick 6
13 21:55:07.076 [debug]application: tick 1
13 21:55:07.810 [debug]application: tick 7
13 21:55:08.076 [debug]application: tick 2
13 21:55:08.810 [debug]application: tick 8
13 21:55:09.077 [debug]application: tick 3
13 21:55:09.810 [debug]application: tick 9
13 21:55:10.077 [debug]application: tick 4
13 21:55:10.810 [debug]application: tick 10
```
### Operating System (Ubuntu 15.10)
Linux fuji 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (OpenJDK 1.8.x)
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

### Expected Behaviour

I expect singleton classes and their companion objects to be instantiated once.

### Actual Behaviour

I get two instances of singleton class and two scheduled jobs running in parallel.

**Comment by schmitch** [comment] 2016-08-14 07:48
It still runs them at once, however the problem is, is that evolutions will restart your application, but not the akka system. and you **never** cancel your system.schedule, which you should do.
You should inject a `ApplicationLifecycle` and add a shutdown hook that will [cancel](http://doc.akka.io/docs/akka/2.4.9-RC2/scala/scheduler.html#The_Cancellable_interface) the scheduler.

This is hardly a bug and more a problem of a missing `stop`. I will close this issue, but feel free to reopen it if you still encounter bugs after adding a shutdown hook.

**Comment by arunasr** [comment] 2016-08-14 13:03
Sorry, should have said that in the original description, but I tried ApplicationLifecycle - nothing happens. According to the log, Application does not get started before the evolution is applied, so "stopHook" is never called.
I am most confused about the companion object being created twice. Aren't objects supposed to be singletons in Scala?

**Comment by schmitch** [comment] 2016-08-14 13:30
Actually as said it's caused by the classloader:
```
[debug] s.Scheduler - tick 12 ReloadableClassLoader(v2){file:/Users/schmitch/projects/schmitch/play/play-demo-bug-test/target/scala-2.11/classes/} 1139444200
[debug] s.Scheduler - tick 18 ReloadableClassLoader(v1){file:/Users/schmitch/projects/schmitch/play/play-demo-bug-test/target/scala-2.11/classes/} 1371870346
```

These are different if you change it to:
`logger.debug(s"tick ${Scheduler.ticker} ${this.getClass.getClassLoader} ${System.identityHashCode(this.getClass.getClassLoader)}")`

I guess the problem is, that the old classloader won't get killed since actorsystem will still use it or something like that.

**Comment by arunasr** [comment] 2016-08-14 15:45
With GlobalSettings deprecated, is there another way to schedule jobs after application start and not before? It seems dependency injection stage is too early for this.
Also, I would like to point out that other supposed singletons, Logger and HikariPool, also seem to be created twice.

**Comment by schmitch** [comment] 2016-08-14 16:03
they won't be created twice. after a application is restarted they will be instanciated again. And the other classloader should probably be garbage collected.

**Comment by arunasr** [comment] 2016-08-14 16:09
Not so worried about the other singletons..
What is the recommended way to add to Application start? I am referring to log line 
```
13 21:55:06.161 [info]play.api.Play: Application started (Dev)
```
I think that it would be appropriate to start scheduled jobs only after the application and the context is fully initiated.

**Comment by schmitch** [comment] 2016-08-14 19:35
Actually the Application start means that **all** components are already loaded.
Play loads the Components in an *undefined* order. At the moment the Evolutions Module will be run **after** your Module, which then will fail, however on *Failure* the stop hooks won't get called (which is bad of course).

It's the recommended way. But as said the ApplicationLoader will never call the stop hooks on failure (yet). Which is of course a bug.

**Comment by gmethvin** [comment] 2016-08-15 10:46
I agree the stop hooks should be called even if the app failed to start properly, since presumably they are added after that component has been started. That's a bug.

If you want to force an ordering you can make your component depend on `ApplicationEvolutions` (though this seems like sort of a hack): 
```scala

class Scheduler @Inject() (val system: ActorSystem, evolutions: ApplicationEvolutions)(implicit ec: ExecutionContext) {
  import Scheduler._
  Logger info "Scheduler class created"

  system.scheduler.schedule(0.seconds, 1.second) {
    Logger debug s"tick $ticker"
    ticker += 1
  }
}
```

**Closed** 2016-08-15 20:40 UTC
Labels: defect

**Comment by arunasr** [comment] 2016-08-16 13:02
Thanks Greg, this helped. I was thinking along the lines of providing my own Evolutions, but merely including the dependency solved the problem.
