### ISSUE TITLE
AssetsController should not clear flash

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#9573] opened 2019-08-15 19:32 UTC
### Play Version
2.6.21

### API
Java

### Operating System
Windows 10

### JDK
JDK 9.0.4

### Library Dependencies
N/A

### Expected Behavior
AssetsController should not clear `PLAY_FLASH` cookie

### Actual Behavior
AssetsController clears `PLAY_FLASH` cookie

### Reproducible Test Case
1. Browser makes request to /foo, which sets request flash
2. Browser makes request to /assets/js, which clears flash
3. Browser makes request to /bar, which is expected to receive flash, but receives null instead

**Comment by mkurz** [comment] 2019-08-15 19:46
The flash scope is used for redirects usually, [see docs](https://www.playframework.com/documentation/2.7.x/JavaSessionFlash#Flash-scope).
It's discouraged to use it for anything but redirects. You will even see a warning in dev mode:
https://github.com/playframework/playframework/blob/d0dea6ca990f4bd7a212ca723e54cc9c175a1a21/core/play/src/main/scala/play/api/mvc/Results.scala#L113-L124

So when action method /foo redirects to /bar, there will no request to /assets/js in between, but only afterwards (because I guess /bar includes /assets/js in its template).
Or am I missing something? How do you use the flash scope?

**Comment by eximius313** [comment] 2019-08-15 21:53
I'm sending the redirect, but because of frontend framework, I can't just do 301 with location (because then fronend framework can't do it's stuff) so I send such json: `{redirect: "/bar"}` and then user is redirected there by frontend framework

**Comment by ignasi35** [comment] 2019-08-22 15:43
@eximius, this sounds to me like your code should recreate the flash cookie or use session cookies instead when doing this _manual redirect_. IMHO this is not an issue.

**Comment by eximius313** [comment] 2019-08-22 15:48
But it's not *my code* that "steals" the FLASH (I woudn't create issue then), but AssetsController in PlayFramework (that's the issue about)

**Comment by marcospereira** [comment] 2019-08-22 15:51
Yeah, does not look like an issue to me as well. Flash is working as designed here. Maybe you shouldn't be using flash but instead another cookie.

@eximius313 I'm closing this. But let us know if we are missing something here.

Best

**Closed by marcospereira** 2019-08-22 15:51 UTC
Labels: closed:invalid
