### ISSUE TITLE
Use 2.4.0-RC1 in Migration Guide instead of 2.4.0

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#4287] opened 2015-04-24 13:25 UTC
Instead of this:

    addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.0")

The [migration guide](https://www.playframework.com/documentation/2.4.0-RC1/Migration24) should say this:

    addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.0-RC1")

**Comment by jroper** [comment] 2015-04-27 01:34
I don't know that we have a good solution for this - the docs are fairly static, and we don't want to have to manually update every version mentioned in the docs every time we cut a release.  We do support a `%PLAY_VERSION%` variable that can be put into the docs, but we can't use that here, because the 2.4 migration guide must only have a 2.4 version there, when we move to Play 3, that will end up being substituted with `3.0.0`, which would be wrong (similarly, consider the Play 2.3 migration docs, if we used `%PLAY_VERSION%` in there, it would now say `2.4.0-RC1`.

The approach I've taken here has been to choose the version that will become valid once Play 2.4.0 is released.

If anyone has any suggestions for a nicer way to address this, I'd love to hear them.

**Comment by mslinn** [comment] 2015-04-27 02:52
Perhaps an Ivy [dynamic version](http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html) like `latest.milestone` or `latest.milestone`? The docs could say:

Use this prior to release of Play 2.4 final:

    addSbtPlugin("com.typesafe.play" % "sbt-plugin" % latest.milestone)

And either this after 2.4 release:

    addSbtPlugin("com.typesafe.play" % "sbt-plugin" % latest.release)

or this:

    addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4")

The latter won't track the inevitable point releases like the former would, however.

**Comment by wsargent** [comment] 2016-03-19 00:48
Duplicate of https://github.com/playframework/play-doc/issues/20

**Closed by wsargent** 2016-03-19 00:48 UTC
Labels: documentation
