### ISSUE TITLE
[2.3.x] Scala Play-cache plugin shuts down entire net.sf.ehcache onStop()

### ISSUE THREAD

**Issue by ssemakin** [playframework/playframework#4327] opened 2015-04-29 15:40 UTC
Hi, we ran into the following issue: using FakeApplication for tests with the cache plugin, seems to completely shuts down net.sf.ehcache. The reason for that appears to be [here](https://github.com/ssemakin/playframework/blob/2.3.x/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala#L168)

```
override def onStop() {
    if (loaded) {
      manager.shutdown()
    }
  }
```

Using net.sf.ehcache for something else in parallel with this pluging can probably cause higher inconvenience.

**Comment by jroper** [comment] 2015-04-30 02:34
Yes, unfortunately, due to ehcache's inherently static nature, storing the manager as a global singleton, there's not a lot we can do about that, we have to shut the whole thing down otherwise it leaks threads and memory.  By default, Play configures your tests to not run concurrently, so this shouldn't be a problem.

**Comment by ssemakin** [comment] 2015-05-01 11:08
Thanks James. So basically you're saying that removing cache onStop() wouldn't help? I mean doing something like this (I'm not really much familiar with net.sf.ehcache):

```
override def onStop() {
    if (loaded) {
      manager.removeCache("play")
    }
  }
```

At least this is what happens at first glance in Play 2.4.x branch.

**Comment by jroper** [comment] 2015-05-01 11:39
Of the top of my head - not sure.  If there is one cache created, Ehcache considers that *the* global singleton cache.  Removing it I think is effectively equivalent to shutting the whole of ehcache down.  It's weird, and I could be off a bit, I haven't been into the ehcache source code for over 6 months.

**Comment by jroper** [comment] 2015-05-01 11:41
There are reasons why Play does what it does.  If you can come up with a better way that doesn't leak threads and/or memory and/or classloaders when Play is shutdown, I'm all ears.  The code you suggest I don't think does what you think it will do, you'll have to dive into the ehcache source code to work out what should be done, and if you submit a PR, make sure you provide a could explanation of why what you're submitting is ok.

**Comment by ssemakin** [comment] 2015-05-01 17:43
Ok, let me double check it and I'll come back to you on this.

**Comment by cchantep** [comment] 2016-09-12 00:18
Closing it for now. If confirmed on master, and discussed first on the mailing list to figure out whether there is something actionable about, an up-to-date ticket could be submitted. Best regards.

**Closed by cchantep** 2016-09-12 00:18 UTC
