### ISSUE TITLE
Play 2.8.18 sbt build failed

### ISSUE THREAD

**Issue by Liu-Eric-Yu** [playframework/playframework#11568] opened 2022-12-09 08:41 UTC
### Play Version

Play 2.8.18

### API

Scala 2.13.10

### JDK

```
java version "11.0.17" 2022-10-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.17+10-LTS-269, mixed mode)
```

### Expected Behavior
sbt build should be finished

### Actual Behavior

```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.2.0, 1.1.1, 1.3.0}
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- org.foundweekends.giter8:giter8-lib_2.12:0.13.1    (depends on 1.3.0)
[error] 	    +- com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.1.1)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
[error]
[error]
```

### QA:
What should I do  that can fix this problem.  And make sure that I can build it successful with sbt.

Thanks in advance.

**Comment by mkurz** [comment] 2022-12-12 10:53
Duplicate of
* #11522

Please
* either stay on sbt 1.7.2 for now (in your `project/build.properties´)
* Or put `
ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always` in your `project/plugins.sbt`, like described in #11522

**Closed by mkurz** 2022-12-12 10:53 UTC

**Comment by Liu-Eric-Yu** [comment] 2022-12-13 00:36
> 
Thanks, It`s worked.
my project sbt version is 1.8.0 
It looked same problem as sbt 1.7.3.
