### ISSUE TITLE
Play Testing API does not handle absent body for POST request

### ISSUE THREAD

**Issue by techmoksha** [playframework/playframework#8632] opened 2018-09-24 22:44 UTC
### Play Version (2.5.x / etc)

Play 2.6.13 (play-test_2.12-2.6.13)

### API

Scala

### Operating System

Mac OS 10.12.1

### JDK

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

### Expected Behavior

1. POST requests using play-test API should support null/absent body.

### Actual Behavior

1. All details mentioned [here](https://discuss.lightbend.com/t/post-method-without-body-for-testing/2216)

### Reproducible Test Case

The [post](https://discuss.lightbend.com/t/post-method-without-body-for-testing/2216) has the code snippet to reproduce the issue.

**Comment by mkurz** [comment] 2019-10-22 09:26
@techmoksha I tried hard, but I can not reproduce the exception using Play-Scala 2.6.13.
Can you provide us a reproducer that "works" (throws the exception)?

I used following test, because the example you give in the original discussion does compile...
```scala
package controllers

import org.scalatestplus.play._
import org.scalatestplus.play.guice._
import play.api.test.Helpers._
import play.api.test._

class HomeControllerSpec extends PlaySpec with GuiceOneAppPerTest with Injecting {

  "HomeController POST" should {

    "not throw an exception with empty body" in {
      val request = FakeRequest(POST, "/uri").withHeaders("<myheader>" -> "headervalue")
      val result = Helpers.route(fakeApplication, request)
    }
  }
}
```

**Comment by mkurz** [comment] 2019-10-30 10:37
I had a look again because I was working on related code. However, I am still not able to reproduce this. The only place where `jRoute` is called is [inside Java's `route` helper](https://github.com/playframework/playframework/blob/cfd5c815b196210e1bb364f9cce78bdadd2a8a3b/testkit/play-test/src/main/java/play/test/Helpers.java#L473-L474). And because this Java `router` helper method expects a `RequestBuilder`, we can be sure that this `RequestBuilder` always has a `RequestBody` set (just look how `RequestBody` is implemented, you will not be able to set `null` as body) (This `RequestBody` can in turn contain `null` but that does not matter here). So it's not possible to run into the NPE (also I was not able to do so).
So maybe the author did use `jRoute` directly and passed `null` explictly as body... However this is not how this should be used.

Because there is no reproducer I will close this.
Feel free to re-open if you know how to reproduce this.

**Closed by mkurz** 2019-10-30 10:37 UTC
Labels: good first issue
