### ISSUE TITLE
Stop/Start programaticaly

### ISSUE THREAD

**Issue by vooolll** [playframework/playframework#6666] opened 2016-10-24 08:47 UTC
I have a problem to stop and start play application programaticaly. I call `Play.stop(application)` (application is instance of current application). Then I call `startNoLicenceApp()`  which does the following:

` private def startNoLicenceApp() = {
    logger.info("starting free version of application")
    Play.start(
      new NoLicenceApplication(
        injector.instanceOf[Environment],
        injector.instanceOf[DefaultApplicationLifecycle],
        injector,
        configuration,
        new NoLicenceHttpRequestHandler(new NoLicenceRouter),
        new NoLicenceHttpErrorHandler,
        actorSystem,
        injector.instanceOf[Materializer]
      ))
  }`

But I have exception: `java.lang.IllegalStateException: Attempted to call materialize() after the ActorMaterializer has been shut down.`

Is it possible somehow start another  play application, after stopping previous?

**Comment by schmitch** [comment] 2016-10-24 08:52
First of all, this is a issue tracker, if you have questions regarding your application, you can ask it on the mailing list: `https://groups.google.com/forum/#!forum/play-framework``

The problem that you encounter is that you try to start the application with the values of the previous `Application`, that **can't** work, you actually need to either create your own Server Start where you manually instantiate all the needed values.

I'm closing but feel free to ask on the Mailing List, if you still have questions.

**Closed by schmitch** 2016-10-24 08:52 UTC

**Comment by vooolll** [comment] 2016-10-24 08:59
@schmitch it is strange, because it is worked in play 2.4. My question is about playframework, is it possible to start it programaticaly... There is no documentation about it. I try to create my own ActorSystem and Materializer, but I still have `java.lang.IllegalStateException: Attempted to call materialize() after the ActorMaterializer has been shut down.`

**Comment by schmitch** [comment] 2016-10-24 09:02
As already said, this is an issue tracker and this is not a bug since you use the same `Materializer` that you previously stopped.
Here are some topics that might help you, but it's better to ask on the Mailing List:

- https://www.playframework.com/documentation/2.5.x/ScalaEmbeddingPlay
- https://www.playframework.com/documentation/2.5.x/ScalaDependencyInjection
- https://www.playframework.com/documentation/2.5.x/ScalaCompileTimeDependencyInjection#Compile-Time-Dependency-Injection

**Comment by vooolll** [comment] 2016-10-26 12:07
@schmitch 
In documentation of Play.stop method there is written that: Stops the given application``

```
package controllers

import com.google.inject.Inject
import play.api.inject.Injector
import play.api.mvc.{Action, Controller}
import play.api.{Application, Play}

class TestController @Inject()(injector: Injector) extends Controller{

  def stop() = Action {
    Play.stop(injector.instanceOf[Application])
    Ok("stop")
  }

  def info() = Action {
    Ok("info")
  }
}
```

Scala 2.11.8, Play 2.5.8, sbt 0.13.8 ubuntu 16.04

**Comment by schmitch** [comment] 2016-10-26 12:20
Well it does stop everything that is attached to the `ApplicationLifecycle`, including the `ActorSystem` so it basically stop's the application but doesn't exit it, the `NettyServer`  will still run. you can actually `sys.exit` for that case. As already said if you want to start and stop the application programaticaly you need to either use the Embedded mode or stop the application and reconstruct it by yourself.

From your snippet:
```
Play.start(
 new NoLicenceApplication(
 injector.instanceOf[Environment],
 injector.instanceOf[DefaultApplicationLifecycle],
 injector,
 configuration,
 new NoLicenceHttpRequestHandler(new NoLicenceRouter),
 new NoLicenceHttpErrorHandler,
 actorSystem,
 injector.instanceOf[Materializer]
 ))
```

Every value of `Injector` might be shutdown and can't be used, you basically need to construct that stuff yourself, including the Injector.
