### ISSUE TITLE
Should Reads[A] be covariant in A?

### ISSUE THREAD

**Issue by mvanderkolff** [playframework/playframework#3934] opened 2015-02-15 21:30 UTC
Use case: https://mvdkolff.wordpress.com/2015/02/15/path-dependent-types-tagged-unions-and-play-for-scala/

Without the type wrapper, I get

found   : play.api.libs.json.Reads[_1] where type _1 >: z.Request <: models.ReportKinds.RunnableReport
[error]  required: play.api.libs.json.Reads[models.ReportKinds.RunnableReport]
[error] Note: _1 <: models.ReportKinds.RunnableReport, but trait Reads is invariant in type A

**Comment by mvanderkolff** [comment] 2015-02-15 21:32
Just an aside - note that Writes[-A] is contravariant in A, so that is at least suggestive...

**Comment by gmethvin** [comment] 2015-02-15 23:12
If you have two classes `Foo` and `Bar` that extend `Baz`, your `Reads[Foo]` and `Reads[Bar]` can make an assumption about which subtype they're reading. You'd expect a `Reads[Baz]` to make some kind of determination about whether it's reading a `Foo` or a `Bar` and produce the right type. So in that sense I don't think it makes sense for `Reads` to be covariant.

**Comment by mvanderkolff** [comment] 2015-02-15 23:58
That doesn't quite smell right. Reads[A] is a thin wrapper over JsValue => JsResult[A], and JsResult is covariant in , and functions are covariant in their return type.

Reads 'reads' from a JsValue and 'writes'/makes an A. Since it makes one, I'm thinking covariant...

Your rationale makes more sense for Writes, afaict...

**Comment by jroper** [comment] 2015-02-16 00:44
If I have:

```scala
trait Baz
case class Bar(bar: String) extends Baz
object Bar {
  implicit val reads = Json.reads[Bar]
}
case class Foo(foo: String) extends Baz
```

Now, if I do:

```scala
Json.fromJson[Baz](Json.obj("foo": "hello"))
```

The above makes sense, we have a JSON representation of a `Foo`, we should be able to deserialise it as a `Baz`.  If we make `Reads` covariant in A, it compiles fine.  But of course, it fails at runtime.  By making `Reads` non variant in A, we move this error to compile time, and that makes sense - just because something knows how to read a subtype of `Baz`, doesn't mean it knows how to read all `Baz`'s, so therefore, it should not be a candidate for reading `Baz`.

**Comment by jroper** [comment] 2015-02-16 00:50
One thing we should do however is change the signature of `orElse` to be:

```scala
def orElse[B :> A](reads: Reads[_ <: B]): Reads[B]
```

Then you can define a `Reads[Baz]` like this:

```scala
implicit val bazReads: Reads[Baz] = implicitly[Reads[Foo]] orElse implicitly[Reads[Bar]]
```

**Comment by mvanderkolff** [comment] 2015-02-16 01:46
OK, so what then do you suggest for the following?

    trait ReportRequest {
        type P
        val writer: Writes[P] //Part of the writer, this works...
        val params: P
        val kind: ReportKind //Used for the writer
        // Some methods for an implementer, like make a PDF, etc.
    }
    sealed trait ReportKind {
        type Parameters
        type Request <: ReportRequest
        
        val id : String
        val formatter : Format[Parameters]
        def makeRequest(p: Parameters) : Request
        trait RRequest extends ReportRequest {
            type P = Parameters
            val writer = formatter
        }
    }
    object BAL extends ReportKind {
        type Parameters = List[Int] //e.g.
        override val formatter = implicitly[Format[List[Int]]]
        override val id = "BAL"
        
        class Request(p: Parameters) extends RRequest {
            override val params = p
            override val kind = BAL
        }
    }
    val reportKinds : Map[String, ReportKind] = Map("BAL" -> BAL ) //Yeah, don't have the relevant macro, trying to figure out how that works...

I would like to write

    implicit val ReportRequestReads : Reads[ReportRequest] = 
        (__ \ "kind").read[String] flatMap (k => reportKinds.get(k).map({ kind =>
            (__ \ "params").read[kind.Parameters](kind.formatter) map { kind.makeRunnable(_) }
        }).getOrElse(Reads[ReportRequest](_ => JsError(s"Unknown report kind: $k"))))

But `(__ \ "params").read[kind.Parameters](kind.formatter) map { kind.makeRunnable(_) }` is something akin to Reads[kind.Request], which apparently can't be promoted to Reads[ReportRequest].

**Comment by mvanderkolff** [comment] 2015-02-16 01:57
Got it! Use type ascription in the function: `kind.makeRunnable(_)` becomes `kind.makeRunnable(_) : ReportRequest`

**Comment by mvanderkolff** [comment] 2015-02-16 07:56
That seems like a kludge - is there anything that would let map do the right thing?

**Comment by mvanderkolff** [comment] 2015-02-16 08:00
That seems like a kludge - is there anything that would let map do the right thing?

**Comment by mvanderkolff** [comment] 2015-02-16 09:43
Perhaps slightly more elegant is filling in the type parameter on map: `map` becomes `map[ReportRequest]` .  I suppose I'm satisfied that if this is an issue, then it's a documentation issue - it seems right that we'd want to statically reject jroper's example.

Thanks for your help, guys :)

**Comment by julienrf** [comment] 2015-02-16 12:55
Hi,

As mentioned by @jroper, the problem is that the `Reads[A]` you write may not work for subtypes of `A`. You as a developer has to explicitly support subtypes (e.g. using a JSON field to store the type tag).

For information, I remember that `Reads` and `Writes` were initially invariant. After some times they were made [co- and contravariant](https://github.com/playframework/playframework/commit/b5da431531f9b74f69072f7320213538e10d0502), but then after some more time we [reverted](https://github.com/playframework/playframework/commit/5ec75f4b8bde1e2251fb34dbcfaa151759b3dc11#diff-70a7ba16492ab8a27232446f8b2d0a53) `Reads` to be invariant. I don’t remember why `Writes` were not reverted too.

It would be great if the macros could generate `Reads` and `Writes` that support union types (as in [play-json-variants](http://github.com/julienrf/play-json-variants)). Are there any plans in this direction? What about using scala-pickling to avoid re-inventing the wheel?

**Comment by cchantep** [comment] 2015-02-16 18:19
I think we can close is issue and discuss potential JSON improvements elsewhere.

**Comment by mvanderkolff** [comment] 2015-02-16 20:56
@cchantep : not sure. I remember reading about covariant and contravariant maps in the tutorial on the website. Can't find it ATM,  but I'd say that the map method deserves the note that sometimes its type parameter might need to be manually annotated.

**Comment by gmethvin** [comment] 2015-02-16 21:19
Closing this issue since I think we're agreed that no changes are needed.

@julienrf It'd be nice to see JSON macros in play-json to support union types. I'd also really like something that takes case objects extending a sealed trait/class and serializes to strings.

I think it's still okay for `Writes[A]` to be contravariant as long as we assume the representation of some type `A` is the same across your application. But that's probably also a discussion for elsewhere...

**Closed by gmethvin** 2015-02-16 21:19 UTC

**Comment by jroper** [comment] 2015-02-17 01:27
Some day I'd love to move to @jto's validation API, I think that's the best place for innovation in the macros.
