### ISSUE TITLE
WSClient doesn't parse UTF-8 `application/json` response correctly

### ISSUE THREAD

**Issue by mikla** [playframework/playframework#7712] opened 2017-08-09 10:18 UTC
I have endpoint that returns UTF-8 JSON. `/utf8response` in the example. I have second endpoint `/requestEmployee` that requests `/utf8response` to obtain employee information (via `WSClient`) and I get response with corrupted encoding.

Controller code: 

```scala
case class Employee(name: String)

@Singleton
class HomeController @Inject()(cc: ControllerComponents, ahc: WSClient)
  extends AbstractController(cc)
    with Circe {

  implicit val employeeDecoder: Decoder[Employee] = deriveDecoder[Employee]
  implicit val employeeEncoder: Encoder[Employee] = deriveEncoder[Employee]

  def utf8response() = Action { implicit req =>
    val employee = Employee("āčēģīķļņšūž ĀČĒĢĪĶĻŅŠŪŽ")
    val json = employee.asJson

    Ok(json).as(JSON) // works fine if replace JSON to "text/json; charset=utf-8"
  }

  def requestEmployee() = Action.async { implicit req =>
    ahc.url("http://localhost:9000/utf8response")
      .get().map(r => Ok(r.body).as(JSON))
  }

}
```

Note: this behavior preserves only for versions 2.6.0, 2.6.1, 2.6.2. 
Behavior is correct on versions 2.6.0-RC2, 2.5.15

### JDK
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### Library Dependencies
circe 0.8.0

### Expected Behavior

1. sbt run
2. curl 'localhost:9000/requestEmployee'
3. Output should be: `{"name":"āčēģīķļņšūž ĀČĒĢĪĶĻŅŠŪŽ"}%`

### Actual Behavior
`curl 'localhost:9000/requestEmployee'` returns json with broken encoding.

Output: 

`{"name":"ÄÄÄÄ£Ä«Ä·Ä¼ÅÅ¡Å«Å¾ ÄÄÄÄ¢ÄªÄ¶Ä»ÅÅ ÅªÅ½"}%`

### Reproducible Test Case

Here is GitHub project to reproduce problem.

https://github.com/mikla/play-framework-wsclient-encoding-problem

Play 2.6.2 in `master` branch
Play 2.5.15 in `play2.5` branch
Play 2.6.0-RC2 in `play2.6.0-RC2` branch

**Comment by gmethvin** [comment] 2017-08-09 11:56
I believe this is a duplicate of https://github.com/playframework/play-ws/issues/150

I suspect if you change `r.body` to `r.bodyAsBytes` that will fix work. Does that change the behavior?

The difference in 2.6.0 is that we are delegating completely to the AsyncHttpClient to handle parsing the body of the response. That library makes different assumptions about the default charset. Previously, if no charset parameter was sent we would assume ISO-8859-1 for text charsets and UTF-8 otherwise. Now it uses ISO-8859-1 as the default regardless.

You're right this is a bug in the sense that it makes the method not do something useful it did do before, but it's important to recognize that the `body: String` method is only a best-guess effort, and it isn't designed to know the encoding rules of every content type. It's generally safer to use `body[Foo]` and define an implicit `BodyReadable[Foo]` to convert the response properly, or use `bodyAsBytes` to get the raw body and handle it how you want.

**Comment by gmethvin** [comment] 2017-09-11 07:08
I'm going to close it since there is already discussion going on in the play-ws repo.

**Closed by gmethvin** 2017-09-11 07:08 UTC
