### ISSUE TITLE
Broken characters in docs

### ISSUE THREAD

**Issue by restlessdesign** [playframework/playframework#5210] opened 2015-10-28 16:00 UTC
It looks like the documentation is breaking on some special characters. For example, the [Anatomy of a Play Application](https://www.playframework.com/documentation/2.4.x/Anatomy) page is breaking on the `└ ` character within [Anatomy.md](https://github.com/playframework/playframework/blob/master/documentation/manual/gettingStarted/Anatomy.md):

<img width="659" alt="screen shot 2015-10-28 at 11 59 16 am" src="https://cloud.githubusercontent.com/assets/128779/10794462/5e411134-7d6b-11e5-9976-69dca4622e1f.png">

Tested on FF and Chrome (OS X).

**Comment by benmccann** [comment] 2015-11-06 17:08
It's working for me in both Chrome and Firefox in Linux Mint. Since I can't reproduce I'll have to leave this for someone else to fix. Pull requests welcome.

**Comment by gmethvin** [comment] 2015-11-08 22:13
Closing because it seems to be fixed. See playframework/playframework.com#41

**Closed by gmethvin** 2015-11-08 22:13 UTC
Labels: documentation

**Comment by restlessdesign** [comment] 2015-11-09 17:09
Yep, confirming that this looks good now!
