### ISSUE TITLE
Assets controller blows up on request to /assets/stylesheets

### ISSUE THREAD

**Issue by pkaeding** [playframework/playframework#4531] opened 2015-05-22 06:13 UTC
Assuming a routes definition like:

    GET     /assets/*file               controllers.Assets.at(path="/public", file)

If I request `/assets/foo` or `/assets/stylesheets/bar`, I get a `404` as expected,  However, accessing `/assets/stylesheets` results in a `500` response with the following logged:

```
! @6m8bn5ei8 - Internal server error, for (GET) [/assets/stylesheets] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: Unexpected error while serving stylesheets at /public: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.RuntimeException: Unexpected error while serving stylesheets at /public: null
	at controllers.AssetsBuilder$$anonfun$at$1$$anonfun$apply$1.applyOrElse(Assets.scala:432) ~[com.typesafe.play.play_2.10-2.3.8.jar:8aae6734e371eeb215085b1bd35fc225ff5f7485]
	at controllers.AssetsBuilder$$anonfun$at$1$$anonfun$apply$1.applyOrElse(Assets.scala:425) ~[com.typesafe.play.play_2.10-2.3.8.jar:8aae6734e371eeb215085b1bd35fc225ff5f7485]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
	at java.io.FilterInputStream.close(FilterInputStream.java:181) ~[na:1.7.0_06]
	at sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream.close(JarURLConnection.java:108) ~[na:1.7.0_06]
	at controllers.AssetInfo$$anonfun$4.apply(Assets.scala:149) ~[com.typesafe.play.play_2.10-2.3.8.jar:8aae6734e371eeb215085b1bd35fc225ff5f7485]
	at controllers.AssetInfo$$anonfun$4.apply(Assets.scala:144) ~[com.typesafe.play.play_2.10-2.3.8.jar:8aae6734e371eeb215085b1bd35fc225ff5f7485]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
```

The same is true for `/assets/images` and `/assets/javascripts`.

**Comment by jroper** [comment] 2015-05-22 06:37
Duplicate of #3459.

**Closed by jroper** 2015-05-22 06:37 UTC
