### ISSUE TITLE
Sporadic binding errors for NameEhCacheProvider

### ISSUE THREAD

**Issue by mikesname** [playframework/playframework#4717] opened 2015-06-19 10:59 UTC
Attempting to migrate 2.3.x apps to 2.4.x I keep running into EhCache binding errors like this:

```
1) Error in custom provider, net.sf.ehcache.ObjectExistsException: Cache play already exists
      at play.api.cache.EhCacheModule.play$api$cache$EhCacheModule$$bindCache$1(Cache.scala:181):
    Binding(interface net.sf.ehcache.Ehcache qualified with QualifierInstance(@play.cache.NamedCache(value=play)) to ProviderTarget(play.api.cache.NamedEhCacheProvider@171916b7)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
      while locating net.sf.ehcache.Ehcache annotated with @play.cache.NamedCache(value=play)
      at play.api.cache.EhCacheModule.play$api$cache$EhCacheModule$$bindCache$1(Cache.scala:182):
    Binding(interface play.api.cache.CacheApi qualified with QualifierInstance(@play.cache.NamedCache(value=play)) to ProviderTarget(play.api.cache.NamedCacheApiProvider@50f2c14d)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
      while locating play.api.cache.CacheApi annotated with @play.cache.NamedCache(value=play)
      while locating play.api.cache.CacheApi

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11.jar:2.4.1-SNAPSHOT]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[play_2.11.jar:2.4.1-SNAPSHOT]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:236) ~[play_2.11.jar:2.4.1-SNAPSHOT]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11.jar:2.4.1-SNAPSHOT]
	at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[play_2.11.jar:2.4.1-SNAPSHOT]
	at play.utils.InlineCache.apply(InlineCache.scala:60) ~[play_2.11.jar:2.4.1-SNAPSHOT]
	at play.api.cache.Cache$.cacheApi(Cache.scala:63) ~[play-cache_2.11.jar:2.4.1-SNAPSHOT]
	at play.api.cache.Cache$.getAs(Cache.scala:127) ~[play-cache_2.11.jar:2.4.1-SNAPSHOT]
Caused by: net.sf.ehcache.ObjectExistsException: Cache play already exists
	at net.sf.ehcache.CacheManager.addCache(CacheManager.java:1171) ~[ehcache-core-2.6.11.jar:na]
	at play.api.cache.NamedEhCacheProvider.get$lzycompute(Cache.scala:213) ~[play-cache_2.11.jar:2.4.1-SNAPSHOT]
	at play.api.cache.NamedEhCacheProvider.get(Cache.scala:210) ~[play-cache_2.11.jar:2.4.1-SNAPSHOT]
	at play.api.cache.NamedEhCacheProvider.get(Cache.scala:208) ~[play-cache_2.11.jar:2.4.1-SNAPSHOT]
	at com.google.inject.util.Providers$GuicifiedProvider.get(Providers.java:119) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016) ~[guice-4.0.jar:na]
```

This seems to be cropping up mostly when:
 - the app is using the legacy global `Cache` instance
 - running repeated tests, possibly with the same `Application` instance (e.g. with the `WithBrowser` test helper, which takes an app argument.)

It also seems to happen on a somewhat sporadic basis, making it hard to put together a minimal sample app which consistently fails. I'm working on that.

While this error might be pointing to the pitfalls of using global state, I don't think this kind of error should be leaking out. That is, if there's actually a problem here the framework should throw a more useful error.

The immediate cause can be fixed by replacing `manager.addCache(name)` with `manager.addCacheIfAbsent(name)` in the `NamedEhCacheProvider`. I'm happy to put in a PR but because I'm a bit hazy on how and when Guice caches the things it binds, maybe fixing this would mask a more pernicious problem with app state in tests.

**Comment by jroper** [comment] 2015-06-22 04:54
`addCacheIfAbsent` won't fix the problem, it will only move the problem.  When `addCache` fails, it means that there are two applications started at once.  If we switch to `addCacheIfAbsent`, then when one of them shuts down, the second one will start throwing errors when it tries to use the cache, or possibly when it shuts the cache down.  So you'll still get ehcache errors, you'll just get different ones at different times.

The problem here actually isn't Play's global state, it's ehcache's global state, which from my investigations, is impossible to work around, ehcache forces every cache manager to put itself into a global singleton of caches.  Once we've fixed Play's global state problems, this problem will still exist.

**Comment by mikesname** [comment] 2015-06-22 06:23
Thanks for your explanation, and I definitely agree with not simply moving the problem. What's made this one so frustrating to me is that each time I've seen it it's had a different root cause that's never been anything much to do with ehcache (the last time it was in due to the inclusion of something in `play.modules.enable` that diddled with the lifecycle somehow.)

I think this might be one of those cases where it's merciful to catch and rethrow the original exception with a length explanatory blurb.

**Comment by jroper** [comment] 2015-06-22 10:08
Yes, that's a good idea.

**Closed** 2015-06-23 05:12 UTC

**Comment by godenji** [comment] 2015-11-19 16:45
This is total madness, getting same error on 2.4 with compile time DI. What exactly are we meant to do here? As with @mikesname the root cause somehow shifts around.

**Comment by richdougherty** [comment] 2015-11-20 00:23
I'm reopening this ticket because I think it may be fixable.

At the moment we're using [`CacheManager.create(InputStream)`](http://grepcode.com/file/repo1.maven.org/maven2/net.sf.ehcache/ehcache/2.8.6/net/sf/ehcache/CacheManager.java#CacheManager.create%28java.io.InputStream%29) which creates a singleton and puts the `CacheManager` into a global map using a name read from `InputStream`. You can see the code that calls `CacheManager.create()` in Play's [`CacheManagerProvider`](https://github.com/playframework/playframework/blob/master/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala#L194-L202).

Instead we should update the `CacheManagerProvider` to:
1. Read the `Configuration` from the `InputStream` ourselves.
2. Call `Configuration.setName()` to give it a random name so it won't conflict in the global map.
3. Call [`CacheManager.newInstance(Configuration, ...)`](http://grepcode.com/file/repo1.maven.org/maven2/net.sf.ehcache/ehcache/2.8.6/net/sf/ehcache/CacheManager.java#CacheManager.newInstance%28java.io.InputStream%29) to create a non-singleton `CacheManager`.

At least I think that would work. Can someone investigate?

**Comment by nowxue** [comment] 2016-01-27 03:08
@richdougherty I think your solution works. I was getting the same error in my application sporadically, and my test suite was always failing with the error reported by @mikesname when I used the test command in activator console (running all the tests at once).
I created a custom cache manager provider as you suggested:
```
@Singleton
class CustomCacheManagerProvider @Inject() (env: Environment, config: Configuration, lifecycle: ApplicationLifecycle) extends Provider[CacheManager] {
  lazy val get: CacheManager = {
    val resourceName = config.underlying.getString("play.cache.configResource")
    val configResource = env.resource(resourceName).getOrElse(env.classLoader.getResource("ehcache-default.xml"))
    val configuration = ConfigurationFactory.parseConfiguration(configResource)
    configuration.setName(UUID.randomUUID.toString)
    val manager = CacheManager.newInstance(configuration)
    lifecycle.addStopHook(() => Future.successful(manager.shutdown()))
    manager
  }
}
```
And overridden  the default CacheManagerProvider in a `CustomApplicationLoader`, and now my test suite is running fine and the application seems to work fine so far.

**Comment by scaryroy** [comment] 2016-02-09 07:20
hi @nowxue are you able to paste up some code of how you bound your CustomCacheManagerProvider using DI? I am having trouble understanding the documentation.

Thanks

**Comment by nowxue** [comment] 2016-02-09 14:29
Sure, you have to create a custom loader and register it in application.conf:

```
import play.api.ApplicationLoader
import play.api.inject._
import play.api.inject.guice._
import net.sf.ehcache.CacheManager

class CustomApplicationLoader extends GuiceApplicationLoader() {
  override def builder(context: ApplicationLoader.Context): GuiceApplicationBuilder = {
    initialBuilder
      .in(context.environment)
      .loadConfig(context.initialConfiguration)
      .overrides(overrides(context): _*)
      //We just override default cache provider with custom one
      .overrides(bind[CacheManager].toProvider[CustomCacheManagerProvider])
  }
}
```

And in application.conf: `play.application.loader = "core.CustomApplicationLoader"`

**Comment by scaryroy** [comment] 2016-02-09 19:16
Thanks @nowxue that works for me too

**Comment by alejandrolujan** [comment] 2016-03-14 21:27
I'm seeing this issue with my students in Play training, using Play 2.5.0. 

Was this ever fixed? the bug shows as closed...

**Comment by pzajac** [comment] 2016-07-12 13:28
I'm also curius why this issue is fixed. I see this problem in test `WithBrowser` when I switch to Play 2.5.3 this week.

**Comment by NK91** [comment] 2016-08-12 08:30
I have the same problem if try to run tests suites with PlaySpecs but adding CustomCacheManagerProvider fixed it

**Comment by MipH** [comment] 2016-08-23 11:09
Got this error without any tests... Why the issue is closed?.. If CustomCacheManagerProvider  is a solution than it would be good to have this information in docs...

**Comment by vidma** [comment] 2017-10-14 09:25
yeah, smells non-sense madness...

**Comment by aturner-tvpage** [comment] 2019-02-26 22:22
Nope - still seeing this error in 2019.  :/.
