### ISSUE TITLE
Current Play ScalaDoc

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#4303] opened 2015-04-27 02:47 UTC
Scala uses current in the URL, like this:
http://www.scala-lang.org/api/current/

After a release, the ScalaDoc is hived. Here is ScalaDoc for Scala 2.10.3:
http://www.scala-lang.org/api/2.10.3/#package

It would be great if Play ScalaDoc could do the same.

**Comment by jroper** [comment] 2015-04-27 03:54
Do you need the docs served at the current URL, or is it ok if the current URL redirects to the latest version?

**Comment by jroper** [comment] 2015-04-27 03:59
On Play, we use the `/latest` to refer to the current stable version, and it's implemented using a redirect, so if you go to https://playframework.com/documentation/latest/ScalaActions, you're redirected to https://playframework.com/documentation/2.3.x/ScalaActions.  I've just [pushed a change](https://github.com/playframework/playframework.com/commit/44f12661becc8a9d39181593d47e824e3bf8e112) that includes the api docs in this redirect:

https://playframework.com/documentation/latest/api/scala/index.html#play.api.Play$

Is that ok?

**Comment by mslinn** [comment] 2015-04-27 04:42
I think the `current` docs for Scala actually go to a version built from HEAD.
`Latest` (stable) is also a good idea, but it serves a different purpose.
Both would be best.

**Comment by jroper** [comment] 2015-04-27 06:09
I'm not sure what the use case for linking to HEAD is - the use case for latest is so that elsewhere can link to our docs and users will get documentation for stable APIs, rather than HEAD which could change at a whim, and may contain features that don't exist in any stable release.  Linking to HEAD of a stable branch makes sense, we provide that through 2.3.x, 2.4.x etc, the links to these APIs not only are stable, they are guaranteed not to have breaking changes made to them.

If we did do this, I'd rather call the link "unstable", or "experimental", to emphasise the point that what you're linking to may be there one day, gone the next.

**Comment by mslinn** [comment] 2015-04-27 10:45
I suggest that the Play team follow the same conventions in this regard that are followed by the Akka and Scala teams. Why not talk to them about exactly what they are doing?

**Comment by jroper** [comment] 2015-04-27 12:54
Well, Akka publish it under snapshot, I think publishing it under snapshot is ok.  But seriously, I'd like to know the use case - without understanding why I'm doing something, how can I implement it right?  You also haven't answered whether you think a redirect is ok, or if you want it actually served under that path?  And why?

I have had plenty of discussions with both the Scala and Akka teams about documentation - don't assume we don't talk.  Neither the Scala or Akka documentation supports translations or switching from one version to another (and ending up on the right page).  The Akka docs are completely static - they updated the look and feel of their site, but their docs are stuck in the past forever.  Following Akka and Scala conventions for documentation would be a regression in my opinion.

**Comment by marcospereira** [comment] 2015-04-27 18:08
@jroper 

A redirect works, but I don't think it is ok mainly because of SEO problems. See this [moz article about redirection](http://moz.com/learn/seo/redirection):

> **Be aware that when moving a page from one URL to another, the search engines will take some time to discover the 301, recognize it, and credit the new page with the rankings and trust of its predecessor**. This process can be lengthier if search engine spiders rarely visit the given web page, or if the new URL doesn't properly resolve.
> 
> Other options for redirection, like 302s and meta refreshes, are poor substitutes, as they generally will not pass the rankings and search engine value like a 301 redirect will. The only time these redirects are good alternatives is if a webmaster purposefully doesn't want to pass link juice from the old page to the new.

This have impact on top search results linking to outdated documentation instead of the latest version. I'm not a SEO expert, but the number of users linking to old versions is a good indication of this problem.

**Comment by mslinn** [comment] 2015-04-27 23:26
Our use case is as follows:
 * [ScalaCourses.com](http://ScalaCourses.com) has been providing online training for Scala and related technology such as Play Framework 2 for two years. We deliver the training via the Cadenza webapp that we developed using Scala, Play, Akka, Slick, and Postgres. Cadenza provides an HTML transcript for every lecture along with a video, and the transcripts contain links to ScalaDoc. Students can print a PDF of the entire course at any time, and they get the current version of the content when they do so. Students can download personalized videos at any time, and they can also update the git repo with the sample code on demand. Course material is searchable and automatically cross-referenced.
 * Unlike traditional media, such as books, our online courses are constantly updated. Changes originate from issues raised by students and by instructors who upgrade the course in response to new versions of the technology that their courses are based upon.
 * We have learned that students want to learn the cutting edge, so we spend a lot of time updating material. Each time we do so we tweet about it, so students know of the new or updated material. Usually we generate several such tweets per week.
 * Revision histories for entire courses are publicly shown in the **Overview** tab. For example, you can read the revision histories for [Introduction to Scala](http://www.scalacourses.com/showCourse/40), [Intermediate Scala](http://www.scalacourses.com/showCourse/45) and [Introduction to Play -  Early Access](http://www.scalacourses.com/showCourse/39). Revision history is also provided for each lecture under the **About** tab.
 * Changes are first made to lecture transcripts, and then when the changes for a lecture has stabilized we update the video. [Our editorial review process](http://www.scalacourses.com/lectures/admin/showLecture/28/34) is described under the **ScalaCourses.com Course Development Workflow** heading. As you can see, we spend a lot of time reviewing material. If a link goes bad at any time, we catch it quickly.
 * Courses are organized into sections, then lectures. Usually, when a technology updates it either affects all lectures to a small degree, or it affects a small number of lectures to a larger degree. We track the technologies that we publish courses on very closely, and we usually know of upcoming changes well before students do.
 
All of the above means that we need a link to Play ScalaDoc that can be referenced early on in our editorial cycle, and continually points to the most current information. Again, if a link goes bad, we catch it quickly.

**Comment by jroper** [comment] 2015-04-28 02:12
Ok, so here's what I see that needs to be done at a minimum:

* There needs to be a way to link to the master development branch of the documentation for the purposes of cutting edge courses linking to the latest pre releases.  It doesn't matter whether this is a redirect or not.  My preference would be to call the path for this `snapshot`.  I think in this case a redirect is fine, the nice thing about redirects is that the URL makes it clear what version you're looking at.
* The `latest` path should be what everyone links to by default, and what is served by default, and it should not redirect, for SEO purposes.  This should be for stable docs, otherwise people are going to get confused - we've had a lot of issues raised in the past when we accidentally had latest redirecting to the master docs.

**Comment by jroper** [comment] 2015-05-14 05:23
The more I think about this, the more I think we shouldn't provide stable links to the current head version.  In Play 3 we're scheduled to do significant refactoring.  For 6 or more months, Play will be in a state of flux, with APIs changing a lot.  Now you may be constantly updating your docs and quick to respond, but if you're updating your course for our Play 3 APIs as they are developed, that would really be bad, because you would be teaching students Play APIs that won't be usable in any stable release for maybe a year, and may never even see the light of day.  The last thing I want is people reporting bugs saying "API X has disappeared with no migration guide", because that's what will happen if you link to our current head version and people start learning that.

**Comment by marcospereira** [comment] 2016-02-19 02:18
Play now have a `/latest/` that redirects to the last stable release:

https://www.playframework.com/documentation/2.4.x/Home

**Closed by marcospereira** 2016-02-19 02:18 UTC

**Comment by mslinn** [comment] 2016-02-19 02:45
I wish the URL did not rewrite from

https://www.playframework.com/documentation/latest

to 

https://www.playframework.com/documentation/2.4.2

The other Scala-related sites do not do this
