### ISSUE TITLE
WS play.ws.ssl.loose.disableHostnameVerification=true doesn't work?

### ISSUE THREAD

**Issue by jxtps** [playframework/playframework#4796] opened 2015-06-30 20:27 UTC
I have set `play.ws.ssl.loose.disableHostnameVerification=true` and then call a web service on localhost that is known to return a certificate for not-localhost (See [this async-http-client issue](https://github.com/AsyncHttpClient/async-http-client/issues/927) for the details), but the call still fails as per the log extract below. 

Windows 8, Play 2.4.1, Scala 2.11.7, Java 8.0_45. 

```
C:\work\play_web>activator run
[info] Loading project definition from C:\work\play_web\project
[info] Set current project to play_web (in build file:/C:/work/play_web/)
Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which in some
cases may be orders of magnitude slower than using node.js.

--- (Running the application, auto-reloading is enabled) ---

[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 1 Scala source to C:\work\play_web\target\scala-2.11\classes...
WARN application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
INFO application - Creating Pool for datasource 'default'
INFO p.a.d.DefaultDBApi - Database [default] connected at jdbc:mysql://localhost/play_dev?useUnicode=yes&characterEncoding=UTF-8&connectionCollation=utf8_general_ci
INFO p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
INFO play.api.Play - Application started (Dev)
WARN p.a.l.w.n.NingAsyncHttpClientConfigBuilder - buildHostnameVerifier: disabling hostname verification
ERROR application - elb failed to fetch example.com https://localhost/monit
java.net.ConnectException: General SSLEngine problem
        at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37) ~[async-http-client-1.9.21.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:101) ~[async-http-client-1.9.21.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) ~[netty-3.10.3.Final.jar:na]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_45]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_45]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_45]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[na:1.8.0_45]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_45]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478) ~[na:1.8.0_45]
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.
        at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:204) ~[na:1.8.0_45]
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:95) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[na:1.8.0_45]		
```

**Comment by jxtps** [comment] 2015-06-30 20:45
Similarly if I use `play.ws.ssl.hostnameVerifierClass=myutil.play.DisabledHostnameVerifier` - the class is instantiated, but never called. 

```scala
class DisabledHostnameVerifier extends HostnameVerifier {

  Logger.info("Instantiating DisabledHostnameVerifier")

  override def verify(hostname: String, sslSession: SSLSession): Boolean = {
    Logger.info(s"Verifying $hostname as true!")
    true
  }
}
```

```
...
INFO play.api.Play - Application started (Dev)
INFO application - Instantiating DisabledHostnameVerifier
ERROR application - elb failed to fetch example.com https://localhost/monit
java.net.ConnectException: General SSLEngine problem
        at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37) ~[async-http-client-1.9.21.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:101) ~[async-http-client-1.9.21.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) ~[netty-3.10.3.Final.jar:na]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_45]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_45]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_45]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[na:1.8.0_45]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_45]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478) ~[na:1.8.0_45]
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.
        at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:204) ~[na:1.8.0_45]
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:95) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[na:1.8.0_45]
```

**Comment by jxtps** [comment] 2015-07-02 22:43
Turns out the AsyncHttpClientConfig.Builder.setHostnameVerifier() method has been removed from async-http-client in master, presumably because it didn't actually work. 

I guess that means this particular configuration option will eventually be removed from Play?

**Comment by wsargent** [comment] 2015-07-06 20:57
@jxtps async-http-client master is way ahead of Play 2.4.x

**Comment by wsargent** [comment] 2015-07-06 21:19
Wasn't this taken care of with https://github.com/AsyncHttpClient/async-http-client/issues/197 ?

**Comment by wsargent** [comment] 2015-07-06 21:26
@jxtps Can you put together a reproducible test case project?  I'd like to poke at things, but I don't know why you're looking at AHC master.

Also, it DID work at one point -- see https://tersesystems.com/2014/03/31/testing-hostname-verification/ for details.

**Comment by jxtps** [comment] 2015-07-06 21:40
I'm not using ACH master, I just looked there when @slandelle said he didn't know of a way to plug in a custom HostnameVerifier. Since it was gone there, I assumed it to be deprecated functionality. I'm using vanilla Play 2.4.1 (so whatever it pulls in when adding a dependency on ws). 

My code is super-simple, it just does a regular WS get, but with hostname verification disabled (`play.ws.ssl.loose.disableHostnameVerification=true `). 

Set that in your application.conf, and then do e.g. 
```scala
import scala.concurrent.ExecutionContext.Implicits.global
WS.url("https://74.125.239.48").
  withVirtualHost("www.google.com").
  get().map(response => Logger.info("Hello Google! " + response.status + ", " + response.body.take(1024))).
  recover {
  case ex: Exception => Logger.info("Failed!", ex)
}
```
(code excerpt from my comment on https://github.com/AsyncHttpClient/async-http-client/issues/927 )

In the event google changes their servers, `nslookup www.google.com`

**Comment by wsargent** [comment] 2015-07-06 22:17
Right... so.  AHC 1.8.15, if you look at NettyConnectListener, the operationComplete() method has a call out to the hostname verifier.

http://grepcode.com/file/repo1.maven.org/maven2/com.ning/async-http-client/1.8.15/com/ning/http/client/providers/netty/NettyConnectListener.java#75

In AHC 1.9.x, it does not.  http://grepcode.com/file/repo1.maven.org/maven2/com.ning/async-http-client/1.9.15/com/ning/http/client/providers/netty/request/NettyConnectListener.java#NettyConnectListener.operationComplete%28org.jboss.netty.channel.ChannelFuture%29

**Comment by slandelle** [comment] 2015-07-06 22:24
@wsargent Passing a HostnameVerifier is still in the 1.9.x API because of the JDK provider (that goes away in AHC2).

**Comment by wsargent** [comment] 2015-07-06 23:34
okay, well... either setEndpointIdentificationAlgorithm is set or it's not, but it doesn't look like there's a custom option now.

**Comment by wsargent** [comment] 2015-07-07 00:08
You can see it's still calling the HostnameChecker under X509ExtendedTrustManager, but there's not an easy way to get at it.  

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/security/ssl/X509TrustManagerImpl.java#455

Looks like hacking directly into the trust manager is the only way.

**Comment by wsargent** [comment] 2015-07-07 00:08
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/security/util/HostnameChecker.java#50

**Comment by wsargent** [comment] 2015-09-30 22:18
Looks good.  This should fix https://github.com/playframework/playframework/issues/4796.  I take it AHC 2.0 does not have hostnameVerifier any more...

**Comment by wsargent** [comment] 2015-09-30 22:20
2.5 will re-enable this setting with https://github.com/playframework/playframework/commit/f35dd0946fb84c8eee623b0e3d3cdee3226118a6

**Comment by pmonestie** [comment] 2015-10-12 10:14
So in play 2.4 there is no way to have this working? Anyone found a workaround for play 2.4?

**Comment by filippomortari** [comment] 2015-10-12 10:45
I am experiencing this issue as well, Play 2.4.3.

**Comment by slandelle** [comment] 2015-10-12 11:12
You can configure the underlying AsyncHttpClient instance with System props: https://github.com/AsyncHttpClient/async-http-client/blob/1.9.x/src/main/java/com/ning/http/client/AsyncHttpClientConfigDefaults.java#L109

**Comment by pmonestie** [comment] 2015-10-12 12:15
Adding -Dcom.ning.http.client.AsyncHttpClientConfig.acceptAnyCertificate=true actually did not work for me - Though doing:
      val config=new AsyncHttpClientConfigBean()
      config.setAcceptAnyCertificate(true)
      val client=new NingWSClient(config)
works - Come to think of it this is a 'better/safer' way of doing this...

**Comment by slandelle** [comment] 2015-10-12 12:21
> Adding -Dcom.ning.http.client.AsyncHttpClientConfig.acceptAnyCertificate=true did not work for me

My2cents: you passed the system prop to the sbt JVM instead of the application one

**Comment by pmonestie** [comment] 2015-10-12 14:02
I even debugged it - the option is set... Maybe play is explicitely setting that config. Regardless I actually prefer to create a client 'by hand'

**Comment by schmitch** [comment] 2015-10-25 12:42
I actuall tried to use ```new NingAsyncHttpClientConfigBuilder()``` and set the configureSSL loose options, however that doesn't work, while ```AsyncHttpClientConfigBean()``` works, so I think the problem lies inside the config builder.

**Comment by schmitch** [comment] 2015-10-26 17:35
Still broken in 2.5-M1

**Comment by museOnSite** [comment] 2016-02-25 10:18
I experience the same problem in 2.4.6 and 2.5.0-RC1 for `play.ws.ssl.loose.acceptAnyCertificate` config.
I got the following error:
> General SSLEngine problem
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I tried this workaround in 2.4.6 without success: 
```scala
val sslLooseConfig = new SSLLooseConfig(acceptAnyCertificate = true)
val sslConfig = new SSLConfig(loose = sslLooseConfig)
val config = new WSClientConfig(ssl = sslConfig)
val builder = new NingAsyncHttpClientConfigBuilder(config)
val ws = new play.api.libs.ws.ning.NingWSClient(builder.build())
```

**Comment by slandelle** [comment] 2016-02-25 10:25
@museOnSite If you can provide a pure AsyncHttpClient based reproducer, please open an issue on [our bug tracker](https://github.com/AsyncHttpClient/async-http-client/issues) and I'll take a look.

**Comment by museOnSite** [comment] 2016-02-25 10:49
@slandelle I opened a bug: https://github.com/AsyncHttpClient/async-http-client/issues/1099

**Comment by slandelle** [comment] 2016-02-25 10:51
@museOnSite Yeah, you provided nothing I asked for...

**Comment by schmitch** [comment] 2016-02-25 10:53
@slandelle actually I didn't have time to try out more, but I think the error lies in the Builder of Play! not in Asynchttpclient, I will further look into it once I fixed #902

**Comment by slandelle** [comment] 2016-02-25 11:08
@schmitch Cool! FYI, I'd like to find a more suitable name for this option. What it does has changed a lot since when it was introduced. What it does now is:
* set a loose TrustManager on the `SSLContext`
* don't set `endpointIdentificationAlgorithm` on the `SSLEngine` params

Enabling it sure disables host name verification, but also disable other things such as SNI. I've seen people going yolo (mostly on Gatling, where security is not a concern), using it in production and having AHC failing to handshake.

cc @wsargent

**Comment by museOnSite** [comment] 2016-02-25 12:20
@slandelle I made the `acceptAnyCertificate` option work with pure _AsyncHttpClient_. Sorry for the issue I opened, I misanderstood you. Here is the code working:
```scala
    val config = new DefaultAsyncHttpClientConfig.Builder().setAcceptAnyCertificate(true).build
    val httpClient = new DefaultAsyncHttpClient(config)
    val resp = httpClient.prepareGet("https://targetUrl").execute()
```

**Comment by rajendrag** [comment] 2016-03-28 20:24
Using DefaultAsyncHttpClient as @museOnSite  suggested fixed my problem, I am planning to upgrade to 2.5, just wanted to confirm if this is fixed in 2.5?

**Comment by Kml55** [comment] 2016-04-05 18:46
Any solution ?

**Comment by sheaney** [comment] 2016-04-05 23:26
Also tried 2.5 and not working.

**Comment by schmitch** [comment] 2016-04-06 08:40
Did you guys checked that: https://www.playframework.com/documentation/2.5.x/LooseSSL#Disabling-Hostname-Verification ? you only need `acceptAnyCertificate` now.

**Comment by Kml55** [comment] 2016-04-06 09:01
I tried. Not working. I use java. @schmitch

**Comment by schmitch** [comment] 2016-04-06 13:46
Actually I tried to reproduce this but `acceptAnyCertificate` to disable `disableHostnameVerification` works. Do you guys use weak ciphers or something like that? I.e. certificates with a Signature of MD5 with Rsa or Rsa1 Signatures?

**Comment by sheaney** [comment] 2016-04-06 17:18
Viewing the certificate from the service I'm trying to access from a Chrome browser I get:
```
Your connection to zzz.zz.zz is encrypted using an obsolete cipher suite.

The connection uses TLS 1.0.

The connection is encrypted using 3DES_EDE_CBC, with HMAC-SHA1 for message authentication and RSA as the key exchange mechanism.
```

I have the following options in my config:

```scala
play.ws.ssl.loose.allowWeakCiphers=true
play.ws.ssl.loose.acceptAnyCertificate=true
```

**Comment by wsargent** [comment] 2016-04-06 18:23
You need to enable weak ciphers, although Java itself is getting to the point where it may not let these ciphers be enabled.

```
play.ws.ssl.loose.allowWeakCiphers=true
```

https://www.playframework.com/documentation/2.5.x/LooseSSL#Disabling-Weak-Ciphers-Checking

**Comment by sheaney** [comment] 2016-04-13 22:38
@wsargent I don't think that's the problem, I was able to replicate the same error using a self signed certificate:

Viewing the generated self signed certificate from a Chrome browser:

```
Your connection to yyy.yyy.yyy is encrypted using a modern cipher suite.

The connection uses TLS 1.2.

The connection is encrypted and authenticated using AES_128_GCM and uses ECDHE_RSA as the key exchange mechanism.
```

And setting the following options in my config:

```scala
play.ws.ssl.loose.acceptAnyCertificate = true
play.ws.ssl.debug.ssl = true
```

Among the logs that are output I can see:

```
AsyncHttpClient-6-1, fatal error: 46: General SSLEngine problem
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

It seems that it's still trying to verify the certificate

**Comment by marcvk** [comment] 2016-05-18 19:53
I'm getting the same error with Play 2.5.3, trying to connect to a Visual Studio 2013 development site running with a self signed certificate, it seems the problem still hasn't been solved. This was/is working fine with Play 2.3.9.

These are the settings I'm using:

play.ws.ssl.loose.acceptAnyCertificate = true
play.ws.ssl.loose.allowWeakCiphers = true
play.ws.ssl.loose.allowWeakProtocols = true
play.ws.ssl.enabledCipherSuites = [
  "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
  "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
  "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
  "TLS_DHE_DSS_WITH_AES_128_CBC_SHA",
  "TLS_RSA_WITH_AES_256_CBC_SHA",
  "TLS_RSA_WITH_AES_128_CBC_SHA",
  "SSL_RSA_WITH_RC4_128_SHA",
  "SSL_RSA_WITH_RC4_128_MD5",
  "TLS_EMPTY_RENEGOTIATION_INFO_SCSV"
]
play.ws.ssl.enabledProtocols = [
  "TLSv1.2",
  "TLSv1.1",
  "TLSv1"
]
play.ws.ssl.debug = {
 ssl = true
 handshake = true
 verbose = true
 data = true
}

While I can appreciate the intention to convince people to use proper ssl encryption I think there should really be an option where you can you can just say, I know what I'm doing, I just don't want to set up the whole key chain stuff just for development and I'll promise I'll use a proper certificate in production.

**Comment by schmitch** [comment] 2016-05-18 20:46
Actually there is a funny thing that even Play's own certificates won't work. so -Dhttps.port=9443 and then point a ws.url to the same instance on another url won't actually work.
However I have a fix.

**Comment by marcvk** [comment] 2016-05-18 21:04
@schmitch cool! This actually works, or better said, it enabled me to get my custom made wsclient to work. For those that don't want to wait for this patch or don't want to recompile play themselves:

```scala
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()

  val config = new AhcWSClientConfig()
  val builder = new AhcConfigBuilder(config)
  val ahcBuilder = builder.configure()
  ahcBuilder.setAcceptAnyCertificate(true)
  ahcBuilder.setSslEngineFactory(null)
  ahcBuilder.setSslContext(SslContextBuilder.forClient()
    .trustManager(InsecureTrustManagerFactory.INSTANCE).build)

  val ws = new AhcWSClient(ahcBuilder.build())

**Closed** 2016-05-19 20:34 UTC

**Comment by matanster** [comment] 2016-05-27 20:26
@gsmaverick many thanks for posting the workaround till a release is made. If it saves one minute to anyone here are the necessary imports for that piece of code just provided by you, I believe: 

```
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import play.api.libs.ws.ahc.AhcWSClientConfig
import play.api.libs.ws.ahc.AhcConfigBuilder
import play.api.libs.ws.ahc.AhcWSClient
import io.netty.handler.ssl.SslContextBuilder
import io.netty.handler.ssl.util.InsecureTrustManagerFactory
```

**Comment by techmag** [comment] 2016-06-05 20:06
Unsure if this will add or subtract from this conversation. 

I have a production environment where I have no choice but to poll other systems that I have ZERO control over their configuration. It is a company that releases their web portal product with self-signed certificates and the IT departments somehow think that is good enough. 

In any case I've just lost a week in debugging hell because it seems that: 

`play.ws.ssl.loose.acceptAnyCertificate=true
`

is **SILENTLY** turned off when moving from dev to testProd (and presumably Prod) 

I do have the following 

```
play.ws.ssl {
  trustManager = {
    stores = [
      { type = "PEM", path = "/Users/me/Documents/github/play/myProject/modules/myModule/conf/defeatthecert.crt" }
    ]
  }
}
```

Unsure if that survives or not. With an absolute path it should work however as the play.ws.ssl.loose.acceptAnyCertificate it is currently a mute point. 

My point for the purpose pf this conversation is that play.ws.ssl.loose.acceptAnyCertificate=true should either NOT fail silently OR it should simply not fail at all. 

Pick one please :)

_It didn't help that the failure was inside an Actor and hence stack traces were invisible. I thought I was tracking down a thread pool issue long before I thought I was dealing with a configuration file that simply refused my clearly stated wishes._ My bad and many painful lessons learnt...

$0.02 for your consideration while your knee deep in the blood and guts of this issue.

**Comment by schmitch** [comment] 2016-06-05 20:14
@techmag in 2.5.4 it will print a warning and it will actually work. But actually it should work in prod and in dev. even before I actually know the code pretty well and it won't change anything when Environment is Prod.

**Comment by techmag** [comment] 2016-06-05 22:14
@schmitch Does that also apply to 2.5.x ? My limited empirical evidence seems to suggest not...

**Comment by schmitch** [comment] 2016-06-05 22:20
2.5.4 will be the next release **with** the warning **and** the fix of the new play-ws. But actually if it worked in Play 2.4 for you in dev mode it **should** work in prod mode, since there is no check or difference how config applies.
The problem with > 2.3 was just that they changed to netty 4 and used JSSE and a more secure configuration which made it impossible for every certificate to work. However the next release will make acceptAnyCertificate way more loose thats why we also added a warning since running play-ws against acceptAnyCertificate is considered bad since it's the same as running over http.

**Comment by techmag** [comment] 2016-06-05 22:21
Well aware of the risks and I scream as loud as I can whenever asked to do this :)

**Comment by schmitch** [comment] 2016-06-05 22:24
as a general idea what we do (at envisia) we have a insecure provider aswell, but we don't run the whole ws insecure against it, we have created a Named binding just for that which uses the configs like that:
```
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()

  val config = new AhcWSClientConfig()
  val builder = new AhcConfigBuilder(config)
  val ahcBuilder = builder.configure()
  ahcBuilder.setAcceptAnyCertificate(true)
  ahcBuilder.setSslEngineFactory(null)
  ahcBuilder.setSslContext(SslContextBuilder.forClient()
    .trustManager(InsecureTrustManagerFactory.INSTANCE).build)

  val ws = new AhcWSClient(ahcBuilder.build())
```

Maybe I will also create some documentation for it.

**Comment by JohnnyHuo** [comment] 2018-03-30 00:19
Hi, any idea where is the class `AhcWSClient`?  Suppose to be `play.api.libs.ws.ahc.AhcWsClient` but it's not there... Using the library here https://mvnrepository.com/artifact/com.typesafe.play/play-ahc-ws-standalone_2.12

**Comment by JohnnyHuo** [comment] 2018-03-30 00:25
It take me a while to figure out how to make it work as there's no AhcWSClient

here's a working code for StandaloneAhcWSClient

```
    val wsConfig = new AhcWSClientConfig()
    val builder = new AhcConfigBuilder(wsConfig)
    val ahcBuilder = builder.configure()
    ahcBuilder.setAcceptAnyCertificate(true)
    ahcBuilder.setSslEngineFactory(null)
    ahcBuilder.setSslContext(SslContextBuilder.forClient()
      .trustManager(InsecureTrustManagerFactory.INSTANCE).build)
    val ahcConfig = ahcBuilder.build()
    val asyncHttpClient = new DefaultAsyncHttpClient(ahcConfig)

    new StandaloneAhcWSClient(asyncHttpClient)

```

**Comment by wsargent** [comment] 2018-03-30 01:00
@JohnnyHuo the instructions for a standalone client are on https://github.com/playframework/play-ws#instantiating-a-standalone-client

There is a section in the Scala WS manual that points you to it: https://www.playframework.com/documentation/2.6.x/ScalaWS#Standalone-WS

**Comment by juanmirocks** [comment] 2020-07-29 13:56
For completeness, for the solution in https://github.com/playframework/playframework/issues/4796#issuecomment-223841556, we need these imports:

```scala
import play.api.libs.ws.ahc._
import org.asynchttpclient.DefaultAsyncHttpClientConfig
import io.netty.handler.ssl.SslContextBuilder
import io.netty.handler.ssl.util.InsecureTrustManagerFactory
```
