### ISSUE TITLE
Returning from triggered execution does not work

### ISSUE THREAD

**Issue by malliina** [playframework/playframework#9365] opened 2019-05-31 20:41 UTC
### Play Version

2.7.2

### API

Scala

### Operating System

MacOS Mojave 10.14.5

### JDK

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

### Expected Behavior

1. git clone git@github.com:playframework/play-samples.git
2. cd play-samples/play-scala-hello-world-tutorial/
3. sbt
4. ~ run
5. After the app has started, the developer should get back to the sbt console by pressing Enter

### Actual Behavior

Nothing happens when pressing Enter or Ctrl-D. 

The only way I know of that exits is Ctrl-C, but this also kills the process, which is undesirable. Returning to the console does work if triggered execution is not used, i.e. when only `sbt run` is used.

Returning from triggered execution works in Play 2.6.17 but not in 2.6.18 onwards. From sbt I think the relevant code is here https://github.com/sbt/sbt/blob/v1.2.0/main-command/src/main/scala/sbt/Watched.scala#L106-L147 but I'm not competent enough to craft a fix myself. 

I don't have issues with triggered execution in non-Play projects, so I figure this is more a Play issue than an sbt one.

**Comment by marcospereira** [comment] 2019-06-03 03:56
Thanks for reporting, @malliina. I can confirm this is happening. I didn't have time to investigate further, but it can be related to https://github.com/playframework/playframework/pull/8565.

**Comment by malliina** [comment] 2019-06-04 21:19
Ok no problem, it's useful to know it is not only specific to my computer.

**Comment by mkurz** [comment] 2024-03-14 09:47
IMHO we can treat this as duplicate of
- #9983

because `~run` is totally broken currently.

**Closed by mkurz** 2024-03-14 09:47 UTC
Labels: type:defect, topic:sbt
