### ISSUE TITLE
Failed: 2.8.x, sbt.inc.Doc$JavadocGenerationFailed

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#10336] opened 2020-06-15 08:20 UTC
(this is a 2.8.x equivalent to https://github.com/playframework/playframework/issues/10328)

The nightly build task nightly-deploy-2.8.x failed.

The full logs for this task have been saved and can be found in /home/play/logs/nightly-deploy-2.8.x-1592019343.log.

```

[info] Play 2.8.2+11-b538b07b-SNAPSHOT Scala API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+11-b538b07b-SNAPSHOT/play-docs_2.12-2.8.2+11-b538b07b-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+11-b538b07b-SNAPSHOT/play-docs_2.12-2.8.2+11-b538b07b-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+11-b538b07b-SNAPSHOT/play-docs_2.12-2.8.2+11-b538b07b-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+11-b538b07b-SNAPSHOT/play-docs_2.12-2.8.2+11-b538b07b-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 167 s (02:47), completed Jun 13, 2020 3:40:30 AM
```

**Comment by jrudolph** [comment] 2020-06-23 09:43
Once again tonight:

```
[info] Play 2.8.2+13-d0b0ba19-SNAPSHOT Scala API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+13-d0b0ba19-SNAPSHOT/play-docs_2.12-2.8.2+13-d0b0ba19-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+13-d0b0ba19-SNAPSHOT/play-docs_2.12-2.8.2+13-d0b0ba19-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+13-d0b0ba19-SNAPSHOT/play-docs_2.12-2.8.2+13-d0b0ba19-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+13-d0b0ba19-SNAPSHOT/play-docs_2.12-2.8.2+13-d0b0ba19-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 165 s (02:45), completed Jun 23, 2020 3:42:07 AM
```

**Comment by jrudolph** [comment] 2020-06-25 12:30
Still failing:

```
[info] Play 2.8.2+13-d0b0ba19-SNAPSHOT Scala API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+13-d0b0ba19-SNAPSHOT/play-docs_2.12-2.8.2+13-d0b0ba19-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+13-d0b0ba19-SNAPSHOT/play-docs_2.12-2.8.2+13-d0b0ba19-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+13-d0b0ba19-SNAPSHOT/play-docs_2.12-2.8.2+13-d0b0ba19-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+13-d0b0ba19-SNAPSHOT/play-docs_2.12-2.8.2+13-d0b0ba19-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
```

**Comment by ennru** [comment] 2020-08-03 06:10
/home/play/logs/nightly-deploy-2.8.x-1596425854.log

```
[warn] 47 warnings found
[info] Play 2.8.2+23-cf4e0cb8-SNAPSHOT Scala API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+23-cf4e0cb8-SNAPSHOT/play-docs_2.12-2.8.2+23-cf4e0cb8-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+23-cf4e0cb8-SNAPSHOT/play-docs_2.12-2.8.2+23-cf4e0cb8-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+23-cf4e0cb8-SNAPSHOT/play-docs_2.12-2.8.2+23-cf4e0cb8-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+23-cf4e0cb8-SNAPSHOT/play-docs_2.12-2.8.2+23-cf4e0cb8-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
```

**Comment by raboof** [comment] 2020-09-02 06:44
duplicate of #10111

**Closed by raboof** 2020-09-02 06:44 UTC
Labels: failed
