### ISSUE TITLE
Request session data in private tab

### ISSUE THREAD

**Issue by cunhazera** [playframework/playframework#11208] opened 2022-03-23 16:47 UTC
### Play Version

2.7.5

### API

Java

### Operating System

Mac OSX

### JDK

1.8

### Expected Behavior

1. Login with an user on Chrome
2. Go to a private tab using Firefox
3. Request session is empty

### Actual Behavior

1. Login with an user on Chrome
2. Go to a private tab using Firefox
3. Request session contains the Chrome user data

### Reproducible Test Case

1. Login with user1 on Chrome
2. Go to a private tab using Firefox
3. Login with user2
4. Take a look at `request.session`, your request body will show `user2`, but the request session contains `user1`

### Session configuration

```
  session {
    secure = false
    httpOnly = true
    domain = "localhost"
    sameSite = "lax"
  }
```

**Comment by mkurz** [comment] 2022-03-28 21:18
@cunhazera Login where? It seems that is a problem specific to your source code. Is it possible to providate a small project which reproduces the problem? Thanks!

**Comment by cunhazera** [comment] 2022-03-28 22:04
@mkurz I think it's a problem with the `Http.Request` class. I realized that this problem doesn't happen with the `Context` class

**Comment by mkurz** [comment] 2022-03-28 22:05
@cunhazera I would need more details so I can reproduce the problem. If you have source code or a small project that would be nice.

**Comment by mkurz** [comment] 2024-03-15 21:44
@cunhazera I am closing this issue because you did not provide more information. If you do have more details to share please comment below and we may re-open the issue then.
Right now I am pretty sure this is a problem in your code, because if what you desribe would happen in other Play applications, we would have 100+ more bug reports already...

**Closed by mkurz** 2024-03-15 21:44 UTC
Labels: status:needs-info
