### ISSUE TITLE
[2.4.1] Bug: Some webjars not working anymore

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#4736] opened 2015-06-22 12:08 UTC
Using `activator-1.3.5-minimal` on Ubuntu 12.04 LTS.

Create a new java project with Play 2.4.0:
```
activator new webjars-bug play-java
```
Add 
```
"org.webjars" % "select2" % "3.5.2-1"
```
to the `build.sbt`.

Run the project and goto http://127.0.0.1:9000/assets/lib/select2/select2.js - the file is found, everything works :+1: 

Change to Play 2.4.1 in `project/plugins.sbt`, re-run the project - the file is **not** found anymore. Bug. :-1: 
[Here](https://github.com/mkurz/webjars-bug/commit/650fe7bc4b56659b7aa7381cbbe926642633a4c5) is a sample project.

Probably related to [this commit](https://github.com/playframework/playframework/commit/4906b4cdbc110f028b4b7fc32df8e7ece752cf12)?

**Comment by mkurz** [comment] 2015-06-22 12:16
BTW: Not all webjars are affected.
E.g.
```
  "org.webjars" % "jquery" % "2.1.4"
```
can be accessed via http://127.0.0.1:9000/assets/lib/jquery/jquery.js.

**Comment by mkurz** [comment] 2015-06-22 12:17
Also it seems like the `select2` webjar does not even get extracted in the `target` folder.

**Comment by jroper** [comment] 2015-06-23 00:43
The select2 webjar is working fine for me.  What OS are you using?  Could you try doing a clean first?

**Comment by jroper** [comment] 2015-06-23 00:51
Ok, I didn't actually test with Play 2.4.1, I just tested with the new webjars extractor (0.25) which I assumed is what was causing the problem, but that works fine with Play 2.4.0, but 2.4.1 the problem is there.

**Comment by jroper** [comment] 2015-06-23 00:54
Right, the bug seems to be introduced by sbt-web 1.2.1.

**Comment by jroper** [comment] 2015-06-23 01:16
Fix is here: https://github.com/webjars/webjars-locator-core/pull/6

**Comment by jroper** [comment] 2015-06-23 03:33
The work around for this is to add the following the `project/plugins.sbt`:

```scala
libraryDependencies += "org.webjars" % "webjars-locator-core" % "0.26"
```

**Comment by mkurz** [comment] 2015-06-23 06:31
Thanks James, I can confirm using version `0.26` of `webjars-locator-core` fixes the issue.

**Comment by benmccann** [comment] 2015-06-30 16:02
Fixed now. Thanks @jroper

**Closed by benmccann** 2015-06-30 16:02 UTC
Labels: has-pr

**Comment by nishanpatel** [comment] 2015-07-02 19:08
Hi,

I have just created simple play application using activator and when I was trying to run it I was getting below error,

java.lang.UnsupportedClassVersionError: org/webjars/WebJarExtractor$Cache : Unsupported major.minor version 51.0

**Comment by benmccann** [comment] 2015-07-02 19:13
@nishanpatel yours seems like a completely different issue. it would be much easier to answer on the mailing list instead of on a bug for a different issue. you problem is that you're running a version of java older than java 7
