### ISSUE TITLE
-Dpidfile.path=NUL no longer works on Windows

### ISSUE THREAD

**Issue by dwickern** [playframework/playframework#7646] opened 2017-07-18 21:47 UTC
This was broken in #7244
```scala
scala> val pid = new java.io.File("NUL")
pid: java.io.File = NUL

scala> new java.io.FileOutputStream(pid).write(42)

scala> java.nio.file.Files.newOutputStream(pid.toPath).write(42)
java.nio.file.FileSystemException: NUL: Incorrect function.

  at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
  at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
  at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
  at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
  at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
  at java.nio.file.Files.newOutputStream(Unknown Source)
  ... 42 elided
```

Workaround is to use `-Dpidfile.path="/dev/null"` even on Windows because [Play has a special case for it](https://github.com/playframework/playframework/blob/ca7cb3b267faad727c62afdbd558c6b44eece47a/framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala#L123)

**Comment by richdougherty** [comment] 2017-07-19 20:55
Hi @dwickern, thanks for the report. Would you mind checking if there are any `OpenOption`s that we can pass to `newOutputStream` that might solve the problem. E.g. perhaps `Files.newOutputStream(pid.toPath, APPEND)` would work for the special `NUL` file, rather than the default of `CREATE, TRUNCATE_EXISTING, WRITE`.

**Comment by dwickern** [comment] 2017-07-19 21:13
Indeed, it works using `APPEND`. It also works with `CREATE+WRITE` but fails if `TRUNCATE_EXISTING` is included.

**Comment by richdougherty** [comment] 2017-07-19 21:41
Thanks for checking. I'll change it to use `APPEND`. Below is the code that I'll change the PID writing code to. I'm pretty sure the `out.write(bytes)` and `out.close` calls will work OK with APPEND but perhaps you could check that too, just in case?

```scala
val pid = "test-pid"
val out = java.nio.file.Files.newOutputStream(pidFile.toPath, APPEND)
try out.write(pid.getBytes) finally out.close()
```

**Comment by dwickern** [comment] 2017-07-19 21:53
LGTM adding the `APPEND` argument. The code already checked that the file doesn't exist so the TRUNCATE was unnecessary in this case

**Comment by schmitch** [comment] 2017-07-24 14:57
well I stumbled upon that a few days ago as well and posted it in gitter:
https://gitter.im/playframework/contributors?at=596c813a3230e14f3a67c56d

actually I didn't had time for creating documentation for it, but I think it's enough to just include a warning that `-Dpidfile.path="/dev/null"` works for all supported systems including windows.

**Comment by richdougherty** [comment] 2017-07-24 21:55
Good tip! I've got a Windows VM downloaded now so I can test this out. I'm not sure about using `APPEND` since that means there's a race condition creating the file. I like the look of `CREATE_NEW` since that is apparently atomic. [(See here.)](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#newByteChannel-java.nio.file.Path-java.util.Set-java.nio.file.attribute.FileAttribute...-)

**Comment by dwickern** [comment] 2017-07-24 22:13
The current code also has a race condition... often the case when you see `file.exists()`. You can use `CREATE_NEW` and catch `FileAlreadyExistsException` to determine if the pidfile exists. That should also work for NUL on Windows.

`-Dpidfile.path=NUL` wasn't documented but there's at least some information out there:
https://stackoverflow.com/questions/15088751/play-2-0-starting-as-windows-service-after-server-restart/17391176#17391176
https://groups.google.com/forum/#!topic/play-framework/4amD9o37Ki4

**Comment by richdougherty** [comment] 2017-07-25 22:57
Thanks for checking that `CREATE_NEW` works works for `NUL` on Windows.

> The current code also has a race condition...

I guess that's because the current code is using `CREATE` instead of `CREATE_NEW`. I think this bit of code needs a unit test at least to ensure we're getting the expected behaviour!

**Comment by schmitch** [comment] 2017-07-27 08:02
@dwickern well I just think that it's better to use `-Dpidfile.path=/dev/null` on both systems, because you don't need seperate vm configurations then ;)
I think why it worked is, because the old way would go trough a windows api where NUL meant something like `/dev/null`.

**Comment by richdougherty** [comment] 2017-07-27 20:38
There is a fix for this now: #7673.

**Closed** 2017-07-28 01:00 UTC
Labels: defect, has-pr, needs-backport

**Comment by richdougherty** [comment] 2017-08-12 06:40
Hi @dwickern, Play 2.6.3 has just been released and it should fix this issue. If you get a chance, it would be great if you could check it and confirm that it's working for you now.

Thanks for reporting the issue and helping to work out a solution!

**Comment by dwickern** [comment] 2017-10-04 18:43
Thanks, can confirm this is working now

**Comment by richdougherty** [comment] 2017-10-05 22:54
Great! Thanks for checking. :)
