### ISSUE TITLE
[Play 2.5] channel not registered to an event loop

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#5430] opened 2015-12-31 01:25 UTC
I decided to try Play Framework 2.5.0-M1 with my existing application and I get theese exceptions with every request:
```
02:22:03.069 [application-akka.actor.default-dispatcher-26] ERROR play.core.server.NettyServer - Exception caught in Netty
java.lang.NullPointerException: null
        at io.netty.channel.nio.AbstractNioChannel.doBeginRead(AbstractNioChannel.java:366) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:679) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1117) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:604) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:585) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:604) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:585) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:95) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:604) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:585) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at com.typesafe.netty.HandlerPublisher.requestDemand(HandlerPublisher.java:86) ~[netty-reactive-streams-1.0.0.jar:na]
        at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:263) ~[netty-reactive-streams-1.0.0.jar:na]
        at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41) ~[netty-reactive-streams-1.0.0.jar:na]
        at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:441) ~[netty-reactive-streams-1.0.0.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) ~[netty-common-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.31.Final.jar:4.0.31.Final]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_65]
02:22:03.570 [netty-event-loop-1] WARN  i.n.u.c.SingleThreadEventExecutor - A task raised an exception.
java.lang.IllegalStateException: channel not registered to an event loop
        at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:111) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.nio.AbstractNioChannel.eventLoop(AbstractNioChannel.java:117) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.nio.AbstractNioChannel.eventLoop(AbstractNioChannel.java:49) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:103) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:583) ~[netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at com.typesafe.netty.HandlerPublisher.requestDemand(HandlerPublisher.java:86) ~[netty-reactive-streams-1.0.0.jar:na]
        at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:263) ~[netty-reactive-streams-1.0.0.jar:na]
        at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41) ~[netty-reactive-streams-1.0.0.jar:na]
        at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:441) ~[netty-reactive-streams-1.0.0.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) ~[netty-common-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-transport-4.0.31.Final.jar:4.0.31.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.31.Final.jar:4.0.31.Final]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_65]
```

**Comment by jroper** [comment] 2015-12-31 01:51
It's odd that you're receiving them with every request, we only saw the problem in 1 in 6 million requests in our performance tests, but nevertheless, the problem is known and has been fixed here:

https://github.com/typesafehub/netty-reactive-streams/pull/4

I'm cutting a new release right now, you should be able to add the following dependency to your project and it will be fixed:

```scala
"com.typesafe.netty" % "netty-reactive-streams-http" % "1.0.2"
```

**Comment by eximius313** [comment] 2015-12-31 15:05
Ok, I confirm that with 1.0.2 this problem disappeared.

Weird thing is, that previously this piece of code:
```
	@Transactional(readOnly = false)
	public Result show(String someId) {
		return Helper.findEntity(someId).map(entity -> {
			//do sth
			return (Result)ok(views.html.myTemplate.render(entity));
		}).orElse((Result)ok(views.html.myTemplate.render(null)));
	}
```
(where ```myTemplate``` is doing one request to the database) run just fine but with version 1.0.2 it throws:
```
[RuntimeException: No EntityManager found in the context. Try to annotate your action method with @play.db.jpa.Transactional]
```

Changing:
```
.orElse((Result)ok(views.html.myTemplate.render(null)));
```
to:
```
orElseGet(() -> (Result)ok(views.html.myTemplate.render(null)));
```
solved the issue...

**Comment by mkurz** [comment] 2016-02-07 11:41
Can this issue be closed? Looks like it has been fixed...

**Closed** 2016-02-07 13:53 UTC
Labels: defect
