### ISSUE TITLE
[2.4.2] Assets.versioned enforce usage of .min files

### ISSUE THREAD

**Issue by alexbernotas** [playframework/playframework#5173] opened 2015-10-12 10:07 UTC
There shouldnt be a default behaviour to enforce the .min file usage (if the file exist in the same directory), this is really inconvenient when developing.
Is there a way to switch this off at the moment?

**Comment by Daxten** [comment] 2015-10-28 11:09
I'm not sure atm, but this shouldn't happen if you use dev mode ($ sbt run) instead of production

**Comment by marcospereira** [comment] 2015-11-23 01:51
You can access the original non minified file if you want, just don't use the `min`, but my suggestion is to use source maps as explained by sbt-uglify docs:

https://github.com/sbt/sbt-uglify

Moreover, I think any further discussion can happen at the [user mailing list](https://groups.google.com/forum/#!forum/play-framework). :-)

**Comment by mkurz** [comment] 2016-07-01 17:08
I am re-opening this issue because there actually **is** a bug.
@marcospereira I can confirm that also in dev mode the `.min` file is served - which is not what we want.

@alexbernotas @Daxten 
As a workaround you can turn off the resolving of the min file globally (for dev and prod mode) via this setting:
```
assets.checkForMinified=false
```

**Comment by mkurz** [comment] 2016-07-01 17:09
Here is a fix: #6291

**Closed** 2016-07-11 00:20 UTC
