### ISSUE TITLE
On OSX, activator ~run stop working after change system time forwards then backwards

### ISSUE THREAD

**Issue by inetfuture** [playframework/playframework#6085] opened 2016-04-25 10:45 UTC
### Play Version 

```
activator --version                                                                                                                             
sbt launcher version 0.13.8-M5
```

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Darwin aaronm 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by wsargent** [comment] 2016-04-26 20:00
@inetfuture Can you say what the system did do?  "Not working" could cover a variety of different responses.

**Comment by inetfuture** [comment] 2016-04-27 03:19
> @inetfuture Can you say what the system did do? "Not working" could cover a variety of different responses.

Not recompiling on files change, I tried `activator clean`, didn't help, I have to work around it by recursively `touch` all files to update their modified date.

**Comment by cchantep** [comment] 2016-05-03 11:52
I cannot reproduce this issue on OS X 10.11, neither by changing backward, nor forward

**Comment by cchantep** [comment] 2016-05-14 22:53
Closing until it can be reproduced. Best regards

**Closed by cchantep** 2016-05-14 22:53 UTC
