### ISSUE TITLE
Exception with Scala Scaffold on latest Play 2.6.12

### ISSUE THREAD

**Issue by allanxp4** [playframework/playframework#8270] opened 2018-03-04 03:31 UTC
Play Version 2.6.12, Scala.

OS: Linux Mint 18.3 (Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

JDK:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

### Library Dependencies

No library dependencies, just the standard starter template.

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Download SBT from https://www.scala-sbt.org/download.html
2. run sbt new playframework/play-scala-seed.g8 on a terminal, leave the default settings (Play 2.6.12) and the project should be created.
3. run 'sbt run' and a server will open with the default template.

### Actual Behavior  

1. Download SBT from https://www.scala-sbt.org/download.html
2. run sbt new playframework/play-scala-seed.g8 on a terminal, leave the default settings (Play 2.6.12) and the project should be created.
3. run 'sbt run'.
4- It will crash with this stack trace:

```
Getting org.scala-sbt sbt 1.0.4  (this may take some time)...
:: retrieving :: org.scala-sbt#boot-app
	confs: [default]
	69 artifacts copied, 0 already retrieved (22031kB/83ms)
Getting Scala 2.12.4 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
	confs: [default]
	5 artifacts copied, 0 already retrieved (18986kB/53ms)
[info] Loading settings from scaffold.sbt,plugins.sbt ...
[info] Loading project definition from /home/allan/dev/autoinova-auth/project
[info] Updating {file:/home/allan/dev/autoinova-auth/project/}autoinova-auth-build...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.webjars:webjars-locator-core:0.33 is selected over 0.32
[warn] 	    +- com.typesafe:npm_2.12:1.2.1                        (depends on 0.32)
[warn] 	    +- com.typesafe.sbt:sbt-web:1.4.3 (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.32)
[warn] 	* org.codehaus.plexus:plexus-utils:3.0.17 is selected over {2.1, 1.5.5}
[warn] 	    +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-model:3.2.2                 (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-artifact:3.2.2              (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)
[warn] 	    +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
[warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 2.1)
[warn] 	* com.google.guava:guava:23.0 is selected over {10.0.1, 16.0, 20.0}
[warn] 	    +- io.methvin:directory-watcher:0.3.2                 (depends on 23.0)
[warn] 	    +- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.8.8 (depends on 10.0.1)
[warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 10.0.1)
[warn] 	    +- com.spotify:docker-client:8.9.0                    (depends on 10.0.1)
[warn] Run 'evicted' to see detailed eviction warnings
[error] java.lang.NoClassDefFoundError: play/api/PlayException$ExceptionSource
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:415)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:54)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
[error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:147)
[error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:143)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:207)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:47)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1267)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1212)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1191)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1174)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:683)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:683)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:677)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:154)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:219)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:555)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:485)
[error] 	at sbt.internal.Load$.load(Load.scala:464)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:249)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.apply(Load.scala:249)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:65)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:688)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.ClassNotFoundException: play.api.PlayException$ExceptionSource
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:415)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:54)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
[error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:147)
[error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:143)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:207)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:47)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1267)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1212)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1191)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1174)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:683)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:683)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:677)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:154)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:219)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:555)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:485)
[error] 	at sbt.internal.Load$.load(Load.scala:464)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:249)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.apply(Load.scala:249)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:65)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:688)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: play/api/PlayException$ExceptionSource
[error] Use 'last' for the full log.
```

Changing the version of Play to 2.6.11 works fine.

### Reproducible Test Case

Just download SBT on a Ubuntu-derivative machine and try to run the default g8 scala scaffold template.

Letting the 2.6.12 version when it's asked will not work; 2.6.11 and earlier works fine.

**Comment by PromanSEW** [comment] 2018-03-04 04:17
See #8235

**Comment by PromanSEW** [comment] 2018-03-13 04:26
https://github.com/playframework/play-scala-starter-example/issues/68#issuecomment-353984741

**Comment by marcospereira** [comment] 2019-04-24 18:08
I was not able to reproduce this with newer versions of Play (2.6.21 and 2.7.1), so I'm closing it. @allanxp4, let me know if you still can reproduce this problem with these versions.

**Closed by marcospereira** 2019-04-24 18:08 UTC
Labels: status:backlog
