### ISSUE TITLE
Deprecate ApplicationLifecycle

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9802] opened 2019-11-06 17:34 UTC
As part of https://github.com/lagom/lagom/pull/2426 Lagom decreased the dependence on `Applicationlifecycle` and it surfaced how `Applicationlifecycle` may gradually become irrelevant and even deprecated and removed in favour of Akka's `CoordinatedShutdown`.

A nice improvement in `CoordinatedShutdown` (as opposed to `Applicationlifecycle`) is the naming of each registered task so even at startup you can debug what's registered to happen on what phase to quickly spot miss-configurations.

**Comment by marcospereira** [comment] 2019-11-07 16:14
Duplicate of #8444.

**Closed by marcospereira** 2019-11-07 16:14 UTC
Labels: type:improvement

**Comment by ignasi35** [comment] 2019-11-07 20:11
> Duplicate of #8444.

I am veeeeery eager to get this done! 😅
