### ISSUE TITLE
Can not send websocket ping frame periodically while setting akka.http.server.websocket.periodic-keep-alive-max-idle to 5 seconds

### ISSUE THREAD

**Issue by lvxudong** [playframework/playframework#9209] opened 2019-04-20 06:59 UTC
### Play Version (2.5.x / etc)

Play 2.7

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle 1.8.0

### Library Dependencies

N/A

### Expected Behavior

1. setting akka.http.server.websocket.periodic-keep-alive-max-idle to 5 seconds for both dev and prod setting

2. Connect to websocket, wait

3. Browser should receive periodic websocket ping frame.

### Actual Behavior

Browser Client didn't receive any periodic websocket ping frame.

### Reproducible Test Case

Neither websocket implemented by ActorFlow nor Akka Stream fails to receive ping frame at browser side

Ref:
https://doc.akka.io/docs/akka-http/current/server-side/websocket-support.html#automatic-keep-alive-ping-support

Settings:
`build.sbt` : `PlayKeys.devSettings += "akka.http.server.websocket.periodic-keep-alive-max-idle" -> "5 seconds"`
`application.conf`: `akka.http.server.websocket.periodic-keep-alive-max-idle = 1 second`

**Comment by marcospereira** [comment] 2019-04-23 21:54
Duplicate of #3861.

**Closed by marcospereira** 2019-04-23 21:54 UTC

**Comment by mkurz** [comment] 2022-11-01 12:16
This has been no been fixed in #11521 and will make its way into Play 2.8.19.
