### ISSUE TITLE
Deadlock issue - play 2.6.1

### ISSUE THREAD

**Issue by leafty** [playframework/playframework#7622] opened 2017-07-13 09:32 UTC
# Deadlock issue - play 2.6.1

Environment: play 2.6.1 - scala 2.12/2.11 - dev mode - java 1.8 (openjdk)

- Symptom: play server ceases to respond to http requests after a few http posts with mid-size payload (~100kB)
- Probable issue: some internal play tasks are never closed running after the request body is fully consumed and the response is sent,
  exhausting the default execution context's thread pool

## How to reproduce

Start from the seed project:
```bash
sbt new playframework/play-scala-seed.g8
```

In `app/controllers/HomeController.scala`, add method `post`:
```scala
def post(): Action[AnyContent] = Action { implicit request: Request[AnyContent] =>
  val t = java.time.Instant.now()
  println(s"In post, $t")
  Ok(s"Ok, $t\n")
}
```

In `conf/routes`, add:
```
POST    /                           controllers.HomeController.post
```

Create a file of size ~100kB:
```bash
base64 /dev/urandom | head -c 100000 > myfile.dat
```

Run server:
```bash
sbt run
```

Make a first empty post, to compile and check the controller:
```bash
curl -v -X POST -H "Content-Type: application/octet-stream" -d "" http://localhost:9000
```

Now, let's send our file (this should be fine):
```bash
curl -v -X POST -H "Content-Type: application/octet-stream" -d @myfile.dat http://localhost:9000
```

Now, let's starve the server:
```bash
for i in {1..1000}; do curl -X POST -H "Content-Type: application/octet-stream" -d @myfile.dat http://localhost:9000; done
```

**Comment by Rovak** [comment] 2017-07-13 11:31
related to https://github.com/playframework/playframework/issues/7614

**Comment by richdougherty** [comment] 2017-07-13 23:03
Thanks for the report. What's interesting to me is that you're only making one request at a time, right? And still we're getting a deadlock. Any chance you could attach a thread dump?

**Comment by leafty** [comment] 2017-07-14 06:22
Yes, the curl calls are serial, and it often happens after just 5 or 6 requests.

I've attached one to my gist here: https://gist.github.com/leafty/1b0bcb9772220eee4c3298ac47351f3e.

**Comment by leszekgruchala** [comment] 2017-07-14 07:52
Same happening to me. `2.6.0` is fine.

**Comment by pschichtel** [comment] 2017-07-15 19:27
I can confirm this issue! It happens within the first 1-2 page loads after starting the server in dev mode.

```2.6.0``` works, ```2.6.1``` also works if you switch to the Netty backend.

Thread Dump: https://gist.github.com/anonymous/58c3567a310c8511f4f759d10928698a

**Comment by richdougherty** [comment] 2017-07-19 20:32
Hi @leafty, @leszekgruchala and @pschichtel, I believe this is the same issue as #7614 which should be fixed on the 2.6.x branch now (see #7627). I'm going to close this issue now because I believe it is fixed. We're going to release Play 2.6.2 soon—I'll ping you on this ticket when we do—and it would be great if you could check if this issue is fixed for you.

**Closed by richdougherty** 2017-07-19 20:32 UTC
Labels: defect, needs-verification

**Comment by richdougherty** [comment] 2017-08-12 06:36
Hi @leafty, @leszekgruchala and @pschichtel, sorry I forgot to ping you to let you know we'd released Play 2.6.2. We're actually up to Play 2.6.3 now! (See https://blog.playframework.com/play-2-6-3-released/). If you do get a chance, it would be great if you could test out the new release and let us know that it's fixed for you. :)

**Comment by leszekgruchala** [comment] 2017-08-12 09:28
I have tested 2.6.2 and problem was solved 🎉

-- 
Leszek Gruchała
http://www.gruchala.eu

Włącz 12 sierpnia 2017 w 08:36:37, Rich Dougherty (notifications@github.com)
Napisał:

**Comment by pschichtel** [comment] 2017-08-12 11:58
Same for me, 2.6.3 now also solves my other issues.

**Comment by leafty** [comment] 2017-08-12 14:08
I can't reproduce it on 2.6.3. Looks like this is solved, thanks.

**Comment by richdougherty** [comment] 2017-08-13 04:03
Thanks guys. :)

> 2.6.3 now also solves my other issues

Hope there weren't too many!
