### ISSUE TITLE
Play project doesn't work with sbt 1.7.3 and 1.8.0+

### ISSUE THREAD

**Issue by unkarjedy** [playframework/playframework#11522] opened 2022-10-31 14:56 UTC
Create new Play 2.8.18 with sbt 1.7.3
(BTW you can do that easily in IntelliJ IDEA via `File | New | New Project | Play 2 | Create`)

Observe error during SBT project loading:
```
[info] welcome to sbt 1.7.3 (Amazon.com Inc. Java 17.0.1)
[info] loading global plugins from ~\.sbt\1.0\plugins
[info] loading settings for project untitled325-build from plugins.sbt ...
[info] loading project definition from ......
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.2.0, 1.1.1}
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.1.1)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.2.0, 1.1.1}
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.1.1)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
```

**UPD**
Scala Plugin issue: https://youtrack.jetbrains.com/issue/SCL-20731

**Comment by unkarjedy** [comment] 2022-10-31 14:59
Probably related change in SBT and Coursier:
- https://github.com/sbt/sbt/pull/7060
- https://github.com/coursier/sbt-coursier/releases/tag/v2.0.12
- https://github.com/coursier/coursier/pull/2548

**Comment by unkarjedy** [comment] 2022-10-31 15:01
cc @ckipp01 @eed3si9n

**Comment by mkurz** [comment] 2022-10-31 15:18
See https://github.com/sbt/sbt/pull/7021#issuecomment-1254787512
Not sure if this was on purpose...

**Comment by jamesward** [comment] 2022-10-31 18:19
Workaround: https://github.com/sbt/sbt/issues/7007#issuecomment-1221823661

**Comment by eed3si9n** [comment] 2022-10-31 18:29
To summarize various other threads, there's no new regression introduced by sbt 1.7.3 right?
sbt 1.7.x series uses scala-compiler 2.12.16 and scala-xml 1.x which are binary compatible with sbt 1.0.0:

```
$ cs resolve org.scala-sbt:sbt:1.7.3 | rg "scala-(xml|compiler)"
org.scala-lang:scala-compiler:2.12.16:default
org.scala-lang.modules:scala-xml_2.12:1.3.0:default
```

We will be breaking this binary compatibility in a coordinated effort (https://github.com/sbt/sbt/issues/6997 + https://github.com/scala/bug/issues/12632) in sbt 1.8.x series by bumping up to scala-compiler 2.12.17.

**Comment by mkurz** [comment] 2022-11-01 20:48
@eed3si9n I know you did not upgrade to Scala 2.12.17 nor to scala-xml 2 in sbt itself, the 1.7.2...1.7.3 diff actually not really special: https://github.com/sbt/sbt/compare/v1.7.2...v1.7.3
The problem is caused by the bump to coursier shaded to 2.0.12: https://github.com/coursier/sbt-coursier/compare/v2.0.11...v2.0.12#diff-f45415265fd14a72d0c7d579db5d9e03c9fd5278fefe931e31b1da1b57a152d8R12 which now sets Scala 2.12.17 as default scala version for sbt projects.

The thing is for sbt users who don't care about sbt internals, changing the version from 1.7.2 to 1.7.3 in their plugins.sbt causes errors in their console, we already get reports: https://github.com/playframework/play-scala-seed.g8/issues/182 and I guarantee there will be more soon.

Anyway, looking at the diffs, there is nothing really pressing to upgrade rom 1.7.2 to 1.7.3 IMHO.
So to be honest, if 1.7.3 is the last 1.7.x release and we jump on the 1.8.x train asap, I think I would just recommend not to upgrade to 1.7.3 right now since it's not really worth it (or urge people to apply to workaround).

For Play 2.8.x that means we probably need coordinated releases of a new Play version itself and all it's dependency (twirl, etc.) with all of them upgraded to scala-xml 2.x and then recommend to use that and upcoming Play versions with sbt 1.8.0+

The workaround is alway an option, however I don't really want to apply it in all the seed projects etc. Better to keep things clean IMHO.

**Comment by xuwei-k** [comment] 2022-11-02 07:42
I think sbt-twirl plugin pulls unused scala-xml dependency.

- https://github.com/playframework/twirl/pull/564
- https://github.com/playframework/twirl/pull/563

**Comment by rmmeans** [comment] 2023-05-01 14:42
For anyone else that bumps into this, I was able to upgrade our large project and get all test automation to pass when I made the following additional changes.

This is on sbt `1.8.2` and Play `2.8.19`

plugins.sbt:
```
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.typesafe.play" % "sbt-twirl"           % "1.5.2")
```

build.sbt:
```
"com.typesafe.play"     %% "play-ahc-ws-standalone"      % "2.1.10+1-13e48d3c-SNAPSHOT",
"com.typesafe.play"     %% "play-ws-standalone-xml"      % "2.1.10+1-13e48d3c-SNAPSHOT",
"com.typesafe.play"     %% "play-ws-standalone-json"     % "2.1.10+1-13e48d3c-SNAPSHOT",
```

The Play-ws was my last holdup, then I found this PR that was not merged that gave me the above snapshot ref: https://github.com/playframework/play-ws/pull/733

**Comment by mkurz** [comment] 2023-09-20 09:15
So there are workarounds to avoid the error with Play 2.8 using sbt 1.7.3+, posted here and also see https://www.playframework.com/documentation/2.9.x/General#End-of-life-(EOL)-Dates.
I am not touching this anymore in 2.8.x since we would need to do major dependency upgrades, which I am not a fan of for 2.8.
Recommendation is to upgrade to Play 2.9 instead: https://github.com/playframework/playframework/releases/tag/2.9.0-RC2

**Closed by mkurz** 2023-09-20 09:15 UTC
