### ISSUE TITLE
IllformedLocaleException caused by dragon browser

### ISSUE THREAD

**Issue by sanitas2** [playframework/playframework#8439] opened 2018-05-27 19:19 UTC
### Actual Behavior
I've noticed in logs that people accessing my webpage using browser with user agent
```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Dragon/45.9.12.393 Chrome/45.0.2454.93 Safari/537.36`
```

are getting 500 errors. The stack trace looks like that:

```
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:251)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
       [...]
Caused by: java.util.IllformedLocaleException: Empty subtag [at index 0]
        at java.util.Locale$Builder.setLanguageTag(Locale.java:2426)
        at play.api.i18n.Lang$.apply(Langs.scala:95)
        at play.api.i18n.Lang.apply(Langs.scala)
        at play.mvc.Http$Context.messages(Http.java:230)
        at play.core.j.PlayMagicForJava$.implicitJavaMessages(TemplateMagicForJava.scala:36)
       [...]
```

I don't think Play should relay on browser providing correct locale information.

**Comment by gmethvin** [comment] 2018-05-28 03:06
Does upgrading to 2.6.15 fix the problem?

**Comment by wsargent** [comment] 2018-05-29 23:50
It wouldn't help -- the code in 2.6.15 still expects there to be a non empty code:

https://github.com/playframework/playframework/blob/2.6.x/framework/src/play/src/main/scala/play/api/i18n/Langs.scala#L95
```
  def apply(code: String): Lang =
    Lang(new Locale.Builder().setLanguageTag(code).build())
```

This appears to be special behavior of `setLanguageTag`:

https://docs.oracle.com/javase/8/docs/api/java/util/Locale.Builder.html#setLanguageTag-java.lang.String-

> Resets the Builder to match the provided IETF BCP 47 language tag. Discards the existing state. Null and the empty string cause the builder to be reset, like clear(). Grandfathered tags (see Locale.forLanguageTag(java.lang.String)) are converted to their canonical form before being processed. Otherwise, the language tag must be well-formed (see Locale) or an exception is thrown (unlike Locale.forLanguageTag, which just discards ill-formed and following portions of the tag).

but the empty sub-tag exception seems to come from LanguageTag

https://github.com/frohoff/jdk8u-dev-jdk/blob/master/src/share/classes/sun/util/locale/LanguageTag.java#L215

So... we need to figure out where it's getting the language set from.  My guess is HTTP header, but we can't reproduce without more detail.

**Comment by axuan25** [comment] 2020-02-21 11:02
We had similar errors in our logs. Just in case, here's what we were doing wrong just in case someone might be doing the same. 

`RequestHeaders.acceptLanguages` fetches a list of recognized languages:
```
lazy val acceptLanguages: Seq[play.api.i18n.Lang] = {
  val langs =
    RequestHeader.acceptHeader(headers, HeaderNames.ACCEPT_LANGUAGE).map(item => (item._1, Lang.get(item._2)))
  langs.sortWith((a, b) => a._1 > b._1).flatMap(_._2)
}
```
`Lang.get` works by using a `Try` on on `Lang.apply`:
```
def get(code: String): Option[Lang] = Try(apply(code)).toOption
```
That's because `Lang.apply` can throw an exception:
```
/**
 * Create a Lang value from a code (such as fr or en-US) and
 *  throw exception if language is unrecognized
 */
def apply(code: String): Lang =
  Lang(new Locale.Builder().setLanguageTag(code).build())
```

In our language support trait, we first fetched the list of accepted languages using Play's helper (`RequestHeader.acceptLanguages`). But our i18n messages use simple language keys that do not differ by region ("`fr`", "`en`" etc). So using the `Seq[Lang]` returned by Play, we called `Lang.apply` with `Lang.language`:
```
val languages = req.acceptLanguages.map(l => Lang(l.language))
messagesApi.preferred(languages)
```

As to why it might still throw an exception even though Play supposedly already parsed the acceptable languages, see `Lang.language`, which calls `java.util.Locale.getLanguage`:
```
/**
 * Returns the language code of this Locale.
 *
 * <p><b>Note:</b> ISO 639 is not a stable standard&mdash; some languages' codes have changed.
 * Locale's constructor recognizes both the new and the old codes for the languages
 * whose codes have changed, but this function always returns the old code.  If you
 * want to check for a specific language whose code has changed, don't do
 * <pre>
 * if (locale.getLanguage().equals("he")) // BAD!
 *    ...
 * </pre>
 * Instead, do
 * <pre>
 * if (locale.getLanguage().equals(new Locale("he").getLanguage()))
 *    ...
 * </pre>
 * @return The language code, or the empty string if none is defined.
 * @see #getDisplayLanguage
 */
public String getLanguage() {
    return baseLocale.getLanguage();
}
```
Thus, my educated guess is that in rare cases, `Lang.apply` was called with an old language code.

Hope this helps!

**Comment by cptwunderlich** [comment] 2023-08-23 08:31
We have also have encountered this issue. However, @axuan25's explanation doesn't pan out.
Just open jshell and try:
`new java.util.Locale.Builder().setLanguageTag("iw").build()` where 'iw' (iwrit) is the old code for modern hebrew ('he'). This will work and `toString()` prints the new code "he".

The exception happens deeper in the parser. The tags are what's separated by hyphens. This triggers the exception:
`new java.util.Locale.Builder().setLanguageTag("iw-").build()`

> |  Exception java.util.IllformedLocaleException: Empty subtag [at index 3]
> |        at Locale$Builder.setLanguageTag (Locale.java:2602)
> |        at (#8:1)

However, I can't reproduce this error. Setting the "Accept-Languages" header doesn't trigger it - and as @axuan25 has shown above, that code uses `Try`. So does the code fetching the language from the cookie.
The third option is the "transient language" - and that I understand the least. How is this set? We never set it explicitly in our code.

**Comment by mkurz** [comment] 2024-03-15 09:54
@cptwunderlich Do you remember which Play version you used when the problem occured in August 2023?
I am pretty sure the original report (first comment here), which was against Play 2.6.10, was fixed with Play 2.6.13, because the faulty line only exists up until Play 2.6.12: https://github.com/playframework/playframework/blob/2.6.12/framework/src/play/src/main/java/play/mvc/Http.java#L230
With Play 2.6.13 that code got refactored: faa85d064b1cbf7b1f5722097ac0d57a650231ff so eventually `...play.api.i18n.Lang.apply(langCookie.value())...` does not even get called anymore...

Also, looking at the code, I agree that all calls to `play.api.i18n.Lang.apply(...)` are wrapped with a try/catch or `Try`, except the transient methods...

Did you encounter the problem again since last year?

**Comment by cptwunderlich** [comment] 2024-03-18 07:58
It was the current 2.8 version at the time. But I have not seen this error since. At the time, I searched for this error and it seemed like it was the same as this. Anyway, seems like it's no longer a problem! Thank you for looking into this.

**Comment by mkurz** [comment] 2024-03-18 08:03
Thanks @cptwunderlich.
Given this report was opened against Play 2.6 long time ago and the "problem" dos not occur anymore, I think it's safe to close this issue, at least for now.

If someone still experience problems, please comment or open a new issue, thanks! If possible with a reproducer and/or a request with all the headers which caused the problem :wink: 
(Right now I can not see why this would still happen because all the code that calls the method in question is wrapped within try and any exception are caught...)

**Closed by mkurz** 2024-03-18 08:03 UTC
Labels: status:needs-info, status:needs-verification
