### ISSUE TITLE
`request.uri` vs `request.path` string mismatch on utf8-encoded urls

### ISSUE THREAD

**Issue by inakianduaga** [playframework/playframework#8679] opened 2018-10-08 10:25 UTC
### Play Version (2.5.x / etc)

Play 2.6.13

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS / Amazon linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_112"

### Expected Behavior

on a empty play app w/ a route and controller 

Please describe the expected behavior of the issue, starting from the first action.

```scala
# routes
GET        /*parameters      @com.MyController.handler(parameters: String)
```

and

```scala
// MyController.scala
def handler(parameters: String) = Action { implicit request =>
    Ok(s"${request.path} is not a literal substring of ${request.uri} due to encoding")    
}
```

1. `curl  localhost:9000/%c3%96hringen
2. `request.path` equals `%C3%96hringen`  and `request.uri = `%c3%96hringen`

### Actual Behavior

`request.path` should be a substring of `request.uri`

### Reproducible Test Case

1. `curl  localhost:9000/%c3%96hringen`

**Comment by marcospereira** [comment] 2019-04-23 22:24
Duplicate of #9190.

**Closed by marcospereira** 2019-04-23 22:24 UTC
Labels: closed:duplicated
