### ISSUE TITLE
Play 2.9.3 - HTTPS issue

### ISSUE THREAD

**Issue by h-ngo** [playframework/playframework#12712] opened 2024-06-06 19:22 UTC
We are in the process of upgrading our Play from 2.8.19 to 2.9.3. We encountered an issue with HTTPS which we are not able to find any clue. (HTTP works fine)

### Play Version
2.9.3

### Operating System
Ubuntu

### JDK

JDK 17
Scala 2.13.14

### Library Dependencies

Akka 2.9.3
Akka-http 10.6.3

### Expected Behavior

1. Call the Play app using "curl -kv https://localhost:4443"
2. Received a response
3. Continue receiving a response in subsequent calls

### Actual Behavior

1. Call the Play app using "curl -kv https://localhost:4443"
2. Received a response
3. On the 2nd call, got below error
* Immediate connect fail for ::1: No route to host
*   Trying 127.0.0.1:4443...
* Connected to localhost (127.0.0.1) port 4443
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*  CAfile: none
*  CApath: none
* loaded libnssckbi.so
* ALPN: offers h2,http/1.1
* timed out before SSL handshake
* Closing connection
curl: (28) timed out before SSL handshake

5. On the 3rd call, got timeout error
Immediate connect fail for ::1: No route to host
*   Trying 127.0.0.1:4443...
* connect to 127.0.0.1 port 4443 failed: Connection refused
* Failed to connect to localhost port 4443 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to localhost port 4443 after 0 ms: Couldn't connect to server

HTTPS seems to die after the successful 1st call. There's no any error in the logs.

We have also tried to revert back Akka to 2.8.3 and Akka-http 10.5.2, which we have been using with Play 2.8.19 for past years, still the same behavior.

**Comment by mkurz** [comment] 2024-06-07 06:45
Your problem is a typo: you are using port 4443 instead of 443. That's it, of course the request times out...

> We have also tried to revert back Akka to 2.8.3 and Akka-http 10.5.2, which we have been using with Play 2.8.19 for past years, still the same behavior.

of course because you use the wrong port, again you are connecting into nirvana here.

**Comment by mkurz** [comment] 2024-06-07 20:22
@h-ngo Isn't this the same like #12711? Or is it just coincidence that both of you open very similiar issues within one hour? (same akka-http, akka, scala versions)

**Comment by h-ngo** [comment] 2024-06-07 22:09
coincidence.

**Comment by h-ngo** [comment] 2024-06-07 22:15
We have yet encountered the issue reported in #12711 . Is Akka 2.9.3 and Akka-http 10.6.3 not fully compatible with Play 2.9.3?

**Comment by mkurz** [comment] 2024-06-10 11:15
Can you reproduce the error 100% each time? Do you see any error logs?

**Comment by mkurz** [comment] 2024-06-11 09:31
@h-ngo Can you please test your application with Play version `2.9.4-M1`? I just published this pre-relase which comes with
- #12719
which fixes
- #12711

so this might also fix your problem :crossed_fingers: 

Please let me know if that works for you or, if still problems occurs, please post errors/exceptions, thanks!

**Comment by h-ngo** [comment] 2024-06-11 15:26
@mkurz we have finally figured out the cause of our issue. It was due to our internal custom SSL Engine. Before Play 2.9.x, we have long been using "val" for "createSSLEngine" and "sslContext"

override val createSSLEngine: SSLEngine
override val sslContext: SSLContext 

after changing to "override def" for both. The issue resolved.

Is this something new in Play 2.9.x? even though in [Play 2.8.x](https://www.playframework.com/documentation/2.8.x/ConfiguringHttps), it suggested to use "def" but we have been using "val" ever since but never caused any issue.

We haven't encountered the https issue reported in #12711. I don't think we have made any changes to switch to the new Netty sever in Play 2.9.x. Play 2.9.x still use Akka HTTP by default or it's not the case?

**Comment by mkurz** [comment] 2024-06-11 19:00
> Is this something new in Play 2.9.x?

No, the interfaces, classes and traits involved did not change as far as I can see.

> it suggested to use "def" but we have been using "val" ever since but never caused any issue.

When upgrading from 2.8.19 to 2.9.3 do you also upgrade(d) the Scala version? IMHO this has nothing to do with Play but with Scala. I have some dark memories that upgrading from a Scala 2.13.x to a newer 2.13.x Scala release something came up in regards of  overriding defs/val´s... Hmm or was it during the Scala 3 migration... can't remember...

> Play 2.9.x still use Akka HTTP by default or it's not the case?

Yes, akka-http ist still the default for 2.9.x

**Comment by h-ngo** [comment] 2024-06-11 19:23
Yes. We did upgrade Scala from 2.13.10 to 2.13.14. Would be surprised if it's related because a patch version should not contain any breaking changes. We have checked Scala release notes too. can't seem to find any changes related to overriding def/val.

Would you suggest us to set this property to ensure our Play uses Akka http?
play.server.provider = play.core.server.AkkaHttpServerProvider

I think we can play around once our upgrades calm down a bit. The reason we wanna stick with Akka http is we are not sure if Lightbend Telemetry supports Play Netty Server if we switch.

**Comment by mkurz** [comment] 2024-06-11 19:49
> Yes. We did upgrade Scala from 2.13.10 to 2.13.14. Would be surprised if it's related because a patch version should not contain any breaking changes.

Yeah, usually nothing should break, however sometimes things do change subtle in behaviour (sometimes this is desired). Would be interesting if your problem also occurs if you try Play 2.9 but stay on Scala 2.13.10. If not then try 2.13.11 and so on to figure out which Scala version caused this. Up to you.

> We have checked Scala release notes too. can't seem to find any changes related to overriding def/val.

Sometimes this is a side effect of other changes and not completely obvious solely from the release notes.

> Would you suggest us to set this property to ensure our Play uses Akka http?

It's not necessary, it's the default anyway. However, if you do set this config key, then you have to set it not just in application.conf, but additionally also in `build.sbt` to take effect in dev mode. Like:
```sbt
PlayKeys.devSettings += "play.server.provide" -> "play.core.server.AkkaHttpServerProvider"
```

Please read [this docs](https://www.playframework.com/documentation/2.9.x/ConfigFile#Using-with-the-run-command) why it is necessary to configure backend server settings like this _in dev mode_.

> I think we can play around once our upgrades calm down a bit. 

Play around with what?

> The reason we wanna stick with Akka http is we are not sure if Lightbend Telemetry supports Play Netty Server if we switch.

According to https://developer.lightbend.com/docs/telemetry/current//home.html:

> _Lightbend Telemetry makes it possible to gather metric, event and trace information from Akka based applications._

So it's a tool to monitor akka based applications. Independent of the used http server (netty or akka-http), Play 2.9 uses akka in the background, so you should be able to use telemetry even when using netty. However of course, to monitor the whole request/response cycle starting from the backend server you probably want to stick to akka-http then.

**Comment by h-ngo** [comment] 2024-06-11 20:22
newbie question: what's the easiest way to tell if Play is using Akka http or Netty?

btw, thank you so much for quick responses. All the info has been super helpful.

**Comment by mkurz** [comment] 2024-06-11 20:37
> newbie question: what's the easiest way to tell if Play is using Akka http or Netty?

When running `sbt run` you will see a log message in your console like:
```
...
[info] INFO  p.c.s.PekkoHttpServer - Listening for HTTP on /127.0.0.1:9000
...
```
So in such a case in _dev mode_, you are using pekko http. (It would say `p.c.s.NettyServer` when netty is active.)
Be aware however of the `PlayKeys.devSettings` and `application.conf` approaches I described above. If the settings differ (or you forget to set one or the other), you may see `p.c.s.PekkoHttpServer` in dev mode and think you are on pekko http in all modes, however it could be that the app conf setting is different so in production you run on netty (unaware of it, because dev mode mislead you).

In code, you can also check which server is running by checking a request attribute. See here:
https://www.playframework.com/documentation/2.9.x/NettyServer#Verifying-that-the-Netty-server-is-running
So you could check that attribute in an action method and throw an exception if the desired http backend is not set, so you would recognize very fast even in production that you are on the "wrong" http backend server. This basically is the bullet proof approach.

**Comment by mkurz** [comment] 2024-06-12 06:51
Let's close this. Not a big in Play.

**Closed by mkurz** 2024-06-12 06:51 UTC
