### ISSUE TITLE
Can not create custom datasource config

### ISSUE THREAD

**Issue by ashishpmalkar** [playframework/playframework#11434] opened 2022-09-21 13:11 UTC
Unable to config custom datasource. I am trying load custom data source from java class on start up. but every time application start up. default database configuration gets loaded and try to connect database from application.conf file 
```

db {
  default {
    driver = com.mysql.jdbc.Driver
    host = "localhost"
....
}

```
I tried to use below still it accessing default database 
play.db.prototype.hikaricp.initializationFailFast=false
db.default.migration.initOnMigrate=false
db.default.migration.validateOnMigrate=false

### Play Version (2.5.X)
Flyaway version 3.2

### JDK (1.8.X)
Expected Behavior
When default datasource's username,password is not specified it should not attempt to connect to default datasource.

**Comment by tototoshi** [comment] 2022-09-22 01:30
It is possible that the problem you are having is with the flyway plugin. With a little more information (e.g. screen captures) I might be able to help.

**Comment by ashishpmalkar** [comment] 2022-09-22 07:43
@tototoshi Thanks for asking 

here is my build.sbt  and I am using "org.flywaydb" %% "flyway-play" % "3.2.0",
![image](https://user-images.githubusercontent.com/47938131/191686047-ff229851-643e-4431-80bc-1fd06866ee31.png)

here are some other files 
![image](https://user-images.githubusercontent.com/47938131/191687647-5eb59584-91f3-4249-8eb3-09edbeefa7a4.png)
![image](https://user-images.githubusercontent.com/47938131/191687712-18b3c2ee-9ebe-413e-885f-cca1b87d12b6.png)
![image](https://user-images.githubusercontent.com/47938131/191687778-87228c4f-d979-4240-95dd-2d61a074876e.png)

**Comment by tototoshi** [comment] 2022-09-22 08:21
Thanks.

> but every time application start up. default database configuration gets loaded and try to connect database from application.conf file

Does this mean that every time you start your app you see a page that flyway-play displays?

**Comment by tototoshi** [comment] 2022-09-22 08:31
And if you can figure out the problem is in flyway, please send the feedback to https://github.com/flyway/flyway-play and close this issue.

**Comment by ashishpmalkar** [comment] 2022-09-22 09:28
> And if you can figure out the problem is in flyway, please send the feedback to https://github.com/flyway/flyway-play and close this issue.



> Thanks.
> 
> > but every time application start up. default database configuration gets loaded and try to connect database from application.conf file
> 
> Does this mean that every time you start your app you see a page that flyway-play displays?
Whenever i start server it is giving me below error

Oops, cannot start the server.\nConfiguration error: Configuration error[Cannot connect to database [default]]\n\tat play.api.Configuration$.configError(Configuration.scala:155)\n\tat play.api.Configuration.reportError(Configuration.scala:808)\n\tat play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:48)\n\tat play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:42)\n\tat scala.collection.immutable.List.foreach(List.scala:381)\n\tat play.api.db.DefaultDBApi.connect(DefaultDBApi.scala:42)\n\tat play.api.db.DBApiProvider.get$lzycompute(DBModule.scala:72)\n\tat play.api.db.DBApiProvider.get(DBModule.scala:62)\n\tat play.api.db.DBApiProvider.get(DBModule.scala:58)\n\tat com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)\n\tat com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)\n\tat com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)\n\tat com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)\n\tat com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)\n\tat com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)\n\tat com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)\n\tat com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)\n\tat com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)\n\tat com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)\n\tat com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)\n\tat com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)\n\tat com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)\n\tat com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)\n\tat com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)\n\tat com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)\n\tat com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)\n\tat com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)\n\tat com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)\n\tat com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)\n\tat com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)\n\tat com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)\n\tat com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:984)\n\tat com.google.inject.util.Providers$GuicifiedProviderWithDependencies.initialize(Providers.java:149)\n\tat com.google.inject.util.Providers$GuicifiedProviderWithDependencies$$FastClassByGuice$$2a7177aa.invoke(<generated>)\n\tat com.google.inject.internal.cglib.reflect.$FastMethod.invoke(FastMethod.java:53)\n\tat com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:57)\n\tat com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:91)\n\tat com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)\n\tat com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)\n\tat com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)\n\tat com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)\n\tat

**Comment by tototoshi** [comment] 2022-09-23 03:55
Ok, It doesn't seem to be related to flyway. This error came from Play's DB Module.

> Expected Behavior
> When default datasource's username,password is not specified it should not attempt to connect to default datasource.

DB Module is not disabled by not specifying username and password.
You need to remove the module from dependencies to disable it. Maybe you have `jdbc` or `javaJdbc` in build.sbt. Try removing it.

**Comment by ihostage** [comment] 2022-09-29 11:50
Thank you, @tototoshi for your help! 👍 

@ashishpmalkar Please, use [Discussions](https://github.com/playframework/playframework/discussions) for your questions 😉 
BTW, **Play 2.5** don't support 🤷‍♂️

**Closed by ihostage** 2022-09-29 11:50 UTC
