### ISSUE TITLE
WS hangs when processing a request with form-url-encoded and a content length

### ISSUE THREAD

**Issue by saeta** [playframework/playframework#5221] opened 2015-11-02 23:55 UTC
Reproducing test case: https://github.com/saeta/play-2.4.x-ws-body-parsing-hanging

Requesting without including the content-length header works correctly:

```
$ curl localhost:9000/test
Got Header: DefaultWSResponseHeaders(200,Map(Via -> Buffer(1.1 vegur), Date -> Buffer(Mon, 02 Nov 2015 23:49:16 GMT), Server -> Buffer(gunicorn/19.3.0), Connection -> Buffer(keep-alive), Content-Type -> Buffer(text/html; charset=utf-8), Sponsored-By -> Buffer(https://www.runscope.com), Content-Length -> Buffer(2))) with stream play.api.libs.ws.ning.NingWSRequest$$anon$2$$anon$3@266fd177
```

When the content length is included as a header, this API hangs forever:

```
$ curl "localhost:9000/test?addBodyLength=true"
^C
[1]    12301 interrupt  curl "localhost:9000/test?addBodyLength=true"
```

**Comment by jroper** [comment] 2015-11-03 00:16
Ok, at first glance, it seems what is happening is that the body is being parsed as an empty form, Play's form parser, if it doesn't find an equals in a form key value pair, ignores it.  Consequently, ning is given no body, there are no form params to set, so none are set, so as far as ning is concerned, there's no body.  So, it doesn't send a body, and since it doesn't send a body, it doesn't make any attempt to set (not set) a content length, since requests with no body don't need (and shouldn't have) a content length.  However, since the content length is being set by the client code, when request bin receives the request, it sees the content length, and then goes on to read the request body, which is never going to be sent, and so the request hangs.

I think the solution here, is if we are going to take over the request body, as we are here when we parse and then reformat, then we must take over all aspects of it, including the content length.  So we should block the content length header.

Another thing I think is that if we know we're not doing an oauth request, we shouldn't attempt to do anything with the body - I think we can know that we're not doing an oauth request by seeing whether there is a request signer set, if not, we shouldn't do anything with the request body, and in that case, we don't need to block the content length.  That will also solve the problem here, and also solve the proxy use case where you don't want the body touched, but the first solution above is the more important, and more correct one, so that's the higher priority one to implement.

**Comment by saeta** [comment] 2015-11-03 00:19
The first solution sounds reasonable, but we are definitely looking for the second one for our use-cases.

Thank you for your prompt attention!

**Comment by wsargent** [comment] 2015-11-03 18:19
I can't reproduce this:

```
➜  ~  curl localhost:9000/test
Got Header: DefaultWSResponseHeaders(200,Map(Via -> Buffer(1.1 vegur), Date -> Buffer(Tue, 03 Nov 2015 18:11:41 GMT), Server -> Buffer(gunicorn/19.3.0), Connection -> Buffer(keep-alive), Content-Type -> Buffer(text/html; charset=utf-8), Sponsored-By -> Buffer(https://www.runscope.com), Content-Length -> Buffer(2))) with stream play.api.libs.ws.ning.NingWSRequest$$anon$2$$anon$3@27097602%                                                                                                                                            ➜  ~  curl "localhost:9000/test?addBodyLength=true"
Got Header: DefaultWSResponseHeaders(499,Map(Date -> Buffer(Tue, 03 Nov 2015 18:12:38 GMT), Server -> Buffer(Cowboy), Connection -> Buffer(keep-alive), Content-Type -> Buffer(text/html; charset=utf-8), Cache-Control -> Buffer(no-cache, no-store), Content-Length -> Buffer(484))) with stream play.api.libs.ws.ning.NingWSRequest$$anon$2$$anon$3@7de23f2f%
```

**Comment by saeta** [comment] 2015-11-03 19:15
@wsargent <https://github.com/wsargent> have you been able to reproduce
this now? It looks like in the text console you sent to me that the
response code is different. (i.e. `DefaultWSResponseHeaders(499,Map(...))`
looks to be response code 499.) Thanks!

**Comment by wsargent** [comment] 2015-11-03 19:17
It's happening from the Play side -- the WS call is timing out, and then Play is resolving the timeout, I think.  I'll strip out Play and work with WS.

**Closed** 2016-02-29 12:18 UTC
Labels: defect
