### ISSUE TITLE
Support for binary certificate key store data in KeyStoreConfig and TrustStoreConfig

### ISSUE THREAD

**Issue by Rogach** [playframework/playframework#6715] opened 2016-11-10 13:54 UTC
### Play Version
2.5.x

It would be useful to be able to configure `SSLConfig` key stores and trust stores with binary data arrays. Currently it is possible only with strings, which works for PEM format but does not help with binary formats (PKCS12, for example). Loading PKCS12 from file works fine, so there are no technical problems here.

Are there any reasons that binary data can't be provided in KeyStoreConfig and TrustStoreConfig? If not, I would be happy to make a pull request which would add that feature.

**Comment by wsargent** [comment] 2016-11-10 16:40
Hi @Rogach can you point to some code and give a reproducible use case?  

Play WS does allow for the use of PKCS12 files:

```
{ type: "PKCS12", path: "/private/keystore.p12" }
```

Please see https://www.playframework.com/documentation/2.5.x/KeyStores#Configuring-a-Key-Manager for more details.

**Comment by Rogach** [comment] 2016-11-10 18:44
Hi @wsargent 

Yes, I have to clarify - Play WS loads PKCS12 files just fine. However, I need to configure it in run-time, and your example will be translated into something like the following:

```scala
SSLConfig(
  keyManagerConfig = KeyManagerConfig(
    algorithm = KeyManagerFactory.getDefaultAlgorithm,
    keyStoreConfigs = Seq(
      KeyStoreConfig(
        storeType = "PKCS12",
        filePath = Some("/private/keystore.p12"),
        data = None,
        password = Some("")
      )
    )    
  )
)
```

But keystore is not always located on local file system - it may be stored in database, for example, in form of `Array[Byte]`.

Currently, it is possible to provide text-based data to `KeyStoreConfig`, so PEM works just fine. But since PKCS12 is not text-based, it is not possible to do that, resulting in ugly workarounds with unnecessary disk writes.

**Comment by wsargent** [comment] 2016-11-10 18:51
@Rogach you can define run time information to Play WS just fine:

https://github.com/wsargent/play-ws-with-letsencrypt/blob/master/app/controllers/LetsEncryptWSClient.scala#L25

There is an entry for more flexible keystore management since JDK 1.8 allows for a keystore builder:

https://github.com/typesafehub/ssl-config/issues/44

Are you asking for the ability to load a keystore from an inputstream?

https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore.html#load-java.io.InputStream-char:A-

It would really help if you provided a step by step breakdown of the problem and a reproducible project.

**Comment by Rogach** [comment] 2016-11-10 18:54
@wsargent Yes, I would like to load KeyStore from an InputStream, and I am aware of `KeyStore.load` - but how should I then pass the resulting `KeyStore` into `WSClient` constructors?

**Comment by wsargent** [comment] 2016-11-10 19:02
@Rogach if you look in the example, `AhcConfigBuilder.configure()` returns an instance of `org.asynchttpclient.DefaultAsyncHttpClientConfig.Builder`.  You need to swap it out there, and call `builder.setSslContext()` with your prebuilt context.

**Comment by wsargent** [comment] 2016-11-10 19:03
Closing as this is not a bug in Play WS.

**Closed by wsargent** 2016-11-10 19:03 UTC

**Comment by Rogach** [comment] 2016-11-10 19:04
@wsargent I'm not sure what you mean by "reproducible project", since what I am asking is currently not possible to do. But here's one possible example with workaround, that involves writing the store to temp file and then using it to create WSClient:

```scala
val pkcs12binaryData: Array[Byte] = ??? // received from somewhere
val tempFile = new File("/tmp/some-random-name.p12")
// uses commons-io helper
FileUtils.writeByteArrayToFile(new File("/tmp/some-random-name.p12"), pkcs12binaryData)
val sslConfig = SSLConfig(
  keyManagerConfig = KeyManagerConfig(
    algorithm = KeyManagerFactory.getDefaultAlgorithm,
    keyStoreConfigs = Seq(
      KeyStoreConfig(
        storeType = "PKCS12",
        filePath = Some(tempFile.getName),
        data = None,
        password = Some("")
      )
    )
  )
)

val ws = NingWSClient(
  NingWSClientConfigFactory.forClientConfig(
    WSClientConfig(ssl = sslConfig)
  )
)

ws.url("https://somewhere.org").get().foreach { result =>
  println(result)
  FileUtils.deleteQuietly(tempFile)
}
```

**Comment by wsargent** [comment] 2016-11-10 19:06
@Rogach if you start with https://github.com/wsargent/play-ws-with-letsencrypt/blob/master/app/controllers/LetsEncryptWSClient.scala#L44 for your custom WSClient and then use `setSslContext` for the ahcBuilder that should do what you want.

**Comment by Rogach** [comment] 2016-11-10 19:08
@wsargent Thanks!
