### ISSUE TITLE
Play project doesn't work if it is not the root

### ISSUE THREAD

**Issue by pauldraper** [playframework/playframework#3794] opened 2015-01-09 00:03 UTC
**project/build.properties**
```
sbt.version=0.13.7
```
**project/plugins.sbt**
```scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.7")
```

**build.sbt**
```scala
lazy val foo = (project in file("foo")).enablePlugins(PlayScala)
```
After `sbt foo/run` and `curl http://localhost:9000/`, there is the exception

```
! Internal server error, for (GET) [/] ->

java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:313) ~[scala-library.jar:na]
    at scala.None$.get(Option.scala:311) ~[scala-library.jar:na]
    at play.PlayReloader$$anon$1.reload(PlayReloader.scala:89) ~[na:na]
    at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.10-2.3.7.jar:2.3.7]
    at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.10-2.3.7.jar:2.3.7]
```

If I change `file("foo")` to `file(".")`, it works.

But this significantly limits what I can do. E.g. I want to have SBT project with a couple dozen projects that share code, including a few Play projects.

**Comment by jroper** [comment] 2015-01-09 00:20
Duplicate of #3484.

**Closed by jroper** 2015-01-09 00:20 UTC
