### ISSUE TITLE
Why Deprecated play.Configuration class ?

### ISSUE THREAD

**Issue by gitssie** [playframework/playframework#7981] opened 2017-11-02 09:26 UTC
I see the play.Configuration class was be @Deprecated，Use {@link Config} instead.

then how I use conf.getInt("ws.hystrix.poolsize",100) method?; let me make a tool class to do that?

because the typesafe Config class unsupported conf.getInt("xxxx",default) or conf.getString("xx",default)

**Comment by PromanSEW** [comment] 2017-11-02 09:57
All values must have defaults described in `application.conf`

**Comment by marcospereira** [comment] 2017-11-02 13:32
Hi @gitssie,

As @PromanSEW said, the idea is that you always declare some (default) value for your configuration, even if the value is `null`. This is [recommended by config](https://github.com/lightbend/config#how-to-handle-defaults) library. So Play moved to this style and, because of that, `play.Configuration` not only lose its value but also becomes against the recommendation. Then it was deprecated.

Moreover, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

I'm closing this since it is a by design change.

Thanks.

**Closed by marcospereira** 2017-11-02 13:32 UTC

**Comment by gitssie** [comment] 2017-11-07 09:45
Thanks
