### ISSUE TITLE
Update scalatest documentation

### ISSUE THREAD

**Issue by soren-schmidt** [playframework/playframework#5976] opened 2016-03-31 09:59 UTC
### API: Scala

Improvements for page https://www.playframework.com/documentation/2.5.x/ScalaTestingWithScalaTest:

1. Replace
"org.scalatestplus" %% "play" % "1.2.0" % "test",
by
"org.scalatestplus.play" %% "scalatestplus-play" % "1.5.0" % "test",
and remove the line:
"org.scalatest" %% "scalatest" % "2.2.1" % "test",
and adapt the text underneath

1. Also the versions page (http://www.scalatest.org/plus/play/versions) should be updated for 1.5.0.

1. Also explain better why on the one hand the documentation announces to use scalatest 3.0, which is not release yet... (https://playframework.com/documentation/2.5.x/Highlights25#ScalaTest-Improvements)
but in fact with the latest scalatestplus-play 1.5 you only use scalatest 2.2.6

1. Repair the link in: "Found an error in this documentation? The source code for this page can be found here. " (https://github.com/playframework/playframework/blob/2.5.x/documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithScalaTest.md returns a 404)

1. There are probably more updates to do that I don't see for the moment.

**Comment by marcospereira** [comment] 2016-03-31 15:22
Hello @soren-schmidt, 

1. This was solved by playframework/scalatestplus-play#43 and playframework/scalatestplus-play#47. Apparently, these changes did not make into 2.5.1 new docs.
2. It would be better to open an issue at https://github.com/scalatest/scalatest-website. See the [relevant page](https://github.com/scalatest/scalatest-website/blob/master/app/views/plus/playVersions.scala.html). Also related to playframework/scalatestplus-play#44 and #4613.
3. This is being solved by #5938.
4. This is a duplicate of #4781.

I will keep the issue open until we figure out what happen at point 1.

@gmethvin, can you help us here?

**Closed** 2016-05-10 00:42 UTC
Labels: documentation
