### ISSUE TITLE
Illegal header: Illegal 'user-agent'

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#7997] opened 2017-11-06 21:51 UTC
### Play Version (2.5.x / etc)
2.6.7

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
SMP Debian 4.4.6-1~bpo8+1 (2016-03-20) x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

### Expected Behavior
No warnings are shown

### Actual Behavior
I deployed fresh application seed into my server and I'm seeing hundrets of this warnings:
```
[warn] a.a.ActorSystemImpl - Illegal header: Illegal 'user-agent' header: Invalid input '[', expected 'EOI', product-or-comment, WSP, comment or CRLF (line 1, column 113): Moz
illa/5.0 (iPhone; CPU iPhone OS 11_0_3 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Mobile/15A432 [FBAN/FBIOS;FBAV/147.0.0.46.81;FBBV/76961488;FBDV/iPhone8,1;FBMD/iPhone;FBSN/iOS;FBSV/11.0.3;FBSS/2;FBCR/T-Mobile.pl;FBID/phone;FBLC/pl_PL;FBOP/5;FBRV/0]
```

```
[warn] a.a.ActorSystemImpl - Illegal header: Illegal 'user-agent' header: Invalid input '[', expected 'EOI', product-or-comment, WSP, comment or CRLF (line 1, column 159): Mozilla/5.0 (Linux; Android 7.0; TRT-LX1 Build/HUAWEITRT-LX1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/14
8.0.0.51.62;]
```
```
[warn] a.a.ActorSystemImpl - Illegal header: Illegal 'user-agent' header: Invalid input '[', expected 'EOI', product-or-comment, WSP, comment or CRLF (line 1, column 153): Moz
illa/5.0 (Linux; Android 7.0; SM-G955F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.84 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/
142.0.0.18.63;]
```

**Comment by gmethvin** [comment] 2017-11-06 22:36
It looks like this is https://github.com/akka/akka-http/issues/687

**Comment by gmethvin** [comment] 2017-11-06 22:49
One workaround here is to switch to the [Netty backend](https://www.playframework.com/documentation/latest/NettyServer).

**Comment by richdougherty** [comment] 2017-11-22 21:42
Tagged as 2.6.8 milestone because we should try and fix this on the 2.6.x branch.

**Comment by richdougherty** [comment] 2017-11-24 05:37
Akka HTTP apparently follows the format given here: https://tools.ietf.org/html/rfc7231#section-5.5.3. However the header format is marked as "SHOULD", not "MUST" in the RFC, so we should allow headers that don't follow that format.

**Comment by richdougherty** [comment] 2017-11-24 06:12
Added issue to track this upstream: https://github.com/akka/akka-http/issues/1550

**Comment by eximius313** [comment] 2018-01-20 14:32
https://github.com/akka/akka-http/issues/1550 seems to be fixed now

**Comment by Flo354** [comment] 2018-01-31 20:22
When can we expect a fix to be released with play?

**Comment by richdougherty** [comment] 2018-02-22 00:41
@Flo354 working on this now.

**Comment by marcospereira** [comment] 2018-04-06 19:55
@eximius313 @Flo354,

There is a fix for this issue on [Play 2.6.13](https://discuss.lightbend.com/t/play-2-6-13-released/629). Could you please try this new version and confirm it is working for you guys?

I'm closing it now, but if the fix doesn't work, we can reopen this issue with the additional information.

Thanks!

**Closed by marcospereira** 2018-04-06 19:55 UTC
Labels: bug, topic:upstream

**Comment by Flo354** [comment] 2018-04-07 14:29
thanks @marcospereira, seems to be working

**Comment by eximius313** [comment] 2018-04-08 16:36
@marcospereira this issue seems to be gone now, but now the logs are polluted with:
```
18:34:46.823 [application-akka.actor.default-dispatcher-9] [debug] akka.actor.RepointableActorRef - Aborting tcp connection to /127.0.0.1:31684 because of upstream failure: akka.http.impl.engine.HttpIdleTimeoutException: HTTP idle-timeout encountered, no bytes passed in the last 75000000000 nanoseconds. This is configurable by akka.http.[server|client].idle-timeout.
18:34:46.928 [application-akka.actor.default-dispatcher-9] [debug] akka.actor.RepointableActorRef - Aborting tcp connection to /127.0.0.1:31686 because of upstream failure: akka.http.impl.engine.HttpIdleTimeoutException: HTTP idle-timeout encountered, no bytes passed in the last 75000000000 nanoseconds. This is configurable by akka.http.[server|client].idle-timeout.
18:34:46.940 [application-akka.actor.default-dispatcher-9] [debug] akka.actor.RepointableActorRef - Aborting tcp connection to /127.0.0.1:31688 because of upstream failure: akka.http.impl.engine.HttpIdleTimeoutException: HTTP idle-timeout encountered, no bytes passed in the last 75000000000 nanoseconds. This is configurable by akka.http.[server|client].idle-timeout.
```
but I guess it's another issue...

**Comment by richdougherty** [comment] 2018-04-08 23:30
@eximius313, I wasn't able to reproduce on a simple test locally. Would you mind opening an issue for this and also explaining any reproduction steps? I note that this is `[debug]` level logging, so perhaps that's something that you have enabled in your application?

**Comment by richdougherty** [comment] 2018-04-11 00:53
@eximius313 would you mind taking a look at this discussion on the forum: https://discuss.lightbend.com/t/play-2-6-13-released/629/2? It appears that #8275 changed the loading behaviour of logback configuration files. There might be some migration needed for the 2.6.13 release and we're just working that out over on the forum.

**Comment by eximius313** [comment] 2018-04-11 10:04
@richdougherty 
1) I don't have `logback-test.xml`, just `logback.xml`
2) I enabled debug on `stage` intentionally - I wanted to know what is going on
3) I think, that [these](https://github.com/playframework/playframework/issues/7997#issuecomment-379563571) messages shouldn't appear in log, because it looks like some kind of bug
4) I'm running `stage` through `mod_rewrite`

My logback.xml:
```
<configuration>
	<conversionRule conversionWord="coloredLevel" converterClass="play.api.libs.logback.ColoredLevel" />

	<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
		<append>true</append>
		<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
			<level>WARN</level>
		</filter>
		<file>${APPLICATION_LOG_DIR:-logs}/application.log</file>
		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
			<fileNamePattern>${APPLICATION_LOG_DIR:-logs}/application.log-%d{yyyy-MM-dd}.gz</fileNamePattern>
			<maxHistory>30</maxHistory>
			<cleanHistoryOnStart>false</cleanHistoryOnStart>
		</rollingPolicy>
		<encoder>
			<pattern>%date{yyyy-MM-dd HH:mm:ss ZZZZ} [%level] from %logger in %thread - %message%n%xException</pattern>
		</encoder>
	</appender>

	<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%d{HH:mm:ss.SSS} [%-10thread] %-5coloredLevel %logger - %msg%n%xException</pattern>
		</encoder>
	</appender>
	<appender name="ASYNCFILE" class="ch.qos.logback.classic.AsyncAppender">
		<queueSize>500</queueSize>
		<discardingThreshold>0</discardingThreshold>
		<appender-ref ref="FILE" />
	</appender>

	<appender name="ASYNCSTDOUT" class="ch.qos.logback.classic.AsyncAppender">
		<queueSize>500</queueSize>
		<discardingThreshold>0</discardingThreshold>
		<appender-ref ref="STDOUT" />
	</appender>

	<root level="DEBUG">
		<if condition='isDefined("APPLICATION_TOKEN")'>
			<then>
				<appender-ref ref="ASYNCSTDOUT" />
				<appender-ref ref="ASYNCFILE" />
			</then>
			<else>
				<appender-ref ref="ASYNCSTDOUT" />
			</else>
		</if>
	</root>
</configuration>
```
My `apache.conf` file:
```
    ProxyPreserveHost On
    ProxyRequests Off

    ProxyPass                /               http://localhost:9000/  nocanon
    ProxyPassReverse    /               http://localhost:9000/
```

**Comment by richdougherty** [comment] 2018-04-12 02:56
An issue has been created to discuss this: https://github.com/playframework/playframework/issues/8361. Can you please try debugging the logging config loading and include the debug info that's logged, as shown here: https://discuss.lightbend.com/t/play-2-6-13-released/629/11.
