### ISSUE TITLE
java.util.NoSuchElementException: http-handler-body-subscriber exception with Play 2.5.3 and nginx

### ISSUE THREAD

**Issue by shkhln** [playframework/playframework#6151] opened 2016-05-12 18:52 UTC
### Are you looking for help?

*Absolutely not*. I've tried to report that issue to the mailing list, since there were already a dedicated [thread](https://groups.google.com/forum/#!topic/play-framework/9utj-Xtv8SU)… that was a dumb idea.

### Play Version (2.5.x / etc)

2.5.3

### API (Scala / Java / Neither / Both)

Neither

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

FreeBSD 10.2, Ubuntu 14.04

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

### Expected Behavior

No exception is thrown.

### Actual Behavior

With nginx set up according to the recommended config (https://www.playframework.com/documentation/2.5.x/HTTPServer#Set-up-with-nginx) once in a while the following exception is thrown:
```
[warn] i.n.u.c.DefaultPromise - An exception was thrown by com.typesafe.netty.HandlerSubscriber$3.operationComplete()
java.util.NoSuchElementException: http-handler-body-subscriber
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1093)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:432)
	at com.typesafe.netty.http.HttpStreamsHandler.completeBody(HttpStreamsHandler.java:294)
	at com.typesafe.netty.http.HttpStreamsHandler.access$400(HttpStreamsHandler.java:14)
	at com.typesafe.netty.http.HttpStreamsHandler$3$1.run(HttpStreamsHandler.java:276)
	at com.typesafe.netty.http.HttpStreamsHandler.executeInEventLoop(HttpStreamsHandler.java:331)
	at com.typesafe.netty.http.HttpStreamsHandler.access$300(HttpStreamsHandler.java:14)
	at com.typesafe.netty.http.HttpStreamsHandler$3.complete(HttpStreamsHandler.java:273)
	at com.typesafe.netty.HandlerSubscriber$3.operationComplete(HandlerSubscriber.java:244)
	at com.typesafe.netty.HandlerSubscriber$3.operationComplete(HandlerSubscriber.java:241)
```

### Reproducible Test Case

1. Take the following snippet:

  ```scala
  @Singleton
  class HomeController @Inject() extends Controller {

    val content = "##########".getBytes("UTF-8")
    val contentLength = content.length

    def index = Action {

      val stream = new java.io.ByteArrayInputStream(content)
      val source = StreamConverters.fromInputStream(() => stream)

      val result = Result(
        ResponseHeader(200),
        HttpEntity.Streamed(source, Some(contentLength), Some("text/plain"))
      )

      result
    }
  }
  ```

2. And run `wrk` benchmarking tool against it (i.e. simulate nginx with keepalive disabled):
 `wrk -H 'Connection: close' http://localhost:9000/`

**Comment by wsargent** [comment] 2016-05-12 19:04
This might be https://github.com/typesafehub/netty-reactive-streams or https://github.com/typesafehub/netty-http-pipelining

**Comment by wsargent** [comment] 2016-05-12 19:22
Seems to be linked to https://github.com/playframework/playframework/issues/5866 and https://github.com/playframework/playframework/issues/5883

**Comment by wsargent** [comment] 2016-05-12 21:23
@shkhln Seems like upgrading to Akka 2.4.4 should fix this https://github.com/playframework/playframework/issues/5883#issuecomment-196680893

**Comment by shkhln** [comment] 2016-05-12 21:38
I pretty sure that's a different bug.

**Comment by gmethvin** [comment] 2016-05-12 23:17
@wsargent @shkhln It may well be an akka streams bug similar to akka/akka#20031. Maybe something else is calling `onComplete` twice. I suspect it may be related to the `RangeResult` changes.

**Comment by francisdb** [comment] 2016-05-13 08:58
I can confirm this issue, since we upgraded to play 2.5.3 we are seeing these about 60 times a day.

**Comment by shkhln** [comment] 2016-05-17 01:41
I did investigate this issue a bit further with the help of [this](https://gist.github.com/shkhln/9ac4999dcdad23f44ffc66ae01776353) Btrace script.

`wrk -c 1 -t 1 -H "Connection: close"`, typical request-response cycle:
 ```
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelRead
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelRegistered
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelActive
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelRead
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete
netty-event-loop-2 com.typesafe.netty.http.HttpStreamsHandler.unbufferedWrite: ctx = io.netty.channel.DefaultChannelHandlerContext@608571cc
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.addAfter0: newCtx = io.netty.channel.DefaultChannelHandlerContext@66502076
netty-event-loop-2 com.typesafe.netty.http.HttpStreamsHandler.completeBody:    ctx = io.netty.channel.DefaultChannelHandlerContext@608571cc
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@66502076
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelInactive
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@6489836
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@608571cc
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@2602a85e
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@6d42b643
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@a76780d
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelRead
netty-event-loop-2 io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete
```

`wrk -c 1 -t 1 -H "Connection: close"`, not so typical request-response cycle:
```
netty-event-loop-5 com.typesafe.netty.http.HttpStreamsHandler.unbufferedWrite: ctx = io.netty.channel.DefaultChannelHandlerContext@395ed596
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.addAfter0: newCtx = io.netty.channel.DefaultChannelHandlerContext@de2f220
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.fireChannelInactive
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered
[This is not supposed to happen]
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@5e384c7b
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@de2f220
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@395ed596
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@4451c66e
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@7939c0a2
netty-event-loop-5 io.netty.channel.DefaultChannelPipeline.remove0:      ctx = io.netty.channel.DefaultChannelHandlerContext@464e9e24
netty-event-loop-5 com.typesafe.netty.http.HttpStreamsHandler.completeBody:    ctx = io.netty.channel.DefaultChannelHandlerContext@395ed596
```
What are assumptions in netty-reactive-streams regarding pipeline teardown? Does it rely on any specific order of events?

**Comment by schmitch** [comment] 2016-05-17 14:51
actually an easy way would be to check if the http-handler-body-subscriber exists inside the ctx pipeline. I mean this error won't actually do any harm

**Comment by gmethvin** [comment] 2016-05-18 18:01
@schmitch I'm not that familiar with the netty-reactive-streams code, but perhaps we should just check if it exists before removing. It doesn't seem like the issue being warned about is harmful at all, just unexpected by the original author. It kind of bothers me to do that though because this warning helped us find akka/akka#20031.

**Comment by schmitch** [comment] 2016-05-18 20:13
@gmethvin since it relies on typesafe config we could easily add a configuration option for it.

**Comment by shkhln** [comment] 2016-05-18 23:49
> assumptions

Normally [unbufferedWrite](https://github.com/typesafehub/netty-reactive-streams/blob/58006dd2e2f3cc20dc38a4601fd0fd11de9c43ef/netty-reactive-streams-http/src/main/java/com/typesafe/netty/http/HttpStreamsHandler.java#L287) registers `body-subscriber`, [completeBody](https://github.com/typesafehub/netty-reactive-streams/blob/58006dd2e2f3cc20dc38a4601fd0fd11de9c43ef/netty-reactive-streams-http/src/main/java/com/typesafe/netty/http/HttpStreamsHandler.java#L294) removes `body-subscriber`, and the channel is  closed after that at [sentOutMessage](https://github.com/typesafehub/netty-reactive-streams/blob/58006dd2e2f3cc20dc38a4601fd0fd11de9c43ef/netty-reactive-streams-http/src/main/java/com/typesafe/netty/http/HttpStreamsServerHandler.java#L114).

> since this is a race condition i think its hard to find

When the channel is closed [here](http://netty.io/4.0/xref/io/netty/channel/nio/AbstractNioByteChannel.html#157), Netty [schedules](http://netty.io/4.0/xref/io/netty/channel/AbstractChannel.html#535) `channelInactive` event, which eventually will call `DefaultChannelPipeline.destroy` and that will remove all the handlers from the pipeline including `body-subscriber`. If that happens before `completeBody` is called, then we get an exception.

**Comment by jroper** [comment] 2016-05-24 04:39
I've created #16 with an alternate solution, I think @shkhln is correct, and this is in particular encountered with nginx since nginx is very eagerly closing the connection when it receives the full response, before the netty-reactive-streams clean up on the channel subscriber is triggered.

At any rate, this bug is benign, just noisy in the logs.

**Comment by schmitch** [comment] 2016-05-29 13:26
this could be closed since its fixed in [master](https://github.com/playframework/playframework/commit/e4154cc174c335667040c66e52bb792ef88a293b) and [2.5.x](https://github.com/playframework/playframework/commit/75aada0ad2bef0ce61df9d5b008b7fe267910061)

**Closed** 2016-05-30 04:45 UTC
