### ISSUE TITLE
Behaviour of the ForwardedHeaderHandler with X-Forwarded-For

### ISSUE THREAD

**Issue by fredoche** [playframework/playframework#4906] opened 2015-07-29 11:41 UTC
I have an issue wth the behaviour of ForwardedHeaderHandler with X-Forwarded-For .
According to the spec, the leftmost value of the header is the original source ip.
`X-Forwarded-For: client, proxy1, proxy2` (source wikipedia)

However, I noticed that when every proxy is trusted, play reports the host address as the remote address when it should really use the header leftmost value.
It creates problems, for example, in my case, when play runs inside a container, where relying on forwarded-for always gives a useless ip.

**Comment by richdougherty** [comment] 2015-07-30 01:15
Can you please proide some debugging information? You can obfuscate the IP addresses if you like.

Suggested information:
* information about which Play version you're using
* `X-Forwarded-For` and `X-Forwarded-Proto` header values
* values for the `remoteAddress` and `secure` properties of the request
* snippet of the code where you're dumping the header values and request properties so we can check which calls you make
* explanations about which IP addresses correspond to the host, proxy, browser, etc
* configuration values

**Comment by jdauphant** [comment] 2015-07-30 08:45
Hello,
We use Play 2.4.2 .

# Example with unexpected value (case described in the issue)
- In application.conf :
```
play.http.forwarded.trustedProxies=["0.0.0.0/0"]
```

- Request Header (send from 172.2.3.4) : 
```
X-Forwarded-For: 65.78.45.55, 52.67.67.55
```

- Result : 
```
remoteAddress = 172.2.3.4 (we expected 65.78.45.55)
```

# Example with expected value 
- In application.conf :
```
play.http.forwarded.trustedProxies=["172.0.0.0/8"]
```

- Request (send from 172.2.3.4) : 
```
X-Forwarded-For: 65.78.45.55, 52.67.67.55
```

- Result : 
```
remoteAddress = 52.67.67.55 (attending behavior)
```

This example come from an elastic beanstalk usecase : 172.2.3.4 is a docker host ip, 52.67.67.55 is an amazon elastic load balancer.
After looking into the play source, in the first example remoteAddress is 172.2.3.4 instead of 65.78.45.55 because 65.78.45.55 is on the trusted subnet (0.0.0.0/0).

**Comment by jroper** [comment] 2015-08-03 06:31
Good catch.

**Comment by mkurz** [comment] 2016-03-11 10:01
Is this still an issue with Play 2.5?

**Comment by martinpallmann** [comment] 2016-05-23 12:11
So basically if all X-Forwarded-For IPs are in the trusted subnet, instead of returning the 'real' client IP it should return the leftmost X-Forwarded-For IP?

Is this the intended behaviour?

**Comment by martinpallmann** [comment] 2016-05-23 15:17
seems to be fixed in master

**Comment by martinpallmann** [comment] 2016-05-23 15:54
seems to be ok. I did two tests here: https://github.com/martinpallmann/playframework/tree/issue-4906

**Comment by mkurz** [comment] 2016-05-23 22:30
@martinpallmann Could you please provide a pull request with your tests?

**Comment by adis-me** [comment] 2016-05-24 08:04
How should this be tested correctly? My test setup:

- Play running on 127.0.0.1:9000 (assigned internal IP adres: 15.0.8.15), with nginx running in front on port 8090
- In my HomeController I log the IP:
    Logger.debug(request().host());

When I connect from another computer (ip 15.0.8.30), on the same network I would still see the following output:

    [debug] application - 15.0.8.15:8090

I have configured my nginx just like the provided example: https://www.playframework.com/documentation/2.5.x/HTTPServer#Set-up-with-nginx

- I am not using HTTPS locally

**Comment by schmitch** [comment] 2016-05-24 08:09
@adis-me could you try to adding a `proxy_set_header        X-Real-IP $remote_addr;`?

**Comment by adis-me** [comment] 2016-05-24 08:14
This is my nginx configuration (partly):

```
location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_buffering    off;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Scheme $scheme;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host $http_host;
    proxy_pass http://my-backend;
 }
```
What I do **not** have is a `trustedProxies` key in my application.conf. But I did not find any documentation about this setting. Although when I try with `play.http.forwarded.trustedProxies=["0.0.0.0/0"]` it gives the same output..

**Comment by schmitch** [comment] 2016-05-24 08:14
@adis-me unfortunatly it's `request().remoteAddress()` not `request().host()`

**Comment by adis-me** [comment] 2016-05-24 08:17
@schmitch Yes, sorry my bad! Then I can confirm too, that this problem is not occurring with 2.5.3. Thanks for your help!

**Comment by martinpallmann** [comment] 2016-05-24 10:08
I created a pull request: https://github.com/playframework/playframework/pull/6186
Strangely it is not linked here.

**Comment by martinpallmann** [comment] 2016-05-25 11:28
@gmethvin this issue can be closed then?

**Comment by mkurz** [comment] 2016-11-18 07:41
I think this can be closed now.

**Closed by mkurz** 2016-11-18 07:41 UTC
Labels: community, defect
