### ISSUE TITLE
No way to set the Object mapper used by Play (2.4) when parsing request body

### ISSUE THREAD

**Issue by maxkremer** [playframework/playframework#5472] opened 2016-01-18 23:38 UTC
This is related to #4897 

The documentation says you can configure the object mapper used by Play however this is not entirely true.
If in your controller you do 
`request().body().asJson()`
 play.libs.Json is not used. Its seems Play uses it's internal ObjectMapper in this case.

**Comment by gmethvin** [comment] 2016-01-19 07:31
This issue in Play Java is fixed in Play 2.5, but as the result of a lot of refactoring. The problem is that the `asJson` method took the body read as Scala `JsValue` and then converted that to `JsonNode`. That was both inefficient and prevented a lot of Jackson configuration from working.

I'm not sure how easy it would be to backport or create another fix for 2.4

**Comment by mkurz** [comment] 2016-02-17 15:31
@gmethvin Will this fix #4763 for Play 2.5 as well?

**Comment by gmethvin** [comment] 2016-02-18 05:29
@mkurz Well, #4763 is fixed now but I don't think it's related to this bug.

**Comment by marcospereira** [comment] 2016-03-15 04:40
@gmethvin I think we can close this issue, right?

**Closed** 2016-03-15 06:02 UTC
