### ISSUE TITLE
Project not loaded properly: java.lang.NoClassDefFoundError: play/Play$

### ISSUE THREAD

**Issue by schwannden** [playframework/playframework#4595] opened 2015-06-02 10:16 UTC
I downloaded activator, use activator ui to setup and download this project, and the following happened

[Loading] Scanning directory /home/schwannden/Downloads/play-scala-intro
[Loading] Found root project root w/ remaining 
play/Play$
java.lang.NoClassDefFoundError: play/Play$
Use 'last' for the full log.
> load-failed
Failed to load project.
> server-wait-for-reboot

**Comment by mkurz** [comment] 2015-06-02 10:37
There is a discussion in the mailing list too:
https://groups.google.com/forum/?fromgroups#!topic/play-framework/_devPRu0rLg

**Comment by jamesward** [comment] 2015-06-02 19:29
Same here.

**Comment by jamesward** [comment] 2015-06-02 19:32
Duplicate of: https://github.com/playframework/playframework/issues/4563

**Comment by cchantep** [comment] 2015-06-02 21:01
Thanks @jamesward . Fix to be attached to #4595 .

**Closed by cchantep** 2015-06-02 21:01 UTC

**Comment by schwannden** [comment] 2015-06-03 02:21
Thanks all!
