### ISSUE TITLE
[2.3.3] No logging with "activator dist"

### ISSUE THREAD

**Issue by slimandslam** [playframework/playframework#3308] opened 2014-08-18 19:27 UTC
Using Java 7 with Play 2.3.3, logging does not work when play is
bundled with the "activator dist" directive.  

With an application-logger.xml file located in conf/application-logger.xml
no application.log or access.log files are created even when set up 
as described here, using the sample application-logger.xml file:

https://www.playframework.com/documentation/2.3.x/SettingsLogger

**Comment by neonal** [comment] 2015-04-01 14:19
In my experience, application reads logger.xml file (It writes logs to console output as I configured). I think the problem is with ${application.home} and ${user.dir} parameters. If my rolling configuration uses either of those (e.g.: `<file>${application.home}/logs/application.log</file>`), it doesn't write logs to file. However if I specify log output as absolute path (e.g.: `<file>/home/user/app/logs/application.log</file>`), it writes logs to files successfully.

**Comment by wsargent** [comment] 2016-03-19 01:54
Closing -- this is not reproducible.

**Closed by wsargent** 2016-03-19 01:54 UTC
Labels: needs-verification
