### ISSUE TITLE
Need to update activator.bat in play activator.

### ISSUE THREAD

**Issue by engrjislam** [playframework/playframework#6700] opened 2016-11-04 09:04 UTC
### Need to update activator.bat in play activator.

activator.bat file includes two wrong declarations [activator version 1.3.12]- 
1. set SBT_HOME=%BIN_DIRECTORY%
2. set FN=%BIN_DIRECTORY%\..\conf\sbtconfig.txt

### Play Version (2.5.x / etc)

2.5.9

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10.

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle 1.8.0_112.

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. set SBT_HOME=%BIN_DIRECTORY% should return the **sbt home** directory like as **C:\sbt**
2. FN=%BIN_DIRECTORY%\..\conf\sbtconfig.txt should return full path of sbtconfig.txt like as **C:\sbt\conf\sbtconfig.txt**

### Actual Behavior

1. set SBT_HOME=%BIN_DIRECTORY% returns **activator's bin path** [like C:\activator\bin] but it should return **sbt's home** as -
set SBT_HOME=%SBT_HOME% 

2. set FN=%BIN_DIRECTORY%\..\conf\sbtconfig.txt returns misleading path [like **C:\activator\bin\\..\conf\sbtconfig.txt** but it should be **C:\sbt\conf\sbtconfig.txt** not the activator path]. So it must be -
set FN=%SBT_HOME%\conf\sbtconfig.txt

**Comment by gmethvin** [comment] 2016-11-05 02:28
I'm not sure if this would be a considered a bug in activator or SBT, but it's definitely not a bug in Play, so I'm closing. I'd suggest starting a discussion on the Play mailing list.

**Closed by gmethvin** 2016-11-05 02:28 UTC
