### ISSUE TITLE
Validation Error on Transient Field present in Model class while binding the request to create form

### ISSUE THREAD

**Issue by abhishek-soam-2** [playframework/playframework#11018] opened 2021-11-19 08:44 UTC
### Play Version

Play version is: 2.5.2

### API

Java

### Operating System

Linux sc191user-ThinkPad-T14-Gen-1 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

### Expected Behavior
Declared a Transient Field inside Model class with `@Transient` Annotation. 
Using FormFactory to bind the request with the model class in this manner. 

`Form<SmsPattern> smsPatternForm = mFormFactory.form(mModelClass).bindFromRequest();` 

1. It should be able to validate the Form Data.

### Actual Behavior

1. It raises a ValidationError on the Transient Field.

**Comment by PromanSEW** [comment] 2021-12-07 18:41
Play 2.5.x is not supported for a long time

**Comment by mkurz** [comment] 2021-12-12 05:59
Play does not and never did support any `@Transient` annotation on form fields. I guess you (re-)used a JPA model as form "model"? You probably want to use a separate class to be used as a form.

**Comment by mkurz** [comment] 2021-12-19 23:37
@abhishek-soam-2  I am closing this, because IMHO this is not a bug in Play. If you have questions, please let me now.

**Closed by mkurz** 2021-12-19 23:37 UTC
