### ISSUE TITLE
[2.5.0 Java] Http.Context.changeLang and Http.Context.setTransientLang does not work in ActionCreator

### ISSUE THREAD

**Issue by franzgranlund** [playframework/playframework#5875] opened 2016-03-14 12:27 UTC
In 2.4 we used to change the context language using `Http.Context.changeLang()` in `HttpRequestHandler` depending on the URL. 

With 2.5 we migrated to ActionCreator, but it seems like `changeLang()` (nor `setTransietLang()`) doesn't work for some reason. `changeLang()` seems to set a new cookie, but the current request doesn't see that.

I have created a sample project here: https://github.com/franzgranlund/play25

ActionCreator: https://github.com/franzgranlund/play25/blob/master/app/ActionCreator.java
HomeController: https://github.com/franzgranlund/play25/blob/master/app/controllers/HomeController.java

Also, it seems like `setTransientLang()` does not work in the controller either.

I also tried with the setting `play.http.actionComposition.executeActionCreatorActionFirst = true` and it didn't make any difference.

**Comment by adis-me** [comment] 2016-03-14 13:34
Is this a confirmed bug? Because I use `changeLang` with 2.5 within a Controller and it works fine, just like in 2.4.6.

If this is not a confirmed bug it should be discussed in the [Play Group](https://groups.google.com/forum/#!forum/play-framework) prior to posting here.

**Comment by mkurz** [comment] 2016-03-14 14:06
I found out what's the problem here. It has nothing to do with the ActionCreator.

`changeLang()` and `setTransientLang()` both set the `lang` variable (see [here](https://github.com/playframework/playframework/blob/2.5.0/framework/src/play/src/main/java/play/mvc/Http.java#L211) and [here](https://github.com/playframework/playframework/blob/2.5.0/framework/src/play/src/main/java/play/mvc/Http.java#L257)) inside the current context. The problem is `ctx().messages()`, which itself [calls](https://github.com/playframework/playframework/blob/2.5.0/framework/src/play/src/main/java/play/mvc/Http.java#L190) `messagesApi().preferred(request())` only [uses the cookie of the request](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L484) to determine the current language. But we didn't change the cookie, only we set the `lang` variable.

IMHO that's a bug in Play, because `ctx().messages()` [says](https://github.com/playframework/playframework/blob/2.5.0/framework/src/play/src/main/java/play/mvc/Http.java#L187) it `returns the messages for the current lang` but that isn't true. It just uses the request, but doesn't care about the `lang` variable, which could be altered be `changeLang()` or `setTransientLang()`.

**Comment by mkurz** [comment] 2016-03-14 14:08
Here is a pull request with a fix: #5876

**Comment by mkurz** [comment] 2016-03-14 14:16
@franzgranlund For now you can use [this workaround](https://github.com/mkurz/play25/commit/46b9dad9ab7f569036b69603a0818d97a582e8a6) until my PR gets merged into 2.5.x.

**Comment by franzgranlund** [comment] 2016-03-14 17:24
@mkurz Thanks! :-)

**Closed** 2016-03-16 20:23 UTC
Labels: has-pr
