### ISSUE TITLE
[Play 2.4 Java]  Connection pool is not closed between tests when using WithApplication

### ISSUE THREAD

**Issue by michalzubkowicz** [playframework/playframework#4838] opened 2015-07-12 14:51 UTC
When I extend class WithApplication connection pool is only created, but not closed between tests which causes "Too many connections error" 
In logs there is only:
[info] p.a.d.HikariCPConnectionPool - datasource [default] bound to JNDI as DefaultDS
application - Creating Pool for datasource 'default'
but I cannot see anywhere
[info] application - Shutting down connection pool.

**Comment by archie-sh** [comment] 2015-10-02 08:38
+1

**Comment by marcospereira** [comment] 2016-02-20 01:17
I think we need to inject a `ApplicationLifecycle` into pool implementations so they can register shutdown hooks.

**Comment by marcospereira** [comment] 2016-02-20 01:36
Or even better, some steps above at the DBModule.

**Comment by mkurz** [comment] 2016-03-11 10:26
@marcospereira Do you think you could provide an PR if you have an idea how to fix it? I would be happy to review.

**Comment by marcospereira** [comment] 2016-03-12 05:34
@mkurz I will submit a PR as soon a possible. I have other changes that are in progress and as soon as they get merged, I will take care of this. :-)

**Comment by mkurz** [comment] 2016-03-12 11:43
@marcospereira :+1:

**Comment by marcospereira** [comment] 2016-03-13 22:20
So, I was not able to reproduce the problem and the solution I was proposing is already there: 

https://github.com/marcospereira/playframework/blob/58a150d/framework/src/play-jdbc/src/main/scala/play/api/db/DBModule.scala#L71-L71

Here is how I've testd it:

* Create a new Java application using `activator new myapp play-java`
* Configure it to use an database and also to bind the data source do JNDI:
```
db {
  default.driver = org.h2.Driver
  default.url = "jdbc:h2:mem:play"
  default.username = sa
  default.password = ""
  default.jndiName=DefaultDS
}
```
* Writing and executing the following test using `WithApplication`:
```java
import org.junit.Test;
import play.db.DBApi;
import play.db.Database;
import play.test.WithApplication;

import java.sql.ResultSet;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class ApplicationTest extends WithApplication {

    @Test
    public void test1() {
        DBApi db = app.injector().instanceOf(DBApi.class);
        Database database = db.getDatabase("default");
        database.withConnection(connection -> {
            ResultSet rs = connection.createStatement().executeQuery("SELECT 1");
            rs.next();
            assertEquals(rs.getLong(1), 1);
        });
        assertTrue(app.isTest());
    }
}
```

With this setup, I'm getting the following logs:

```
[info] application - Creating Pool for datasource 'default'
[info] p.a.d.HikariCPConnectionPool - datasource [default] bound to JNDI as DefaultDS
[info] application - ApplicationTimer demo: Starting application at 2016-03-13T22:11:54.695Z
[info] application - ApplicationTimer demo: Stopping application at 2016-03-13T22:11:55.056Z after 1s.
[info] application - Shutting down connection pool.
```

@mkurz, @michalzubkowicz and @archie-sh could you please provide a application showing this problem?

**Comment by michalzubkowicz** [comment] 2016-03-14 16:18
I can confirm that in version 2.5.0 it seems to be fixed.

**Comment by mkurz** [comment] 2016-03-14 16:21
Good. Closing. Feel free to open another issue in case you run into problems again.

**Closed by mkurz** 2016-03-14 16:21 UTC
Labels: community, defect, newbie
