### ISSUE TITLE
Unneccesary second compilation in dev mode. 

### ISSUE THREAD

**Issue by sheavner** [playframework/playframework#3954] opened 2015-02-21 08:54 UTC
I've got a launcher script that runs 'activator compile' then 'activator run' back to back.   But on the first page load, it goes out and recompiles all the code which I just compiled.    

This second compile should not be performed.  There has just been a complete compile and nothing was changed.

play 2.3.7 | sbt 0.13.7 | scala 2.10.4 

```
activator compile
[info] Loading project definition from /Users/sdh/olset/olset-traveler/project
[info] Set current project to traveler-profile (in build file:/Users/sdh/olset/olset-traveler/)
[info] Compiling 42 Scala sources and 379 Java sources to /Users/sdh/olset/olset-traveler/target/scala-2.10/classes...
[success] Total time: 89 s, completed Feb 20, 2015 11:08:50 AM

activator -Dlogback.configurationFile=conf/dev-application-logger.xml -Dapplication.build=1  'run 9000'
[info] Loading project definition from /Users/sdh/olset/olset-traveler/project
[info] Set current project to traveler-profile (in build file:/Users/sdh/olset/olset-traveler/)

--- (Running the application, auto-reloading is enabled) ---


(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 4 Java sources to /Users/sdh/olset/olset-traveler/target/scala-2.10/classes...
[info] Compiling 2 Scala sources and 42 Java sources to /Users/sdh/olset/olset-traveler/target/scala-2.10/classes...
[info] Compiling 4 Scala sources and 21 Java sources to /Users/sdh/olset/olset-traveler/target/scala-2.10/classes...
[info] Compiling 42 Scala sources and 379 Java sources to /Users/sdh/olset/olset-traveler/target/scala-2.10/classes...
[info] Compiling 4 Java sources to /Users/sdh/olset/olset-traveler/target/scala-2.10/classes...
[info] Compiling 42 Java sources to /Users/sdh/olset/olset-traveler/target/scala-2.10/classes...
```

**Comment by jroper** [comment] 2015-02-23 01:35
@sheavner What happens if you run `activator compile` twice?  If that results in the same behaviour, then this isn't a Play problem, it's an incremental compilation problem in your project, possibly because you are generating source files on every compile, rather than only generating them when something has changed.

**Comment by benmccann** [comment] 2015-03-13 15:57
@sheavner we'd love more info on this. otherwise i'm afraid we'll have to close the issue as non-responsive

**Comment by benmccann** [comment] 2015-03-17 23:54
@sheavner do you think you'll be able to get back to this with more info?

**Comment by myrosia** [comment] 2015-03-27 18:09
I am a different user but I am experiencing a similar problem with recompilation after "run". Running "compile" twice indeed causes more compilation as well. But I have pretty standard build.sbt, based on the Play template (as below), so I am not sure what the problem might be.

build.sbt
```
name := "idealwebapp"

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.1"

libraryDependencies ++= Seq(
  javaJdbc,
  javaEbean,
  cache,
  javaWs,
  "mysql" % "mysql-connector-java" % "5.1.+",
  "org.perf4j" % "perf4j" % "0.9.+",
  "com.novocode" % "junit-interface" % "0.9" % "test"
)

javacOptions ++= Seq("-encoding", "utf8", "-g", "-Xlint:unchecked")

PlayKeys.routesImport += "binders._"

PlayKeys.routesImport += "binders.Conversions._"

includeFilter in (Assets, LessKeys.less) := "main.less" | "bootstrap-custom.less"

pipelineStages := Seq(digest, gzip)
```

Compilation
[idealwebapp] $ compile
[info] Compiling 37 Scala sources and 63 Java sources to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[success] Total time: 13 s, completed 27 бер 2015 18:01:29
[idealwebapp] $ compile
[info] Compiling 4 Java sources to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[success] Total time: 2 s, completed 27 бер 2015 18:01:33

**Comment by jroper** [comment] 2015-03-30 01:17
@myrosia After running `compile` the second time, could you run `last`?  This will have an analysis of what changed and why it recompiled those files.

Are you running an IDE concurrently to doing this test?  If so, shut down the IDE, and see if the problem remains.

What filesystem are you running on?  The `/afs` prefix looks like it might be a network filesystem.  Could you try running on a local filesystem and see if the problem persists?

**Comment by myrosia** [comment] 2015-03-30 12:01
Here is an example of 2 compiles followed by `last`. I was editing in Eclipse at the time. Closed eclipse, attempted to recompile - problem persisted. Running  "clean", and then compile solved the problem - unnecessary recompilation stopped. I also tried editing the same file in Emacs that I was editing in Eclipse, and recompiling. So I am guessing that Eclipse is indeed the problem.

I am on AFS, so networked file system, too. I can try doing it on my local drive if you think it's worthwhile at this point, but it seems to be that it's the eclipse issue.

```
$ compile
[info] Compiling 1 Java source to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[success] Total time: 2 s, completed 30 бер 2015 12:52:40
[idealwebapp] $ compile
[info] Compiling 1 Java source to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[success] Total time: 2 s, completed 30 бер 2015 12:52:44
[idealwebapp] $ last
[debug] Invalidating /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes/controllers/LoggingContext$TipIDJsonModule.class: stamp changed from lastModified(1427710786000) to lastModified(1427716359000)
[debug]
[debug] Initial source changes:
[debug]         removed:Set()
[debug]         added: Set()
[debug]         modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set(/afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes/controllers/LoggingContext$TipIDJsonModule.class)
[debug] Initial directly invalidated sources: Set()
[debug]
[debug] Sources indirectly invalidated by:
[debug]         product: Set()
[debug]         binary dep: Set(/afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/app/controllers/LoggingContext.java)
[debug]         external source: Set()
[debug] All initially invalidated sources: Set(/afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/app/controllers/LoggingContext.java)
[info] Compiling 1 Java source to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[debug] Attempting to call javac directly...
[debug] com.sun.tools.javac.Main not found with appropriate method signature; forking javac instead
[debug] Forking javac: javac @/tmp/sbt_f3f62549/argfile
[debug] javac returned exit code: 0
[debug] Java compilation took 1.108137692 s
[debug] Java analysis took 0.116285105 s
[debug] New invalidations:
[debug]         Set()
[debug] Initial set of included nodes: Set()
[debug] Previously invalidated, but (transitively) depend on new invalidations:
[debug]         Set()
[debug] All newly invalidated sources after taking into account (previously) recompiled sources:Set()
[success] Total time: 2 s, completed 30 бер 2015 12:52:44
```

**Comment by jroper** [comment] 2015-03-31 02:39
How are you loading the project in Eclipse?  I think (need to confirm) we tell Eclipse to use a different output directory to the one sbt uses, because if it uses the same, you end up with the sbt scala compiler and the Eclipse scala compiler running concurrently outputting the same classes, which is what causes many of these problems.

**Comment by benmccann** [comment] 2015-03-31 03:51
The Eclipse is fixed in sbteclipse 3.0.0 which is used by the latest versions of Play. I'm not sure what 2.3.7 is using, but I would recommend using 2.3.8 to be safe since I know the issue is fixed there.

**Comment by myrosia** [comment] 2015-04-01 11:42
I was using the standard .project file generated by `activator eclipse`. It outputs to `target/scala-2.11/classes`. I don't quite have enough sbt knowledge to figure out what version of sbteclipse is getting used, but I will upgrade to 2.3.8 and re-test to see if this solves the problem.

**Comment by benmccann** [comment] 2015-04-01 16:55
@myrosia the fixed version should output to a `bin/` directory. if you have that directory then you're good. if it's going to `target/scala-2.11/classes` then you have an old broken version

**Comment by myrosia** [comment] 2015-04-02 16:13
I updated to 2.3.8, and then it started causing real problems, because it does not output to bin. Where should I open an issue for that? My generated eclipse file contains
```
  <classpathentry kind="src" path="app" output="target/scala-2.11/classes"/>
  <classpathentry kind="src" path="test" output="target/scala-2.11/test-classes"/>
  <classpathentry kind="output" path="bin"/>
```
Which then causes seriously confusing and problematic errors (e.g., class not found during compilation if this accidentally happens while Eclipse is compiling as well). This wasn't happening in 2.3.7, so it is a regression for me.

**Comment by benmccann** [comment] 2015-04-02 16:23
@myrosia your .classpath file is wrong. I'm not sure where that's coming from. You should have this for app:

    <classpathentry kind="src" path="app"/>

Make sure you're not including sbteclipse yourself in project/plugins.sbt. Then delete all your eclipse files and run the eclipse command again to generate a new set

**Comment by myrosia** [comment] 2015-04-02 16:30
That's what I meant - the automatically generated file is wrong in 2.3.8. I generated it exactly as you described, and then it included the incorrect lines quoted above. Here are the commands I run to get it:

```
> rm .classpath .project
> activator eclipse
[info] Loading project definition from /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/project
[info] Set current project to idealwebapp (in build file:/afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/)
[info] About to create Eclipse project files for your project(s).
[info] Compiling 1 Scala source and 7 Java sources to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[info] Compiling 12 Scala sources and 16 Java sources to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[info] Compiling 18 Scala sources and 32 Java sources to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[info] Compiling 38 Scala sources and 63 Java sources to /afs/inf.ed.ac.uk/user/m/mdzikovs/research/ideal/software/gui/idealwebapp/target/scala-2.11/classes...
[info] Successfully created Eclipse project files for project(s):
[info] idealwebapp
``` 

My plugins.sbt does not include sbteclipse:
```

// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.3")

addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.1")

// Javascript handling as recommended by 2.3 migration
addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.0")

// To support mocha, an asynchronous javascript testing framework
addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.0.0")
~

```

**Comment by benmccann** [comment] 2015-04-02 16:36
@myrosia you're using Play 2.3.3. not Play 2.3.8. that's your problem

    addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.3")

also, this line is insecure. you should use https:

    resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

**Comment by myrosia** [comment] 2015-04-02 16:41
Ahh, I see, sorry. I was clearly confused about how to go on to upgrade play version, I thought just downloading the new one from Play website did it. I'll fix this and re-test the original problem.

**Comment by myrosia** [comment] 2015-04-02 16:54
OK, yes, with the correct upgrade to 2.3.8 my second recompilation problem is resolved.

**Comment by benmccann** [comment] 2015-04-02 16:58
Great! Glad we could get this fixed for you

**Closed by benmccann** 2015-04-02 16:58 UTC
