### ISSUE TITLE
java.lang.UnsatisfiedLinkError on Apple M1 with Play 2.8.8

### ISSUE THREAD

**Issue by giannoug** [playframework/playframework#10867] opened 2021-05-21 09:07 UTC
### Play Version

```
$ cat project/plugins.sbt
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.8")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.11.0")
```

### API

```
$ cat build.sbt
name := """play-scala-seed"""
organization := "com.example"

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.13.6"

libraryDependencies += guice
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "5.0.0" % Test

// Adds additional packages into Twirl
//TwirlKeys.templateImports += "com.example.controllers._"

// Adds additional packages into conf/routes
// play.sbt.routes.RoutesKeys.routesImport += "com.example.binders._"
```

### Operating System

```
$ uname -a
Darwin redacted.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64
```

### JDK

```
$ java --version
openjdk 11.0.10 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)
```

### Library Dependencies

None at all, project is freshly scaffolded with `sbt new playframework/play-scala-seed.g8`

### Expected Behavior

1. Bootstrap new Play application on an Apple M1 machine
2. After finishing, start the application
3. The application should start and be accessible on localhost:9000 and serve the welcome page

### Actual Behavior

1. Bootstraping works fine and finishes without any error
2. Running the application with `sbt run` crashes with the following exception:

```
[error] java.lang.UnsatisfiedLinkError: /Users/user/Library/Caches/JNA/temp/jna648037593543371482.tmp: dlopen(/Users/user/Library/Caches/JNA/temp/jna648037593543371482.tmp, 1): no suitable image found.  Did find:
[error] 	/Users/user/Library/Caches/JNA/temp/jna648037593543371482.tmp: no matching architecture in universal wrapper
[error] 	/Users/user/Library/Caches/JNA/temp/jna648037593543371482.tmp: no matching architecture in universal wrapper
[error] 	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
[error] 	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
[error] 	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
[error] 	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
[error] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
[error] 	at java.base/java.lang.Runtime.load0(Runtime.java:768)
[error] 	at java.base/java.lang.System.load(System.java:1837)
[error] 	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
[error] 	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
[error] 	at com.sun.jna.Native.<clinit>(Native.java:195)
[error] 	at io.methvin.watchservice.jna.CarbonAPI.<clinit>(CarbonAPI.java:20)
[error] 	at io.methvin.watchservice.jna.CFStringRef.toCFString(CFStringRef.java:23)
[error] 	at io.methvin.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:127)
[error] 	at io.methvin.watchservice.WatchablePath.register(WatchablePath.java:50)
[error] 	at io.methvin.watcher.DirectoryWatcher.register(DirectoryWatcher.java:400)
[error] 	at io.methvin.watcher.DirectoryWatcher.registerAll(DirectoryWatcher.java:373)
[error] 	at io.methvin.watcher.DirectoryWatcher.<init>(DirectoryWatcher.java:193)
[error] 	at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:122)
[error] 	at play.dev.filewatch.DefaultFileWatchService.watch(DefaultFileWatchService.scala:44)
[error] 	at play.dev.filewatch.FileWatchService$$anon$1.watch(FileWatchService.scala:95)
[error] 	at play.runsupport.Reloader.<init>(Reloader.scala:443)
[error] 	at play.runsupport.Reloader$.reloader$lzycompute$1(Reloader.scala:283)
[error] 	at play.runsupport.Reloader$.play$runsupport$Reloader$$reloader$1(Reloader.scala:275)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:100)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:83)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:107)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.UnsatisfiedLinkError: /Users/user/Library/Caches/JNA/temp/jna648037593543371482.tmp: dlopen(/Users/user/Library/Caches/JNA/temp/jna648037593543371482.tmp, 1): no suitable image found.  Did find:
[error] 	/Users/user/Library/Caches/JNA/temp/jna648037593543371482.tmp: no matching architecture in universal wrapper
[error] 	/Users/user/Library/Caches/JNA/temp/jna648037593543371482.tmp: no matching architecture in universal wrapper
[error] Total time: 8 s, completed May 21, 2021, 11:57:15 AM
```

### Reproducible Test Case

It can be reproduced by simply scaffolding a new Play application on an Apple M1 machine.

**Comment by gmethvin** [comment] 2021-07-19 01:05
It seems the issue is that sbt uses an older version of JNA that doesn't support Apple M1. See this issue: https://github.com/sbt/io/issues/320

**Comment by fernandoracca** [comment] 2021-07-19 20:20
Just tried the code, and didn't fail.

> sbt
> [info] Updated file /Users/fer/Code/Lightbend/play-bug-10867/project/build.properties: set sbt.version to 1.5.1
> [info] welcome to sbt 1.5.1 (GraalVM Community Java 11.0.11)
> ...
> run
> ...
> --- (Running the application, auto-reloading is enabled) ---
> 
> [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
> 
> (Server started, use Enter to stop and go back to the console...)

**Comment by ignasi35** [comment] 2021-07-20 17:18
@giannoug I just noticed you use Zulu JDK11. I wonder if that could be a factor causing the issue.

Could you try this out using AdoptOpenJDK 11.0.x (the latest available)? Thanks

**Comment by mkurz** [comment] 2021-07-27 06:48
@ignasi35 AFAIK this also happens with AdoptOpenJDK, e.g. there is another report: https://github.com/irundaia/sbt-sassify/issues/48.

However the problem got fixed by bumping JNA to the latest version in sbt io, see https://github.com/sbt/io/pull/321. Now we have to wait for a sbt release that includes that patch, see https://github.com/sbt/io/pull/321#issuecomment-882748205.

**Comment by easel** [comment] 2021-11-02 16:02
There's a preview build of sbt at https://github.com/sbt/sbt/releases/tag/v1.6.0-M1 that includes the JNA dependency update and appears to be working for me. This is a pretty big deal, for my project build+test is over 4x slower on x86_64 with rosetta2 than on arm64. Thanks @eed3si9n !

**Comment by mkurz** [comment] 2021-11-12 20:11
@easel That's great news, thanks for sharing.

**Comment by mkurz** [comment] 2022-02-16 14:58
I am closing this now that sbt 1.6 is released which should work well with Apple silicon.

**Closed by mkurz** 2022-02-16 14:58 UTC
