### ISSUE TITLE
Malformed Config Files Kill Server With Useless Error Message [2.7.0]

### ISSUE THREAD

**Issue by SattaiLanfear** [playframework/playframework#9020] opened 2019-02-11 08:15 UTC
### Play Version (2.5.x / etc)

2.7.0

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

### Library Dependencies

N/A

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Malformed application.conf is placed in ./conf
2. Run Play dev-mode
3. Attempt to load a page
4. Error: Malformed application.conf is logged/reported.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "the page renders a 500 error code with no body content."  Copy and paste logs, and include any URLs.  Turn on internal Play logging with `<logger name="play" value="TRACE"/>` if there is no log output.  

* Error 500 is provided to the browser with no body.
* At step 4 above, the following output has been provided to the log (with "TRACE" enabled as described above), producing:  
```console
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000

(Server started, use Enter to stop and go back to the console...)

[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:504)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
```

### Reproducible Test Case

Sample project available here:
https://github.com/SattaiLanfear/play27malformedconf/

This project was generated using the play scala giter8 on 2/10/2019.
application.conf and logback.xml are the only files that should have been changed from default.

**Comment by marcospereira** [comment] 2019-04-01 20:33
Thanks for the reproducer, @SattaiLanfear. I can confirm this is happening. Also, this is logged when exiting using `ctrl+c`:

> [warn] a.a.CoordinatedShutdown - Task [shutdown-application-dev-mode] failed in phase [service-stop]: Configuration error[application.conf @ file:/Users/marcospereira/tmp/play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]

**Comment by mkurz** [comment] 2019-06-13 10:55
When running the provided example with the [netty backend](https://www.playframework.com/documentation/2.7.x/NettyServer#Netty-Server-Backend) I get much better error message:

<details>
<summary>Click here to view the stack trace</summary>

```
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
play.api.Configuration$$anon$1: Configuration error[application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
	at play.api.Configuration$.configError(Configuration.scala:171)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.Configuration$.load(Configuration.scala:121)
	at play.api.Configuration$.load(Configuration.scala:128)
	at play.api.http.DefaultHttpErrorHandler$.setEditor$lzycompute(HttpErrorHandler.scala:487)
	at play.api.http.DefaultHttpErrorHandler$.setEditor(HttpErrorHandler.scala:486)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:495)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:104)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
Caused by: com.typesafe.config.ConfigException$Parse: application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
play.api.Configuration$$anon$1: Configuration error[application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
	at play.api.Configuration$.configError(Configuration.scala:171)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.Configuration$.load(Configuration.scala:121)
	at play.api.Configuration$.load(Configuration.scala:128)
	at play.api.http.DefaultHttpErrorHandler$.setEditor$lzycompute(HttpErrorHandler.scala:487)
	at play.api.http.DefaultHttpErrorHandler$.setEditor(HttpErrorHandler.scala:486)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:495)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:104)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
Caused by: com.typesafe.config.ConfigException$Parse: application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
play.api.Configuration$$anon$1: Configuration error[application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
	at play.api.Configuration$.configError(Configuration.scala:171)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.Configuration$.load(Configuration.scala:121)
	at play.api.Configuration$.load(Configuration.scala:128)
	at play.api.http.DefaultHttpErrorHandler$.setEditor$lzycompute(HttpErrorHandler.scala:487)
	at play.api.http.DefaultHttpErrorHandler$.setEditor(HttpErrorHandler.scala:486)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:495)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:104)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
Caused by: com.typesafe.config.ConfigException$Parse: application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
play.api.Configuration$$anon$1: Configuration error[application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
	at play.api.Configuration$.configError(Configuration.scala:171)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.Configuration$.load(Configuration.scala:121)
	at play.api.Configuration$.load(Configuration.scala:128)
	at play.api.http.DefaultHttpErrorHandler$.setEditor$lzycompute(HttpErrorHandler.scala:487)
	at play.api.http.DefaultHttpErrorHandler$.setEditor(HttpErrorHandler.scala:486)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:495)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:104)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
Caused by: com.typesafe.config.ConfigException$Parse: application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
play.api.Configuration$$anon$1: Configuration error[application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
	at play.api.Configuration$.configError(Configuration.scala:171)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.Configuration$.load(Configuration.scala:121)
	at play.api.Configuration$.load(Configuration.scala:128)
	at play.api.http.DefaultHttpErrorHandler$.setEditor$lzycompute(HttpErrorHandler.scala:487)
	at play.api.http.DefaultHttpErrorHandler$.setEditor(HttpErrorHandler.scala:486)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:495)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:104)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
Caused by: com.typesafe.config.ConfigException$Parse: application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
play.api.Configuration$$anon$1: Configuration error[application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
	at play.api.Configuration$.configError(Configuration.scala:171)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.Configuration$.load(Configuration.scala:121)
	at play.api.Configuration$.load(Configuration.scala:128)
	at play.api.http.DefaultHttpErrorHandler$.setEditor$lzycompute(HttpErrorHandler.scala:487)
	at play.api.http.DefaultHttpErrorHandler$.setEditor(HttpErrorHandler.scala:486)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:495)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:104)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
Caused by: com.typesafe.config.ConfigException$Parse: application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
play.api.Configuration$$anon$1: Configuration error[application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
	at play.api.Configuration$.configError(Configuration.scala:171)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.Configuration$.load(Configuration.scala:121)
	at play.api.Configuration$.load(Configuration.scala:128)
	at play.api.http.DefaultHttpErrorHandler$.setEditor$lzycompute(HttpErrorHandler.scala:487)
	at play.api.http.DefaultHttpErrorHandler$.setEditor(HttpErrorHandler.scala:486)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:495)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:104)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
Caused by: com.typesafe.config.ConfigException$Parse: application.conf @ file:./play27malformedconf/target/scala-2.12/classes/application.conf: 3: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
```

</details>

**Comment by ctoomey** [comment] 2019-12-10 19:06
We're getting this too, and when using http/2 requests as needed for gRPC we don't get any error log at all, which is even worse.

The reason for this is that when the config. can't be loaded, the [default error handler](https://github.com/playframework/playframework/blob/2.7.x/core/play/src/main/scala/play/api/http/HttpErrorHandler.scala#L474) is used, and  its implementation of `onServerError` first attempts to set the editor from the config. before logging via the superclass method. Since loading the config. is what's failing obviously this fails/throws and so nothing is logged. This can be easily fixed by wrapping a try around the `setEditor` block.

```
object DefaultHttpErrorHandler
    extends DefaultHttpErrorHandler(HttpErrorConfig(showDevErrors = true, playEditor = None), None, None) {
  private lazy val setEditor: Unit = {
    val conf = Configuration.load(Environment.simple())
    conf.getOptional[String]("play.editor").foreach(setPlayEditor)
  }
  override def onClientError(request: RequestHeader, statusCode: Int, message: String): Future[Result] = {
    setEditor
    super.onClientError(request, statusCode, message)
  }
  override def onServerError(request: RequestHeader, exception: Throwable): Future[Result] = {
    setEditor
    super.onServerError(request, exception)
  }
}
```

**Comment by neilchaudhuri** [comment] 2020-04-02 02:16
I get this error simply by upgrading to Play 2.6.25 from 2.6.17 and from SBT 0.13 to 1.3.5. My `application.conf` works in 2.6.17, so I don't know why these changes to versions would generate this obscure error...

**Comment by Tasselmi** [comment] 2020-09-05 17:05
I have the same problem with play 2.8.2

**Comment by laguiz** [comment] 2020-09-10 18:37
Just to add to the context, I got the same issue : message was not clear : 

```
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
```

I am using `.env` and `application.conf` and switching to an other computer I missed to align environment variables.

**Comment by talkdirty** [comment] 2021-01-25 14:08
Someone in my team just encountered this. Useless error messages cost easily avoidable time. 2 years since opening the issue, any plans to resolve? Happy to take a look as well if a contributor could point at the likely cause

**Comment by mkurz** [comment] 2021-01-26 20:35
I finally had a look at this issue and @ctoomey's is [absolutely correct](https://github.com/playframework/playframework/issues/9020#issuecomment-564184187), it's the `setEditor` in the error handler causing the problem. I already have a working fix I will submit soon (together with other stuff I am working on).

**Comment by mkurz** [comment] 2021-01-27 11:02
Fix is here: #10662

**Closed** 2021-01-27 17:19 UTC
Labels: type:defect

**Comment by talkdirty** [comment] 2021-01-27 21:58
Thanks for making it happen @mkurz  :+1:

**Comment by laguiz** [comment] 2021-01-27 22:03
Thank you for this one. 👍

**Comment by mkurz** [comment] 2021-01-27 22:16
@talkdirty @laguiz Just wondering, is this issue such a big problem for you? I mean it only happens when the config file is invalid (or not?) which should not happen that often or not?

**Comment by ctoomey** [comment] 2021-01-27 22:30
Thanks @mkurz!

**Comment by laguiz** [comment] 2021-01-27 22:33
Not a big deal as you say no worries.

However for newcomers it may be a big deal (like a colleague just today). I told him 'yeah don't worry look at your config 😅'. 

It's part of the 'dev experience' we love Play so clean error save time :-) 

As an illustration, Angular team recently pushed a big effort on "common errors". For me it's pretty important to have clean errors especially when it's very easy to make.

All this said I did not try to do PR so it was definitly not blocking issue :-)

Keep great work.

**Comment by talkdirty** [comment] 2021-01-27 22:34
@mkurz indeed it's not a huge deal. I've just witnessed people hitting this issue on multiple occasions now onboarding. These people are generally new to scala/play. The reason is of course them not properly reading the documentation of our packages (i.e., which environment variables to set), however due to the in-transparent message that happened until now they think they've broke something unrelated before asking for help or figuring out the issue is actually related to configuration.

**Comment by laguiz** [comment] 2021-01-27 22:35
I confirm that in our case it happen (only) when I missed declare a variable in my .env file (using env plugin).
