### ISSUE TITLE
Cannot access test resource file from test class.

### ISSUE THREAD

**Issue by playtowork** [playframework/playframework#8284] opened 2018-03-10 23:23 UTC
### Play Version (2.5.x / etc)
2.6

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Ubuntu 16.04

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

### Problem
I have the following directory structure.
```
data
    - src
        - main
            - java
        - test
            - java
            - resources
```

In the above, "data" is a module, "src/main/java" is a Sources Root, "src/test/java" is a Test Sources Root, and "src/test/resources" is a Test Resources Root.

In a Test class (A) under "src/test/java", I want to read a file (X) from "src/test/resources". That seems to be the best practice for separating the test resources from the test classes. **However, I am unable to do so.**

If I place X anywhere under "src/test/java" though, then I am able to read it from A by traversing the directory structure. For example, if X is at "src/test/java/X" and A is at "src/test/java/dir_one/A", then the below code in A would let me read the file:
```
    try (InputStream inputStream = A.class.getResourceAsStream("../X")) {
        ...
    }
```

**Comment by martin-g** [comment] 2018-03-10 23:56
`test` folder is usually under `src` folder, not next to it.

**Comment by playtowork** [comment] 2018-03-11 00:00
@martin-g You're correct, of course. I have it that way in my project, just wrote it wrong here. I've corrected on the issue now.

**Comment by cchantep** [comment] 2018-07-15 09:08
If `../X` is not a typo then I guess that's what's wrong, as the test class and test resource are at the same level.

**Comment by marcospereira** [comment] 2019-04-24 18:10
Closing since we don't get any new pieces of information here. @playtowork, let me know if the comments above helped you to solve the problem or if it is still happening. A reproducer would be welcome if you can still reproduce the error.

**Closed by marcospereira** 2019-04-24 18:10 UTC
Labels: status:backlog
