### ISSUE TITLE
connection is frozen on bigger files during POST and some error

### ISSUE THREAD

**Issue by jinnzest** [playframework/playframework#5520] opened 2016-01-29 10:51 UTC
I have discovered weird behaviour of play during handling error situations. 
When you post some file bigger then approximately 1040 bytes and controller throws say IllegalStateException then play returns HTTP code 100 and keeps connection to client opened. 
Is it expected behaviour of the Play?

Here you can clone project which reproduces this issue: https://github.com/jinnzest/play_error_handling_issue.
README file contains files and curl commands to reproduce issue. 

Reproduced on OSs:
1. Mac OS X 10.11.3, oracle64-1.8.0.72, scala 2.11.7
2. CentOS Linux release 7.2.1511, oracle jdk1.8.0_65, scala 2.11.7

[application.log.zip](https://github.com/playframework/playframework/files/110746/application.log.zip)

**Comment by wsargent** [comment] 2016-01-29 21:07
Hi @jinnzest Please add 

```
<logger name="play" value="TRACE"/> 
```

To your logback.xml file and attach the logs to this issue.  You also should include the details of your OS, Play version, JDK version, whether you're running Java or Scala, and include details about the actual reproducing case as well.

**Comment by jinnzest** [comment] 2016-01-30 11:00
I have added log file and details about env.

**Comment by jroper** [comment] 2016-02-01 03:27
I can verify this bug - Play is sending a `100 Continue` response because `curl` is sending the `Expect: 100-continue` header, which it does when the body is greater than a certain size, that's expected and correct behaviour, see [here](https://jazzy.id.au/2013/07/16/100_continue_support_in_play.html) for more details on 100 continue.  However, after receiving the body and getting the error, Play doesn't seem to be sending the error response, so it seems that Play's error handling code is not correctly hooking up the error response to the connection in the case of 100 continue requests.

The code that handles 100 continue in Play has been completely rewritten on master (in fact, it doesn't even live in Play anymore, it lives in netty-reactive-streams), so I suspect the bug doesn't exist on master, but nevertheless, it would be good to write tests for this condition on both Play 2.4 and on master, and fix on Play 2.4.

**Comment by wsargent** [comment] 2016-02-01 21:20
Vaguely remember https://github.com/playframework/playframework/issues/2485 as well.

**Comment by mkurz** [comment] 2016-03-12 16:46
I can reproduce this with Play 2.4.6.
But I can **not** reproduce this with Play 2.5 anymore, as expected by jroper in his comment above.

However `curl` shows that Play returns **two** HTTP codes at once (within on response) when sending the larger file (which failed in Play 2.4.6 previously): 100 and 500.
Is that actually OK and expected or a bug in Play?
```
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Content-Length: 7303
< Content-Type: text/html; charset=utf-8
< Date: Sat, 12 Mar 2016 16:31:45 GMT
* HTTP error before end of send, stop sending
< 
// HTML with error description
* Closing connection 0
```

**Comment by wsargent** [comment] 2016-03-14 19:13
@mkurz 100 Continue means that it will stream up to the content length and then send back the real response code, so that's valid.

**Comment by mkurz** [comment] 2016-03-14 23:06
@wsargent Thanks! Then I think we can close this issue.

**Closed** 2016-03-14 23:06 UTC
Labels: defect
