### ISSUE TITLE
File download problem utf-8 added before file name

### ISSUE THREAD

**Issue by ksv510** [playframework/playframework#6836] opened 2016-12-26 14:16 UTC
### Play Version (2.5.x / etc)
2.5.10

### API (Scala / Java / Neither / Both)
JAVA

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_102"

### Expected Behavior
file name in response contains only file name like this http://take.ms/NEf86

### Actual Behavior
file name in response contains utf-8'' prefix http://take.ms/qYWPX

### Reproducible Test Case

in any controller 
File file = ...
return ok( file, file.getName() );

workaround

return ok( file )
              .withHeader( "Content-Disposition", "inline; filename=\"" + file.getName() + "\"" );

all this happen because of https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L278

**Comment by gmethvin** [comment] 2016-12-28 04:24
@ksv510 When I attempt to reproduce I'm getting the correct `Content-Disposition` header:
```
Content-Disposition:inline; filename="file.txt"; filename*=utf-8''file.txt
```
This is just with the default [play-java](https://github.com/playframework/play-java) template with an action added as you described. (The intended behavior is to add both the `filename` and `filename*` parameter as described in [RFC6266](https://tools.ietf.org/html/rfc6266#section-5).)

Can you provide a sample app demonstrating the issue?

**Comment by shkhln** [comment] 2016-12-28 09:52
There is `Server: akka-http/2.4.12` in the response headers on the screenshot.

**Comment by shkhln** [comment] 2016-12-28 17:54
More details:
```
scala> import akka.http.scaladsl.model._
import akka.http.scaladsl.model._

scala> HttpHeader.parse("Content-Disposition", "inline; filename=\"fn\"; filename*=utf-8''fn")
res0: akka.http.scaladsl.model.HttpHeader.ParsingResult = Ok(Content-Disposition: inline; filename="utf-8''fn",List())
```

I guess it is sufficient to change `push("filename")` to `push("filename*")` @ https://github.com/akka/akka-http/blob/ff434be5200f9ef81f97760580927c4fef1fd548/akka-http-core/src/main/scala/akka/http/impl/model/parser/ContentDispositionHeader.scala#L29.

**Comment by schmitch** [comment] 2016-12-28 18:29
in fact, that looks like a bug: https://github.com/akka/akka-http/pull/695
It will be rendered as `filename="utf-8''fn"` instead of `filename*="utf-8''fn"` and your change description was pretty pretty good. thanks.

**Comment by richdougherty** [comment] 2017-07-18 18:32
Yes, I'll close this issue now…

**Closed by richdougherty** 2017-07-18 18:32 UTC
Labels: needs-verification
