### ISSUE TITLE
Play 2.4 breaks compatibility with ScalaIDE

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#4340] opened 2015-04-30 13:51 UTC
Even though my project compiles and runs fine, I get following error for reverse routes in the (latest) ScalaIDE - which also causes that autocompletion doesn't work (Also a weird thing is that the error is not showing up in the "Problems" tab of the IDE):

![scala-ide-error](https://cloud.githubusercontent.com/assets/644927/7413081/11f4a788-ef49-11e4-8bd4-2280973830c9.png)

I created a [simple test project](https://github.com/mkurz/play-java-eclipse) based on the latest [play-java template](https://github.com/playframework/playframework/tree/master/templates/play-java) with only a [few modification](https://github.com/mkurz/play-java-eclipse/commits/master) to reproduce the issue.

Going further I tried making it a Java-only project (without the Scala Nature) as described [here](https://github.com/playframework/playframework/blob/master/documentation/manual/gettingStarted/IDE.md#setup-sbteclipse) by adding:
```sbt
EclipseKeys.projectFlavor := EclipseProjectFlavor.Java           // Java project. Don't expect Scala IDE
EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)  // Use .class files instead of generated .scala files for views and routes 
EclipseKeys.preTasks := Seq(compile in Compile)                  // Compile the project before generating Eclipse files, so that .class files for views and routes are present
```

This makes it even worse as ScalaIDE now shows following 2 errors (in the "Problems" tab now):
```
controllers.routes cannot be resolved
views.html.index cannot be resolved to a type
```

The same happens when using pure Eclipse as well.

**Comment by mkurz** [comment] 2015-04-30 14:11
BTW: The same error ("XXX cannot be resolved to a type") is shown for the type `ReverseAssets` and the package `controllers.javascript` inside the file `target/scala-2.11/routes/main/controllers/routes.java` as well.
Is it possible that the IDE doesn't pick up the `controller` package from `target/scala-2.11/routes/main/router/routes_reverseRouting.scala`?

**Comment by mkurz** [comment] 2015-04-30 22:20
I forgot to mention: When I rewrite the controller in Scala, the ScalaIDE is **not** complaining about the reverse route `controllers.routes.Application.contact()` inside this Scala controller anymore. It looks like only play-java has some issues here...

I am not entirely sure if this has something todo with the IDE or play-java is just broken. Could someone check this in IntelliJ?

**Comment by mkurz** [comment] 2015-04-30 22:31
The same issue also occurs when using Play 2.3.8...

**Comment by benmccann** [comment] 2015-05-05 06:27
This is an issue with sbteclipse 4.0.0-RC1. Filed https://github.com/typesafehub/sbteclipse/issues/266 to track this

**Comment by mkurz** [comment] 2015-05-05 06:31
Thanks @benmccann !

**Comment by benmccann** [comment] 2015-05-06 00:53
I'm going to close this here and use the issue at sbteclipse to track this. It's fixed there. Just need a new release now

**Comment by mkurz** [comment] 2015-05-07 10:26
@benmccann I just tested sbteclipse 4.0.0-RC2:  Unfortunately the issue is not completely fixed yet.
I still get the error `"ReverseApplication cannot be resolved to a type"` like described in my initial bug report above (see the screenshot I attached there). As reported this happens when importing a play-java project into ScalaIDE **without** setting any of the `EclipseKeys`' (so it just stays a Scala flavoured project). I updated [my simple testproject](https://github.com/mkurz/play-java-eclipse) to reproduce the problem.

However the errors `controllers.routes cannot be resolved` and `views.html.index cannot be resolved to a type` are fixed now for Java flavored projects - thanks for this.

**Comment by benmccann** [comment] 2015-05-07 15:01
Ok, well glad we're making progress at least.

When you import without setting `EclipseKeys` do you get any references to the directories `target/scala-2.11/routes` and `target/scala-2.11/twirl` in your .classpath file? These should only show up without the additional settings. With the extra settings you should instead get `target/scala-2.11/classes_managed`.

**Comment by mkurz** [comment] 2015-05-07 17:40
That's the `.classpath` file without the `EclipseKeys`:
```
<classpath>
  <classpathentry kind="src" path="app"/>
  <classpathentry kind="src" path="conf"/>
  <classpathentry kind="src" path="target/scala-2.11/twirl/main"/>
  <classpathentry kind="src" path="target/scala-2.11/routes/main"/>
  <classpathentry excluding="resources/" kind="src" path="test"/>
  <classpathentry kind="con" path="org.scala-ide.sdt.launching.SCALA_CONTAINER"/>
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
  <classpathentry kind="output" path="bin"/>
  <!-- skipped libs from the ~/.ivy folder  -->
</classpath>
```
And here the `.classpath` with the three `EclipseKeys` set:
```
<classpath>
  <classpathentry kind="src" path="app"/>
  <classpathentry kind="src" path="conf"/>
  <classpathentry excluding="resources/" kind="src" path="test"/>
  <classpathentry kind="lib" path="./target/scala-2.11/classes_managed"/>
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
  <classpathentry kind="output" path="bin"/>
  <!-- skipped libs from the ~/.ivy folder  -->
</classpath>
```

**Comment by mkurz** [comment] 2015-05-07 17:45
So the settings, as you described them, should be fine.

The problem only occurs in the first case, when `EclipseKeys` are NOT set.

**Comment by benmccann** [comment] 2015-05-07 18:41
Hmm. I don't know what the problem is then. As far as I know, that's what your're supposed to have. Have you also compiled your project on the command line? That might still be necessary in the Scala IDE case. Can you try again this time with just the `EclipseKeys.preTasks := Seq(compile in Compile)` line? That will recompile everything before generating your Eclipse settings.

You can list the directory contents to check, but you should have the files Eclipse can't find in target/scala-2.11/routes/main and that folder should be in your Package Explorer in Eclipse as well.

I guess the other thing that might help was if this worked for you in Play 2.3.8 with the version of sbteclipse it includes (3.0 I think) then post your .classpath from that version. I'd expect them to be the same. It sounds like they're not though if it used to work and now doesn't. If we can figure out what's different that would help a lot.

**Comment by mkurz** [comment] 2015-05-07 19:02
It did **not** work with Play 2.3.8 too. It has exactly the same problem. The thing is I just recently switched from Eclipse to ScalaIDE using 2.3.8 (because I wanted to add some .scala files) and just ignored the error for the time being. Now when testing 2.4.0 I finally created a bug report.

Also tried your suggestions now:
No change, still the same result when trying `activator compile` before or when setting `EclipseKeys.preTasks := Seq(compile in Compile)`.

The `target/scala-2.11/routes/main` folder should be fine too:
![untitled](https://cloud.githubusercontent.com/assets/644927/7523326/4c121484-f4fb-11e4-871d-bbfd93aae6de.png)

By the way, I am using Ubuntu 12.04 LTS. But I also tested this scenario on a  completely different machine running Windows 7 with a complete fresh ScalaIDE installation (was never installed on this machine before) and it gives me the exact same error.

And again, what's weird is that this error does not show up in the "Problems" tab of the IDE.

**Comment by benmccann** [comment] 2015-05-07 19:24
Hmmm. So my only other thought is that you should check what's in routes.java and what's in routes_reverseRouting.scala and routes_routing.scala. Are you having trouble referencing all of them? Maybe it's just the references to .scala files that are failing? What if you add a .scala file elsewhere in your project and try to reference it from one of your Java files?

As far as I can tell, Play and sbteclipse are doing everything correctly here. At this point, I'd guess any bug is in ScalaIDE and you might want to file an issue in [their issue tracker](https://github.com/scala-ide/scala-ide-play2/issues). Unfortunately, I've never gotten ScalaIDE to work for me and it doesn't seem to be super well-maintained, so I'm not sure what to do from here.

**Comment by mkurz** [comment] 2015-05-08 00:16
> What if you add a .scala file elsewhere in your project and try to reference it from one of your Java files?

This is working, I created a .scala file and could reference it from any Java file and vica verca.

I now tested the same project in IntelliJ and it was working fine there, no complaints.

After lot's of testing I would also say this is a bug in the ScalaIDE. I am going to raise an issue there..

**Comment by marcospereira** [comment] 2015-05-08 03:08
@benmccann and @mkurz, 

Since this looks like a bug in ScalaIDE, I'm closing this issue. Please, feel free to reopen it if necessary.

**Comment by mkurz** [comment] 2015-05-08 09:56
Reported a bug to ScalaIDE:
https://scala-ide-portfolio.assembla.com/spaces/scala-ide/support/tickets/1002450

**Comment by dotta** [comment] 2015-05-11 12:01
@benmccann My current thinking is that we need to tweak sbteclipse to get around the Scala IDE limitation (see my comments in the [above linked Scala IDE ticket](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002450)). Do you think is possible? Also, is that something you could have a look at? (I'm happy to review and monkey test any code you may push :-))

**Comment by benmccann** [comment] 2015-05-11 21:05
Here's the [ticket regarding root cause](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1001154#/activity/ticket:) that the others are marked as a duplicate of

@dotta I'm not sure how we would tweak sbteclipse. Maybe we could tweak Play. But I'm not sure why we should have to do either of these things instead of just fixing the real issue. Why is it that the bug in Scala IDE isn't being fixed?

**Comment by cchantep** [comment] 2015-05-11 21:09
Agree with @benmaccann

**Comment by dotta** [comment] 2015-05-12 07:30
@benmccann @cchantep If only it was that simple :-) We have known that issue for more than 3+ years, and it wasn't fixed because it's a tricky one. The issue is in the Scala Presentation Compiler, i.e., scalac itself, not the Scala IDE.

In fact, the ticket in the Scala IDE you have linked to is about producing a warning when the package declaration and the source location are not in sync. It's not about fixing the underlying problem :-)

Regardless, we currently also have a usability problem that is independent of the Scala IDE: Java Play 2.4 users that are using Eclipse seem to be now required to install the Scala IDE to work on their project (because the generated routes and templates Scala source folders are needed to typecheck their project). This was not the case when using Play 2.3. Ben, have I got this wrong?

**Comment by mkurz** [comment] 2015-05-12 07:57
@dotta As I wrote in my last comment in the ScalaIDE Ticket, it is **not** required to install ScalaIDE for Play Java projects in 2.4. **You only have to install ScalaIDE if you have scala sources in your project.** As [shown in the documentation](https://www.playframework.com/documentation/2.4.x/IDE#Setup-sbteclipse) you just have to set following keys in `build.sbt` to use a Play Java project in pure Eclipse:
>If you do **not** want to install Scala IDE and have only Java sources in your project, then you can set the following:
```
EclipseKeys.projectFlavor := EclipseProjectFlavor.Java           // Java project. Don't expect Scala IDE
EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)  // Use .class files instead of generated .scala files for views and routes 
EclipseKeys.preTasks := Seq(compile in Compile)                  // Compile the project before generating Eclipse files, so that .class files for views and routes are present
```

**Comment by dotta** [comment] 2015-05-12 08:53
@mkurz Thanks for the pointer! Glad to hear there is a workaround, but to me it looks like we are not been very kind to our Java users. Ideally, the above settings should be set by default when using Play with Java. I wonder if it would make sense in sbteclipse to scan the source folders and, if only java sources are present, then defaulting to the above settings. @benmccann Do you think this is a viable solution? Or am I overengineering it?

**Comment by mkurz** [comment] 2015-05-12 09:11
@dotta Even if the above settings are the default for Play Java users, it does not fix the problem. Because as soon as you add scala sources to a (Java) project, someone probably wants to remove these settings to gain full ScalaIDE support (that's the case in a project of ours, we have a mixed Java/Scala project). And then you run into the issue again.

The only solution I can think of (except fixing the Scala Presentation Compiler) is to split  `routes_reverseRouting.scala` and put it some of it's content into `target/scala-2.11/routes/main/controllers` and `target/scala-2.11/routes/main/controllers/javascript` so all packages are placed in the correct (physical) location.
I have done this by hand to test it and can confirm this would fix the issue - everything works as intended.

**Comment by dotta** [comment] 2015-05-12 09:24
I believe we are discussing two problems here:

1) Provide a great user experience for Java Play 2.4 projects in Eclipse.
2) Provide a great user experience to Scala (or mixed Java/Scala) Play 2.4 projects in Eclipse.

For 1), I believe users should not have to know about the above sbteclipse settings when exporting their project. If possible, it should just work out of the box. [My previous comment](https://github.com/playframework/playframework/issues/4340#issuecomment-101195887) was meant to address this problem.

For 2), I agree with you, and in fact I'm discussing (on the Play contributors gitter.im channel) with the other contributors to Play if they'd be ok in changing the way routes and templates sources are generated, so that they end up at the right place. Is this something you'd be interested on working on? Are you able to join the discussion on gitter https://gitter.im/playframework/contributors? (if not, let me know, and I'll see if/how I can add you :-))

**Comment by jroper** [comment] 2015-05-12 12:05
For 1) It used to work out of the box, but this had some distinct disadvantages, it meant that Play was tied to a particular release of sbteclipse, users couldn't upgrade because newer versions broke compatibility, and the Play specific configuration got in the way.  So out of the box, things worked ok, except for where there were bugs, and then it was terrible, because you couldn't even work around the problems.

**Comment by dotta** [comment] 2015-05-12 14:05
@jroper Absolutely. I'm not suggesting we should move back to what we had before. I'd like to see the issue fixed in sbteclipse itself.

**Comment by benmccann** [comment] 2015-05-12 15:40
@dotta I think sbteclipse works exactly as it should. You'll have to be more specific about what it is that you'd like to see changed. Are you saying that we should build logic specifically for Play into sbteclipse that detects if you're using Play and alters your settings based on that? I think it's better that sbteclipse and Play don't need to know anything about each other.

Changing Play so that it works around the Scala IDE compiler bug seems like a reasonable step.

Is there a ticket for the underlying problem in scalac that you can link to? I'd love to better understand what the problem is there

**Comment by jroper** [comment] 2015-05-13 01:22
Building logic into sbteclipse specifically to detect and handle Play is not that bad an option I think.  sbteclipse is a bridge, it only exists because Eclipse doesn't have good (or any?) sbt support.  So, imagine that Eclipse provided first class support for sbt, what would it look like?  Whatever that is, sbteclipse should do.  If detecting and reconfiguring things in order to better support Play is part of that, then it should do that.

**Comment by benmccann** [comment] 2015-05-13 01:37
I don't think that if Eclipse had first-class SBT support it would need any knowledge of Play. E.g. IntelliJ has first-class knowledge of SBT and has no special knowledge of Play.

**Comment by jroper** [comment] 2015-05-13 01:55
No, it wouldn't need to acknowledge Play, but it doesn't have first class sbt support, and so is unable to do what it needs to to treat a Play project in a way that doesn't require it to have knowledge of Play, and for that reason, the bridge needs to acknowledge Play.

**Comment by benmccann** [comment] 2015-05-13 02:01
I'm still wondering what compiler bug is...

**Comment by dotta** [comment] 2015-05-13 10:28
@benmccann Looks like we actually didn't open a ticket in the scala issue tracker. But I just did so https://issues.scala-lang.org/browse/SI-9309

**Comment by dotta** [comment] 2015-05-13 10:43
> @dotta I think sbteclipse works exactly as it should. You'll have to be more specific about what it is that you'd like to see changed. Are you saying that we should build logic specifically for Play into sbteclipse that detects if you're using Play and alters your settings based on that? I think it's better that sbteclipse and Play don't need to know anything about each other.

I'm wondering if the settings in [this comment](https://github.com/playframework/playframework/issues/4340#issuecomment-101177614) could be applied to any Java project. That's all. I wasn't suggesting that sbteclipse should have any specific knowledge about Play, even though it's actually not a bad idea. As James pointed out, sbteclipse is only useful until we have first-class support for sbt in Eclipse.

**Comment by dotta** [comment] 2015-05-13 12:39
@mkurz @benmccann Turns out there is also an issue on the Scala IDE side https://scala-ide-portfolio.assembla.com/spaces/scala-ide/support/tickets/1002460

**Comment by mkurz** [comment] 2015-05-14 09:33
@dotta I am a bit confused now. Does this mean the [bug you just reported (1002460)](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/support/tickets/1002460) to ScalaIDE is the cause of the problem? So if that ScalaIDE bug gets fixed, do we still need to split the `routes_reverseRouting.scala`?

**Comment by benmccann** [comment] 2015-05-14 21:09
I'm going to reopen this issue because I think we should provide a workaround for this in Play

**Comment by dotta** [comment] 2015-05-15 05:50
@mkurz Ideally, we should resolve both [Scala IDE 1002460](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/support/tickets/1002460) and [Scala Compiler SI-9309](https://issues.scala-lang.org/browse/SI-9309). However, I don't think that will happen in the near future (furthermore, to profit of a presentation compiler fix we would have to wait for the next Scala release). Splitting `routes_reverseRouting.scala` also doesn't seem an option, as we are already in RC cycle for Play 2.4.

@benmccann Not sure if anything I've said here is relevant for this ticket. Feel free to cancel this comment if it doesn't help.

**Comment by santoshv98** [comment] 2015-05-15 06:05
Just wanted to let you guys know, I have spent almost an hour trying to understand why the routes appeared unfound in scala-ide. It was made worse that I had some compilation issues with the templates as I was porting an open source starter application from 2.3 to 2.4. Going back to the console did help to find out about the templates issue and get everything to compile but I still see them in RED. You have no way of knowing till you run the application as to why the routes were showing in red inside the controllers. If there are workarounds possible, I request that some importance be attached to fixing this.

By the way, 2.3 templates didn't compile in 2.4. Is there any documentation on what has changed? I banked them out and started debugging the application to proceed.

**Closed** 2015-05-19 00:23 UTC
