### ISSUE TITLE
Playframework.com is down

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7207] opened 2017-04-09 09:29 UTC
![image](https://cloud.githubusercontent.com/assets/100349/24836264/a15f631a-1d17-11e7-9f0b-2151d3c2b7e8.png)

**Comment by PromanSEW** [comment] 2017-04-09 11:08
Now it works normally

**Comment by SpaceCowboyMax** [comment] 2017-04-09 13:16
no its still down

**Comment by domdorn** [comment] 2017-04-09 14:03
According to Whois.com ( https://www.whois.com/whois/playframework.com ) , the nameservers are 
ns39.domaincontrol.com
ns40.domaincontrol.com

those and google dns still return 
50.63.202.38


> nslookup playframework.com ns39.domaincontrol.com
> Server:		ns39.domaincontrol.com
> Address:	216.69.185.20#53
> 
> Name:	playframework.com
> Address: 50.63.202.38
> 
> nslookup playframework.com ns40.domaincontrol.com
> Server:		ns40.domaincontrol.com
> Address:	208.109.255.20#53
> 
> Name:	playframework.com
> Address: 50.63.202.38
> 
> nslookup playframework.com 8.8.8.8
> Server:		8.8.8.8
> Address:	8.8.8.8#53
> 
> Non-authoritative answer:
> Name:	playframework.com
> Address: 50.63.202.38

@PromanSEW  which IP do you get from which nameserver ?

**Comment by wsargent** [comment] 2017-04-09 15:07
@domdorn It's being worked on -- please start up a server with http://localhost:9000/@documentation or go to the documentation source at https://github.com/playframework/playframework/tree/2.5.x/documentation/manual in the mean time

**Comment by PromanSEW** [comment] 2017-04-09 15:29
@domdorn now the site is really down, but when I wrote comment it worked

**Comment by wsargent** [comment] 2017-04-09 17:25
More updates on https://twitter.com/playframework -- basically Godaddy has a "domain compliance" team that does not work on weekends, and there is literally nothing we can do except wait until Monday.

**Comment by wsargent** [comment] 2017-04-09 17:26
Closing, please use twitter account for updates.

**Comment by wsargent** [comment] 2017-04-09 20:40
Reopening, as we're getting comments on https://github.com/playframework/playframework/issues/2390#issuecomment-292811299 as well.

**Comment by gmethvin** [comment] 2017-04-10 14:34
This has also been discussed on the mailing list and twitter. We are working to get this resolved as soon as possible today. The issue is that our domain registrar has redirected the DNS to alternate servers, and for some reason the people able to resolve this issue are unavailable on the weekend.

The site itself is up, and you can confirm this by manually setting the IP address in your hosts file:

```
104.24.97.161 playframework.com
104.24.97.161 www.playframework.com
```

**Comment by wsargent** [comment] 2017-04-10 20:39
Okay, it's up now.

**Closed by wsargent** 2017-04-10 20:39 UTC

**Comment by domdorn** [comment] 2017-04-11 08:33
finally! would be great to get a short info on what was godaddys problem? Was it that the contact was named "Office IT" or that it was still "Typesafe Inc. " ?

**Comment by wsargent** [comment] 2017-04-11 15:11
We will have a post-mortem up.  The short story is that the contact email was "offieit@typesafe.com" instead of "officeit@typesafe.com".

**Comment by Alvaroisit** [comment] 2017-04-18 00:02
I noticed this the other day, it seemed you went from none www to www or vice versa and the 301 redirect was not properly set-up.


Alvaro Pereyra

**Comment by domdorn** [comment] 2017-04-18 12:33
As mentioned above, the issue was with GoDaddy and a incomplete contact email. 
The issue has been resolved, closed and I'm locking this ticket now. 
If you experience website downtime again, please first look at our twitter handle 
https://twitter.com/playframework and/or our gitter channel https://gitter.im/playframework/playframework 
If nothing helps, create a new issue.
