### ISSUE TITLE
[2.8.15] Guice crash on startup using java17 with PlayJava plugin

### ISSUE THREAD

**Issue by aelgn** [playframework/playframework#11220] opened 2022-04-05 16:14 UTC
### Play Version
2.8.15

### API
Java

### Operating System
alpine

### JDK
jlinked openjdk 17.0.2_8

### Library Dependencies
```
libraryDependencies ++= Seq(
  "com.google.inject"            % "guice"                % "5.1.0",
  "com.google.inject.extensions" % "guice-assistedinject" % "5.1.0",
  "net.jodah"                    % "typetools"            % "0.6.3"
)
```
etc...

### Expected Behavior

1. Server starts

### Actual Behavior

1. Crash on startup

Using java16 on play 2.8.x and/or java17 on play 2.8.15 with the `PlayJava` plugin results in guice having a meltdown on startup. Best I can tell the Hibernate Validator pollutes the classpath with an old javax validation-api artifact.

Interesting that this is not happening in our dev environment (intellij), but only in prod runtime (AshScriptPlugin in alpine image)

## Workaround
1. If not using JavaForms, change your build.sbt to use the `PlayMinimalJava` plugin instead. As per: https://www.playframework.com/documentation/2.8.x/JavaForms
`.enablePlugins(PlayMinimalJava)`
instead of
`.enablePlugins(PlayJava)`
This has the added benefit of removing hibernate and spring cruft from your classpath altogether!

or

2. Explicitly set validation-api version in your dependecies in build.sbt:
`libraryDependencies += "jakarta.validation" % "jakarta.validation-api" % "2.0.2"`

or

3. Might be solved by upgrading to a newer Hibernate Validator version, but I have not investigated that.

### Log
```
16:43:58,102 [#033[37minfo#033[0m] (-dispatcher-6) () [akka.event.slf4j.Slf4jLogger]: Slf4jLogger started
16:44:00,850 [#033[37minfo#033[0m] (main) () [org.hibernate.validator.internal.util.Version]: HV000001: Hibernate Validator 6.1.7.Final
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) [Guice/ErrorInjectingConstructor]: NoSuchMethodError: 'String BootstrapConfiguration.getClockProviderClassName()'
 at ValidatorFactoryProvider.<init>(ValidatorFactoryProvider.java:27)
 at ValidatorFactoryProvider.class(ValidatorFactoryProvider.java:20)
 while locating ValidatorFactoryProvider
 at FormFactory.<init>(FormFactory.java:32)
     \_ for 3rd parameter
 at BindingKey.toSelf(BindingKey.java:166):
Binding(class FormFactory to self)
     \_ installed by: Modules$OverrideModule -> GuiceableModuleConversions$$anon$4
 while locating FormFactory
Learn more:
 https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: NoSuchMethodError: 'String BootstrapConfiguration.getClockProviderClassName()'
at ValidationBootstrapParameters.<init>(ValidationBootstrapParameters.java:65)
at AbstractConfigurationImpl.parseValidationXml(AbstractConfigurationImpl.java:664)
at AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:421)
at ValidatorFactoryProvider.<init>(ValidatorFactoryProvider.java:33)
at ValidatorFactoryProvider$$FastClassByGuice$$103719352.GUICE$TRAMPOLINE(<generated>)
at ValidatorFactoryProvider$$FastClassByGuice$$103719352.apply(<generated>)
at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
at ConstructorInjector.provision(ConstructorInjector.java:114)
at ConstructorInjector.construct(ConstructorInjector.java:91)
at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at SingletonScope$1.get(SingletonScope.java:169)
at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
at BoundProviderFactory.get(BoundProviderFactory.java:58)
at SingleParameterInjector.inject(SingleParameterInjector.java:40)
at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
at ConstructorInjector.provision(ConstructorInjector.java:113)
at ConstructorInjector.construct(ConstructorInjector.java:91)
at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at SingletonScope$1.get(SingletonScope.java:169)
at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
at Guice.createInjector(Guice.java:87)
at Guice.createInjector(Guice.java:78)
at GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
at GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
at GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
at ProdServerStart$.start(ProdServerStart.scala:53)
at ProdServerStart$.main(ProdServerStart.scala:29)
at ProdServerStart.main(ProdServerStart.scala)
2) [Guice/ErrorInjectingConstructor]: NoSuchMethodError: 'String BootstrapConfiguration.getClockProviderClassName()'
 at ValidatorFactoryProvider.<init>(ValidatorFactoryProvider.java:27)
 at ValidatorFactoryProvider.class(ValidatorFactoryProvider.java:20)
 while locating ValidatorFactoryProvider
Learn more:
 https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: NoSuchMethodError: 'String BootstrapConfiguration.getClockProviderClassName()'
at ValidationBootstrapParameters.<init>(ValidationBootstrapParameters.java:65)
at AbstractConfigurationImpl.parseValidationXml(AbstractConfigurationImpl.java:664)
at AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:421)
at ValidatorFactoryProvider.<init>(ValidatorFactoryProvider.java:33)
at ValidatorFactoryProvider$$FastClassByGuice$$103719352.GUICE$TRAMPOLINE(<generated>)
at ValidatorFactoryProvider$$FastClassByGuice$$103719352.apply(<generated>)
at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
at ConstructorInjector.provision(ConstructorInjector.java:114)
at ConstructorInjector.construct(ConstructorInjector.java:91)
at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at SingletonScope$1.get(SingletonScope.java:169)
at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
at Guice.createInjector(Guice.java:87)
at Guice.createInjector(Guice.java:78)
at GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
at GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
at GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
at ProdServerStart$.start(ProdServerStart.scala:53)
at ProdServerStart$.main(ProdServerStart.scala:29)
at ProdServerStart.main(ProdServerStart.scala)
3) [Guice/ErrorInjectingConstructor]: NoSuchMethodError: 'String BootstrapConfiguration.getClockProviderClassName()'
 at ValidatorProvider.<init>(ValidatorProvider.java:30)
 at ValidatorProvider.class(ValidatorProvider.java:22)
 while locating ValidatorProvider
Learn more:
 https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: NoSuchMethodError: 'String BootstrapConfiguration.getClockProviderClassName()'
at ValidationBootstrapParameters.<init>(ValidationBootstrapParameters.java:65)
at AbstractConfigurationImpl.parseValidationXml(AbstractConfigurationImpl.java:664)
at AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:421)
at ValidatorProvider.<init>(ValidatorProvider.java:36)
at ValidatorProvider$$FastClassByGuice$$102216060.GUICE$TRAMPOLINE(<generated>)
at ValidatorProvider$$FastClassByGuice$$102216060.apply(<generated>)
at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
at ConstructorInjector.provision(ConstructorInjector.java:114)
at ConstructorInjector.construct(ConstructorInjector.java:91)
at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at SingletonScope$1.get(SingletonScope.java:169)
at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
at Guice.createInjector(Guice.java:87)
at Guice.createInjector(Guice.java:78)
at GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
at GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
at GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
at ProdServerStart$.start(ProdServerStart.scala:53)
at ProdServerStart$.main(ProdServerStart.scala:29)
at ProdServerStart.main(ProdServerStart.scala)
3 errors
======================
Full classname legend:
======================
AbstractConfigurationImpl:                             "org.hibernate.validator.internal.engine.AbstractConfigurationImpl"
BindingKey:                                            "play.inject.BindingKey"
BootstrapConfiguration:                                "javax.validation.BootstrapConfiguration"
BoundProviderFactory:                                  "com.google.inject.internal.BoundProviderFactory"
ConstructorBindingImpl$Factory:                        "com.google.inject.internal.ConstructorBindingImpl$Factory"
ConstructorInjector:                                   "com.google.inject.internal.ConstructorInjector"
DefaultConstructionProxyFactory$FastClassProxy:        "com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy"
FormFactory:                                           "play.data.FormFactory"
Guice:                                                 "com.google.inject.Guice"
GuiceApplicationBuilder:                               "play.api.inject.guice.GuiceApplicationBuilder"
GuiceApplicationLoader:                                "play.api.inject.guice.GuiceApplicationLoader"
GuiceBuilder:                                          "play.api.inject.guice.GuiceBuilder"
GuiceableModuleConversions$$anon$4:                    "play.api.inject.guice.GuiceableModuleConversions$$anon$4"
InternalFactoryToProviderAdapter:                      "com.google.inject.internal.InternalFactoryToProviderAdapter"
InternalInjectorCreator:                               "com.google.inject.internal.InternalInjectorCreator"
Modules$OverrideModule:                                "com.google.inject.util.Modules$OverrideModule"
ProdServerStart:                                       "play.core.server.ProdServerStart"
ProdServerStart$:                                      "play.core.server.ProdServerStart$"
ProviderToInternalFactoryAdapter:                      "com.google.inject.internal.ProviderToInternalFactoryAdapter"
SingleParameterInjector:                               "com.google.inject.internal.SingleParameterInjector"
SingletonScope$1:                                      "com.google.inject.internal.SingletonScope$1"
ValidationBootstrapParameters:                         "org.hibernate.validator.internal.xml.config.ValidationBootstrapParameters"
ValidatorFactoryProvider:                              "play.data.validation.ValidatorFactoryProvider"
ValidatorFactoryProvider$$FastClassByGuice$$103719352: "play.data.validation.ValidatorFactoryProvider$$FastClassByGuice$$103719352"
ValidatorProvider:                                     "play.data.validation.ValidatorProvider"
ValidatorProvider$$FastClassByGuice$$102216060:        "play.data.validation.ValidatorProvider$$FastClassByGuice$$102216060"
========================
End of classname legend:
========================
at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:576)
at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
at com.google.inject.Guice.createInjector(Guice.java:87)
at com.google.inject.Guice.createInjector(Guice.java:78)
at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
at play.core.server.ProdServerStart$.start(ProdServerStart.scala:53)
at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

**Comment by aelgn** [comment] 2022-04-07 07:56
The problem is that an old validation-api artifact is packaged with the target.
The BootstrapConfiguration.getClockProviderClassName method is indeed not a part of the validation-api in versions earlier than 2.0
https://docs.jboss.org/hibernate/beanvalidation/spec/2.0/api/javax/validation/BootstrapConfiguration.html#getClockProviderClassName--

Digging around in the dependency tree reveals that:
```
[info]   | +-org.hibernate.validator:hibernate-validator:6.1.7.Final
[info]   | | +-com.fasterxml:classmate:1.3.4
[info]   | | +-jakarta.validation:jakarta.validation-api:2.0.2
[info]   | | +-org.jboss.logging:jboss-logging:3.3.2.Final
```
```
[info]   +-com.fasterxml.jackson.module:jackson-module-jsonSchema:2.12.6
[info]   | +-com.fasterxml.jackson.core:jackson-annotations:2.12.6
[info]   | +-com.fasterxml.jackson.core:jackson-core:2.12.6
[info]   | +-com.fasterxml.jackson.core:jackson-databind:2.12.6
[info]   | | +-com.fasterxml.jackson.core:jackson-annotations:2.12.6
[info]   | | +-com.fasterxml.jackson.core:jackson-core:2.12.6
[info]   | | 
[info]   | +-javax.validation:validation-api:1.1.0.Final
```
So it seems that the jackson-module-jsonSchema dependency on the old validation-api is evicting the transitive dependency of hibernate.

So the has nothing to do with play, ie. resolved with `not-my-problem` :)

**Comment by mkurz** [comment] 2022-04-07 08:40
I see. So the problem is that the groupId changed and therefore both artifacts get packaged, because sbt is not evicting the old one:

* `jakarta.validation` (`jakarta.validation-api`)
* `javax.validation` (`validation-api`)

So the solution is to exclude the old api:
```sbt
libraryDependencies += ("com.fasterxml.jackson.module" % "jackson-module-jsonSchema" % "2.12.6")
    .exclude("javax.validation",  "validation-api")
```

Closing since this is not caused by Play.
@aelgn Thanks again for the report!

**Closed by mkurz** 2022-04-07 08:40 UTC
Labels: status:needs-info, topic:jdk-next

**Comment by mkurz** [comment] 2022-04-07 15:03
@sleski You have to keep 
```
libraryDependencies ++= Seq(
  guice, ...
```
and **additionally** add 
```
"com.google.inject" % "guice" % "5.1.0",
"com.google.inject.extensions" % "guice-assistedinject" % "5.1.0",
```

**Comment by sleski** [comment] 2022-04-07 18:35
Thanks @mkurz, it works 🎉
