### ISSUE TITLE
[2.4.x] Java Http Context not set when using EventSource

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6162] opened 2016-05-16 20:11 UTC
For example, the following code

```java
public Result connect() {
  return ok(EventSource.whenConnected(this::createClientConnection));
}


public void createClientConnection(EventSource eventSource) {
  System.out.println("in manager " + play.mvc.Http.Context.current());
}
```
should provide some obvious way to set the HTTP context in the `createClientConnection` method.

**Comment by wsargent** [comment] 2016-05-18 03:52
So the reason that EventSource doesn't know about this is because it's based on Chunk, and so streams out the response.  To pass in the request, you can do this:

```
    public Result liveClock() {
        Http.Context context = Http.Context.current();
        return ok(EventSource.whenConnected(es -> {
            play.Logger.info("context = " + context);
            clock.tell(es, null);
        }));
    }
```

**Comment by wsargent** [comment] 2016-05-18 03:56
I've got a branch which passes in the context into the EventSource, but I think since an end user can subclass EventSource in the same way:

https://github.com/playframework/playframework/commit/151bf53e013cf1fe0647dcd7dc0250b7ba2a3672

**Comment by wsargent** [comment] 2016-05-18 04:15
Same with 2.5.x:

```
    public Result streamClock() {
        final Http.Context context = Http.Context.current();
        final Source<EventSource.Event, ?> eventSource = getStringSource(context).map(EventSource.Event::event);
        return ok().chunked(eventSource.via(EventSource.flow())).as(Http.MimeTypes.EVENT_STREAM);
    }

    default Source<String, ?> getStringSource(Http.Context context) {
        play.Logger.info("context = " + context);
        final DateTimeFormatter df = DateTimeFormatter.ofPattern("HH mm ss");
        final Source<String, Cancellable> tickSource = Source.tick(Duration.Zero(), Duration.create(100, MILLISECONDS), "TICK");
        return tickSource.map((tick) -> {
            play.Logger.info("tick " + tick + ", context = " + context);

            return df.format(ZonedDateTime.now());
        });
    }
```

**Comment by bbarkley** [comment] 2016-05-18 17:10
It's easy to close over the context but I think the larger problem here is that the ThreadLocal isn't being set correctly. This is especially confusing if you're using a method reference to some code that may also be used with a normal controller and uses Http.Context.current. It works fine in the controller use case but breaks in the EventSource usage.

**Comment by wsargent** [comment] 2016-05-18 18:00
The ThreadLocal is being set in the controller's action, and the Context can be captured and passed through from there, so the workaround is the pass around the context.

This is very similar to the Akka actor sender() method -- the actor will have a sender, but inside a closure, the sender may change, and likewise, if you're referencing a request inside an equivalent Scala action, you would have to explicitly declare the request as a parameter to the method.  

I'm not sure I'd say the ThreadLocal is being set incorrectly -- looking at it, the problem is that `Http.Context.current()` is a static method magic that can be called from anywhere. Because there's a ThreadLocal involved, the question is then "why doesn't Http.Context.current() work in my method" rather than "how is it I can get the current request from the action."  

There is a patch we could make https://github.com/playframework/playframework/commit/151bf53e013cf1fe0647dcd7dc0250b7ba2a3672 to EventSource, but it's using capture rather than ThreadLocal and so you'd still need to call getContext() to see if you had one in scope.  You would have to return an Optional<Http.Context> because an EventSource can technically be instantiated from anywhere, including outside of a running application.  But even that's not the biggest problem.

The biggest problem is that there is no reason why we couldn't call Http.Context.current() from any method, with the same argument.  And given that we're trying to peel away Play's architecture from ThreadLocal and static methods, it would work against the other options.

@jroper, @gmethvin WDYT?

**Comment by gmethvin** [comment] 2016-05-18 20:23
I actually think Will's suggestion of closing over the context seems pretty reasonable. I don't think there's a clear, consistent solution to this. How do we decide where a context should be accessible from? The only place I know for sure it should be is in the controller method itself.

**Comment by wsargent** [comment] 2016-05-24 04:12
Closing until there's a good way to scope an HTTP context (which is probably going to be 2.6.x based since it's so architecture based...)

**Closed by wsargent** 2016-05-24 04:12 UTC
