### ISSUE TITLE
Using custom ObjectMapper doesn't work when deployed?

### ISSUE THREAD

**Issue by realjax** [playframework/playframework#8921] opened 2019-01-08 11:17 UTC
### JDK OpenJDK 1.8.0_191

I am using the Play framework (2.6) in which I have set a custom ObjectMapper to create JsonNodes as per the documentation.

```
public class CustomObjectMapper {

  CustomObjectMapper() {
    ObjectMapper mapper = Json.newDefaultMapper()
        .setSerializationInclusion(JsonInclude.Include.NON_NULL);
    Json.setObjectMapper(mapper);
  }
}

```

```
public class CustomObjectMapperModule extends AbstractModule {

  @Override
  protected void configure() {
    bind(CustomObjectMapper.class).asEagerSingleton();
  }

}

```
application.conf:

```
play.modules.disabled += "play.core.ObjectMapperModule"
play.modules.enabled  += "CustomObjectMapperModule"
```

This works as expected in development mode and null fields are excluded in the generated json. However, when running the binary version created using SBT's dist task this seems to fail and null fields are included.

**Comment by realjax** [comment] 2019-01-10 12:58
Not at the moment I'm afraid.  Will try at some later time.

**Comment by Ove-Karlson** [comment] 2019-01-27 03:59
@realjax I managed it with the the Provider<T> interface. Have a look at  following snippet:
```java
public class CustomObjectMapperProvider implements Provider<ObjectMapper> {
    private final Config config;
    private final ApplicationLifecycle lifecycle;

    @Inject
    public CustomObjectMapperProvider(Config config, ApplicationLifecycle lifecycle) {
        this.config = config;
        this.lifecycle = lifecycle;
    }

    @Override
    public ObjectMapper get() {
        ObjectMapper mapper = Json.newDefaultMapper();
        InjectableValues injectableValues = new InjectableValues.Std().addValue("config", config);
        mapper.setInjectableValues(injectableValues);
        Json.setObjectMapper(mapper);
        lifecycle.addStopHook(() -> CompletableFuture.runAsync(() -> Json.setObjectMapper(null)));
        return mapper;
    }
}
```

And then bind it into a module like:
```java
public class CustomObjectMapperModule extends AbstractModule {

    @Override
    protected void configure() {
        bind(ObjectMapper.class).toProvider(CustomObjectMapperProvider.class).asEagerSingleton();
    }
}
```

Have a look into the original ObjectMapperModule, they are almost the same.
Hope it helps

**Comment by marcospereira** [comment] 2019-04-25 04:53
Hey @realjax, I could not reproduce this using the same code you shared here and Play 2.6.21. I'm closing this for now, but if you manage to have a reproducer, we can reopen it. :-)

**Closed by marcospereira** 2019-04-25 04:53 UTC
Labels: status:backlog, status:needs-info
