### ISSUE TITLE
[2.5.x] Netty server does not start when a JDBC datasource connection pool cannot create

### ISSUE THREAD

**Issue by zarinfam** [playframework/playframework#6706] opened 2016-11-07 13:50 UTC
I have a Play 2.5 (Java) project, my project depend on 3 JDBC datasources that defined in application.conf. Why Play Framework does not start when one of these JDBC datasources cannot create? My system can work without one of these JDBC datasources but i see this log and netty server does not start:

Configuration error: Configuration error[Cannot connect to database [datasource_name]]

I have tested this scenario in a Play, Scala and Slick project and it works correctly and netty started even datasource cannot create.

**Comment by cchantep** [comment] 2016-11-07 22:02
Hi, have you first asked on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework)? Topic?

**Comment by zarinfam** [comment] 2016-11-08 07:10
@cchantep I asked this question in stackoverflow and after test this scenario in a play, scala and slick project(it works), i guess this is a conceptual problem.

**Comment by gmethvin** [comment] 2016-11-08 09:04
@zarinfam To answer your question, the reason Play does not start is that when the `DBApi` is created, we [try to connect](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-jdbc/src/main/scala/play/api/db/DBModule.scala#L72) to all the datasources. I believe that's generally a good idea (it will easily catch configuration errors and other issues that might break your app anyway). But if you don't like that behavior you could create a custom provider that didn't do that.

Since this is currently an intended behavior, I'm closing this issue, but I'm happy to discuss different approaches on the mailing list.

**Closed by gmethvin** 2016-11-08 09:04 UTC

**Comment by zarinfam** [comment] 2016-11-08 09:31
@gmethvin Why in play, scala and slick projects this behavior is different?

**Comment by schmitch** [comment] 2016-11-08 09:51
The behavior is not different if you would use HikariCP and init your connection at startup.
Also play allows you to configure it, you can set:
`play.db.prototype.hikaricp.initializationFailFast=false`
which will happily start your application even without a db connection, it's just not a good idea to do so.

**Comment by zarinfam** [comment] 2016-11-08 09:57
@schmitch i used initializationFailFast configuration but it does not work!

**Comment by cchantep** [comment] 2016-11-08 17:50
@zarinfam I think the MailingList is the place to discuss.

**Comment by zarinfam** [comment] 2016-11-13 12:43
Thnaks @gmethvin for your guide. I fixed it by implementing custom DB and JPA modules but i think this is better to be configurable in application.conf file.

**Comment by gmethvin** [comment] 2018-06-27 21:03
I do think this should be configurable. Would be a nice feature for 2.7.
