### ISSUE TITLE
Bug in FormError format method

### ISSUE THREAD

**Issue by costabas** [playframework/playframework#8081] opened 2017-12-08 07:05 UTC
### Play Version (2.5.x / etc)
2.6.7

### API (Scala / Java / Neither / Both)
Scala 2.12.4

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
macOS 10.12.6 

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Picked up _JAVA_OPTIONS: -Xms1024m -Xmx2048m
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

The FormError.format method should call messages.apply(message, args: **_***) instead of messages.apply(message, args) in order to properly format the values of the arguments.

### Actual Behavior

As an example, the format method produces the text: minimum WrappedArray(-2)! instead of minimum -2!.

### Reproducible Test Case

```
import play.api.mvc.Results
import play.api.test.{FakeRequest, PlaySpecification}

import scala.concurrent.Future

object FormData {
  import play.api.data.Forms._
  import play.api.data._
  import play.api.i18n._
  import play.api.libs.json._

  val form = Form(
    mapping(
      "name" -> text,
      "age" -> number(min = -2)
    )(UserData.apply)(UserData.unapply)
  )

  case class UserData(name: String, age: Int)
}

class ExampleFormSpec extends PlaySpecification with Results {

  import play.api.data._
  import play.api.i18n._
  import play.api.libs.json._
  import FormData._

  "Form" should {
    "be valid" in {
      val messagesApi = new DefaultMessagesApi(
        Map("en" ->
            Map("error.min" -> "minimum {0}!")
        )
      )
      implicit val request = {
        FakeRequest("POST", "/")
          .withFormUrlEncodedBody("name" -> "Play", "age" -> "-3")
      }
      implicit val messages = messagesApi.preferred(request)

      def errorFunc(badForm: Form[UserData]) = {
        BadRequest(Json.toJson(badForm.errors.map(e => e.key -> e.format)))
      }

      def successFunc(userData: UserData) = {
        Redirect("/").flashing("success" -> "success form!")
      }

      val result = Future.successful(form.bindFromRequest().fold(errorFunc, successFunc))
      println( contentAsString(result))
      Json.parse(contentAsString(result)) must beEqualTo(Json.obj("age" -> Json.arr("minimum -2!")))
    }
  }
}
```

This produces the following output:

```
Form should

[["age","minimum WrappedArray(-2)!"]] != {"age":["minimum -2!"]}
Expected :{"age":["minimum -2!"]}
Actual   :[["age","minimum WrappedArray(-2)!"]]

```

**Comment by richdougherty** [comment] 2017-12-10 19:51
Thanks for the detailed report - down to finding the line of code responsible and writing a test case!

I've marked this as a **good first issue** and **help wanted** because I believe someone should be able to take what you've written and produce a fix pretty easily.

Steps:
1. reproduce and verify in a simple project and comment on this ticket when you've done that
2. add a test to [`FormSpec.scala`](https://github.com/playframework/playframework/blob/1bdb9255110cd07d1f9829fb7a225f9104daa7e9/framework/src/play/src/test/scala/play/api/data/FormSpec.scala) to reproduce - you can use the code @costabas has kindly provided.
3. fix the bug in [`Form.scala`](https://github.com/playframework/playframework/blob/1bdb9255110cd07d1f9829fb7a225f9104daa7e9/framework/src/play/src/main/scala/play/api/data/Form.scala#L435) - again @costabas has provided the fix!

Also marked as **needs-backport** because this is a simple bug fix we can make to the 2.6.x branch.

**Comment by DanielKulesza** [comment] 2017-12-12 03:08
Hi @costabas @richdougherty,

Is anyone working on this issue? If not, I can tackle it.
Seems like a good way to start contributing to the Play framework open source.

Thanks,
Daniel

**Comment by gmethvin** [comment] 2017-12-12 03:24
@DanielKulesza Nope, feel free to take it.

**Comment by costa100** [comment] 2017-12-15 23:12
@DanielKulesza : I am not working on this. I thought you guys want to have someone other than the person that reported it to work on it.
@gmethvin : do you have a document that describes that patching process for the playframework, just in case I decide to provide patches? Thank you

**Comment by gmethvin** [comment] 2017-12-16 00:50
There are some contributing guidelines on https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md

**Closed** 2018-01-18 23:15 UTC
Labels: bug, good first issue, help wanted, help:needs-verification, status:needs-backport
